In [14]:
# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

"""Attacker agent benchmark comparison in presence of a basic defender

This notebooks can be run directly from VSCode, to generate a
traditional Jupyter Notebook to open in your browser
 you can run the VSCode command `Export Currenty Python File As Jupyter Notebook`.
"""

'Attacker agent benchmark comparison in presence of a basic defender\n\nThis notebooks can be run directly from VSCode, to generate a\ntraditional Jupyter Notebook to open in your browser\n you can run the VSCode command `Export Currenty Python File As Jupyter Notebook`.\n'

In [15]:
import sys
import os
import logging
import gymnasium as gym
import importlib
import cyberbattle.agents.baseline.learner as learner
import cyberbattle.agents.baseline.plotting as p
import cyberbattle.agents.baseline.agent_wrapper as w
import cyberbattle.agents.baseline.agent_dql as dqla
import cyberbattle.agents.baseline.agent_randomcredlookup as rca
from cyberbattle.agents.baseline.agent_wrapper import Verbosity
from cyberbattle._env.defender import Demon
from cyberbattle._env.cyberbattle_env import AttackerGoal, DefenderConstraint, CyberBattleEnv

importlib.reload(learner)
importlib.reload(p)
importlib.reload(p)

logging.basicConfig(stream=sys.stdout, level=logging.ERROR, format="%(levelname)s: %(message)s")
# %matplotlib inline

In [16]:
iteration_count = 600
training_episode_count = 10
plots_dir = "output/plots"

In [17]:
gym_env = gym.make(
    "CyberBattleChain-v0",
    size=10,
    attacker_goal=AttackerGoal(own_atleast=0, own_atleast_percent=1.0),
    defender_constraint=DefenderConstraint(maintain_sla=0.80),
    defender_agent=Demon(),
).unwrapped

cyberbattlechain_defender = gym_env.unwrapped
assert isinstance(cyberbattlechain_defender, CyberBattleEnv)

# import plotly.offline as plo
# plo.init_notebook_mode(connected=True)

ep = w.EnvironmentBounds.of_identifiers(maximum_total_credentials=22, maximum_node_count=22, identifiers=cyberbattlechain_defender.identifiers)

In [18]:
dqn_with_defender = learner.epsilon_greedy_search(
    cyberbattle_gym_env=cyberbattlechain_defender,
    environment_properties=ep,
    learner=dqla.DeepQLearnerPolicy(ep=ep, gamma=0.15, replay_memory_size=10000, target_update=5, batch_size=256, learning_rate=0.01),
    episode_count=training_episode_count,
    iteration_count=iteration_count,
    epsilon=0.90,
    render=False,
    epsilon_exponential_decay=5000,
    epsilon_minimum=0.10,
    verbosity=Verbosity.Quiet,
    title="DQL",
)

###### DQL
Learning with: episode_count=10,iteration_count=600,ϵ=0.9,ϵ_min=0.1, ϵ_expdecay=5000,γ=0.15, lr=0.01, replaymemory=10000,
batch=256, target_update=5
  ## Episode: 1/10 'DQL' ϵ=0.9000, γ=0.15, lr=0.01, replaymemory=10000,
batch=256, target_update=5

Episode 1|Iteration 0|reward: ------|last_reward_at: ----|Elapsed Time: 0:00:00||
Episode 1|Iteration 1|reward:    0.0|last_reward_at: ----|Elapsed Time: 0:00:00||
Episode 1|Iteration 12|reward:   14.0|last_reward_at: ----|Elapsed Time: 0:00:00||
Episode 1|Iteration 12|reward:   14.0|last_reward_at:   12|Elapsed Time: 0:00:00||
Episode 1|Iteration 17|reward:   16.0|last_reward_at:   12|Elapsed Time: 0:00:00||
Episode 1|Iteration 17|reward:   16.0|last_reward_at:   17|Elapsed Time: 0:00:00||
Episode 1|Iteration 30|reward:   20.0|last_reward_at:   17|Elapsed Time: 0:00:00||
Episode 1|Iteration 30|reward:   20.0|last_reward_at:   30|Elapsed Time: 0:00:00||
Episode 1|Iteration 54|reward:   20.0|last_reward_at:   30|Elapsed Time: 0:00:00||
Episode 1|Iteration 71|reward:  120.0|last_reward_at:   30|Elapsed Time: 0:00:00||
Episode 1|Iteration 71|reward:  120.0|last_reward_at:   71|Elapsed Time: 0:00:00||
Episode 1|Iteration 81|reward:  131.0|last_reward_at:   71|Elapsed Time: 0:00:00||
Episode 1|Iteration 81|reward:  131.0|last_reward_at:   81|Elapsed Time: 0:00:00||
Episode 1|Iteration 82|reward:  139.0|last_reward_at:   81|Elapsed Time: 0:00:00||
Episode 1|Iteration 82|reward:  139.0|last_reward_at:   82|Elapsed Time: 0:00:00||
Episode 1|Iteration 94|reward:  148.0|last_reward_at:   82|Elapsed Time: 0:00:00||
Episode 1|Iteration 94|reward:  148.0|last_reward_at:   94|Elapsed Time: 0:00:00||
Episode 1|Iteration 110|reward:  154.0|last_reward_at:   94|Elapsed Time: 0:00:00||
Episode 1|Iteration 110|reward:  154.0|last_reward_at:  110|Elapsed Time: 0:00:00||
Episode 1|Iteration 130|reward:  154.0|last_reward_at:  110|Elapsed Time: 0:00:00||
Episode 1|Iteration 152|reward:  154.0|last_reward_at:  110|Elapsed Time: 0:00:00||
Episode 1|Iteration 175|reward:  154.0|last_reward_at:  110|Elapsed Time: 0:00:00||
Episode 1|Iteration 198|reward:  154.0|last_reward_at:  110|Elapsed Time: 0:00:00||
Episode 1|Iteration 221|reward:  154.0|last_reward_at:  110|Elapsed Time: 0:00:00||
Episode 1|Iteration 244|reward:  154.0|last_reward_at:  110|Elapsed Time: 0:00:00||
Episode 1|Iteration 258|reward:  154.0|last_reward_at:  110|Elapsed Time: 0:00:00||
Episode 1|Iteration 266|reward:  154.0|last_reward_at:  110|Elapsed Time: 0:00:00||
Episode 1|Iteration 274|reward:  154.0|last_reward_at:  110|Elapsed Time: 0:00:00||
Episode 1|Iteration 282|reward:  154.0|last_reward_at:  110|Elapsed Time: 0:00:00||
Episode 1|Iteration 289|reward:  154.0|last_reward_at:  110|Elapsed Time: 0:00:01||
Episode 1|Iteration 297|reward:  154.0|last_reward_at:  110|Elapsed Time: 0:00:01||
Episode 1|Iteration 304|reward:  154.0|last_reward_at:  110|Elapsed Time: 0:00:01||
Episode 1|Iteration 312|reward:  154.0|last_reward_at:  110|Elapsed Time: 0:00:01||
Episode 1|Iteration 319|reward:  154.0|last_reward_at:  110|Elapsed Time: 0:00:01||
Episode 1|Iteration 327|reward:  154.0|last_reward_at:  110|Elapsed Time: 0:00:01||
Episode 1|Iteration 335|reward:  154.0|last_reward_at:  110|Elapsed Time: 0:00:01||
Episode 1|Iteration 342|reward:  154.0|last_reward_at:  110|Elapsed Time: 0:00:01||
Episode 1|Iteration 350|reward:  154.0|last_reward_at:  110|Elapsed Time: 0:00:01||
Episode 1|Iteration 357|reward:  154.0|last_reward_at:  110|Elapsed Time: 0:00:01||
Episode 1|Iteration 365|reward:  154.0|last_reward_at:  110|Elapsed Time: 0:00:01||
Episode 1|Iteration 373|reward:  154.0|last_reward_at:  110|Elapsed Time: 0:00:01||
Episode 1|Iteration 380|reward:  154.0|last_reward_at:  110|Elapsed Time: 0:00:01||
Episode 1|Iteration 388|reward:  154.0|last_reward_at:  110|Elapsed Time: 0:00:01||
Episode 1|Iteration 395|reward:  154.0|last_reward_at:  110|Elapsed Time: 0:00:01||
Episode 1|Iteration 403|reward:  154.0|last_reward_at:  110|Elapsed Time: 0:00:01||
Episode 1|Iteration 411|reward:  154.0|last_reward_at:  110|Elapsed Time: 0:00:02||
Episode 1|Iteration 418|reward:  154.0|last_reward_at:  110|Elapsed Time: 0:00:02||
Episode 1|Iteration 426|reward:  154.0|last_reward_at:  110|Elapsed Time: 0:00:02||
Episode 1|Iteration 433|reward:  154.0|last_reward_at:  110|Elapsed Time: 0:00:02||
Episode 1|Iteration 441|reward:  154.0|last_reward_at:  110|Elapsed Time: 0:00:02||
Episode 1|Iteration 449|reward:  154.0|last_reward_at:  110|Elapsed Time: 0:00:02||
Episode 1|Iteration 456|reward:  154.0|last_reward_at:  110|Elapsed Time: 0:00:02||
Episode 1|Iteration 464|reward:  154.0|last_reward_at:  110|Elapsed Time: 0:00:02||
Episode 1|Iteration 471|reward:  154.0|last_reward_at:  110|Elapsed Time: 0:00:02||
Episode 1|Iteration 479|reward:  154.0|last_reward_at:  110|Elapsed Time: 0:00:02||
Episode 1|Iteration 487|reward:  154.0|last_reward_at:  110|Elapsed Time: 0:00:02||
Episode 1|Iteration 494|reward:  154.0|last_reward_at:  110|Elapsed Time: 0:00:02||
Episode 1|Iteration 502|reward:  154.0|last_reward_at:  110|Elapsed Time: 0:00:02||
Episode 1|Iteration 509|reward:  154.0|last_reward_at:  110|Elapsed Time: 0:00:02||
Episode 1|Iteration 517|reward:  154.0|last_reward_at:  110|Elapsed Time: 0:00:02||
Episode 1|Iteration 525|reward:  154.0|last_reward_at:  110|Elapsed Time: 0:00:02||
Episode 1|Iteration 532|reward:  154.0|last_reward_at:  110|Elapsed Time: 0:00:03||
Episode 1|Iteration 540|reward:  154.0|last_reward_at:  110|Elapsed Time: 0:00:03||
Episode 1|Iteration 547|reward:  154.0|last_reward_at:  110|Elapsed Time: 0:00:03||
Episode 1|Iteration 555|reward:  154.0|last_reward_at:  110|Elapsed Time: 0:00:03||
Episode 1|Iteration 563|reward:  154.0|last_reward_at:  110|Elapsed Time: 0:00:03||
Episode 1|Iteration 570|reward:  154.0|last_reward_at:  110|Elapsed Time: 0:00:03||
Episode 1|Iteration 578|reward:  154.0|last_reward_at:  110|Elapsed Time: 0:00:03||
Episode 1|Iteration 585|reward:  154.0|last_reward_at:  110|Elapsed Time: 0:00:03||
Episode 1|Iteration 593|reward:  154.0|last_reward_at:  110|Elapsed Time: 0:00:03||
Episode 1|Iteration 600|reward:  154.0|last_reward_at:  110|Elapsed Time: 0:00:03||
Episode 1|Iteration 600|reward:  154.0|last_reward_at:  110|Elapsed Time: 0:00:03||

  Episode 1 stopped at t=600
  Breakdown [Reward/NoReward (Success rate)]
    explore-local: 3/95 (0.03)
    explore-remote: 4/211 (0.02)
    explore-connect: 1/179 (0.01)
    exploit-local: 0/8 (0.00)
    exploit-remote: 0/13 (0.00)
    exploit-connect: 0/86 (0.00)
  exploit deflected to exploration: 4
  ## Episode: 2/10 'DQL' ϵ=0.8097, γ=0.15, lr=0.01, replaymemory=10000,
batch=256, target_update=5

Episode 2|Iteration 0|reward: ------|last_reward_at: ----|Elapsed Time: 0:00:00||
Episode 2|Iteration 1|reward:    0.0|last_reward_at: ----|Elapsed Time: 0:00:00||
Episode 2|Iteration 3|reward:   14.0|last_reward_at: ----|Elapsed Time: 0:00:00||
Episode 2|Iteration 3|reward:   14.0|last_reward_at:    3|Elapsed Time: 0:00:00||
Episode 2|Iteration 9|reward:   18.0|last_reward_at:    3|Elapsed Time: 0:00:00||
Episode 2|Iteration 9|reward:   18.0|last_reward_at:    9|Elapsed Time: 0:00:00||
Episode 2|Iteration 18|reward:   20.0|last_reward_at:    9|Elapsed Time: 0:00:00||
Episode 2|Iteration 18|reward:   20.0|last_reward_at:   18|Elapsed Time: 0:00:00||
Episode 2|Iteration 20|reward:  120.0|last_reward_at:   18|Elapsed Time: 0:00:00||
Episode 2|Iteration 20|reward:  120.0|last_reward_at:   20|Elapsed Time: 0:00:00||
Episode 2|Iteration 24|reward:  131.0|last_reward_at:   20|Elapsed Time: 0:00:00||
Episode 2|Iteration 24|reward:  131.0|last_reward_at:   24|Elapsed Time: 0:00:00||
Episode 2|Iteration 30|reward:  139.0|last_reward_at:   24|Elapsed Time: 0:00:00||
Episode 2|Iteration 30|reward:  139.0|last_reward_at:   30|Elapsed Time: 0:00:00||
Episode 2|Iteration 33|reward:  145.0|last_reward_at:   30|Elapsed Time: 0:00:00||
Episode 2|Iteration 33|reward:  145.0|last_reward_at:   33|Elapsed Time: 0:00:00||
Episode 2|Iteration 46|reward:  145.0|last_reward_at:   33|Elapsed Time: 0:00:00||
Episode 2|Iteration 46|reward:  154.0|last_reward_at:   33|Elapsed Time: 0:00:00||
Episode 2|Iteration 46|reward:  154.0|last_reward_at:   46|Elapsed Time: 0:00:00||
Episode 2|Iteration 54|reward:  154.0|last_reward_at:   46|Elapsed Time: 0:00:00||
Episode 2|Iteration 61|reward:  154.0|last_reward_at:   46|Elapsed Time: 0:00:00||
Episode 2|Iteration 69|reward:  154.0|last_reward_at:   46|Elapsed Time: 0:00:00||
Episode 2|Iteration 76|reward:  154.0|last_reward_at:   46|Elapsed Time: 0:00:00||
Episode 2|Iteration 84|reward:  154.0|last_reward_at:   46|Elapsed Time: 0:00:00||
Episode 2|Iteration 92|reward:  154.0|last_reward_at:   46|Elapsed Time: 0:00:00||
Episode 2|Iteration 99|reward:  154.0|last_reward_at:   46|Elapsed Time: 0:00:00||
Episode 2|Iteration 107|reward:  154.0|last_reward_at:   46|Elapsed Time: 0:00:00||
Episode 2|Iteration 114|reward:  154.0|last_reward_at:   46|Elapsed Time: 0:00:00||
Episode 2|Iteration 122|reward:  154.0|last_reward_at:   46|Elapsed Time: 0:00:01||
Episode 2|Iteration 129|reward:  254.0|last_reward_at:   46|Elapsed Time: 0:00:01||
Episode 2|Iteration 129|reward:  254.0|last_reward_at:  129|Elapsed Time: 0:00:01||
Episode 2|Iteration 137|reward:  254.0|last_reward_at:  129|Elapsed Time: 0:00:01||
Episode 2|Iteration 142|reward:  254.0|last_reward_at:  129|Elapsed Time: 0:00:01||
Episode 2|Iteration 150|reward:  254.0|last_reward_at:  129|Elapsed Time: 0:00:01||
Episode 2|Iteration 155|reward:  265.0|last_reward_at:  129|Elapsed Time: 0:00:01||
Episode 2|Iteration 155|reward:  265.0|last_reward_at:  155|Elapsed Time: 0:00:01||
Episode 2|Iteration 162|reward:  269.0|last_reward_at:  155|Elapsed Time: 0:00:01||
Episode 2|Iteration 162|reward:  269.0|last_reward_at:  162|Elapsed Time: 0:00:01||
Episode 2|Iteration 168|reward:  269.0|last_reward_at:  162|Elapsed Time: 0:00:01||
Episode 2|Iteration 175|reward:  269.0|last_reward_at:  162|Elapsed Time: 0:00:01||
Episode 2|Iteration 183|reward:  269.0|last_reward_at:  162|Elapsed Time: 0:00:01||
Episode 2|Iteration 190|reward:  269.0|last_reward_at:  162|Elapsed Time: 0:00:01||
Episode 2|Iteration 198|reward:  269.0|last_reward_at:  162|Elapsed Time: 0:00:01||
Episode 2|Iteration 200|reward:  271.0|last_reward_at:  162|Elapsed Time: 0:00:01||
Episode 2|Iteration 200|reward:  271.0|last_reward_at:  200|Elapsed Time: 0:00:01||
Episode 2|Iteration 206|reward:  271.0|last_reward_at:  200|Elapsed Time: 0:00:01||
Episode 2|Iteration 207|reward:  280.0|last_reward_at:  200|Elapsed Time: 0:00:01||
Episode 2|Iteration 207|reward:  280.0|last_reward_at:  207|Elapsed Time: 0:00:01||
Episode 2|Iteration 218|reward:  280.0|last_reward_at:  207|Elapsed Time: 0:00:02||
Episode 2|Iteration 228|reward:  280.0|last_reward_at:  207|Elapsed Time: 0:00:02||
Episode 2|Iteration 236|reward:  280.0|last_reward_at:  207|Elapsed Time: 0:00:02||
Episode 2|Iteration 244|reward:  280.0|last_reward_at:  207|Elapsed Time: 0:00:02||
Episode 2|Iteration 251|reward:  280.0|last_reward_at:  207|Elapsed Time: 0:00:02||
Episode 2|Iteration 259|reward:  280.0|last_reward_at:  207|Elapsed Time: 0:00:02||
Episode 2|Iteration 263|reward:  380.0|last_reward_at:  207|Elapsed Time: 0:00:02||
Episode 2|Iteration 263|reward:  380.0|last_reward_at:  263|Elapsed Time: 0:00:02||
Episode 2|Iteration 265|reward:  391.0|last_reward_at:  263|Elapsed Time: 0:00:02||
Episode 2|Iteration 265|reward:  391.0|last_reward_at:  265|Elapsed Time: 0:00:02||
Episode 2|Iteration 272|reward:  399.0|last_reward_at:  265|Elapsed Time: 0:00:02||
Episode 2|Iteration 272|reward:  399.0|last_reward_at:  272|Elapsed Time: 0:00:02||
Episode 2|Iteration 281|reward:  399.0|last_reward_at:  272|Elapsed Time: 0:00:02||
Episode 2|Iteration 289|reward:  399.0|last_reward_at:  272|Elapsed Time: 0:00:02||
Episode 2|Iteration 292|reward:  405.0|last_reward_at:  272|Elapsed Time: 0:00:02||
Episode 2|Iteration 292|reward:  405.0|last_reward_at:  292|Elapsed Time: 0:00:02||
Episode 2|Iteration 304|reward:  405.0|last_reward_at:  292|Elapsed Time: 0:00:02||
Episode 2|Iteration 312|reward:  405.0|last_reward_at:  292|Elapsed Time: 0:00:03||
Episode 2|Iteration 319|reward:  405.0|last_reward_at:  292|Elapsed Time: 0:00:03||
Episode 2|Iteration 327|reward:  405.0|last_reward_at:  292|Elapsed Time: 0:00:03||
Episode 2|Iteration 335|reward:  405.0|last_reward_at:  292|Elapsed Time: 0:00:03||
Episode 2|Iteration 342|reward:  405.0|last_reward_at:  292|Elapsed Time: 0:00:03||
Episode 2|Iteration 350|reward:  405.0|last_reward_at:  292|Elapsed Time: 0:00:03||
Episode 2|Iteration 355|reward:  414.0|last_reward_at:  292|Elapsed Time: 0:00:03||
Episode 2|Iteration 355|reward:  414.0|last_reward_at:  355|Elapsed Time: 0:00:03||
Episode 2|Iteration 365|reward:  414.0|last_reward_at:  355|Elapsed Time: 0:00:03||
Episode 2|Iteration 373|reward:  414.0|last_reward_at:  355|Elapsed Time: 0:00:03||
Episode 2|Iteration 380|reward:  414.0|last_reward_at:  355|Elapsed Time: 0:00:03||
Episode 2|Iteration 388|reward:  414.0|last_reward_at:  355|Elapsed Time: 0:00:03||
Episode 2|Iteration 395|reward:  414.0|last_reward_at:  355|Elapsed Time: 0:00:03||
Episode 2|Iteration 400|reward:  514.0|last_reward_at:  355|Elapsed Time: 0:00:03||
Episode 2|Iteration 400|reward:  514.0|last_reward_at:  400|Elapsed Time: 0:00:03||
Episode 2|Iteration 409|reward:  514.0|last_reward_at:  400|Elapsed Time: 0:00:03||
Episode 2|Iteration 410|reward:  525.0|last_reward_at:  400|Elapsed Time: 0:00:03||
Episode 2|Iteration 410|reward:  525.0|last_reward_at:  410|Elapsed Time: 0:00:03||
Episode 2|Iteration 411|reward:  534.0|last_reward_at:  410|Elapsed Time: 0:00:03||
Episode 2|Iteration 411|reward:  534.0|last_reward_at:  411|Elapsed Time: 0:00:03||
Episode 2|Iteration 418|reward:  534.0|last_reward_at:  411|Elapsed Time: 0:00:04||
Episode 2|Iteration 420|reward:  634.0|last_reward_at:  411|Elapsed Time: 0:00:04||
Episode 2|Iteration 420|reward:  634.0|last_reward_at:  420|Elapsed Time: 0:00:04||
Episode 2|Iteration 422|reward:  648.0|last_reward_at:  420|Elapsed Time: 0:00:04||
Episode 2|Iteration 422|reward:  648.0|last_reward_at:  422|Elapsed Time: 0:00:04||
Episode 2|Iteration 423|reward:  748.0|last_reward_at:  422|Elapsed Time: 0:00:04||
Episode 2|Iteration 423|reward:  748.0|last_reward_at:  423|Elapsed Time: 0:00:04||
Episode 2|Iteration 425|reward:  748.0|last_reward_at:  423|Elapsed Time: 0:00:04||
Episode 2|Iteration 428|reward:  750.0|last_reward_at:  423|Elapsed Time: 0:00:04||
Episode 2|Iteration 428|reward:  750.0|last_reward_at:  428|Elapsed Time: 0:00:04||
Episode 2|Iteration 433|reward:  756.0|last_reward_at:  428|Elapsed Time: 0:00:04||
Episode 2|Iteration 433|reward:  756.0|last_reward_at:  433|Elapsed Time: 0:00:04||
Episode 2|Iteration 438|reward:  762.0|last_reward_at:  433|Elapsed Time: 0:00:04||
Episode 2|Iteration 438|reward:  762.0|last_reward_at:  438|Elapsed Time: 0:00:04||
Episode 2|Iteration 439|reward:  776.0|last_reward_at:  438|Elapsed Time: 0:00:04||
Episode 2|Iteration 439|reward:  776.0|last_reward_at:  439|Elapsed Time: 0:00:04||
Episode 2|Iteration 441|reward:  780.0|last_reward_at:  439|Elapsed Time: 0:00:04||
Episode 2|Iteration 441|reward:  780.0|last_reward_at:  441|Elapsed Time: 0:00:04||
Episode 2|Iteration 446|reward:  786.0|last_reward_at:  441|Elapsed Time: 0:00:04||
Episode 2|Iteration 446|reward:  786.0|last_reward_at:  446|Elapsed Time: 0:00:04||
Episode 2|Iteration 456|reward:  786.0|last_reward_at:  446|Elapsed Time: 0:00:04||
Episode 2|Iteration 462|reward:  788.0|last_reward_at:  446|Elapsed Time: 0:00:04||
Episode 2|Iteration 462|reward:  788.0|last_reward_at:  462|Elapsed Time: 0:00:04||
Episode 2|Iteration 471|reward:  788.0|last_reward_at:  462|Elapsed Time: 0:00:04||
Episode 2|Iteration 479|reward:  788.0|last_reward_at:  462|Elapsed Time: 0:00:04||
Episode 2|Iteration 487|reward:  788.0|last_reward_at:  462|Elapsed Time: 0:00:04||
Episode 2|Iteration 494|reward:  788.0|last_reward_at:  462|Elapsed Time: 0:00:04||
Episode 2|Iteration 502|reward:  788.0|last_reward_at:  462|Elapsed Time: 0:00:05||
Episode 2|Iteration 509|reward:  788.0|last_reward_at:  462|Elapsed Time: 0:00:05||
Episode 2|Iteration 517|reward:  788.0|last_reward_at:  462|Elapsed Time: 0:00:05||
Episode 2|Iteration 525|reward:  788.0|last_reward_at:  462|Elapsed Time: 0:00:05||
Episode 2|Iteration 525|reward:  888.0|last_reward_at:  462|Elapsed Time: 0:00:05||
Episode 2|Iteration 525|reward:  888.0|last_reward_at:  525|Elapsed Time: 0:00:05||
Episode 2|Iteration 532|reward:  888.0|last_reward_at:  525|Elapsed Time: 0:00:05||
Episode 2|Iteration 535|reward:  902.0|last_reward_at:  525|Elapsed Time: 0:00:05||
Episode 2|Iteration 535|reward:  902.0|last_reward_at:  535|Elapsed Time: 0:00:05||
Episode 2|Iteration 539|reward: 1002.0|last_reward_at:  535|Elapsed Time: 0:00:05||
Episode 2|Iteration 539|reward: 1002.0|last_reward_at:  539|Elapsed Time: 0:00:05||
Episode 2|Iteration 546|reward: 1002.0|last_reward_at:  539|Elapsed Time: 0:00:05||
Episode 2|Iteration 550|reward: 1002.0|last_reward_at:  539|Elapsed Time: 0:00:05||
Episode 2|Iteration 551|reward: 1008.0|last_reward_at:  539|Elapsed Time: 0:00:05||
Episode 2|Iteration 551|reward: 1008.0|last_reward_at:  551|Elapsed Time: 0:00:05||
Episode 2|Iteration 557|reward: 1010.0|last_reward_at:  551|Elapsed Time: 0:00:05||
Episode 2|Iteration 557|reward: 1010.0|last_reward_at:  557|Elapsed Time: 0:00:05||
Episode 2|Iteration 563|reward: 1010.0|last_reward_at:  557|Elapsed Time: 0:00:05||
Episode 2|Iteration 569|reward: 1010.0|last_reward_at:  557|Elapsed Time: 0:00:05||
Episode 2|Iteration 577|reward: 1016.0|last_reward_at:  557|Elapsed Time: 0:00:06||
Episode 2|Iteration 577|reward: 1016.0|last_reward_at:  577|Elapsed Time: 0:00:06||
Episode 2|Iteration 579|reward: 1022.0|last_reward_at:  577|Elapsed Time: 0:00:06||
Episode 2|Iteration 579|reward: 1022.0|last_reward_at:  579|Elapsed Time: 0:00:06||
Episode 2|Iteration 582|reward: 1033.0|last_reward_at:  579|Elapsed Time: 0:00:06||
Episode 2|Iteration 582|reward: 1033.0|last_reward_at:  582|Elapsed Time: 0:00:06||
Episode 2|Iteration 592|reward: 1033.0|last_reward_at:  582|Elapsed Time: 0:00:06||
Episode 2|Iteration 600|reward: 1033.0|last_reward_at:  582|Elapsed Time: 0:00:06||
Episode 2|Iteration 600|reward: 1033.0|last_reward_at:  582|Elapsed Time: 0:00:06||

  Episode 2 stopped at t=600
  Breakdown [Reward/NoReward (Success rate)]
    explore-local: 10/115 (0.08)
    explore-remote: 14/171 (0.08)
    explore-connect: 2/170 (0.01)
    exploit-local: 5/45 (0.10)
    exploit-remote: 2/39 (0.05)
    exploit-connect: 6/21 (0.22)
  exploit deflected to exploration: 20
  ## Episode: 3/10 'DQL' ϵ=0.7294, γ=0.15, lr=0.01, replaymemory=10000,
batch=256, target_update=5

Episode 3|Iteration 0|reward: ------|last_reward_at: ----|Elapsed Time: 0:00:00||
Episode 3|Iteration 1|reward:    0.0|last_reward_at: ----|Elapsed Time: 0:00:00||
Episode 3|Iteration 5|reward:   14.0|last_reward_at: ----|Elapsed Time: 0:00:00||
Episode 3|Iteration 5|reward:   14.0|last_reward_at:    5|Elapsed Time: 0:00:00||
Episode 3|Iteration 9|reward:   18.0|last_reward_at:    5|Elapsed Time: 0:00:00||
Episode 3|Iteration 9|reward:   18.0|last_reward_at:    9|Elapsed Time: 0:00:00||
Episode 3|Iteration 11|reward:   20.0|last_reward_at:    9|Elapsed Time: 0:00:00||
Episode 3|Iteration 11|reward:   20.0|last_reward_at:   11|Elapsed Time: 0:00:00||
Episode 3|Iteration 23|reward:   20.0|last_reward_at:   11|Elapsed Time: 0:00:00||
Episode 3|Iteration 31|reward:   20.0|last_reward_at:   11|Elapsed Time: 0:00:00||
Episode 3|Iteration 38|reward:   20.0|last_reward_at:   11|Elapsed Time: 0:00:00||
Episode 3|Iteration 40|reward:  120.0|last_reward_at:   11|Elapsed Time: 0:00:00||
Episode 3|Iteration 40|reward:  120.0|last_reward_at:   40|Elapsed Time: 0:00:00||
Episode 3|Iteration 49|reward:  134.0|last_reward_at:   40|Elapsed Time: 0:00:00||
Episode 3|Iteration 49|reward:  134.0|last_reward_at:   49|Elapsed Time: 0:00:00||
Episode 3|Iteration 57|reward:  234.0|last_reward_at:   49|Elapsed Time: 0:00:00||
Episode 3|Iteration 57|reward:  234.0|last_reward_at:   57|Elapsed Time: 0:00:00||
Episode 3|Iteration 59|reward:  240.0|last_reward_at:   57|Elapsed Time: 0:00:00||
Episode 3|Iteration 59|reward:  240.0|last_reward_at:   59|Elapsed Time: 0:00:00||
Episode 3|Iteration 69|reward:  240.0|last_reward_at:   59|Elapsed Time: 0:00:00||
Episode 3|Iteration 75|reward:  246.0|last_reward_at:   59|Elapsed Time: 0:00:00||
Episode 3|Iteration 75|reward:  246.0|last_reward_at:   75|Elapsed Time: 0:00:00||
Episode 3|Iteration 80|reward:  252.0|last_reward_at:   75|Elapsed Time: 0:00:00||
Episode 3|Iteration 80|reward:  252.0|last_reward_at:   80|Elapsed Time: 0:00:00||
Episode 3|Iteration 81|reward:  266.0|last_reward_at:   80|Elapsed Time: 0:00:00||
Episode 3|Iteration 81|reward:  266.0|last_reward_at:   81|Elapsed Time: 0:00:00||
Episode 3|Iteration 82|reward:  268.0|last_reward_at:   81|Elapsed Time: 0:00:00||
Episode 3|Iteration 82|reward:  268.0|last_reward_at:   82|Elapsed Time: 0:00:00||
Episode 3|Iteration 92|reward:  268.0|last_reward_at:   82|Elapsed Time: 0:00:00||
Episode 3|Iteration 94|reward:  272.0|last_reward_at:   82|Elapsed Time: 0:00:00||
Episode 3|Iteration 94|reward:  272.0|last_reward_at:   94|Elapsed Time: 0:00:00||
Episode 3|Iteration 102|reward:  278.0|last_reward_at:   94|Elapsed Time: 0:00:00||
Episode 3|Iteration 102|reward:  278.0|last_reward_at:  102|Elapsed Time: 0:00:00||
Episode 3|Iteration 113|reward:  378.0|last_reward_at:  102|Elapsed Time: 0:00:00||
Episode 3|Iteration 113|reward:  378.0|last_reward_at:  113|Elapsed Time: 0:00:00||
Episode 3|Iteration 114|reward:  392.0|last_reward_at:  113|Elapsed Time: 0:00:01||
Episode 3|Iteration 114|reward:  392.0|last_reward_at:  114|Elapsed Time: 0:00:01||
Episode 3|Iteration 117|reward:  492.0|last_reward_at:  114|Elapsed Time: 0:00:01||
Episode 3|Iteration 117|reward:  492.0|last_reward_at:  117|Elapsed Time: 0:00:01||
Episode 3|Iteration 120|reward:  498.0|last_reward_at:  117|Elapsed Time: 0:00:01||
Episode 3|Iteration 120|reward:  498.0|last_reward_at:  120|Elapsed Time: 0:00:01||
Episode 3|Iteration 124|reward:  504.0|last_reward_at:  120|Elapsed Time: 0:00:01||
Episode 3|Iteration 124|reward:  504.0|last_reward_at:  124|Elapsed Time: 0:00:01||
Episode 3|Iteration 126|reward:  510.0|last_reward_at:  124|Elapsed Time: 0:00:01||
Episode 3|Iteration 126|reward:  510.0|last_reward_at:  126|Elapsed Time: 0:00:01||
Episode 3|Iteration 129|reward:  524.0|last_reward_at:  126|Elapsed Time: 0:00:01||
Episode 3|Iteration 129|reward:  524.0|last_reward_at:  129|Elapsed Time: 0:00:01||
Episode 3|Iteration 137|reward:  524.0|last_reward_at:  129|Elapsed Time: 0:00:01||
Episode 3|Iteration 145|reward:  524.0|last_reward_at:  129|Elapsed Time: 0:00:01||
Episode 3|Iteration 145|reward:  530.0|last_reward_at:  129|Elapsed Time: 0:00:01||
Episode 3|Iteration 145|reward:  530.0|last_reward_at:  145|Elapsed Time: 0:00:01||
Episode 3|Iteration 149|reward:  534.0|last_reward_at:  145|Elapsed Time: 0:00:01||
Episode 3|Iteration 149|reward:  534.0|last_reward_at:  149|Elapsed Time: 0:00:01||
Episode 3|Iteration 160|reward:  534.0|last_reward_at:  149|Elapsed Time: 0:00:01||
Episode 3|Iteration 165|reward:  634.0|last_reward_at:  149|Elapsed Time: 0:00:01||
Episode 3|Iteration 165|reward:  634.0|last_reward_at:  165|Elapsed Time: 0:00:01||
Episode 3|Iteration 175|reward:  634.0|last_reward_at:  165|Elapsed Time: 0:00:01||
Episode 3|Iteration 177|reward:  648.0|last_reward_at:  165|Elapsed Time: 0:00:01||
Episode 3|Iteration 177|reward:  648.0|last_reward_at:  177|Elapsed Time: 0:00:01||
Episode 3|Iteration 181|reward:  650.0|last_reward_at:  177|Elapsed Time: 0:00:01||
Episode 3|Iteration 181|reward:  650.0|last_reward_at:  181|Elapsed Time: 0:00:01||
Episode 3|Iteration 190|reward:  650.0|last_reward_at:  181|Elapsed Time: 0:00:01||
Episode 3|Iteration 197|reward:  658.0|last_reward_at:  181|Elapsed Time: 0:00:01||
Episode 3|Iteration 197|reward:  658.0|last_reward_at:  197|Elapsed Time: 0:00:01||
Episode 3|Iteration 206|reward:  658.0|last_reward_at:  197|Elapsed Time: 0:00:02||
Episode 3|Iteration 213|reward:  658.0|last_reward_at:  197|Elapsed Time: 0:00:02||
Episode 3|Iteration 221|reward:  658.0|last_reward_at:  197|Elapsed Time: 0:00:02||
Episode 3|Iteration 228|reward:  658.0|last_reward_at:  197|Elapsed Time: 0:00:02||
Episode 3|Iteration 236|reward:  658.0|last_reward_at:  197|Elapsed Time: 0:00:02||
Episode 3|Iteration 244|reward:  658.0|last_reward_at:  197|Elapsed Time: 0:00:02||
Episode 3|Iteration 251|reward:  658.0|last_reward_at:  197|Elapsed Time: 0:00:02||
Episode 3|Iteration 259|reward:  658.0|last_reward_at:  197|Elapsed Time: 0:00:02||
Episode 3|Iteration 266|reward:  658.0|last_reward_at:  197|Elapsed Time: 0:00:02||
Episode 3|Iteration 274|reward:  658.0|last_reward_at:  197|Elapsed Time: 0:00:02||
Episode 3|Iteration 278|reward:  664.0|last_reward_at:  197|Elapsed Time: 0:00:02||
Episode 3|Iteration 278|reward:  664.0|last_reward_at:  278|Elapsed Time: 0:00:02||
Episode 3|Iteration 289|reward:  664.0|last_reward_at:  278|Elapsed Time: 0:00:02||
Episode 3|Iteration 290|reward:  764.0|last_reward_at:  278|Elapsed Time: 0:00:02||
Episode 3|Iteration 290|reward:  764.0|last_reward_at:  290|Elapsed Time: 0:00:02||
Episode 3|Iteration 297|reward:  764.0|last_reward_at:  290|Elapsed Time: 0:00:02||
Episode 3|Iteration 303|reward:  778.0|last_reward_at:  290|Elapsed Time: 0:00:03||
Episode 3|Iteration 303|reward:  778.0|last_reward_at:  303|Elapsed Time: 0:00:03||
Episode 3|Iteration 306|reward:  782.0|last_reward_at:  303|Elapsed Time: 0:00:03||
Episode 3|Iteration 306|reward:  782.0|last_reward_at:  306|Elapsed Time: 0:00:03||
Episode 3|Iteration 312|reward:  782.0|last_reward_at:  306|Elapsed Time: 0:00:03||
Episode 3|Iteration 316|reward:  788.0|last_reward_at:  306|Elapsed Time: 0:00:03||
Episode 3|Iteration 316|reward:  788.0|last_reward_at:  316|Elapsed Time: 0:00:03||
Episode 3|Iteration 325|reward:  788.0|last_reward_at:  316|Elapsed Time: 0:00:03||
Episode 3|Iteration 335|reward:  788.0|last_reward_at:  316|Elapsed Time: 0:00:03||
Episode 3|Iteration 341|reward:  794.0|last_reward_at:  316|Elapsed Time: 0:00:03||
Episode 3|Iteration 341|reward:  794.0|last_reward_at:  341|Elapsed Time: 0:00:03||
Episode 3|Iteration 350|reward:  794.0|last_reward_at:  341|Elapsed Time: 0:00:03||
Episode 3|Iteration 355|reward:  796.0|last_reward_at:  341|Elapsed Time: 0:00:03||
Episode 3|Iteration 355|reward:  796.0|last_reward_at:  355|Elapsed Time: 0:00:03||
Episode 3|Iteration 365|reward:  796.0|last_reward_at:  355|Elapsed Time: 0:00:03||
Episode 3|Iteration 373|reward:  796.0|last_reward_at:  355|Elapsed Time: 0:00:03||
Episode 3|Iteration 380|reward:  796.0|last_reward_at:  355|Elapsed Time: 0:00:03||
Episode 3|Iteration 388|reward:  796.0|last_reward_at:  355|Elapsed Time: 0:00:03||
Episode 3|Iteration 388|reward:  896.0|last_reward_at:  355|Elapsed Time: 0:00:03||
Episode 3|Iteration 388|reward:  896.0|last_reward_at:  388|Elapsed Time: 0:00:03||
Episode 3|Iteration 393|reward:  910.0|last_reward_at:  388|Elapsed Time: 0:00:04||
Episode 3|Iteration 393|reward:  910.0|last_reward_at:  393|Elapsed Time: 0:00:04||
Episode 3|Iteration 397|reward: 1010.0|last_reward_at:  393|Elapsed Time: 0:00:04||
Episode 3|Iteration 397|reward: 1010.0|last_reward_at:  397|Elapsed Time: 0:00:04||
Episode 3|Iteration 398|reward: 1024.0|last_reward_at:  397|Elapsed Time: 0:00:04||
Episode 3|Iteration 398|reward: 1024.0|last_reward_at:  398|Elapsed Time: 0:00:04||
Episode 3|Iteration 402|reward: 1030.0|last_reward_at:  398|Elapsed Time: 0:00:04||
Episode 3|Iteration 402|reward: 1030.0|last_reward_at:  402|Elapsed Time: 0:00:04||
Episode 3|Iteration 411|reward: 1030.0|last_reward_at:  402|Elapsed Time: 0:00:04||
Episode 3|Iteration 414|reward: 1036.0|last_reward_at:  402|Elapsed Time: 0:00:04||
Episode 3|Iteration 414|reward: 1036.0|last_reward_at:  414|Elapsed Time: 0:00:04||
Episode 3|Iteration 415|reward: 1040.0|last_reward_at:  414|Elapsed Time: 0:00:04||
Episode 3|Iteration 415|reward: 1040.0|last_reward_at:  415|Elapsed Time: 0:00:04||
Episode 3|Iteration 417|reward: 1140.0|last_reward_at:  415|Elapsed Time: 0:00:04||
Episode 3|Iteration 417|reward: 1140.0|last_reward_at:  417|Elapsed Time: 0:00:04||
Episode 3|Iteration 418|reward: 1154.0|last_reward_at:  417|Elapsed Time: 0:00:04||
Episode 3|Iteration 418|reward: 1154.0|last_reward_at:  418|Elapsed Time: 0:00:04||
Episode 3|Iteration 426|reward: 1154.0|last_reward_at:  418|Elapsed Time: 0:00:04||
Episode 3|Iteration 427|reward: 1160.0|last_reward_at:  418|Elapsed Time: 0:00:04||
Episode 3|Iteration 427|reward: 1160.0|last_reward_at:  427|Elapsed Time: 0:00:04||
Episode 3|Iteration 433|reward: 1160.0|last_reward_at:  427|Elapsed Time: 0:00:04||
Episode 3|Iteration 436|reward: 1260.0|last_reward_at:  427|Elapsed Time: 0:00:04||
Episode 3|Iteration 436|reward: 1260.0|last_reward_at:  436|Elapsed Time: 0:00:04||
Episode 3|Iteration 441|reward: 1260.0|last_reward_at:  436|Elapsed Time: 0:00:04||
Episode 3|Iteration 441|reward: 1271.0|last_reward_at:  436|Elapsed Time: 0:00:04||
Episode 3|Iteration 441|reward: 1271.0|last_reward_at:  441|Elapsed Time: 0:00:04||
Episode 3|Iteration 442|reward: 1280.0|last_reward_at:  441|Elapsed Time: 0:00:04||
Episode 3|Iteration 442|reward: 1280.0|last_reward_at:  442|Elapsed Time: 0:00:04||
Episode 3|Iteration 449|reward: 1280.0|last_reward_at:  442|Elapsed Time: 0:00:04||
Episode 3|Iteration 456|reward: 1280.0|last_reward_at:  442|Elapsed Time: 0:00:04||
Episode 3|Iteration 459|reward: 2280.0|last_reward_at:  442|Elapsed Time: 0:00:04||
Episode 3|Iteration 459|reward: 2280.0|last_reward_at:  459|Elapsed Time: 0:00:04||
Episode 3|Iteration 464|reward: 2280.0|last_reward_at:  459|Elapsed Time: 0:00:04||
Episode 3|Iteration 466|reward: 2280.0|last_reward_at:  459|Elapsed Time: 0:00:05||
Episode 3|Iteration 469|reward: 2280.0|last_reward_at:  459|Elapsed Time: 0:00:05||
Episode 3|Iteration 475|reward: 2280.0|last_reward_at:  459|Elapsed Time: 0:00:05||
Episode 3|Iteration 476|reward: 2286.0|last_reward_at:  459|Elapsed Time: 0:00:05||
Episode 3|Iteration 476|reward: 2286.0|last_reward_at:  476|Elapsed Time: 0:00:05||
Episode 3|Iteration 480|reward: 2286.0|last_reward_at:  476|Elapsed Time: 0:00:05||
Episode 3|Iteration 487|reward: 2286.0|last_reward_at:  476|Elapsed Time: 0:00:05||
Episode 3|Iteration 494|reward: 2286.0|last_reward_at:  476|Elapsed Time: 0:00:05||
Episode 3|Iteration 498|reward: 2286.0|last_reward_at:  476|Elapsed Time: 0:00:05||
Episode 3|Iteration 506|reward: 2292.0|last_reward_at:  476|Elapsed Time: 0:00:05||
Episode 3|Iteration 506|reward: 2292.0|last_reward_at:  506|Elapsed Time: 0:00:05||
Episode 3|Iteration 510|reward: 2298.0|last_reward_at:  506|Elapsed Time: 0:00:05||
Episode 3|Iteration 510|reward: 2298.0|last_reward_at:  510|Elapsed Time: 0:00:05||
Episode 3|Iteration 516|reward: 2300.0|last_reward_at:  510|Elapsed Time: 0:00:06||
Episode 3|Iteration 516|reward: 2300.0|last_reward_at:  516|Elapsed Time: 0:00:06||
Episode 3|Iteration 518|reward: 2300.0|last_reward_at:  516|Elapsed Time: 0:00:06||
Episode 3|Iteration 525|reward: 2300.0|last_reward_at:  516|Elapsed Time: 0:00:06||
Episode 3|Iteration 532|reward: 2300.0|last_reward_at:  516|Elapsed Time: 0:00:06||
Episode 3|Iteration 533|reward: 2300.0|last_reward_at:  516|Elapsed Time: 0:00:06||
Episode 3|Iteration 537|reward: 2300.0|last_reward_at:  516|Elapsed Time: 0:00:06||
Episode 3|Iteration 541|reward: 2300.0|last_reward_at:  516|Elapsed Time: 0:00:06||
Episode 3|Iteration 547|reward: 2300.0|last_reward_at:  516|Elapsed Time: 0:00:06||
Episode 3|Iteration 554|reward: 2300.0|last_reward_at:  516|Elapsed Time: 0:00:06||
Episode 3|Iteration 562|reward: 2300.0|last_reward_at:  516|Elapsed Time: 0:00:06||
Episode 3|Iteration 570|reward: 2300.0|last_reward_at:  516|Elapsed Time: 0:00:07||
Episode 3|Iteration 573|reward: 2306.0|last_reward_at:  516|Elapsed Time: 0:00:07||
Episode 3|Iteration 573|reward: 2306.0|last_reward_at:  573|Elapsed Time: 0:00:07||
Episode 3|Iteration 575|reward: 2306.0|last_reward_at:  573|Elapsed Time: 0:00:07||
Episode 3|Iteration 583|reward: 2306.0|last_reward_at:  573|Elapsed Time: 0:00:07||
Episode 3|Iteration 591|reward: 2306.0|last_reward_at:  573|Elapsed Time: 0:00:07||
Episode 3|Iteration 599|reward: 2306.0|last_reward_at:  573|Elapsed Time: 0:00:07||
Episode 3|Iteration 600|reward: 2306.0|last_reward_at:  573|Elapsed Time: 0:00:07||

  Episode 3 stopped at t=600
  Breakdown [Reward/NoReward (Success rate)]
    explore-local: 9/109 (0.08)
    explore-remote: 12/162 (0.07)
    explore-connect: 2/156 (0.01)
    exploit-local: 12/43 (0.22)
    exploit-remote: 8/52 (0.13)
    exploit-connect: 9/26 (0.26)
  exploit deflected to exploration: 14
  ## Episode: 4/10 'DQL' ϵ=0.6583, γ=0.15, lr=0.01, replaymemory=10000,
batch=256, target_update=5

Episode 4|Iteration 0|reward: ------|last_reward_at: ----|Elapsed Time: 0:00:00||
Episode 4|Iteration 1|reward:    0.0|last_reward_at: ----|Elapsed Time: 0:00:00||
Episode 4|Iteration 3|reward:   14.0|last_reward_at: ----|Elapsed Time: 0:00:00||
Episode 4|Iteration 3|reward:   14.0|last_reward_at:    3|Elapsed Time: 0:00:00||
Episode 4|Iteration 6|reward:   18.0|last_reward_at:    3|Elapsed Time: 0:00:00||
Episode 4|Iteration 6|reward:   18.0|last_reward_at:    6|Elapsed Time: 0:00:00||
Episode 4|Iteration 11|reward:   20.0|last_reward_at:    6|Elapsed Time: 0:00:00||
Episode 4|Iteration 11|reward:   20.0|last_reward_at:   11|Elapsed Time: 0:00:00||
Episode 4|Iteration 23|reward:   20.0|last_reward_at:   11|Elapsed Time: 0:00:00||
Episode 4|Iteration 31|reward:   20.0|last_reward_at:   11|Elapsed Time: 0:00:00||
Episode 4|Iteration 38|reward:   20.0|last_reward_at:   11|Elapsed Time: 0:00:00||
Episode 4|Iteration 46|reward:   20.0|last_reward_at:   11|Elapsed Time: 0:00:00||
Episode 4|Iteration 54|reward:   20.0|last_reward_at:   11|Elapsed Time: 0:00:00||
Episode 4|Iteration 60|reward:  120.0|last_reward_at:   11|Elapsed Time: 0:00:00||
Episode 4|Iteration 60|reward:  120.0|last_reward_at:   60|Elapsed Time: 0:00:00||
Episode 4|Iteration 62|reward:  134.0|last_reward_at:   60|Elapsed Time: 0:00:00||
Episode 4|Iteration 62|reward:  134.0|last_reward_at:   62|Elapsed Time: 0:00:00||
Episode 4|Iteration 65|reward:  140.0|last_reward_at:   62|Elapsed Time: 0:00:00||
Episode 4|Iteration 65|reward:  140.0|last_reward_at:   65|Elapsed Time: 0:00:00||
Episode 4|Iteration 70|reward:  148.0|last_reward_at:   65|Elapsed Time: 0:00:00||
Episode 4|Iteration 70|reward:  148.0|last_reward_at:   70|Elapsed Time: 0:00:00||
Episode 4|Iteration 80|reward:  154.0|last_reward_at:   70|Elapsed Time: 0:00:00||
Episode 4|Iteration 80|reward:  154.0|last_reward_at:   80|Elapsed Time: 0:00:00||
Episode 4|Iteration 92|reward:  154.0|last_reward_at:   80|Elapsed Time: 0:00:00||
Episode 4|Iteration 99|reward:  154.0|last_reward_at:   80|Elapsed Time: 0:00:00||
Episode 4|Iteration 107|reward:  154.0|last_reward_at:   80|Elapsed Time: 0:00:00||
Episode 4|Iteration 114|reward:  154.0|last_reward_at:   80|Elapsed Time: 0:00:00||
Episode 4|Iteration 122|reward:  154.0|last_reward_at:   80|Elapsed Time: 0:00:01||
Episode 4|Iteration 124|reward:  254.0|last_reward_at:   80|Elapsed Time: 0:00:01||
Episode 4|Iteration 124|reward:  254.0|last_reward_at:  124|Elapsed Time: 0:00:01||
Episode 4|Iteration 127|reward:  268.0|last_reward_at:  124|Elapsed Time: 0:00:01||
Episode 4|Iteration 127|reward:  268.0|last_reward_at:  127|Elapsed Time: 0:00:01||
Episode 4|Iteration 129|reward:  270.0|last_reward_at:  127|Elapsed Time: 0:00:01||
Episode 4|Iteration 129|reward:  270.0|last_reward_at:  129|Elapsed Time: 0:00:01||
Episode 4|Iteration 136|reward:  274.0|last_reward_at:  129|Elapsed Time: 0:00:01||
Episode 4|Iteration 136|reward:  274.0|last_reward_at:  136|Elapsed Time: 0:00:01||
Episode 4|Iteration 145|reward:  274.0|last_reward_at:  136|Elapsed Time: 0:00:01||
Episode 4|Iteration 152|reward:  274.0|last_reward_at:  136|Elapsed Time: 0:00:01||
Episode 4|Iteration 160|reward:  274.0|last_reward_at:  136|Elapsed Time: 0:00:01||
Episode 4|Iteration 168|reward:  274.0|last_reward_at:  136|Elapsed Time: 0:00:01||
Episode 4|Iteration 168|reward:  374.0|last_reward_at:  136|Elapsed Time: 0:00:01||
Episode 4|Iteration 168|reward:  374.0|last_reward_at:  168|Elapsed Time: 0:00:01||
Episode 4|Iteration 169|reward:  388.0|last_reward_at:  168|Elapsed Time: 0:00:01||
Episode 4|Iteration 169|reward:  388.0|last_reward_at:  169|Elapsed Time: 0:00:01||
Episode 4|Iteration 175|reward:  388.0|last_reward_at:  169|Elapsed Time: 0:00:01||
Episode 4|Iteration 181|reward:  394.0|last_reward_at:  169|Elapsed Time: 0:00:01||
Episode 4|Iteration 181|reward:  394.0|last_reward_at:  181|Elapsed Time: 0:00:01||
Episode 4|Iteration 186|reward:  400.0|last_reward_at:  181|Elapsed Time: 0:00:01||
Episode 4|Iteration 186|reward:  400.0|last_reward_at:  186|Elapsed Time: 0:00:01||
Episode 4|Iteration 189|reward:  408.0|last_reward_at:  186|Elapsed Time: 0:00:01||
Episode 4|Iteration 189|reward:  408.0|last_reward_at:  189|Elapsed Time: 0:00:01||
Episode 4|Iteration 195|reward:  414.0|last_reward_at:  189|Elapsed Time: 0:00:01||
Episode 4|Iteration 195|reward:  414.0|last_reward_at:  195|Elapsed Time: 0:00:01||
Episode 4|Iteration 204|reward:  514.0|last_reward_at:  195|Elapsed Time: 0:00:01||
Episode 4|Iteration 204|reward:  514.0|last_reward_at:  204|Elapsed Time: 0:00:01||
Episode 4|Iteration 208|reward:  528.0|last_reward_at:  204|Elapsed Time: 0:00:01||
Episode 4|Iteration 208|reward:  528.0|last_reward_at:  208|Elapsed Time: 0:00:01||
Episode 4|Iteration 212|reward:  530.0|last_reward_at:  208|Elapsed Time: 0:00:01||
Episode 4|Iteration 212|reward:  530.0|last_reward_at:  212|Elapsed Time: 0:00:01||
Episode 4|Iteration 214|reward:  630.0|last_reward_at:  212|Elapsed Time: 0:00:01||
Episode 4|Iteration 214|reward:  630.0|last_reward_at:  214|Elapsed Time: 0:00:01||
Episode 4|Iteration 221|reward:  630.0|last_reward_at:  214|Elapsed Time: 0:00:02||
Episode 4|Iteration 221|reward:  644.0|last_reward_at:  214|Elapsed Time: 0:00:02||
Episode 4|Iteration 221|reward:  644.0|last_reward_at:  221|Elapsed Time: 0:00:02||
Episode 4|Iteration 228|reward:  644.0|last_reward_at:  221|Elapsed Time: 0:00:02||
Episode 4|Iteration 229|reward:  652.0|last_reward_at:  221|Elapsed Time: 0:00:02||
Episode 4|Iteration 229|reward:  652.0|last_reward_at:  229|Elapsed Time: 0:00:02||
Episode 4|Iteration 231|reward:  658.0|last_reward_at:  229|Elapsed Time: 0:00:02||
Episode 4|Iteration 231|reward:  658.0|last_reward_at:  231|Elapsed Time: 0:00:02||
Episode 4|Iteration 241|reward:  658.0|last_reward_at:  231|Elapsed Time: 0:00:02||
Episode 4|Iteration 251|reward:  658.0|last_reward_at:  231|Elapsed Time: 0:00:02||
Episode 4|Iteration 256|reward:  660.0|last_reward_at:  231|Elapsed Time: 0:00:02||
Episode 4|Iteration 256|reward:  660.0|last_reward_at:  256|Elapsed Time: 0:00:02||
Episode 4|Iteration 262|reward:  760.0|last_reward_at:  256|Elapsed Time: 0:00:02||
Episode 4|Iteration 262|reward:  760.0|last_reward_at:  262|Elapsed Time: 0:00:02||
Episode 4|Iteration 264|reward:  774.0|last_reward_at:  262|Elapsed Time: 0:00:02||
Episode 4|Iteration 264|reward:  774.0|last_reward_at:  264|Elapsed Time: 0:00:02||
Episode 4|Iteration 265|reward:  874.0|last_reward_at:  264|Elapsed Time: 0:00:02||
Episode 4|Iteration 265|reward:  874.0|last_reward_at:  265|Elapsed Time: 0:00:02||
Episode 4|Iteration 267|reward:  888.0|last_reward_at:  265|Elapsed Time: 0:00:02||
Episode 4|Iteration 267|reward:  888.0|last_reward_at:  267|Elapsed Time: 0:00:02||
Episode 4|Iteration 274|reward:  888.0|last_reward_at:  267|Elapsed Time: 0:00:02||
Episode 4|Iteration 277|reward:  988.0|last_reward_at:  267|Elapsed Time: 0:00:02||
Episode 4|Iteration 277|reward:  988.0|last_reward_at:  277|Elapsed Time: 0:00:02||
Episode 4|Iteration 278|reward: 1002.0|last_reward_at:  277|Elapsed Time: 0:00:02||
Episode 4|Iteration 278|reward: 1002.0|last_reward_at:  278|Elapsed Time: 0:00:02||
Episode 4|Iteration 280|reward: 1008.0|last_reward_at:  278|Elapsed Time: 0:00:02||
Episode 4|Iteration 280|reward: 1008.0|last_reward_at:  280|Elapsed Time: 0:00:02||
Episode 4|Iteration 282|reward: 1108.0|last_reward_at:  280|Elapsed Time: 0:00:02||
Episode 4|Iteration 282|reward: 1108.0|last_reward_at:  282|Elapsed Time: 0:00:02||
Episode 4|Iteration 283|reward: 1122.0|last_reward_at:  282|Elapsed Time: 0:00:02||
Episode 4|Iteration 283|reward: 1122.0|last_reward_at:  283|Elapsed Time: 0:00:02||
Episode 4|Iteration 289|reward: 1122.0|last_reward_at:  283|Elapsed Time: 0:00:02||
Episode 4|Iteration 292|reward: 1124.0|last_reward_at:  283|Elapsed Time: 0:00:02||
Episode 4|Iteration 292|reward: 1124.0|last_reward_at:  292|Elapsed Time: 0:00:02||
Episode 4|Iteration 293|reward: 1130.0|last_reward_at:  292|Elapsed Time: 0:00:02||
Episode 4|Iteration 293|reward: 1130.0|last_reward_at:  293|Elapsed Time: 0:00:02||
Episode 4|Iteration 297|reward: 1136.0|last_reward_at:  293|Elapsed Time: 0:00:02||
Episode 4|Iteration 297|reward: 1136.0|last_reward_at:  297|Elapsed Time: 0:00:02||
Episode 4|Iteration 303|reward: 1144.0|last_reward_at:  297|Elapsed Time: 0:00:03||
Episode 4|Iteration 303|reward: 1144.0|last_reward_at:  303|Elapsed Time: 0:00:03||
Episode 4|Iteration 306|reward: 1244.0|last_reward_at:  303|Elapsed Time: 0:00:03||
Episode 4|Iteration 306|reward: 1244.0|last_reward_at:  306|Elapsed Time: 0:00:03||
Episode 4|Iteration 307|reward: 1246.0|last_reward_at:  306|Elapsed Time: 0:00:03||
Episode 4|Iteration 307|reward: 1246.0|last_reward_at:  307|Elapsed Time: 0:00:03||
Episode 4|Iteration 309|reward: 1260.0|last_reward_at:  307|Elapsed Time: 0:00:03||
Episode 4|Iteration 309|reward: 1260.0|last_reward_at:  309|Elapsed Time: 0:00:03||
Episode 4|Iteration 312|reward: 2260.0|last_reward_at:  309|Elapsed Time: 0:00:03||
Episode 4|Iteration 312|reward: 2260.0|last_reward_at:  312|Elapsed Time: 0:00:03||
Episode 4|Iteration 315|reward: 2260.0|last_reward_at:  312|Elapsed Time: 0:00:03||
Episode 4|Iteration 323|reward: 2262.0|last_reward_at:  312|Elapsed Time: 0:00:03||
Episode 4|Iteration 323|reward: 2262.0|last_reward_at:  323|Elapsed Time: 0:00:03||
Episode 4|Iteration 330|reward: 2262.0|last_reward_at:  323|Elapsed Time: 0:00:03||
Episode 4|Iteration 335|reward: 2262.0|last_reward_at:  323|Elapsed Time: 0:00:03||
Episode 4|Iteration 336|reward: 2268.0|last_reward_at:  323|Elapsed Time: 0:00:03||
Episode 4|Iteration 336|reward: 2268.0|last_reward_at:  336|Elapsed Time: 0:00:03||
Episode 4|Iteration 340|reward: 2274.0|last_reward_at:  336|Elapsed Time: 0:00:03||
Episode 4|Iteration 340|reward: 2274.0|last_reward_at:  340|Elapsed Time: 0:00:03||
Episode 4|Iteration 348|reward: 2274.0|last_reward_at:  340|Elapsed Time: 0:00:03||
Episode 4|Iteration 353|reward: 2274.0|last_reward_at:  340|Elapsed Time: 0:00:04||
Episode 4|Iteration 357|reward: 2274.0|last_reward_at:  340|Elapsed Time: 0:00:04||
Episode 4|Iteration 361|reward: 2280.0|last_reward_at:  340|Elapsed Time: 0:00:04||
Episode 4|Iteration 361|reward: 2280.0|last_reward_at:  361|Elapsed Time: 0:00:04||
Episode 4|Iteration 367|reward: 2280.0|last_reward_at:  361|Elapsed Time: 0:00:04||
Episode 4|Iteration 373|reward: 2280.0|last_reward_at:  361|Elapsed Time: 0:00:04||
Episode 4|Iteration 380|reward: 2280.0|last_reward_at:  361|Elapsed Time: 0:00:04||
Episode 4|Iteration 387|reward: 2280.0|last_reward_at:  361|Elapsed Time: 0:00:04||
Episode 4|Iteration 394|reward: 2280.0|last_reward_at:  361|Elapsed Time: 0:00:04||
Episode 4|Iteration 402|reward: 2280.0|last_reward_at:  361|Elapsed Time: 0:00:04||
Episode 4|Iteration 405|reward: 2280.0|last_reward_at:  361|Elapsed Time: 0:00:04||
Episode 4|Iteration 406|reward: 2286.0|last_reward_at:  361|Elapsed Time: 0:00:04||
Episode 4|Iteration 406|reward: 2286.0|last_reward_at:  406|Elapsed Time: 0:00:04||
Episode 4|Iteration 411|reward: 2286.0|last_reward_at:  406|Elapsed Time: 0:00:04||
Episode 4|Iteration 418|reward: 2286.0|last_reward_at:  406|Elapsed Time: 0:00:05||
Episode 4|Iteration 419|reward: 2286.0|last_reward_at:  406|Elapsed Time: 0:00:05||
Episode 4|Iteration 426|reward: 2286.0|last_reward_at:  406|Elapsed Time: 0:00:05||
Episode 4|Iteration 430|reward: 2292.0|last_reward_at:  406|Elapsed Time: 0:00:05||
Episode 4|Iteration 430|reward: 2292.0|last_reward_at:  430|Elapsed Time: 0:00:05||
Episode 4|Iteration 438|reward: 2292.0|last_reward_at:  430|Elapsed Time: 0:00:05||
Episode 4|Iteration 445|reward: 2292.0|last_reward_at:  430|Elapsed Time: 0:00:05||
Episode 4|Iteration 453|reward: 2292.0|last_reward_at:  430|Elapsed Time: 0:00:05||
Episode 4|Iteration 462|reward: 2292.0|last_reward_at:  430|Elapsed Time: 0:00:05||
Episode 4|Iteration 471|reward: 2292.0|last_reward_at:  430|Elapsed Time: 0:00:05||
Episode 4|Iteration 473|reward: 2294.0|last_reward_at:  430|Elapsed Time: 0:00:05||
Episode 4|Iteration 473|reward: 2294.0|last_reward_at:  473|Elapsed Time: 0:00:05||
Episode 4|Iteration 479|reward: 2294.0|last_reward_at:  473|Elapsed Time: 0:00:05||
Episode 4|Iteration 486|reward: 2294.0|last_reward_at:  473|Elapsed Time: 0:00:06||
Episode 4|Iteration 492|reward: 2294.0|last_reward_at:  473|Elapsed Time: 0:00:06||
Episode 4|Iteration 500|reward: 2294.0|last_reward_at:  473|Elapsed Time: 0:00:06||
Episode 4|Iteration 508|reward: 2294.0|last_reward_at:  473|Elapsed Time: 0:00:06||
Episode 4|Iteration 516|reward: 2294.0|last_reward_at:  473|Elapsed Time: 0:00:06||
Episode 4|Iteration 524|reward: 2294.0|last_reward_at:  473|Elapsed Time: 0:00:06||
Episode 4|Iteration 531|reward: 2294.0|last_reward_at:  473|Elapsed Time: 0:00:06||
Episode 4|Iteration 539|reward: 2294.0|last_reward_at:  473|Elapsed Time: 0:00:06||
Episode 4|Iteration 547|reward: 2294.0|last_reward_at:  473|Elapsed Time: 0:00:07||
Episode 4|Iteration 554|reward: 2294.0|last_reward_at:  473|Elapsed Time: 0:00:07||
Episode 4|Iteration 562|reward: 2294.0|last_reward_at:  473|Elapsed Time: 0:00:07||
Episode 4|Iteration 570|reward: 2294.0|last_reward_at:  473|Elapsed Time: 0:00:07||
Episode 4|Iteration 572|reward: 2294.0|last_reward_at:  473|Elapsed Time: 0:00:07||
Episode 4|Iteration 578|reward: 2294.0|last_reward_at:  473|Elapsed Time: 0:00:07||
Episode 4|Iteration 585|reward: 2294.0|last_reward_at:  473|Elapsed Time: 0:00:07||
Episode 4|Iteration 592|reward: 2294.0|last_reward_at:  473|Elapsed Time: 0:00:07||
Episode 4|Iteration 600|reward: 2294.0|last_reward_at:  473|Elapsed Time: 0:00:07||
Episode 4|Iteration 600|reward: 2294.0|last_reward_at:  473|Elapsed Time: 0:00:07||

  Episode 4 stopped at t=600
  Breakdown [Reward/NoReward (Success rate)]
    explore-local: 6/89 (0.06)
    explore-remote: 14/125 (0.10)
    explore-connect: 1/160 (0.01)
    exploit-local: 13/51 (0.20)
    exploit-remote: 6/114 (0.05)
    exploit-connect: 10/11 (0.48)
  exploit deflected to exploration: 16
  ## Episode: 5/10 'DQL' ϵ=0.5951, γ=0.15, lr=0.01, replaymemory=10000,
batch=256, target_update=5

Episode 5|Iteration 0|reward: ------|last_reward_at: ----|Elapsed Time: 0:00:00||
Episode 5|Iteration 1|reward:   14.0|last_reward_at: ----|Elapsed Time: 0:00:00||
Episode 5|Iteration 1|reward:   14.0|last_reward_at:    1|Elapsed Time: 0:00:00||
Episode 5|Iteration 4|reward:   16.0|last_reward_at:    1|Elapsed Time: 0:00:00||
Episode 5|Iteration 4|reward:   16.0|last_reward_at:    4|Elapsed Time: 0:00:00||
Episode 5|Iteration 8|reward:   20.0|last_reward_at:    4|Elapsed Time: 0:00:00||
Episode 5|Iteration 8|reward:   20.0|last_reward_at:    8|Elapsed Time: 0:00:00||
Episode 5|Iteration 9|reward:  120.0|last_reward_at:    8|Elapsed Time: 0:00:00||
Episode 5|Iteration 9|reward:  120.0|last_reward_at:    9|Elapsed Time: 0:00:00||
Episode 5|Iteration 10|reward:  134.0|last_reward_at:    9|Elapsed Time: 0:00:00||
Episode 5|Iteration 10|reward:  134.0|last_reward_at:   10|Elapsed Time: 0:00:00||
Episode 5|Iteration 15|reward:  140.0|last_reward_at:   10|Elapsed Time: 0:00:00||
Episode 5|Iteration 15|reward:  140.0|last_reward_at:   15|Elapsed Time: 0:00:00||
Episode 5|Iteration 16|reward:  148.0|last_reward_at:   15|Elapsed Time: 0:00:00||
Episode 5|Iteration 16|reward:  148.0|last_reward_at:   16|Elapsed Time: 0:00:00||
Episode 5|Iteration 19|reward:  154.0|last_reward_at:   16|Elapsed Time: 0:00:00||
Episode 5|Iteration 19|reward:  154.0|last_reward_at:   19|Elapsed Time: 0:00:00||
Episode 5|Iteration 31|reward:  154.0|last_reward_at:   19|Elapsed Time: 0:00:00||
Episode 5|Iteration 31|reward:  254.0|last_reward_at:   19|Elapsed Time: 0:00:00||
Episode 5|Iteration 31|reward:  254.0|last_reward_at:   31|Elapsed Time: 0:00:00||
Episode 5|Iteration 32|reward:  268.0|last_reward_at:   31|Elapsed Time: 0:00:00||
Episode 5|Iteration 32|reward:  268.0|last_reward_at:   32|Elapsed Time: 0:00:00||
Episode 5|Iteration 35|reward:  272.0|last_reward_at:   32|Elapsed Time: 0:00:00||
Episode 5|Iteration 35|reward:  272.0|last_reward_at:   35|Elapsed Time: 0:00:00||
Episode 5|Iteration 36|reward:  372.0|last_reward_at:   35|Elapsed Time: 0:00:00||
Episode 5|Iteration 36|reward:  372.0|last_reward_at:   36|Elapsed Time: 0:00:00||
Episode 5|Iteration 37|reward:  386.0|last_reward_at:   36|Elapsed Time: 0:00:00||
Episode 5|Iteration 37|reward:  386.0|last_reward_at:   37|Elapsed Time: 0:00:00||
Episode 5|Iteration 39|reward:  486.0|last_reward_at:   37|Elapsed Time: 0:00:00||
Episode 5|Iteration 39|reward:  486.0|last_reward_at:   39|Elapsed Time: 0:00:00||
Episode 5|Iteration 40|reward:  500.0|last_reward_at:   39|Elapsed Time: 0:00:00||
Episode 5|Iteration 40|reward:  500.0|last_reward_at:   40|Elapsed Time: 0:00:00||
Episode 5|Iteration 43|reward:  600.0|last_reward_at:   40|Elapsed Time: 0:00:00||
Episode 5|Iteration 43|reward:  600.0|last_reward_at:   43|Elapsed Time: 0:00:00||
Episode 5|Iteration 44|reward:  614.0|last_reward_at:   43|Elapsed Time: 0:00:00||
Episode 5|Iteration 44|reward:  614.0|last_reward_at:   44|Elapsed Time: 0:00:00||
Episode 5|Iteration 45|reward:  616.0|last_reward_at:   44|Elapsed Time: 0:00:00||
Episode 5|Iteration 45|reward:  616.0|last_reward_at:   45|Elapsed Time: 0:00:00||
Episode 5|Iteration 49|reward:  622.0|last_reward_at:   45|Elapsed Time: 0:00:00||
Episode 5|Iteration 49|reward:  622.0|last_reward_at:   49|Elapsed Time: 0:00:00||
Episode 5|Iteration 56|reward:  628.0|last_reward_at:   49|Elapsed Time: 0:00:00||
Episode 5|Iteration 56|reward:  628.0|last_reward_at:   56|Elapsed Time: 0:00:00||
Episode 5|Iteration 64|reward:  636.0|last_reward_at:   56|Elapsed Time: 0:00:00||
Episode 5|Iteration 64|reward:  636.0|last_reward_at:   64|Elapsed Time: 0:00:00||
Episode 5|Iteration 67|reward:  642.0|last_reward_at:   64|Elapsed Time: 0:00:00||
Episode 5|Iteration 67|reward:  642.0|last_reward_at:   67|Elapsed Time: 0:00:00||
Episode 5|Iteration 75|reward:  644.0|last_reward_at:   67|Elapsed Time: 0:00:00||
Episode 5|Iteration 75|reward:  644.0|last_reward_at:   75|Elapsed Time: 0:00:00||
Episode 5|Iteration 76|reward:  650.0|last_reward_at:   75|Elapsed Time: 0:00:00||
Episode 5|Iteration 76|reward:  650.0|last_reward_at:   76|Elapsed Time: 0:00:00||
Episode 5|Iteration 84|reward:  650.0|last_reward_at:   76|Elapsed Time: 0:00:00||
Episode 5|Iteration 85|reward:  750.0|last_reward_at:   76|Elapsed Time: 0:00:00||
Episode 5|Iteration 85|reward:  750.0|last_reward_at:   85|Elapsed Time: 0:00:00||
Episode 5|Iteration 89|reward:  764.0|last_reward_at:   85|Elapsed Time: 0:00:01||
Episode 5|Iteration 89|reward:  764.0|last_reward_at:   89|Elapsed Time: 0:00:01||
Episode 5|Iteration 94|reward:  864.0|last_reward_at:   89|Elapsed Time: 0:00:01||
Episode 5|Iteration 94|reward:  864.0|last_reward_at:   94|Elapsed Time: 0:00:01||
Episode 5|Iteration 95|reward:  878.0|last_reward_at:   94|Elapsed Time: 0:00:01||
Episode 5|Iteration 95|reward:  878.0|last_reward_at:   95|Elapsed Time: 0:00:01||
Episode 5|Iteration 99|reward:  884.0|last_reward_at:   95|Elapsed Time: 0:00:01||
Episode 5|Iteration 99|reward:  884.0|last_reward_at:   99|Elapsed Time: 0:00:01||
Episode 5|Iteration 101|reward:  890.0|last_reward_at:   99|Elapsed Time: 0:00:01||
Episode 5|Iteration 101|reward:  890.0|last_reward_at:  101|Elapsed Time: 0:00:01||
Episode 5|Iteration 107|reward:  890.0|last_reward_at:  101|Elapsed Time: 0:00:01||
Episode 5|Iteration 107|reward:  892.0|last_reward_at:  101|Elapsed Time: 0:00:01||
Episode 5|Iteration 107|reward:  892.0|last_reward_at:  107|Elapsed Time: 0:00:01||
Episode 5|Iteration 108|reward:  900.0|last_reward_at:  107|Elapsed Time: 0:00:01||
Episode 5|Iteration 108|reward:  900.0|last_reward_at:  108|Elapsed Time: 0:00:01||
Episode 5|Iteration 114|reward:  900.0|last_reward_at:  108|Elapsed Time: 0:00:01||
Episode 5|Iteration 114|reward:  902.0|last_reward_at:  108|Elapsed Time: 0:00:01||
Episode 5|Iteration 114|reward:  902.0|last_reward_at:  114|Elapsed Time: 0:00:01||
Episode 5|Iteration 121|reward:  904.0|last_reward_at:  114|Elapsed Time: 0:00:01||
Episode 5|Iteration 121|reward:  904.0|last_reward_at:  121|Elapsed Time: 0:00:01||
Episode 5|Iteration 130|reward:  904.0|last_reward_at:  121|Elapsed Time: 0:00:01||
Episode 5|Iteration 133|reward:  910.0|last_reward_at:  121|Elapsed Time: 0:00:01||
Episode 5|Iteration 133|reward:  910.0|last_reward_at:  133|Elapsed Time: 0:00:01||
Episode 5|Iteration 143|reward:  910.0|last_reward_at:  133|Elapsed Time: 0:00:01||
Episode 5|Iteration 147|reward:  916.0|last_reward_at:  133|Elapsed Time: 0:00:01||
Episode 5|Iteration 147|reward:  916.0|last_reward_at:  147|Elapsed Time: 0:00:01||
Episode 5|Iteration 157|reward: 1016.0|last_reward_at:  147|Elapsed Time: 0:00:01||
Episode 5|Iteration 157|reward: 1016.0|last_reward_at:  157|Elapsed Time: 0:00:01||
Episode 5|Iteration 159|reward: 1030.0|last_reward_at:  157|Elapsed Time: 0:00:01||
Episode 5|Iteration 159|reward: 1030.0|last_reward_at:  159|Elapsed Time: 0:00:01||
Episode 5|Iteration 160|reward: 1130.0|last_reward_at:  159|Elapsed Time: 0:00:01||
Episode 5|Iteration 160|reward: 1130.0|last_reward_at:  160|Elapsed Time: 0:00:01||
Episode 5|Iteration 164|reward: 1144.0|last_reward_at:  160|Elapsed Time: 0:00:01||
Episode 5|Iteration 164|reward: 1144.0|last_reward_at:  164|Elapsed Time: 0:00:01||
Episode 5|Iteration 166|reward: 1146.0|last_reward_at:  164|Elapsed Time: 0:00:01||
Episode 5|Iteration 166|reward: 1146.0|last_reward_at:  166|Elapsed Time: 0:00:01||
Episode 5|Iteration 171|reward: 1152.0|last_reward_at:  166|Elapsed Time: 0:00:01||
Episode 5|Iteration 171|reward: 1152.0|last_reward_at:  171|Elapsed Time: 0:00:02||
Episode 5|Iteration 180|reward: 1152.0|last_reward_at:  171|Elapsed Time: 0:00:02||
Episode 5|Iteration 188|reward: 1152.0|last_reward_at:  171|Elapsed Time: 0:00:02||
Episode 5|Iteration 195|reward: 1152.0|last_reward_at:  171|Elapsed Time: 0:00:02||
Episode 5|Iteration 204|reward: 1152.0|last_reward_at:  171|Elapsed Time: 0:00:02||
Episode 5|Iteration 207|reward: 1160.0|last_reward_at:  171|Elapsed Time: 0:00:02||
Episode 5|Iteration 207|reward: 1160.0|last_reward_at:  207|Elapsed Time: 0:00:02||
Episode 5|Iteration 213|reward: 1160.0|last_reward_at:  207|Elapsed Time: 0:00:02||
Episode 5|Iteration 217|reward: 1166.0|last_reward_at:  207|Elapsed Time: 0:00:02||
Episode 5|Iteration 217|reward: 1166.0|last_reward_at:  217|Elapsed Time: 0:00:02||
Episode 5|Iteration 225|reward: 1166.0|last_reward_at:  217|Elapsed Time: 0:00:02||
Episode 5|Iteration 234|reward: 1166.0|last_reward_at:  217|Elapsed Time: 0:00:02||
Episode 5|Iteration 243|reward: 1166.0|last_reward_at:  217|Elapsed Time: 0:00:02||
Episode 5|Iteration 251|reward: 1166.0|last_reward_at:  217|Elapsed Time: 0:00:02||
Episode 5|Iteration 259|reward: 1166.0|last_reward_at:  217|Elapsed Time: 0:00:03||
Episode 5|Iteration 266|reward: 1166.0|last_reward_at:  217|Elapsed Time: 0:00:03||
Episode 5|Iteration 274|reward: 1166.0|last_reward_at:  217|Elapsed Time: 0:00:03||
Episode 5|Iteration 280|reward: 1172.0|last_reward_at:  217|Elapsed Time: 0:00:03||
Episode 5|Iteration 280|reward: 1172.0|last_reward_at:  280|Elapsed Time: 0:00:03||
Episode 5|Iteration 288|reward: 1172.0|last_reward_at:  280|Elapsed Time: 0:00:03||
Episode 5|Iteration 296|reward: 1172.0|last_reward_at:  280|Elapsed Time: 0:00:03||
Episode 5|Iteration 297|reward: 1272.0|last_reward_at:  280|Elapsed Time: 0:00:03||
Episode 5|Iteration 297|reward: 1272.0|last_reward_at:  297|Elapsed Time: 0:00:03||
Episode 5|Iteration 299|reward: 1286.0|last_reward_at:  297|Elapsed Time: 0:00:03||
Episode 5|Iteration 299|reward: 1286.0|last_reward_at:  299|Elapsed Time: 0:00:03||
Episode 5|Iteration 301|reward: 2286.0|last_reward_at:  299|Elapsed Time: 0:00:03||
Episode 5|Iteration 301|reward: 2286.0|last_reward_at:  301|Elapsed Time: 0:00:03||
Episode 5|Iteration 309|reward: 2286.0|last_reward_at:  301|Elapsed Time: 0:00:03||
Episode 5|Iteration 317|reward: 2286.0|last_reward_at:  301|Elapsed Time: 0:00:03||
Episode 5|Iteration 325|reward: 2286.0|last_reward_at:  301|Elapsed Time: 0:00:03||
Episode 5|Iteration 333|reward: 2286.0|last_reward_at:  301|Elapsed Time: 0:00:04||
Episode 5|Iteration 334|reward: 2288.0|last_reward_at:  301|Elapsed Time: 0:00:04||
Episode 5|Iteration 334|reward: 2288.0|last_reward_at:  334|Elapsed Time: 0:00:04||
Episode 5|Iteration 338|reward: 2294.0|last_reward_at:  334|Elapsed Time: 0:00:04||
Episode 5|Iteration 338|reward: 2294.0|last_reward_at:  338|Elapsed Time: 0:00:04||
Episode 5|Iteration 346|reward: 2294.0|last_reward_at:  338|Elapsed Time: 0:00:04||
Episode 5|Iteration 354|reward: 2294.0|last_reward_at:  338|Elapsed Time: 0:00:04||
Episode 5|Iteration 362|reward: 2294.0|last_reward_at:  338|Elapsed Time: 0:00:04||
Episode 5|Iteration 370|reward: 2294.0|last_reward_at:  338|Elapsed Time: 0:00:04||
Episode 5|Iteration 378|reward: 2294.0|last_reward_at:  338|Elapsed Time: 0:00:04||
Episode 5|Iteration 386|reward: 2294.0|last_reward_at:  338|Elapsed Time: 0:00:04||
Episode 5|Iteration 394|reward: 2294.0|last_reward_at:  338|Elapsed Time: 0:00:04||
Episode 5|Iteration 402|reward: 2294.0|last_reward_at:  338|Elapsed Time: 0:00:04||
Episode 5|Iteration 410|reward: 2294.0|last_reward_at:  338|Elapsed Time: 0:00:05||
Episode 5|Iteration 418|reward: 2294.0|last_reward_at:  338|Elapsed Time: 0:00:05||
Episode 5|Iteration 420|reward: 2294.0|last_reward_at:  338|Elapsed Time: 0:00:05||
Episode 5|Iteration 423|reward: 2294.0|last_reward_at:  338|Elapsed Time: 0:00:05||
Episode 5|Iteration 431|reward: 2294.0|last_reward_at:  338|Elapsed Time: 0:00:05||
Episode 5|Iteration 435|reward: 2300.0|last_reward_at:  338|Elapsed Time: 0:00:05||
Episode 5|Iteration 435|reward: 2300.0|last_reward_at:  435|Elapsed Time: 0:00:05||
Episode 5|Iteration 441|reward: 2300.0|last_reward_at:  435|Elapsed Time: 0:00:05||
Episode 5|Iteration 448|reward: 2300.0|last_reward_at:  435|Elapsed Time: 0:00:05||
Episode 5|Iteration 456|reward: 2300.0|last_reward_at:  435|Elapsed Time: 0:00:05||
Episode 5|Iteration 464|reward: 2300.0|last_reward_at:  435|Elapsed Time: 0:00:05||
Episode 5|Iteration 471|reward: 2300.0|last_reward_at:  435|Elapsed Time: 0:00:06||
Episode 5|Iteration 477|reward: 2300.0|last_reward_at:  435|Elapsed Time: 0:00:06||
Episode 5|Iteration 485|reward: 2300.0|last_reward_at:  435|Elapsed Time: 0:00:06||
Episode 5|Iteration 493|reward: 2300.0|last_reward_at:  435|Elapsed Time: 0:00:06||
Episode 5|Iteration 501|reward: 2300.0|last_reward_at:  435|Elapsed Time: 0:00:06||
Episode 5|Iteration 509|reward: 2300.0|last_reward_at:  435|Elapsed Time: 0:00:06||
Episode 5|Iteration 509|reward: 2306.0|last_reward_at:  435|Elapsed Time: 0:00:06||
Episode 5|Iteration 509|reward: 2306.0|last_reward_at:  509|Elapsed Time: 0:00:06||
Episode 5|Iteration 511|reward: 2306.0|last_reward_at:  509|Elapsed Time: 0:00:06||
Episode 5|Iteration 517|reward: 2306.0|last_reward_at:  509|Elapsed Time: 0:00:06||
Episode 5|Iteration 519|reward: 2306.0|last_reward_at:  509|Elapsed Time: 0:00:06||
Episode 5|Iteration 525|reward: 2306.0|last_reward_at:  509|Elapsed Time: 0:00:06||
Episode 5|Iteration 532|reward: 2306.0|last_reward_at:  509|Elapsed Time: 0:00:07||
Episode 5|Iteration 539|reward: 2306.0|last_reward_at:  509|Elapsed Time: 0:00:07||
Episode 5|Iteration 547|reward: 2306.0|last_reward_at:  509|Elapsed Time: 0:00:07||
Episode 5|Iteration 554|reward: 2306.0|last_reward_at:  509|Elapsed Time: 0:00:07||
Episode 5|Iteration 562|reward: 2306.0|last_reward_at:  509|Elapsed Time: 0:00:07||
Episode 5|Iteration 570|reward: 2306.0|last_reward_at:  509|Elapsed Time: 0:00:07||
Episode 5|Iteration 577|reward: 2306.0|last_reward_at:  509|Elapsed Time: 0:00:07||
Episode 5|Iteration 585|reward: 2306.0|last_reward_at:  509|Elapsed Time: 0:00:07||
Episode 5|Iteration 592|reward: 2306.0|last_reward_at:  509|Elapsed Time: 0:00:07||
Episode 5|Iteration 599|reward: 2306.0|last_reward_at:  509|Elapsed Time: 0:00:07||
Episode 5|Iteration 600|reward: 2306.0|last_reward_at:  509|Elapsed Time: 0:00:07||

  Episode 5 stopped at t=600
  Breakdown [Reward/NoReward (Success rate)]
    explore-local: 7/85 (0.08)
    explore-remote: 8/113 (0.07)
    explore-connect: 1/124 (0.01)
    exploit-local: 14/51 (0.22)
    exploit-remote: 12/174 (0.06)
    exploit-connect: 10/1 (0.91)
  exploit deflected to exploration: 5
  ## Episode: 6/10 'DQL' ϵ=0.5391, γ=0.15, lr=0.01, replaymemory=10000,
batch=256, target_update=5

Episode 6|Iteration 0|reward: ------|last_reward_at: ----|Elapsed Time: 0:00:00||
Episode 6|Iteration 1|reward:    0.0|last_reward_at: ----|Elapsed Time: 0:00:00||
Episode 6|Iteration 8|reward:    0.0|last_reward_at: ----|Elapsed Time: 0:00:00||
Episode 6|Iteration 8|reward:   14.0|last_reward_at: ----|Elapsed Time: 0:00:00||
Episode 6|Iteration 8|reward:   14.0|last_reward_at:    8|Elapsed Time: 0:00:00||
Episode 6|Iteration 9|reward:   18.0|last_reward_at:    8|Elapsed Time: 0:00:00||
Episode 6|Iteration 9|reward:   18.0|last_reward_at:    9|Elapsed Time: 0:00:00||
Episode 6|Iteration 12|reward:   20.0|last_reward_at:    9|Elapsed Time: 0:00:00||
Episode 6|Iteration 12|reward:   20.0|last_reward_at:   12|Elapsed Time: 0:00:00||
Episode 6|Iteration 23|reward:   20.0|last_reward_at:   12|Elapsed Time: 0:00:00||
Episode 6|Iteration 26|reward:  120.0|last_reward_at:   12|Elapsed Time: 0:00:00||
Episode 6|Iteration 26|reward:  120.0|last_reward_at:   26|Elapsed Time: 0:00:00||
Episode 6|Iteration 27|reward:  134.0|last_reward_at:   26|Elapsed Time: 0:00:00||
Episode 6|Iteration 27|reward:  134.0|last_reward_at:   27|Elapsed Time: 0:00:00||
Episode 6|Iteration 29|reward:  142.0|last_reward_at:   27|Elapsed Time: 0:00:00||
Episode 6|Iteration 29|reward:  142.0|last_reward_at:   29|Elapsed Time: 0:00:00||
Episode 6|Iteration 38|reward:  142.0|last_reward_at:   29|Elapsed Time: 0:00:00||
Episode 6|Iteration 46|reward:  142.0|last_reward_at:   29|Elapsed Time: 0:00:00||
Episode 6|Iteration 46|reward:  242.0|last_reward_at:   29|Elapsed Time: 0:00:00||
Episode 6|Iteration 46|reward:  242.0|last_reward_at:   46|Elapsed Time: 0:00:00||
Episode 6|Iteration 48|reward:  248.0|last_reward_at:   46|Elapsed Time: 0:00:00||
Episode 6|Iteration 48|reward:  248.0|last_reward_at:   48|Elapsed Time: 0:00:00||
Episode 6|Iteration 50|reward:  262.0|last_reward_at:   48|Elapsed Time: 0:00:00||
Episode 6|Iteration 50|reward:  262.0|last_reward_at:   50|Elapsed Time: 0:00:00||
Episode 6|Iteration 51|reward:  362.0|last_reward_at:   50|Elapsed Time: 0:00:00||
Episode 6|Iteration 51|reward:  362.0|last_reward_at:   51|Elapsed Time: 0:00:00||
Episode 6|Iteration 53|reward:  376.0|last_reward_at:   51|Elapsed Time: 0:00:00||
Episode 6|Iteration 53|reward:  376.0|last_reward_at:   53|Elapsed Time: 0:00:00||
Episode 6|Iteration 57|reward:  476.0|last_reward_at:   53|Elapsed Time: 0:00:00||
Episode 6|Iteration 57|reward:  476.0|last_reward_at:   57|Elapsed Time: 0:00:00||
Episode 6|Iteration 58|reward:  490.0|last_reward_at:   57|Elapsed Time: 0:00:00||
Episode 6|Iteration 58|reward:  490.0|last_reward_at:   58|Elapsed Time: 0:00:00||
Episode 6|Iteration 61|reward:  590.0|last_reward_at:   58|Elapsed Time: 0:00:00||
Episode 6|Iteration 61|reward:  590.0|last_reward_at:   61|Elapsed Time: 0:00:00||
Episode 6|Iteration 62|reward:  604.0|last_reward_at:   61|Elapsed Time: 0:00:00||
Episode 6|Iteration 62|reward:  604.0|last_reward_at:   62|Elapsed Time: 0:00:00||
Episode 6|Iteration 65|reward:  606.0|last_reward_at:   62|Elapsed Time: 0:00:00||
Episode 6|Iteration 65|reward:  606.0|last_reward_at:   65|Elapsed Time: 0:00:00||
Episode 6|Iteration 67|reward:  612.0|last_reward_at:   65|Elapsed Time: 0:00:00||
Episode 6|Iteration 67|reward:  612.0|last_reward_at:   67|Elapsed Time: 0:00:00||
Episode 6|Iteration 69|reward:  712.0|last_reward_at:   67|Elapsed Time: 0:00:00||
Episode 6|Iteration 69|reward:  712.0|last_reward_at:   69|Elapsed Time: 0:00:00||
Episode 6|Iteration 72|reward:  726.0|last_reward_at:   69|Elapsed Time: 0:00:00||
Episode 6|Iteration 72|reward:  726.0|last_reward_at:   72|Elapsed Time: 0:00:00||
Episode 6|Iteration 73|reward:  728.0|last_reward_at:   72|Elapsed Time: 0:00:00||
Episode 6|Iteration 73|reward:  728.0|last_reward_at:   73|Elapsed Time: 0:00:00||
Episode 6|Iteration 74|reward:  828.0|last_reward_at:   73|Elapsed Time: 0:00:00||
Episode 6|Iteration 74|reward:  828.0|last_reward_at:   74|Elapsed Time: 0:00:00||
Episode 6|Iteration 75|reward:  842.0|last_reward_at:   74|Elapsed Time: 0:00:00||
Episode 6|Iteration 75|reward:  842.0|last_reward_at:   75|Elapsed Time: 0:00:00||
Episode 6|Iteration 77|reward:  942.0|last_reward_at:   75|Elapsed Time: 0:00:00||
Episode 6|Iteration 77|reward:  942.0|last_reward_at:   77|Elapsed Time: 0:00:00||
Episode 6|Iteration 78|reward:  948.0|last_reward_at:   77|Elapsed Time: 0:00:00||
Episode 6|Iteration 78|reward:  948.0|last_reward_at:   78|Elapsed Time: 0:00:00||
Episode 6|Iteration 80|reward:  962.0|last_reward_at:   78|Elapsed Time: 0:00:00||
Episode 6|Iteration 80|reward:  962.0|last_reward_at:   80|Elapsed Time: 0:00:00||
Episode 6|Iteration 81|reward: 1062.0|last_reward_at:   80|Elapsed Time: 0:00:00||
Episode 6|Iteration 81|reward: 1062.0|last_reward_at:   81|Elapsed Time: 0:00:00||
Episode 6|Iteration 82|reward: 1076.0|last_reward_at:   81|Elapsed Time: 0:00:00||
Episode 6|Iteration 82|reward: 1076.0|last_reward_at:   82|Elapsed Time: 0:00:00||
Episode 6|Iteration 85|reward: 1082.0|last_reward_at:   82|Elapsed Time: 0:00:00||
Episode 6|Iteration 85|reward: 1082.0|last_reward_at:   85|Elapsed Time: 0:00:00||
Episode 6|Iteration 87|reward: 1182.0|last_reward_at:   85|Elapsed Time: 0:00:01||
Episode 6|Iteration 87|reward: 1182.0|last_reward_at:   87|Elapsed Time: 0:00:01||
Episode 6|Iteration 88|reward: 1196.0|last_reward_at:   87|Elapsed Time: 0:00:01||
Episode 6|Iteration 88|reward: 1196.0|last_reward_at:   88|Elapsed Time: 0:00:01||
Episode 6|Iteration 89|reward: 2196.0|last_reward_at:   88|Elapsed Time: 0:00:01||
Episode 6|Iteration 89|reward: 2196.0|last_reward_at:   89|Elapsed Time: 0:00:01||
Episode 6|Iteration 90|reward: 2198.0|last_reward_at:   89|Elapsed Time: 0:00:01||
Episode 6|Iteration 90|reward: 2198.0|last_reward_at:   90|Elapsed Time: 0:00:01||
Episode 6|Iteration 94|reward: 2204.0|last_reward_at:   90|Elapsed Time: 0:00:01||
Episode 6|Iteration 94|reward: 2204.0|last_reward_at:   94|Elapsed Time: 0:00:01||
Episode 6|Iteration 97|reward: 2210.0|last_reward_at:   94|Elapsed Time: 0:00:01||
Episode 6|Iteration 97|reward: 2210.0|last_reward_at:   97|Elapsed Time: 0:00:01||
Episode 6|Iteration 100|reward: 2216.0|last_reward_at:   97|Elapsed Time: 0:00:01||
Episode 6|Iteration 100|reward: 2216.0|last_reward_at:  100|Elapsed Time: 0:00:01||
Episode 6|Iteration 103|reward: 2218.0|last_reward_at:  100|Elapsed Time: 0:00:01||
Episode 6|Iteration 103|reward: 2218.0|last_reward_at:  103|Elapsed Time: 0:00:01||
Episode 6|Iteration 106|reward: 2218.0|last_reward_at:  103|Elapsed Time: 0:00:01||
Episode 6|Iteration 109|reward: 2224.0|last_reward_at:  103|Elapsed Time: 0:00:01||
Episode 6|Iteration 109|reward: 2224.0|last_reward_at:  109|Elapsed Time: 0:00:01||
Episode 6|Iteration 112|reward: 2226.0|last_reward_at:  109|Elapsed Time: 0:00:01||
Episode 6|Iteration 112|reward: 2226.0|last_reward_at:  112|Elapsed Time: 0:00:01||
Episode 6|Iteration 114|reward: 2232.0|last_reward_at:  112|Elapsed Time: 0:00:01||
Episode 6|Iteration 114|reward: 2232.0|last_reward_at:  114|Elapsed Time: 0:00:01||
Episode 6|Iteration 115|reward: 2238.0|last_reward_at:  114|Elapsed Time: 0:00:01||
Episode 6|Iteration 115|reward: 2238.0|last_reward_at:  115|Elapsed Time: 0:00:01||
Episode 6|Iteration 122|reward: 2238.0|last_reward_at:  115|Elapsed Time: 0:00:01||
Episode 6|Iteration 127|reward: 2240.0|last_reward_at:  115|Elapsed Time: 0:00:01||
Episode 6|Iteration 127|reward: 2240.0|last_reward_at:  127|Elapsed Time: 0:00:01||
Episode 6|Iteration 134|reward: 2240.0|last_reward_at:  127|Elapsed Time: 0:00:01||
Episode 6|Iteration 142|reward: 2240.0|last_reward_at:  127|Elapsed Time: 0:00:01||
Episode 6|Iteration 144|reward: 2240.0|last_reward_at:  127|Elapsed Time: 0:00:02||
Episode 6|Iteration 150|reward: 2246.0|last_reward_at:  127|Elapsed Time: 0:00:02||
Episode 6|Iteration 150|reward: 2246.0|last_reward_at:  150|Elapsed Time: 0:00:02||
Episode 6|Iteration 151|reward: 2252.0|last_reward_at:  150|Elapsed Time: 0:00:02||
Episode 6|Iteration 151|reward: 2252.0|last_reward_at:  151|Elapsed Time: 0:00:02||
Episode 6|Iteration 153|reward: 2258.0|last_reward_at:  151|Elapsed Time: 0:00:02||
Episode 6|Iteration 153|reward: 2258.0|last_reward_at:  153|Elapsed Time: 0:00:02||
Episode 6|Iteration 159|reward: 2258.0|last_reward_at:  153|Elapsed Time: 0:00:02||
Episode 6|Iteration 167|reward: 2264.0|last_reward_at:  153|Elapsed Time: 0:00:02||
Episode 6|Iteration 167|reward: 2264.0|last_reward_at:  167|Elapsed Time: 0:00:02||
Episode 6|Iteration 175|reward: 2264.0|last_reward_at:  167|Elapsed Time: 0:00:02||
Episode 6|Iteration 182|reward: 2264.0|last_reward_at:  167|Elapsed Time: 0:00:02||
Episode 6|Iteration 189|reward: 2264.0|last_reward_at:  167|Elapsed Time: 0:00:02||
Episode 6|Iteration 193|reward: 2270.0|last_reward_at:  167|Elapsed Time: 0:00:02||
Episode 6|Iteration 193|reward: 2270.0|last_reward_at:  193|Elapsed Time: 0:00:02||
Episode 6|Iteration 198|reward: 2270.0|last_reward_at:  193|Elapsed Time: 0:00:02||
Episode 6|Iteration 201|reward: 2276.0|last_reward_at:  193|Elapsed Time: 0:00:02||
Episode 6|Iteration 201|reward: 2276.0|last_reward_at:  201|Elapsed Time: 0:00:02||
Episode 6|Iteration 206|reward: 2276.0|last_reward_at:  201|Elapsed Time: 0:00:02||
Episode 6|Iteration 211|reward: 2276.0|last_reward_at:  201|Elapsed Time: 0:00:03||
Episode 6|Iteration 213|reward: 2276.0|last_reward_at:  201|Elapsed Time: 0:00:03||
Episode 6|Iteration 218|reward: 2276.0|last_reward_at:  201|Elapsed Time: 0:00:03||
Episode 6|Iteration 221|reward: 2278.0|last_reward_at:  201|Elapsed Time: 0:00:03||
Episode 6|Iteration 221|reward: 2278.0|last_reward_at:  221|Elapsed Time: 0:00:03||
Episode 6|Iteration 228|reward: 2278.0|last_reward_at:  221|Elapsed Time: 0:00:03||
Episode 6|Iteration 231|reward: 2278.0|last_reward_at:  221|Elapsed Time: 0:00:03||
Episode 6|Iteration 236|reward: 2278.0|last_reward_at:  221|Elapsed Time: 0:00:03||
Episode 6|Iteration 244|reward: 2278.0|last_reward_at:  221|Elapsed Time: 0:00:03||
Episode 6|Iteration 249|reward: 2278.0|last_reward_at:  221|Elapsed Time: 0:00:03||
Episode 6|Iteration 253|reward: 2278.0|last_reward_at:  221|Elapsed Time: 0:00:04||
Episode 6|Iteration 256|reward: 2278.0|last_reward_at:  221|Elapsed Time: 0:00:04||
Episode 6|Iteration 260|reward: 2278.0|last_reward_at:  221|Elapsed Time: 0:00:04||
Episode 6|Iteration 261|reward: 2280.0|last_reward_at:  221|Elapsed Time: 0:00:04||
Episode 6|Iteration 261|reward: 2280.0|last_reward_at:  261|Elapsed Time: 0:00:04||
Episode 6|Iteration 266|reward: 2280.0|last_reward_at:  261|Elapsed Time: 0:00:04||
Episode 6|Iteration 267|reward: 2280.0|last_reward_at:  261|Elapsed Time: 0:00:04||
Episode 6|Iteration 274|reward: 2280.0|last_reward_at:  261|Elapsed Time: 0:00:04||
Episode 6|Iteration 278|reward: 2280.0|last_reward_at:  261|Elapsed Time: 0:00:04||
Episode 6|Iteration 284|reward: 2280.0|last_reward_at:  261|Elapsed Time: 0:00:04||
Episode 6|Iteration 289|reward: 2280.0|last_reward_at:  261|Elapsed Time: 0:00:04||
Episode 6|Iteration 296|reward: 2280.0|last_reward_at:  261|Elapsed Time: 0:00:05||
Episode 6|Iteration 301|reward: 2280.0|last_reward_at:  261|Elapsed Time: 0:00:05||
Episode 6|Iteration 309|reward: 2280.0|last_reward_at:  261|Elapsed Time: 0:00:05||
Episode 6|Iteration 317|reward: 2280.0|last_reward_at:  261|Elapsed Time: 0:00:05||
Episode 6|Iteration 325|reward: 2280.0|last_reward_at:  261|Elapsed Time: 0:00:05||
Episode 6|Iteration 328|reward: 2286.0|last_reward_at:  261|Elapsed Time: 0:00:05||
Episode 6|Iteration 328|reward: 2286.0|last_reward_at:  328|Elapsed Time: 0:00:05||
Episode 6|Iteration 335|reward: 2286.0|last_reward_at:  328|Elapsed Time: 0:00:05||
Episode 6|Iteration 338|reward: 2292.0|last_reward_at:  328|Elapsed Time: 0:00:05||
Episode 6|Iteration 338|reward: 2292.0|last_reward_at:  338|Elapsed Time: 0:00:05||
Episode 6|Iteration 346|reward: 2292.0|last_reward_at:  338|Elapsed Time: 0:00:05||
Episode 6|Iteration 354|reward: 2292.0|last_reward_at:  338|Elapsed Time: 0:00:05||
Episode 6|Iteration 362|reward: 2292.0|last_reward_at:  338|Elapsed Time: 0:00:05||
Episode 6|Iteration 370|reward: 2292.0|last_reward_at:  338|Elapsed Time: 0:00:06||
Episode 6|Iteration 378|reward: 2292.0|last_reward_at:  338|Elapsed Time: 0:00:06||
Episode 6|Iteration 386|reward: 2292.0|last_reward_at:  338|Elapsed Time: 0:00:06||
Episode 6|Iteration 392|reward: 2298.0|last_reward_at:  338|Elapsed Time: 0:00:06||
Episode 6|Iteration 392|reward: 2298.0|last_reward_at:  392|Elapsed Time: 0:00:06||
Episode 6|Iteration 400|reward: 2298.0|last_reward_at:  392|Elapsed Time: 0:00:06||
Episode 6|Iteration 408|reward: 2298.0|last_reward_at:  392|Elapsed Time: 0:00:06||
Episode 6|Iteration 413|reward: 2298.0|last_reward_at:  392|Elapsed Time: 0:00:06||
Episode 6|Iteration 418|reward: 2298.0|last_reward_at:  392|Elapsed Time: 0:00:06||
Episode 6|Iteration 420|reward: 2298.0|last_reward_at:  392|Elapsed Time: 0:00:06||
Episode 6|Iteration 426|reward: 2298.0|last_reward_at:  392|Elapsed Time: 0:00:06||
Episode 6|Iteration 433|reward: 2298.0|last_reward_at:  392|Elapsed Time: 0:00:07||
Episode 6|Iteration 439|reward: 2298.0|last_reward_at:  392|Elapsed Time: 0:00:07||
Episode 6|Iteration 446|reward: 2298.0|last_reward_at:  392|Elapsed Time: 0:00:07||
Episode 6|Iteration 455|reward: 2298.0|last_reward_at:  392|Elapsed Time: 0:00:07||
Episode 6|Iteration 462|reward: 2298.0|last_reward_at:  392|Elapsed Time: 0:00:07||
Episode 6|Iteration 471|reward: 2298.0|last_reward_at:  392|Elapsed Time: 0:00:07||
Episode 6|Iteration 479|reward: 2298.0|last_reward_at:  392|Elapsed Time: 0:00:07||
Episode 6|Iteration 487|reward: 2298.0|last_reward_at:  392|Elapsed Time: 0:00:07||
Episode 6|Iteration 494|reward: 2298.0|last_reward_at:  392|Elapsed Time: 0:00:07||
Episode 6|Iteration 501|reward: 2298.0|last_reward_at:  392|Elapsed Time: 0:00:08||
Episode 6|Iteration 509|reward: 2298.0|last_reward_at:  392|Elapsed Time: 0:00:08||
Episode 6|Iteration 515|reward: 2298.0|last_reward_at:  392|Elapsed Time: 0:00:08||
Episode 6|Iteration 523|reward: 2298.0|last_reward_at:  392|Elapsed Time: 0:00:08||
Episode 6|Iteration 531|reward: 2298.0|last_reward_at:  392|Elapsed Time: 0:00:08||
Episode 6|Iteration 539|reward: 2298.0|last_reward_at:  392|Elapsed Time: 0:00:08||
Episode 6|Iteration 547|reward: 2298.0|last_reward_at:  392|Elapsed Time: 0:00:08||
Episode 6|Iteration 554|reward: 2298.0|last_reward_at:  392|Elapsed Time: 0:00:08||
Episode 6|Iteration 562|reward: 2298.0|last_reward_at:  392|Elapsed Time: 0:00:08||
Episode 6|Iteration 569|reward: 2298.0|last_reward_at:  392|Elapsed Time: 0:00:09||
Episode 6|Iteration 577|reward: 2298.0|last_reward_at:  392|Elapsed Time: 0:00:09||
Episode 6|Iteration 585|reward: 2298.0|last_reward_at:  392|Elapsed Time: 0:00:09||
Episode 6|Iteration 592|reward: 2298.0|last_reward_at:  392|Elapsed Time: 0:00:09||
Episode 6|Iteration 600|reward: 2298.0|last_reward_at:  392|Elapsed Time: 0:00:09||
Episode 6|Iteration 600|reward: 2298.0|last_reward_at:  392|Elapsed Time: 0:00:09||

  Episode 6 stopped at t=600
  Breakdown [Reward/NoReward (Success rate)]
    explore-local: 5/83 (0.06)
    explore-remote: 8/121 (0.06)
    explore-connect: 1/109 (0.01)
    exploit-local: 16/110 (0.13)
    exploit-remote: 12/124 (0.09)
    exploit-connect: 10/1 (0.91)
  exploit deflected to exploration: 27
  ## Episode: 7/10 'DQL' ϵ=0.4895, γ=0.15, lr=0.01, replaymemory=10000,
batch=256, target_update=5

Episode 7|Iteration 0|reward: ------|last_reward_at: ----|Elapsed Time: 0:00:00||
Episode 7|Iteration 1|reward:   14.0|last_reward_at: ----|Elapsed Time: 0:00:00||
Episode 7|Iteration 1|reward:   14.0|last_reward_at:    1|Elapsed Time: 0:00:00||
Episode 7|Iteration 4|reward:   18.0|last_reward_at:    1|Elapsed Time: 0:00:00||
Episode 7|Iteration 4|reward:   18.0|last_reward_at:    4|Elapsed Time: 0:00:00||
Episode 7|Iteration 5|reward:   20.0|last_reward_at:    4|Elapsed Time: 0:00:00||
Episode 7|Iteration 5|reward:   20.0|last_reward_at:    5|Elapsed Time: 0:00:00||
Episode 7|Iteration 16|reward:   20.0|last_reward_at:    5|Elapsed Time: 0:00:00||
Episode 7|Iteration 21|reward:  120.0|last_reward_at:    5|Elapsed Time: 0:00:00||
Episode 7|Iteration 21|reward:  120.0|last_reward_at:   21|Elapsed Time: 0:00:00||
Episode 7|Iteration 22|reward:  134.0|last_reward_at:   21|Elapsed Time: 0:00:00||
Episode 7|Iteration 22|reward:  134.0|last_reward_at:   22|Elapsed Time: 0:00:00||
Episode 7|Iteration 25|reward:  140.0|last_reward_at:   22|Elapsed Time: 0:00:00||
Episode 7|Iteration 25|reward:  140.0|last_reward_at:   25|Elapsed Time: 0:00:00||
Episode 7|Iteration 27|reward:  146.0|last_reward_at:   25|Elapsed Time: 0:00:00||
Episode 7|Iteration 27|reward:  146.0|last_reward_at:   27|Elapsed Time: 0:00:00||
Episode 7|Iteration 29|reward:  154.0|last_reward_at:   27|Elapsed Time: 0:00:00||
Episode 7|Iteration 29|reward:  154.0|last_reward_at:   29|Elapsed Time: 0:00:00||
Episode 7|Iteration 38|reward:  154.0|last_reward_at:   29|Elapsed Time: 0:00:00||
Episode 7|Iteration 46|reward:  154.0|last_reward_at:   29|Elapsed Time: 0:00:00||
Episode 7|Iteration 54|reward:  154.0|last_reward_at:   29|Elapsed Time: 0:00:00||
Episode 7|Iteration 56|reward:  254.0|last_reward_at:   29|Elapsed Time: 0:00:00||
Episode 7|Iteration 56|reward:  254.0|last_reward_at:   56|Elapsed Time: 0:00:00||
Episode 7|Iteration 58|reward:  268.0|last_reward_at:   56|Elapsed Time: 0:00:00||
Episode 7|Iteration 58|reward:  268.0|last_reward_at:   58|Elapsed Time: 0:00:00||
Episode 7|Iteration 59|reward:  274.0|last_reward_at:   58|Elapsed Time: 0:00:00||
Episode 7|Iteration 59|reward:  274.0|last_reward_at:   59|Elapsed Time: 0:00:00||
Episode 7|Iteration 61|reward:  374.0|last_reward_at:   59|Elapsed Time: 0:00:00||
Episode 7|Iteration 61|reward:  374.0|last_reward_at:   61|Elapsed Time: 0:00:00||
Episode 7|Iteration 65|reward:  388.0|last_reward_at:   61|Elapsed Time: 0:00:00||
Episode 7|Iteration 65|reward:  388.0|last_reward_at:   65|Elapsed Time: 0:00:00||
Episode 7|Iteration 67|reward:  488.0|last_reward_at:   65|Elapsed Time: 0:00:00||
Episode 7|Iteration 67|reward:  488.0|last_reward_at:   67|Elapsed Time: 0:00:00||
Episode 7|Iteration 68|reward:  502.0|last_reward_at:   67|Elapsed Time: 0:00:00||
Episode 7|Iteration 68|reward:  502.0|last_reward_at:   68|Elapsed Time: 0:00:00||
Episode 7|Iteration 69|reward:  602.0|last_reward_at:   68|Elapsed Time: 0:00:00||
Episode 7|Iteration 69|reward:  602.0|last_reward_at:   69|Elapsed Time: 0:00:00||
Episode 7|Iteration 70|reward:  616.0|last_reward_at:   69|Elapsed Time: 0:00:00||
Episode 7|Iteration 70|reward:  616.0|last_reward_at:   70|Elapsed Time: 0:00:00||
Episode 7|Iteration 76|reward:  616.0|last_reward_at:   70|Elapsed Time: 0:00:00||
Episode 7|Iteration 83|reward:  622.0|last_reward_at:   70|Elapsed Time: 0:00:00||
Episode 7|Iteration 83|reward:  622.0|last_reward_at:   83|Elapsed Time: 0:00:00||
Episode 7|Iteration 87|reward:  630.0|last_reward_at:   83|Elapsed Time: 0:00:00||
Episode 7|Iteration 87|reward:  630.0|last_reward_at:   87|Elapsed Time: 0:00:00||
Episode 7|Iteration 89|reward:  636.0|last_reward_at:   87|Elapsed Time: 0:00:00||
Episode 7|Iteration 89|reward:  636.0|last_reward_at:   89|Elapsed Time: 0:00:00||
Episode 7|Iteration 91|reward:  642.0|last_reward_at:   89|Elapsed Time: 0:00:00||
Episode 7|Iteration 91|reward:  642.0|last_reward_at:   91|Elapsed Time: 0:00:00||
Episode 7|Iteration 96|reward:  644.0|last_reward_at:   91|Elapsed Time: 0:00:00||
Episode 7|Iteration 96|reward:  644.0|last_reward_at:   96|Elapsed Time: 0:00:01||
Episode 7|Iteration 104|reward:  650.0|last_reward_at:   96|Elapsed Time: 0:00:01||
Episode 7|Iteration 104|reward:  650.0|last_reward_at:  104|Elapsed Time: 0:00:01||
Episode 7|Iteration 107|reward:  652.0|last_reward_at:  104|Elapsed Time: 0:00:01||
Episode 7|Iteration 107|reward:  652.0|last_reward_at:  107|Elapsed Time: 0:00:01||
Episode 7|Iteration 109|reward:  654.0|last_reward_at:  107|Elapsed Time: 0:00:01||
Episode 7|Iteration 109|reward:  654.0|last_reward_at:  109|Elapsed Time: 0:00:01||
Episode 7|Iteration 114|reward:  660.0|last_reward_at:  109|Elapsed Time: 0:00:01||
Episode 7|Iteration 114|reward:  660.0|last_reward_at:  114|Elapsed Time: 0:00:01||
Episode 7|Iteration 121|reward:  760.0|last_reward_at:  114|Elapsed Time: 0:00:01||
Episode 7|Iteration 121|reward:  760.0|last_reward_at:  121|Elapsed Time: 0:00:01||
Episode 7|Iteration 123|reward:  774.0|last_reward_at:  121|Elapsed Time: 0:00:01||
Episode 7|Iteration 123|reward:  774.0|last_reward_at:  123|Elapsed Time: 0:00:01||
Episode 7|Iteration 126|reward:  874.0|last_reward_at:  123|Elapsed Time: 0:00:01||
Episode 7|Iteration 126|reward:  874.0|last_reward_at:  126|Elapsed Time: 0:00:01||
Episode 7|Iteration 127|reward:  888.0|last_reward_at:  126|Elapsed Time: 0:00:01||
Episode 7|Iteration 127|reward:  888.0|last_reward_at:  127|Elapsed Time: 0:00:01||
Episode 7|Iteration 130|reward:  896.0|last_reward_at:  127|Elapsed Time: 0:00:01||
Episode 7|Iteration 130|reward:  896.0|last_reward_at:  130|Elapsed Time: 0:00:01||
Episode 7|Iteration 133|reward:  902.0|last_reward_at:  130|Elapsed Time: 0:00:01||
Episode 7|Iteration 133|reward:  902.0|last_reward_at:  133|Elapsed Time: 0:00:01||
Episode 7|Iteration 139|reward:  908.0|last_reward_at:  133|Elapsed Time: 0:00:01||
Episode 7|Iteration 139|reward:  908.0|last_reward_at:  139|Elapsed Time: 0:00:01||
Episode 7|Iteration 145|reward:  908.0|last_reward_at:  139|Elapsed Time: 0:00:01||
Episode 7|Iteration 146|reward:  910.0|last_reward_at:  139|Elapsed Time: 0:00:01||
Episode 7|Iteration 146|reward:  910.0|last_reward_at:  146|Elapsed Time: 0:00:01||
Episode 7|Iteration 147|reward:  912.0|last_reward_at:  146|Elapsed Time: 0:00:01||
Episode 7|Iteration 147|reward:  912.0|last_reward_at:  147|Elapsed Time: 0:00:01||
Episode 7|Iteration 156|reward:  912.0|last_reward_at:  147|Elapsed Time: 0:00:01||
Episode 7|Iteration 166|reward:  912.0|last_reward_at:  147|Elapsed Time: 0:00:01||
Episode 7|Iteration 167|reward:  918.0|last_reward_at:  147|Elapsed Time: 0:00:01||
Episode 7|Iteration 167|reward:  918.0|last_reward_at:  167|Elapsed Time: 0:00:01||
Episode 7|Iteration 168|reward: 1018.0|last_reward_at:  167|Elapsed Time: 0:00:01||
Episode 7|Iteration 168|reward: 1018.0|last_reward_at:  168|Elapsed Time: 0:00:01||
Episode 7|Iteration 170|reward: 1032.0|last_reward_at:  168|Elapsed Time: 0:00:01||
Episode 7|Iteration 170|reward: 1032.0|last_reward_at:  170|Elapsed Time: 0:00:01||
Episode 7|Iteration 171|reward: 1132.0|last_reward_at:  170|Elapsed Time: 0:00:01||
Episode 7|Iteration 171|reward: 1132.0|last_reward_at:  171|Elapsed Time: 0:00:01||
Episode 7|Iteration 172|reward: 1146.0|last_reward_at:  171|Elapsed Time: 0:00:01||
Episode 7|Iteration 172|reward: 1146.0|last_reward_at:  172|Elapsed Time: 0:00:01||
Episode 7|Iteration 181|reward: 1146.0|last_reward_at:  172|Elapsed Time: 0:00:02||
Episode 7|Iteration 190|reward: 1146.0|last_reward_at:  172|Elapsed Time: 0:00:02||
Episode 7|Iteration 194|reward: 1152.0|last_reward_at:  172|Elapsed Time: 0:00:02||
Episode 7|Iteration 194|reward: 1152.0|last_reward_at:  194|Elapsed Time: 0:00:02||
Episode 7|Iteration 196|reward: 1158.0|last_reward_at:  194|Elapsed Time: 0:00:02||
Episode 7|Iteration 196|reward: 1158.0|last_reward_at:  196|Elapsed Time: 0:00:02||
Episode 7|Iteration 205|reward: 1258.0|last_reward_at:  196|Elapsed Time: 0:00:02||
Episode 7|Iteration 205|reward: 1258.0|last_reward_at:  205|Elapsed Time: 0:00:02||
Episode 7|Iteration 206|reward: 1272.0|last_reward_at:  205|Elapsed Time: 0:00:02||
Episode 7|Iteration 206|reward: 1272.0|last_reward_at:  206|Elapsed Time: 0:00:02||
Episode 7|Iteration 209|reward: 2272.0|last_reward_at:  206|Elapsed Time: 0:00:02||
Episode 7|Iteration 209|reward: 2272.0|last_reward_at:  209|Elapsed Time: 0:00:02||
Episode 7|Iteration 216|reward: 2274.0|last_reward_at:  209|Elapsed Time: 0:00:02||
Episode 7|Iteration 216|reward: 2274.0|last_reward_at:  216|Elapsed Time: 0:00:02||
Episode 7|Iteration 221|reward: 2274.0|last_reward_at:  216|Elapsed Time: 0:00:02||
Episode 7|Iteration 226|reward: 2276.0|last_reward_at:  216|Elapsed Time: 0:00:02||
Episode 7|Iteration 226|reward: 2276.0|last_reward_at:  226|Elapsed Time: 0:00:02||
Episode 7|Iteration 234|reward: 2276.0|last_reward_at:  226|Elapsed Time: 0:00:02||
Episode 7|Iteration 235|reward: 2282.0|last_reward_at:  226|Elapsed Time: 0:00:02||
Episode 7|Iteration 235|reward: 2282.0|last_reward_at:  235|Elapsed Time: 0:00:02||
Episode 7|Iteration 243|reward: 2282.0|last_reward_at:  235|Elapsed Time: 0:00:02||
Episode 7|Iteration 251|reward: 2282.0|last_reward_at:  235|Elapsed Time: 0:00:02||
Episode 7|Iteration 258|reward: 2282.0|last_reward_at:  235|Elapsed Time: 0:00:03||
Episode 7|Iteration 261|reward: 2288.0|last_reward_at:  235|Elapsed Time: 0:00:03||
Episode 7|Iteration 261|reward: 2288.0|last_reward_at:  261|Elapsed Time: 0:00:03||
Episode 7|Iteration 266|reward: 2288.0|last_reward_at:  261|Elapsed Time: 0:00:03||
Episode 7|Iteration 266|reward: 2294.0|last_reward_at:  261|Elapsed Time: 0:00:03||
Episode 7|Iteration 266|reward: 2294.0|last_reward_at:  266|Elapsed Time: 0:00:03||
Episode 7|Iteration 274|reward: 2294.0|last_reward_at:  266|Elapsed Time: 0:00:03||
Episode 7|Iteration 281|reward: 2294.0|last_reward_at:  266|Elapsed Time: 0:00:03||
Episode 7|Iteration 289|reward: 2294.0|last_reward_at:  266|Elapsed Time: 0:00:03||
Episode 7|Iteration 290|reward: 2294.0|last_reward_at:  266|Elapsed Time: 0:00:03||
Episode 7|Iteration 292|reward: 2294.0|last_reward_at:  266|Elapsed Time: 0:00:03||
Episode 7|Iteration 294|reward: 2294.0|last_reward_at:  266|Elapsed Time: 0:00:03||
Episode 7|Iteration 300|reward: 2294.0|last_reward_at:  266|Elapsed Time: 0:00:03||
Episode 7|Iteration 309|reward: 2294.0|last_reward_at:  266|Elapsed Time: 0:00:03||
Episode 7|Iteration 311|reward: 2294.0|last_reward_at:  266|Elapsed Time: 0:00:04||
Episode 7|Iteration 315|reward: 2294.0|last_reward_at:  266|Elapsed Time: 0:00:04||
Episode 7|Iteration 319|reward: 2296.0|last_reward_at:  266|Elapsed Time: 0:00:04||
Episode 7|Iteration 319|reward: 2296.0|last_reward_at:  319|Elapsed Time: 0:00:04||
Episode 7|Iteration 321|reward: 2296.0|last_reward_at:  319|Elapsed Time: 0:00:04||
Episode 7|Iteration 327|reward: 2296.0|last_reward_at:  319|Elapsed Time: 0:00:04||
Episode 7|Iteration 333|reward: 2296.0|last_reward_at:  319|Elapsed Time: 0:00:04||
Episode 7|Iteration 341|reward: 2296.0|last_reward_at:  319|Elapsed Time: 0:00:04||
Episode 7|Iteration 348|reward: 2296.0|last_reward_at:  319|Elapsed Time: 0:00:04||
Episode 7|Iteration 354|reward: 2296.0|last_reward_at:  319|Elapsed Time: 0:00:04||
Episode 7|Iteration 356|reward: 2296.0|last_reward_at:  319|Elapsed Time: 0:00:05||
Episode 7|Iteration 360|reward: 2296.0|last_reward_at:  319|Elapsed Time: 0:00:05||
Episode 7|Iteration 365|reward: 2296.0|last_reward_at:  319|Elapsed Time: 0:00:05||
Episode 7|Iteration 370|reward: 2296.0|last_reward_at:  319|Elapsed Time: 0:00:05||
Episode 7|Iteration 371|reward: 2302.0|last_reward_at:  319|Elapsed Time: 0:00:05||
Episode 7|Iteration 371|reward: 2302.0|last_reward_at:  371|Elapsed Time: 0:00:05||
Episode 7|Iteration 378|reward: 2302.0|last_reward_at:  371|Elapsed Time: 0:00:05||
Episode 7|Iteration 384|reward: 2302.0|last_reward_at:  371|Elapsed Time: 0:00:05||
Episode 7|Iteration 388|reward: 2302.0|last_reward_at:  371|Elapsed Time: 0:00:05||
Episode 7|Iteration 392|reward: 2302.0|last_reward_at:  371|Elapsed Time: 0:00:05||
Episode 7|Iteration 396|reward: 2302.0|last_reward_at:  371|Elapsed Time: 0:00:05||
Episode 7|Iteration 402|reward: 2302.0|last_reward_at:  371|Elapsed Time: 0:00:06||
Episode 7|Iteration 403|reward: 2302.0|last_reward_at:  371|Elapsed Time: 0:00:06||
Episode 7|Iteration 409|reward: 2302.0|last_reward_at:  371|Elapsed Time: 0:00:06||
Episode 7|Iteration 416|reward: 2302.0|last_reward_at:  371|Elapsed Time: 0:00:06||
Episode 7|Iteration 424|reward: 2302.0|last_reward_at:  371|Elapsed Time: 0:00:06||
Episode 7|Iteration 429|reward: 2302.0|last_reward_at:  371|Elapsed Time: 0:00:06||
Episode 7|Iteration 436|reward: 2302.0|last_reward_at:  371|Elapsed Time: 0:00:06||
Episode 7|Iteration 441|reward: 2302.0|last_reward_at:  371|Elapsed Time: 0:00:06||
Episode 7|Iteration 447|reward: 2302.0|last_reward_at:  371|Elapsed Time: 0:00:06||
Episode 7|Iteration 453|reward: 2302.0|last_reward_at:  371|Elapsed Time: 0:00:06||
Episode 7|Iteration 461|reward: 2302.0|last_reward_at:  371|Elapsed Time: 0:00:07||
Episode 7|Iteration 469|reward: 2302.0|last_reward_at:  371|Elapsed Time: 0:00:07||
Episode 7|Iteration 477|reward: 2302.0|last_reward_at:  371|Elapsed Time: 0:00:07||
Episode 7|Iteration 486|reward: 2302.0|last_reward_at:  371|Elapsed Time: 0:00:07||
Episode 7|Iteration 494|reward: 2302.0|last_reward_at:  371|Elapsed Time: 0:00:07||
Episode 7|Iteration 502|reward: 2302.0|last_reward_at:  371|Elapsed Time: 0:00:07||
Episode 7|Iteration 509|reward: 2302.0|last_reward_at:  371|Elapsed Time: 0:00:07||
Episode 7|Iteration 517|reward: 2302.0|last_reward_at:  371|Elapsed Time: 0:00:07||
Episode 7|Iteration 525|reward: 2302.0|last_reward_at:  371|Elapsed Time: 0:00:07||
Episode 7|Iteration 532|reward: 2302.0|last_reward_at:  371|Elapsed Time: 0:00:07||
Episode 7|Iteration 539|reward: 2302.0|last_reward_at:  371|Elapsed Time: 0:00:08||
Episode 7|Iteration 547|reward: 2302.0|last_reward_at:  371|Elapsed Time: 0:00:08||
Episode 7|Iteration 555|reward: 2302.0|last_reward_at:  371|Elapsed Time: 0:00:08||
Episode 7|Iteration 563|reward: 2302.0|last_reward_at:  371|Elapsed Time: 0:00:08||
Episode 7|Iteration 570|reward: 2302.0|last_reward_at:  371|Elapsed Time: 0:00:08||
Episode 7|Iteration 577|reward: 2302.0|last_reward_at:  371|Elapsed Time: 0:00:08||
Episode 7|Iteration 585|reward: 2302.0|last_reward_at:  371|Elapsed Time: 0:00:08||
Episode 7|Iteration 592|reward: 2302.0|last_reward_at:  371|Elapsed Time: 0:00:08||
Episode 7|Iteration 595|reward: 2302.0|last_reward_at:  371|Elapsed Time: 0:00:08||
Episode 7|Iteration 600|reward: 2302.0|last_reward_at:  371|Elapsed Time: 0:00:08||
Episode 7|Iteration 600|reward: 2302.0|last_reward_at:  371|Elapsed Time: 0:00:08||

  Episode 7 stopped at t=600
  Breakdown [Reward/NoReward (Success rate)]
    explore-local: 6/89 (0.06)
    explore-remote: 9/83 (0.10)
    explore-connect: 1/91 (0.01)
    exploit-local: 15/120 (0.11)
    exploit-remote: 11/162 (0.06)
    exploit-connect: 10/3 (0.77)
  exploit deflected to exploration: 11
  ## Episode: 8/10 'DQL' ϵ=0.4454, γ=0.15, lr=0.01, replaymemory=10000,
batch=256, target_update=5

Episode 8|Iteration 0|reward: ------|last_reward_at: ----|Elapsed Time: 0:00:00||
Episode 8|Iteration 1|reward:    0.0|last_reward_at: ----|Elapsed Time: 0:00:00||
Episode 8|Iteration 3|reward:   14.0|last_reward_at: ----|Elapsed Time: 0:00:00||
Episode 8|Iteration 3|reward:   14.0|last_reward_at:    3|Elapsed Time: 0:00:00||
Episode 8|Iteration 6|reward:   18.0|last_reward_at:    3|Elapsed Time: 0:00:00||
Episode 8|Iteration 6|reward:   18.0|last_reward_at:    6|Elapsed Time: 0:00:00||
Episode 8|Iteration 10|reward:   20.0|last_reward_at:    6|Elapsed Time: 0:00:00||
Episode 8|Iteration 10|reward:   20.0|last_reward_at:   10|Elapsed Time: 0:00:00||
Episode 8|Iteration 23|reward:   20.0|last_reward_at:   10|Elapsed Time: 0:00:00||
Episode 8|Iteration 31|reward:   20.0|last_reward_at:   10|Elapsed Time: 0:00:00||
Episode 8|Iteration 38|reward:   20.0|last_reward_at:   10|Elapsed Time: 0:00:00||
Episode 8|Iteration 46|reward:   20.0|last_reward_at:   10|Elapsed Time: 0:00:00||
Episode 8|Iteration 54|reward:   20.0|last_reward_at:   10|Elapsed Time: 0:00:00||
Episode 8|Iteration 59|reward:  120.0|last_reward_at:   10|Elapsed Time: 0:00:00||
Episode 8|Iteration 59|reward:  120.0|last_reward_at:   59|Elapsed Time: 0:00:00||
Episode 8|Iteration 62|reward:  134.0|last_reward_at:   59|Elapsed Time: 0:00:00||
Episode 8|Iteration 62|reward:  134.0|last_reward_at:   62|Elapsed Time: 0:00:00||
Episode 8|Iteration 66|reward:  142.0|last_reward_at:   62|Elapsed Time: 0:00:00||
Episode 8|Iteration 66|reward:  142.0|last_reward_at:   66|Elapsed Time: 0:00:00||
Episode 8|Iteration 72|reward:  148.0|last_reward_at:   66|Elapsed Time: 0:00:00||
Episode 8|Iteration 72|reward:  148.0|last_reward_at:   72|Elapsed Time: 0:00:00||
Episode 8|Iteration 84|reward:  148.0|last_reward_at:   72|Elapsed Time: 0:00:00||
Episode 8|Iteration 92|reward:  148.0|last_reward_at:   72|Elapsed Time: 0:00:00||
Episode 8|Iteration 99|reward:  148.0|last_reward_at:   72|Elapsed Time: 0:00:00||
Episode 8|Iteration 102|reward:  154.0|last_reward_at:   72|Elapsed Time: 0:00:00||
Episode 8|Iteration 102|reward:  154.0|last_reward_at:  102|Elapsed Time: 0:00:00||
Episode 8|Iteration 114|reward:  154.0|last_reward_at:  102|Elapsed Time: 0:00:00||
Episode 8|Iteration 122|reward:  154.0|last_reward_at:  102|Elapsed Time: 0:00:00||
Episode 8|Iteration 130|reward:  154.0|last_reward_at:  102|Elapsed Time: 0:00:01||
Episode 8|Iteration 137|reward:  154.0|last_reward_at:  102|Elapsed Time: 0:00:01||
Episode 8|Iteration 145|reward:  154.0|last_reward_at:  102|Elapsed Time: 0:00:01||
Episode 8|Iteration 152|reward:  154.0|last_reward_at:  102|Elapsed Time: 0:00:01||
Episode 8|Iteration 160|reward:  154.0|last_reward_at:  102|Elapsed Time: 0:00:01||
Episode 8|Iteration 168|reward:  154.0|last_reward_at:  102|Elapsed Time: 0:00:01||
Episode 8|Iteration 175|reward:  154.0|last_reward_at:  102|Elapsed Time: 0:00:01||
Episode 8|Iteration 183|reward:  154.0|last_reward_at:  102|Elapsed Time: 0:00:01||
Episode 8|Iteration 190|reward:  154.0|last_reward_at:  102|Elapsed Time: 0:00:01||
Episode 8|Iteration 198|reward:  154.0|last_reward_at:  102|Elapsed Time: 0:00:01||
Episode 8|Iteration 200|reward:  254.0|last_reward_at:  102|Elapsed Time: 0:00:01||
Episode 8|Iteration 200|reward:  254.0|last_reward_at:  200|Elapsed Time: 0:00:01||
Episode 8|Iteration 201|reward:  268.0|last_reward_at:  200|Elapsed Time: 0:00:01||
Episode 8|Iteration 201|reward:  268.0|last_reward_at:  201|Elapsed Time: 0:00:01||
Episode 8|Iteration 203|reward:  368.0|last_reward_at:  201|Elapsed Time: 0:00:01||
Episode 8|Iteration 203|reward:  368.0|last_reward_at:  203|Elapsed Time: 0:00:01||
Episode 8|Iteration 204|reward:  382.0|last_reward_at:  203|Elapsed Time: 0:00:01||
Episode 8|Iteration 204|reward:  382.0|last_reward_at:  204|Elapsed Time: 0:00:01||
Episode 8|Iteration 209|reward:  482.0|last_reward_at:  204|Elapsed Time: 0:00:01||
Episode 8|Iteration 209|reward:  482.0|last_reward_at:  209|Elapsed Time: 0:00:01||
Episode 8|Iteration 212|reward:  496.0|last_reward_at:  209|Elapsed Time: 0:00:01||
Episode 8|Iteration 212|reward:  496.0|last_reward_at:  212|Elapsed Time: 0:00:01||
Episode 8|Iteration 213|reward:  596.0|last_reward_at:  212|Elapsed Time: 0:00:01||
Episode 8|Iteration 213|reward:  596.0|last_reward_at:  213|Elapsed Time: 0:00:01||
Episode 8|Iteration 217|reward:  610.0|last_reward_at:  213|Elapsed Time: 0:00:01||
Episode 8|Iteration 217|reward:  610.0|last_reward_at:  217|Elapsed Time: 0:00:01||
Episode 8|Iteration 218|reward:  616.0|last_reward_at:  217|Elapsed Time: 0:00:01||
Episode 8|Iteration 218|reward:  616.0|last_reward_at:  218|Elapsed Time: 0:00:01||
Episode 8|Iteration 219|reward:  622.0|last_reward_at:  218|Elapsed Time: 0:00:01||
Episode 8|Iteration 219|reward:  622.0|last_reward_at:  219|Elapsed Time: 0:00:01||
Episode 8|Iteration 226|reward:  628.0|last_reward_at:  219|Elapsed Time: 0:00:01||
Episode 8|Iteration 226|reward:  628.0|last_reward_at:  226|Elapsed Time: 0:00:01||
Episode 8|Iteration 230|reward:  630.0|last_reward_at:  226|Elapsed Time: 0:00:01||
Episode 8|Iteration 230|reward:  630.0|last_reward_at:  230|Elapsed Time: 0:00:01||
Episode 8|Iteration 231|reward:  636.0|last_reward_at:  230|Elapsed Time: 0:00:01||
Episode 8|Iteration 231|reward:  636.0|last_reward_at:  231|Elapsed Time: 0:00:01||
Episode 8|Iteration 233|reward:  638.0|last_reward_at:  231|Elapsed Time: 0:00:01||
Episode 8|Iteration 233|reward:  638.0|last_reward_at:  233|Elapsed Time: 0:00:01||
Episode 8|Iteration 243|reward:  646.0|last_reward_at:  233|Elapsed Time: 0:00:02||
Episode 8|Iteration 243|reward:  646.0|last_reward_at:  243|Elapsed Time: 0:00:02||
Episode 8|Iteration 251|reward:  646.0|last_reward_at:  243|Elapsed Time: 0:00:02||
Episode 8|Iteration 253|reward:  652.0|last_reward_at:  243|Elapsed Time: 0:00:02||
Episode 8|Iteration 253|reward:  652.0|last_reward_at:  253|Elapsed Time: 0:00:02||
Episode 8|Iteration 259|reward:  652.0|last_reward_at:  253|Elapsed Time: 0:00:02||
Episode 8|Iteration 264|reward:  658.0|last_reward_at:  253|Elapsed Time: 0:00:02||
Episode 8|Iteration 264|reward:  658.0|last_reward_at:  264|Elapsed Time: 0:00:02||
Episode 8|Iteration 274|reward:  658.0|last_reward_at:  264|Elapsed Time: 0:00:02||
Episode 8|Iteration 281|reward:  664.0|last_reward_at:  264|Elapsed Time: 0:00:02||
Episode 8|Iteration 281|reward:  664.0|last_reward_at:  281|Elapsed Time: 0:00:02||
Episode 8|Iteration 282|reward:  666.0|last_reward_at:  281|Elapsed Time: 0:00:02||
Episode 8|Iteration 282|reward:  666.0|last_reward_at:  282|Elapsed Time: 0:00:02||
Episode 8|Iteration 289|reward:  666.0|last_reward_at:  282|Elapsed Time: 0:00:02||
Episode 8|Iteration 296|reward:  766.0|last_reward_at:  282|Elapsed Time: 0:00:02||
Episode 8|Iteration 296|reward:  766.0|last_reward_at:  296|Elapsed Time: 0:00:02||
Episode 8|Iteration 297|reward:  768.0|last_reward_at:  296|Elapsed Time: 0:00:02||
Episode 8|Iteration 297|reward:  768.0|last_reward_at:  297|Elapsed Time: 0:00:02||
Episode 8|Iteration 298|reward:  782.0|last_reward_at:  297|Elapsed Time: 0:00:02||
Episode 8|Iteration 298|reward:  782.0|last_reward_at:  298|Elapsed Time: 0:00:02||
Episode 8|Iteration 299|reward:  882.0|last_reward_at:  298|Elapsed Time: 0:00:02||
Episode 8|Iteration 299|reward:  882.0|last_reward_at:  299|Elapsed Time: 0:00:02||
Episode 8|Iteration 300|reward:  896.0|last_reward_at:  299|Elapsed Time: 0:00:02||
Episode 8|Iteration 300|reward:  896.0|last_reward_at:  300|Elapsed Time: 0:00:02||
Episode 8|Iteration 301|reward:  996.0|last_reward_at:  300|Elapsed Time: 0:00:02||
Episode 8|Iteration 301|reward:  996.0|last_reward_at:  301|Elapsed Time: 0:00:02||
Episode 8|Iteration 302|reward: 1010.0|last_reward_at:  301|Elapsed Time: 0:00:02||
Episode 8|Iteration 302|reward: 1010.0|last_reward_at:  302|Elapsed Time: 0:00:02||
Episode 8|Iteration 303|reward: 1110.0|last_reward_at:  302|Elapsed Time: 0:00:02||
Episode 8|Iteration 303|reward: 1110.0|last_reward_at:  303|Elapsed Time: 0:00:02||
Episode 8|Iteration 304|reward: 1124.0|last_reward_at:  303|Elapsed Time: 0:00:02||
Episode 8|Iteration 304|reward: 1124.0|last_reward_at:  304|Elapsed Time: 0:00:02||
Episode 8|Iteration 305|reward: 1224.0|last_reward_at:  304|Elapsed Time: 0:00:02||
Episode 8|Iteration 305|reward: 1224.0|last_reward_at:  305|Elapsed Time: 0:00:02||
Episode 8|Iteration 307|reward: 1238.0|last_reward_at:  305|Elapsed Time: 0:00:02||
Episode 8|Iteration 307|reward: 1238.0|last_reward_at:  307|Elapsed Time: 0:00:02||
Episode 8|Iteration 308|reward: 2238.0|last_reward_at:  307|Elapsed Time: 0:00:02||
Episode 8|Iteration 308|reward: 2238.0|last_reward_at:  308|Elapsed Time: 0:00:02||
Episode 8|Iteration 310|reward: 2238.0|last_reward_at:  308|Elapsed Time: 0:00:02||
Episode 8|Iteration 311|reward: 2244.0|last_reward_at:  308|Elapsed Time: 0:00:02||
Episode 8|Iteration 311|reward: 2244.0|last_reward_at:  311|Elapsed Time: 0:00:02||
Episode 8|Iteration 319|reward: 2244.0|last_reward_at:  311|Elapsed Time: 0:00:03||
Episode 8|Iteration 326|reward: 2244.0|last_reward_at:  311|Elapsed Time: 0:00:03||
Episode 8|Iteration 327|reward: 2246.0|last_reward_at:  311|Elapsed Time: 0:00:03||
Episode 8|Iteration 327|reward: 2246.0|last_reward_at:  327|Elapsed Time: 0:00:03||
Episode 8|Iteration 328|reward: 2252.0|last_reward_at:  327|Elapsed Time: 0:00:03||
Episode 8|Iteration 328|reward: 2252.0|last_reward_at:  328|Elapsed Time: 0:00:03||
Episode 8|Iteration 330|reward: 2258.0|last_reward_at:  328|Elapsed Time: 0:00:03||
Episode 8|Iteration 330|reward: 2258.0|last_reward_at:  330|Elapsed Time: 0:00:03||
Episode 8|Iteration 331|reward: 2264.0|last_reward_at:  330|Elapsed Time: 0:00:03||
Episode 8|Iteration 331|reward: 2264.0|last_reward_at:  331|Elapsed Time: 0:00:03||
Episode 8|Iteration 339|reward: 2270.0|last_reward_at:  331|Elapsed Time: 0:00:03||
Episode 8|Iteration 339|reward: 2270.0|last_reward_at:  339|Elapsed Time: 0:00:03||
Episode 8|Iteration 344|reward: 2276.0|last_reward_at:  339|Elapsed Time: 0:00:03||
Episode 8|Iteration 344|reward: 2276.0|last_reward_at:  344|Elapsed Time: 0:00:03||
Episode 8|Iteration 346|reward: 2282.0|last_reward_at:  344|Elapsed Time: 0:00:03||
Episode 8|Iteration 346|reward: 2282.0|last_reward_at:  346|Elapsed Time: 0:00:03||
Episode 8|Iteration 355|reward: 2282.0|last_reward_at:  346|Elapsed Time: 0:00:03||
Episode 8|Iteration 358|reward: 2288.0|last_reward_at:  346|Elapsed Time: 0:00:03||
Episode 8|Iteration 358|reward: 2288.0|last_reward_at:  358|Elapsed Time: 0:00:03||
Episode 8|Iteration 361|reward: 2288.0|last_reward_at:  358|Elapsed Time: 0:00:03||
Episode 8|Iteration 366|reward: 2290.0|last_reward_at:  358|Elapsed Time: 0:00:03||
Episode 8|Iteration 366|reward: 2290.0|last_reward_at:  366|Elapsed Time: 0:00:03||
Episode 8|Iteration 373|reward: 2290.0|last_reward_at:  366|Elapsed Time: 0:00:03||
Episode 8|Iteration 380|reward: 2290.0|last_reward_at:  366|Elapsed Time: 0:00:03||
Episode 8|Iteration 382|reward: 2292.0|last_reward_at:  366|Elapsed Time: 0:00:04||
Episode 8|Iteration 382|reward: 2292.0|last_reward_at:  382|Elapsed Time: 0:00:04||
Episode 8|Iteration 388|reward: 2292.0|last_reward_at:  382|Elapsed Time: 0:00:04||
Episode 8|Iteration 395|reward: 2292.0|last_reward_at:  382|Elapsed Time: 0:00:04||
Episode 8|Iteration 403|reward: 2292.0|last_reward_at:  382|Elapsed Time: 0:00:04||
Episode 8|Iteration 411|reward: 2292.0|last_reward_at:  382|Elapsed Time: 0:00:04||
Episode 8|Iteration 417|reward: 2294.0|last_reward_at:  382|Elapsed Time: 0:00:04||
Episode 8|Iteration 417|reward: 2294.0|last_reward_at:  417|Elapsed Time: 0:00:04||
Episode 8|Iteration 418|reward: 2300.0|last_reward_at:  417|Elapsed Time: 0:00:04||
Episode 8|Iteration 418|reward: 2300.0|last_reward_at:  418|Elapsed Time: 0:00:04||
Episode 8|Iteration 422|reward: 2300.0|last_reward_at:  418|Elapsed Time: 0:00:04||
Episode 8|Iteration 424|reward: 2300.0|last_reward_at:  418|Elapsed Time: 0:00:04||
Episode 8|Iteration 432|reward: 2300.0|last_reward_at:  418|Elapsed Time: 0:00:04||
Episode 8|Iteration 434|reward: 2300.0|last_reward_at:  418|Elapsed Time: 0:00:04||
Episode 8|Iteration 441|reward: 2300.0|last_reward_at:  418|Elapsed Time: 0:00:05||
Episode 8|Iteration 442|reward: 2300.0|last_reward_at:  418|Elapsed Time: 0:00:05||
Episode 8|Iteration 449|reward: 2300.0|last_reward_at:  418|Elapsed Time: 0:00:05||
Episode 8|Iteration 456|reward: 2300.0|last_reward_at:  418|Elapsed Time: 0:00:05||
Episode 8|Iteration 463|reward: 2300.0|last_reward_at:  418|Elapsed Time: 0:00:05||
Episode 8|Iteration 471|reward: 2300.0|last_reward_at:  418|Elapsed Time: 0:00:05||
Episode 8|Iteration 478|reward: 2300.0|last_reward_at:  418|Elapsed Time: 0:00:05||
Episode 8|Iteration 486|reward: 2300.0|last_reward_at:  418|Elapsed Time: 0:00:05||
Episode 8|Iteration 494|reward: 2300.0|last_reward_at:  418|Elapsed Time: 0:00:05||
Episode 8|Iteration 501|reward: 2300.0|last_reward_at:  418|Elapsed Time: 0:00:05||
Episode 8|Iteration 509|reward: 2300.0|last_reward_at:  418|Elapsed Time: 0:00:05||
Episode 8|Iteration 516|reward: 2300.0|last_reward_at:  418|Elapsed Time: 0:00:06||
Episode 8|Iteration 524|reward: 2300.0|last_reward_at:  418|Elapsed Time: 0:00:06||
Episode 8|Iteration 532|reward: 2300.0|last_reward_at:  418|Elapsed Time: 0:00:06||
Episode 8|Iteration 539|reward: 2300.0|last_reward_at:  418|Elapsed Time: 0:00:06||
Episode 8|Iteration 547|reward: 2300.0|last_reward_at:  418|Elapsed Time: 0:00:06||
Episode 8|Iteration 548|reward: 2300.0|last_reward_at:  418|Elapsed Time: 0:00:06||
Episode 8|Iteration 555|reward: 2300.0|last_reward_at:  418|Elapsed Time: 0:00:06||
Episode 8|Iteration 561|reward: 2300.0|last_reward_at:  418|Elapsed Time: 0:00:06||
Episode 8|Iteration 569|reward: 2300.0|last_reward_at:  418|Elapsed Time: 0:00:06||
Episode 8|Iteration 571|reward: 2300.0|last_reward_at:  418|Elapsed Time: 0:00:07||
Episode 8|Iteration 578|reward: 2300.0|last_reward_at:  418|Elapsed Time: 0:00:07||
Episode 8|Iteration 585|reward: 2300.0|last_reward_at:  418|Elapsed Time: 0:00:07||
Episode 8|Iteration 592|reward: 2300.0|last_reward_at:  418|Elapsed Time: 0:00:07||
Episode 8|Iteration 600|reward: 2300.0|last_reward_at:  418|Elapsed Time: 0:00:07||
Episode 8|Iteration 600|reward: 2300.0|last_reward_at:  418|Elapsed Time: 0:00:07||

  Episode 8 stopped at t=600
  Breakdown [Reward/NoReward (Success rate)]
    explore-local: 2/59 (0.03)
    explore-remote: 8/98 (0.08)
    explore-connect: 1/100 (0.01)
    exploit-local: 19/107 (0.15)
    exploit-remote: 12/179 (0.06)
    exploit-connect: 10/5 (0.67)
  exploit deflected to exploration: 14
  ## Episode: 9/10 'DQL' ϵ=0.4064, γ=0.15, lr=0.01, replaymemory=10000,
batch=256, target_update=5

Episode 9|Iteration 0|reward: ------|last_reward_at: ----|Elapsed Time: 0:00:00||
Episode 9|Iteration 1|reward:   14.0|last_reward_at: ----|Elapsed Time: 0:00:00||
Episode 9|Iteration 1|reward:   14.0|last_reward_at:    1|Elapsed Time: 0:00:00||
Episode 9|Iteration 6|reward:   18.0|last_reward_at:    1|Elapsed Time: 0:00:00||
Episode 9|Iteration 6|reward:   18.0|last_reward_at:    6|Elapsed Time: 0:00:00||
Episode 9|Iteration 14|reward:   20.0|last_reward_at:    6|Elapsed Time: 0:00:00||
Episode 9|Iteration 14|reward:   20.0|last_reward_at:   14|Elapsed Time: 0:00:00||
Episode 9|Iteration 23|reward:   20.0|last_reward_at:   14|Elapsed Time: 0:00:00||
Episode 9|Iteration 31|reward:   20.0|last_reward_at:   14|Elapsed Time: 0:00:00||
Episode 9|Iteration 38|reward:   20.0|last_reward_at:   14|Elapsed Time: 0:00:00||
Episode 9|Iteration 46|reward:   20.0|last_reward_at:   14|Elapsed Time: 0:00:00||
Episode 9|Iteration 54|reward:   20.0|last_reward_at:   14|Elapsed Time: 0:00:00||
Episode 9|Iteration 61|reward:   20.0|last_reward_at:   14|Elapsed Time: 0:00:00||
Episode 9|Iteration 69|reward:   20.0|last_reward_at:   14|Elapsed Time: 0:00:00||
Episode 9|Iteration 76|reward:   20.0|last_reward_at:   14|Elapsed Time: 0:00:00||
Episode 9|Iteration 84|reward:   20.0|last_reward_at:   14|Elapsed Time: 0:00:00||
Episode 9|Iteration 92|reward:   20.0|last_reward_at:   14|Elapsed Time: 0:00:00||
Episode 9|Iteration 95|reward:  120.0|last_reward_at:   14|Elapsed Time: 0:00:00||
Episode 9|Iteration 95|reward:  120.0|last_reward_at:   95|Elapsed Time: 0:00:00||
Episode 9|Iteration 96|reward:  134.0|last_reward_at:   95|Elapsed Time: 0:00:00||
Episode 9|Iteration 96|reward:  134.0|last_reward_at:   96|Elapsed Time: 0:00:00||
Episode 9|Iteration 99|reward:  140.0|last_reward_at:   96|Elapsed Time: 0:00:00||
Episode 9|Iteration 99|reward:  140.0|last_reward_at:   99|Elapsed Time: 0:00:00||
Episode 9|Iteration 106|reward:  146.0|last_reward_at:   99|Elapsed Time: 0:00:00||
Episode 9|Iteration 106|reward:  146.0|last_reward_at:  106|Elapsed Time: 0:00:00||
Episode 9|Iteration 107|reward:  154.0|last_reward_at:  106|Elapsed Time: 0:00:00||
Episode 9|Iteration 107|reward:  154.0|last_reward_at:  107|Elapsed Time: 0:00:00||
Episode 9|Iteration 114|reward:  154.0|last_reward_at:  107|Elapsed Time: 0:00:01||
Episode 9|Iteration 122|reward:  154.0|last_reward_at:  107|Elapsed Time: 0:00:01||
Episode 9|Iteration 125|reward:  254.0|last_reward_at:  107|Elapsed Time: 0:00:01||
Episode 9|Iteration 125|reward:  254.0|last_reward_at:  125|Elapsed Time: 0:00:01||
Episode 9|Iteration 127|reward:  268.0|last_reward_at:  125|Elapsed Time: 0:00:01||
Episode 9|Iteration 127|reward:  268.0|last_reward_at:  127|Elapsed Time: 0:00:01||
Episode 9|Iteration 128|reward:  368.0|last_reward_at:  127|Elapsed Time: 0:00:01||
Episode 9|Iteration 128|reward:  368.0|last_reward_at:  128|Elapsed Time: 0:00:01||
Episode 9|Iteration 129|reward:  382.0|last_reward_at:  128|Elapsed Time: 0:00:01||
Episode 9|Iteration 129|reward:  382.0|last_reward_at:  129|Elapsed Time: 0:00:01||
Episode 9|Iteration 131|reward:  388.0|last_reward_at:  129|Elapsed Time: 0:00:01||
Episode 9|Iteration 131|reward:  388.0|last_reward_at:  131|Elapsed Time: 0:00:01||
Episode 9|Iteration 133|reward:  394.0|last_reward_at:  131|Elapsed Time: 0:00:01||
Episode 9|Iteration 133|reward:  394.0|last_reward_at:  133|Elapsed Time: 0:00:01||
Episode 9|Iteration 136|reward:  494.0|last_reward_at:  133|Elapsed Time: 0:00:01||
Episode 9|Iteration 136|reward:  494.0|last_reward_at:  136|Elapsed Time: 0:00:01||
Episode 9|Iteration 138|reward:  508.0|last_reward_at:  136|Elapsed Time: 0:00:01||
Episode 9|Iteration 138|reward:  508.0|last_reward_at:  138|Elapsed Time: 0:00:01||
Episode 9|Iteration 139|reward:  608.0|last_reward_at:  138|Elapsed Time: 0:00:01||
Episode 9|Iteration 139|reward:  608.0|last_reward_at:  139|Elapsed Time: 0:00:01||
Episode 9|Iteration 140|reward:  622.0|last_reward_at:  139|Elapsed Time: 0:00:01||
Episode 9|Iteration 140|reward:  622.0|last_reward_at:  140|Elapsed Time: 0:00:01||
Episode 9|Iteration 141|reward:  628.0|last_reward_at:  140|Elapsed Time: 0:00:01||
Episode 9|Iteration 141|reward:  628.0|last_reward_at:  141|Elapsed Time: 0:00:01||
Episode 9|Iteration 143|reward:  634.0|last_reward_at:  141|Elapsed Time: 0:00:01||
Episode 9|Iteration 143|reward:  634.0|last_reward_at:  143|Elapsed Time: 0:00:01||
Episode 9|Iteration 145|reward:  640.0|last_reward_at:  143|Elapsed Time: 0:00:01||
Episode 9|Iteration 145|reward:  640.0|last_reward_at:  145|Elapsed Time: 0:00:01||
Episode 9|Iteration 146|reward:  646.0|last_reward_at:  145|Elapsed Time: 0:00:01||
Episode 9|Iteration 146|reward:  646.0|last_reward_at:  146|Elapsed Time: 0:00:01||
Episode 9|Iteration 147|reward:  654.0|last_reward_at:  146|Elapsed Time: 0:00:01||
Episode 9|Iteration 147|reward:  654.0|last_reward_at:  147|Elapsed Time: 0:00:01||
Episode 9|Iteration 152|reward:  660.0|last_reward_at:  147|Elapsed Time: 0:00:01||
Episode 9|Iteration 152|reward:  660.0|last_reward_at:  152|Elapsed Time: 0:00:01||
Episode 9|Iteration 154|reward:  662.0|last_reward_at:  152|Elapsed Time: 0:00:01||
Episode 9|Iteration 154|reward:  662.0|last_reward_at:  154|Elapsed Time: 0:00:01||
Episode 9|Iteration 165|reward:  662.0|last_reward_at:  154|Elapsed Time: 0:00:01||
Episode 9|Iteration 168|reward:  664.0|last_reward_at:  154|Elapsed Time: 0:00:01||
Episode 9|Iteration 168|reward:  664.0|last_reward_at:  168|Elapsed Time: 0:00:01||
Episode 9|Iteration 175|reward:  664.0|last_reward_at:  168|Elapsed Time: 0:00:01||
Episode 9|Iteration 180|reward:  666.0|last_reward_at:  168|Elapsed Time: 0:00:01||
Episode 9|Iteration 180|reward:  666.0|last_reward_at:  180|Elapsed Time: 0:00:01||
Episode 9|Iteration 186|reward:  766.0|last_reward_at:  180|Elapsed Time: 0:00:01||
Episode 9|Iteration 186|reward:  766.0|last_reward_at:  186|Elapsed Time: 0:00:01||
Episode 9|Iteration 188|reward:  780.0|last_reward_at:  186|Elapsed Time: 0:00:01||
Episode 9|Iteration 188|reward:  780.0|last_reward_at:  188|Elapsed Time: 0:00:01||
Episode 9|Iteration 189|reward:  880.0|last_reward_at:  188|Elapsed Time: 0:00:01||
Episode 9|Iteration 189|reward:  880.0|last_reward_at:  189|Elapsed Time: 0:00:01||
Episode 9|Iteration 190|reward:  894.0|last_reward_at:  189|Elapsed Time: 0:00:01||
Episode 9|Iteration 190|reward:  894.0|last_reward_at:  190|Elapsed Time: 0:00:01||
Episode 9|Iteration 191|reward:  900.0|last_reward_at:  190|Elapsed Time: 0:00:01||
Episode 9|Iteration 191|reward:  900.0|last_reward_at:  191|Elapsed Time: 0:00:01||
Episode 9|Iteration 193|reward:  906.0|last_reward_at:  191|Elapsed Time: 0:00:01||
Episode 9|Iteration 193|reward:  906.0|last_reward_at:  193|Elapsed Time: 0:00:01||
Episode 9|Iteration 200|reward:  908.0|last_reward_at:  193|Elapsed Time: 0:00:02||
Episode 9|Iteration 200|reward:  908.0|last_reward_at:  200|Elapsed Time: 0:00:02||
Episode 9|Iteration 201|reward:  914.0|last_reward_at:  200|Elapsed Time: 0:00:02||
Episode 9|Iteration 201|reward:  914.0|last_reward_at:  201|Elapsed Time: 0:00:02||
Episode 9|Iteration 206|reward:  914.0|last_reward_at:  201|Elapsed Time: 0:00:02||
Episode 9|Iteration 206|reward:  916.0|last_reward_at:  201|Elapsed Time: 0:00:02||
Episode 9|Iteration 206|reward:  916.0|last_reward_at:  206|Elapsed Time: 0:00:02||
Episode 9|Iteration 210|reward:  918.0|last_reward_at:  206|Elapsed Time: 0:00:02||
Episode 9|Iteration 210|reward:  918.0|last_reward_at:  210|Elapsed Time: 0:00:02||
Episode 9|Iteration 212|reward:  926.0|last_reward_at:  210|Elapsed Time: 0:00:02||
Episode 9|Iteration 212|reward:  926.0|last_reward_at:  212|Elapsed Time: 0:00:02||
Episode 9|Iteration 218|reward: 1026.0|last_reward_at:  212|Elapsed Time: 0:00:02||
Episode 9|Iteration 218|reward: 1026.0|last_reward_at:  218|Elapsed Time: 0:00:02||
Episode 9|Iteration 219|reward: 1040.0|last_reward_at:  218|Elapsed Time: 0:00:02||
Episode 9|Iteration 219|reward: 1040.0|last_reward_at:  219|Elapsed Time: 0:00:02||
Episode 9|Iteration 220|reward: 1140.0|last_reward_at:  219|Elapsed Time: 0:00:02||
Episode 9|Iteration 220|reward: 1140.0|last_reward_at:  220|Elapsed Time: 0:00:02||
Episode 9|Iteration 222|reward: 1154.0|last_reward_at:  220|Elapsed Time: 0:00:02||
Episode 9|Iteration 222|reward: 1154.0|last_reward_at:  222|Elapsed Time: 0:00:02||
Episode 9|Iteration 223|reward: 1160.0|last_reward_at:  222|Elapsed Time: 0:00:02||
Episode 9|Iteration 223|reward: 1160.0|last_reward_at:  223|Elapsed Time: 0:00:02||
Episode 9|Iteration 228|reward: 1160.0|last_reward_at:  223|Elapsed Time: 0:00:02||
Episode 9|Iteration 228|reward: 1166.0|last_reward_at:  223|Elapsed Time: 0:00:02||
Episode 9|Iteration 228|reward: 1166.0|last_reward_at:  228|Elapsed Time: 0:00:02||
Episode 9|Iteration 230|reward: 1168.0|last_reward_at:  228|Elapsed Time: 0:00:02||
Episode 9|Iteration 230|reward: 1168.0|last_reward_at:  230|Elapsed Time: 0:00:02||
Episode 9|Iteration 233|reward: 1170.0|last_reward_at:  230|Elapsed Time: 0:00:02||
Episode 9|Iteration 233|reward: 1170.0|last_reward_at:  233|Elapsed Time: 0:00:02||
Episode 9|Iteration 239|reward: 1270.0|last_reward_at:  233|Elapsed Time: 0:00:02||
Episode 9|Iteration 239|reward: 1270.0|last_reward_at:  239|Elapsed Time: 0:00:02||
Episode 9|Iteration 240|reward: 1284.0|last_reward_at:  239|Elapsed Time: 0:00:02||
Episode 9|Iteration 240|reward: 1284.0|last_reward_at:  240|Elapsed Time: 0:00:02||
Episode 9|Iteration 243|reward: 2284.0|last_reward_at:  240|Elapsed Time: 0:00:02||
Episode 9|Iteration 243|reward: 2284.0|last_reward_at:  243|Elapsed Time: 0:00:02||
Episode 9|Iteration 251|reward: 2284.0|last_reward_at:  243|Elapsed Time: 0:00:02||
Episode 9|Iteration 258|reward: 2284.0|last_reward_at:  243|Elapsed Time: 0:00:02||
Episode 9|Iteration 266|reward: 2284.0|last_reward_at:  243|Elapsed Time: 0:00:02||
Episode 9|Iteration 268|reward: 2290.0|last_reward_at:  243|Elapsed Time: 0:00:02||
Episode 9|Iteration 268|reward: 2290.0|last_reward_at:  268|Elapsed Time: 0:00:02||
Episode 9|Iteration 274|reward: 2290.0|last_reward_at:  268|Elapsed Time: 0:00:03||
Episode 9|Iteration 275|reward: 2290.0|last_reward_at:  268|Elapsed Time: 0:00:03||
Episode 9|Iteration 282|reward: 2290.0|last_reward_at:  268|Elapsed Time: 0:00:03||
Episode 9|Iteration 284|reward: 2296.0|last_reward_at:  268|Elapsed Time: 0:00:03||
Episode 9|Iteration 284|reward: 2296.0|last_reward_at:  284|Elapsed Time: 0:00:03||
Episode 9|Iteration 289|reward: 2296.0|last_reward_at:  284|Elapsed Time: 0:00:03||
Episode 9|Iteration 296|reward: 2296.0|last_reward_at:  284|Elapsed Time: 0:00:03||
Episode 9|Iteration 304|reward: 2296.0|last_reward_at:  284|Elapsed Time: 0:00:03||
Episode 9|Iteration 305|reward: 2296.0|last_reward_at:  284|Elapsed Time: 0:00:03||
Episode 9|Iteration 309|reward: 2302.0|last_reward_at:  284|Elapsed Time: 0:00:03||
Episode 9|Iteration 309|reward: 2302.0|last_reward_at:  309|Elapsed Time: 0:00:03||
Episode 9|Iteration 317|reward: 2302.0|last_reward_at:  309|Elapsed Time: 0:00:03||
Episode 9|Iteration 323|reward: 2302.0|last_reward_at:  309|Elapsed Time: 0:00:03||
Episode 9|Iteration 325|reward: 2302.0|last_reward_at:  309|Elapsed Time: 0:00:03||
Episode 9|Iteration 334|reward: 2302.0|last_reward_at:  309|Elapsed Time: 0:00:04||
Episode 9|Iteration 342|reward: 2302.0|last_reward_at:  309|Elapsed Time: 0:00:04||
Episode 9|Iteration 349|reward: 2302.0|last_reward_at:  309|Elapsed Time: 0:00:04||
Episode 9|Iteration 357|reward: 2302.0|last_reward_at:  309|Elapsed Time: 0:00:04||
Episode 9|Iteration 364|reward: 2302.0|last_reward_at:  309|Elapsed Time: 0:00:04||
Episode 9|Iteration 371|reward: 2302.0|last_reward_at:  309|Elapsed Time: 0:00:04||
Episode 9|Iteration 379|reward: 2302.0|last_reward_at:  309|Elapsed Time: 0:00:04||
Episode 9|Iteration 386|reward: 2302.0|last_reward_at:  309|Elapsed Time: 0:00:04||
Episode 9|Iteration 393|reward: 2302.0|last_reward_at:  309|Elapsed Time: 0:00:04||
Episode 9|Iteration 400|reward: 2302.0|last_reward_at:  309|Elapsed Time: 0:00:05||
Episode 9|Iteration 407|reward: 2302.0|last_reward_at:  309|Elapsed Time: 0:00:05||
Episode 9|Iteration 414|reward: 2302.0|last_reward_at:  309|Elapsed Time: 0:00:05||
Episode 9|Iteration 416|reward: 2302.0|last_reward_at:  309|Elapsed Time: 0:00:05||
Episode 9|Iteration 424|reward: 2302.0|last_reward_at:  309|Elapsed Time: 0:00:05||
Episode 9|Iteration 431|reward: 2302.0|last_reward_at:  309|Elapsed Time: 0:00:05||
Episode 9|Iteration 438|reward: 2302.0|last_reward_at:  309|Elapsed Time: 0:00:05||
Episode 9|Iteration 446|reward: 2302.0|last_reward_at:  309|Elapsed Time: 0:00:05||
Episode 9|Iteration 454|reward: 2302.0|last_reward_at:  309|Elapsed Time: 0:00:05||
Episode 9|Iteration 461|reward: 2302.0|last_reward_at:  309|Elapsed Time: 0:00:05||
Episode 9|Iteration 469|reward: 2302.0|last_reward_at:  309|Elapsed Time: 0:00:06||
Episode 9|Iteration 477|reward: 2302.0|last_reward_at:  309|Elapsed Time: 0:00:06||
Episode 9|Iteration 485|reward: 2302.0|last_reward_at:  309|Elapsed Time: 0:00:06||
Episode 9|Iteration 491|reward: 2302.0|last_reward_at:  309|Elapsed Time: 0:00:06||
Episode 9|Iteration 500|reward: 2302.0|last_reward_at:  309|Elapsed Time: 0:00:06||
Episode 9|Iteration 508|reward: 2302.0|last_reward_at:  309|Elapsed Time: 0:00:06||
Episode 9|Iteration 516|reward: 2302.0|last_reward_at:  309|Elapsed Time: 0:00:06||
Episode 9|Iteration 524|reward: 2302.0|last_reward_at:  309|Elapsed Time: 0:00:06||
Episode 9|Iteration 532|reward: 2302.0|last_reward_at:  309|Elapsed Time: 0:00:06||
Episode 9|Iteration 540|reward: 2302.0|last_reward_at:  309|Elapsed Time: 0:00:07||
Episode 9|Iteration 547|reward: 2302.0|last_reward_at:  309|Elapsed Time: 0:00:07||
Episode 9|Iteration 555|reward: 2302.0|last_reward_at:  309|Elapsed Time: 0:00:07||
Episode 9|Iteration 557|reward: 2302.0|last_reward_at:  309|Elapsed Time: 0:00:07||
Episode 9|Iteration 560|reward: 2302.0|last_reward_at:  309|Elapsed Time: 0:00:07||
Episode 9|Iteration 568|reward: 2302.0|last_reward_at:  309|Elapsed Time: 0:00:07||
Episode 9|Iteration 572|reward: 2302.0|last_reward_at:  309|Elapsed Time: 0:00:07||
Episode 9|Iteration 578|reward: 2302.0|last_reward_at:  309|Elapsed Time: 0:00:07||
Episode 9|Iteration 584|reward: 2302.0|last_reward_at:  309|Elapsed Time: 0:00:07||
Episode 9|Iteration 590|reward: 2302.0|last_reward_at:  309|Elapsed Time: 0:00:07||
Episode 9|Iteration 593|reward: 2302.0|last_reward_at:  309|Elapsed Time: 0:00:08||
Episode 9|Iteration 598|reward: 2302.0|last_reward_at:  309|Elapsed Time: 0:00:08||
Episode 9|Iteration 599|reward: 2302.0|last_reward_at:  309|Elapsed Time: 0:00:08||
Episode 9|Iteration 600|reward: 2302.0|last_reward_at:  309|Elapsed Time: 0:00:08||

  Episode 9 stopped at t=600
  Breakdown [Reward/NoReward (Success rate)]
    explore-local: 1/65 (0.02)
    explore-remote: 8/92 (0.08)
    explore-connect: 1/87 (0.01)
    exploit-local: 20/94 (0.18)
    exploit-remote: 12/196 (0.06)
    exploit-connect: 10/14 (0.42)
  exploit deflected to exploration: 19
  ## Episode: 10/10 'DQL' ϵ=0.3717, γ=0.15, lr=0.01, replaymemory=10000,
batch=256, target_update=5

Episode 10|Iteration 0|reward: ------|last_reward_at: ----|Elapsed Time: 0:00:00||
Episode 10|Iteration 1|reward:    0.0|last_reward_at: ----|Elapsed Time: 0:00:00||
Episode 10|Iteration 2|reward:   14.0|last_reward_at: ----|Elapsed Time: 0:00:00||
Episode 10|Iteration 2|reward:   14.0|last_reward_at:    2|Elapsed Time: 0:00:00||
Episode 10|Iteration 3|reward:   16.0|last_reward_at:    2|Elapsed Time: 0:00:00||
Episode 10|Iteration 3|reward:   16.0|last_reward_at:    3|Elapsed Time: 0:00:00||
Episode 10|Iteration 6|reward:   20.0|last_reward_at:    3|Elapsed Time: 0:00:00||
Episode 10|Iteration 6|reward:   20.0|last_reward_at:    6|Elapsed Time: 0:00:00||
Episode 10|Iteration 16|reward:   20.0|last_reward_at:    6|Elapsed Time: 0:00:00||
Episode 10|Iteration 23|reward:   20.0|last_reward_at:    6|Elapsed Time: 0:00:00||
Episode 10|Iteration 31|reward:   20.0|last_reward_at:    6|Elapsed Time: 0:00:00||
Episode 10|Iteration 38|reward:   20.0|last_reward_at:    6|Elapsed Time: 0:00:00||
Episode 10|Iteration 46|reward:   20.0|last_reward_at:    6|Elapsed Time: 0:00:00||
Episode 10|Iteration 54|reward:   20.0|last_reward_at:    6|Elapsed Time: 0:00:00||
Episode 10|Iteration 69|reward:   20.0|last_reward_at:    6|Elapsed Time: 0:00:00||
Episode 10|Iteration 84|reward:   20.0|last_reward_at:    6|Elapsed Time: 0:00:00||
Episode 10|Iteration 92|reward:   20.0|last_reward_at:    6|Elapsed Time: 0:00:00||
Episode 10|Iteration 106|reward:   20.0|last_reward_at:    6|Elapsed Time: 0:00:00||
Episode 10|Iteration 110|reward:  120.0|last_reward_at:    6|Elapsed Time: 0:00:00||
Episode 10|Iteration 110|reward:  120.0|last_reward_at:  110|Elapsed Time: 0:00:00||
Episode 10|Iteration 111|reward:  134.0|last_reward_at:  110|Elapsed Time: 0:00:00||
Episode 10|Iteration 111|reward:  134.0|last_reward_at:  111|Elapsed Time: 0:00:00||
Episode 10|Iteration 113|reward:  140.0|last_reward_at:  111|Elapsed Time: 0:00:00||
Episode 10|Iteration 113|reward:  140.0|last_reward_at:  113|Elapsed Time: 0:00:00||
Episode 10|Iteration 114|reward:  146.0|last_reward_at:  113|Elapsed Time: 0:00:00||
Episode 10|Iteration 114|reward:  146.0|last_reward_at:  114|Elapsed Time: 0:00:00||
Episode 10|Iteration 121|reward:  154.0|last_reward_at:  114|Elapsed Time: 0:00:00||
Episode 10|Iteration 121|reward:  154.0|last_reward_at:  121|Elapsed Time: 0:00:00||
Episode 10|Iteration 126|reward:  254.0|last_reward_at:  121|Elapsed Time: 0:00:00||
Episode 10|Iteration 126|reward:  254.0|last_reward_at:  126|Elapsed Time: 0:00:00||
Episode 10|Iteration 127|reward:  268.0|last_reward_at:  126|Elapsed Time: 0:00:01||
Episode 10|Iteration 127|reward:  268.0|last_reward_at:  127|Elapsed Time: 0:00:01||
Episode 10|Iteration 129|reward:  270.0|last_reward_at:  127|Elapsed Time: 0:00:01||
Episode 10|Iteration 129|reward:  270.0|last_reward_at:  129|Elapsed Time: 0:00:01||
Episode 10|Iteration 130|reward:  370.0|last_reward_at:  129|Elapsed Time: 0:00:01||
Episode 10|Iteration 130|reward:  370.0|last_reward_at:  130|Elapsed Time: 0:00:01||
Episode 10|Iteration 131|reward:  384.0|last_reward_at:  130|Elapsed Time: 0:00:01||
Episode 10|Iteration 131|reward:  384.0|last_reward_at:  131|Elapsed Time: 0:00:01||
Episode 10|Iteration 132|reward:  390.0|last_reward_at:  131|Elapsed Time: 0:00:01||
Episode 10|Iteration 132|reward:  390.0|last_reward_at:  132|Elapsed Time: 0:00:01||
Episode 10|Iteration 133|reward:  398.0|last_reward_at:  132|Elapsed Time: 0:00:01||
Episode 10|Iteration 133|reward:  398.0|last_reward_at:  133|Elapsed Time: 0:00:01||
Episode 10|Iteration 141|reward:  404.0|last_reward_at:  133|Elapsed Time: 0:00:01||
Episode 10|Iteration 141|reward:  404.0|last_reward_at:  141|Elapsed Time: 0:00:01||
Episode 10|Iteration 145|reward:  504.0|last_reward_at:  141|Elapsed Time: 0:00:01||
Episode 10|Iteration 145|reward:  504.0|last_reward_at:  145|Elapsed Time: 0:00:01||
Episode 10|Iteration 146|reward:  518.0|last_reward_at:  145|Elapsed Time: 0:00:01||
Episode 10|Iteration 146|reward:  518.0|last_reward_at:  146|Elapsed Time: 0:00:01||
Episode 10|Iteration 147|reward:  618.0|last_reward_at:  146|Elapsed Time: 0:00:01||
Episode 10|Iteration 147|reward:  618.0|last_reward_at:  147|Elapsed Time: 0:00:01||
Episode 10|Iteration 148|reward:  632.0|last_reward_at:  147|Elapsed Time: 0:00:01||
Episode 10|Iteration 148|reward:  632.0|last_reward_at:  148|Elapsed Time: 0:00:01||
Episode 10|Iteration 150|reward:  638.0|last_reward_at:  148|Elapsed Time: 0:00:01||
Episode 10|Iteration 150|reward:  638.0|last_reward_at:  150|Elapsed Time: 0:00:01||
Episode 10|Iteration 151|reward:  738.0|last_reward_at:  150|Elapsed Time: 0:00:01||
Episode 10|Iteration 151|reward:  738.0|last_reward_at:  151|Elapsed Time: 0:00:01||
Episode 10|Iteration 153|reward:  752.0|last_reward_at:  151|Elapsed Time: 0:00:01||
Episode 10|Iteration 153|reward:  752.0|last_reward_at:  153|Elapsed Time: 0:00:01||
Episode 10|Iteration 154|reward:  852.0|last_reward_at:  153|Elapsed Time: 0:00:01||
Episode 10|Iteration 154|reward:  852.0|last_reward_at:  154|Elapsed Time: 0:00:01||
Episode 10|Iteration 155|reward:  858.0|last_reward_at:  154|Elapsed Time: 0:00:01||
Episode 10|Iteration 155|reward:  858.0|last_reward_at:  155|Elapsed Time: 0:00:01||
Episode 10|Iteration 156|reward:  872.0|last_reward_at:  155|Elapsed Time: 0:00:01||
Episode 10|Iteration 156|reward:  872.0|last_reward_at:  156|Elapsed Time: 0:00:01||
Episode 10|Iteration 157|reward:  878.0|last_reward_at:  156|Elapsed Time: 0:00:01||
Episode 10|Iteration 157|reward:  878.0|last_reward_at:  157|Elapsed Time: 0:00:01||
Episode 10|Iteration 159|reward:  884.0|last_reward_at:  157|Elapsed Time: 0:00:01||
Episode 10|Iteration 159|reward:  884.0|last_reward_at:  159|Elapsed Time: 0:00:01||
Episode 10|Iteration 160|reward:  886.0|last_reward_at:  159|Elapsed Time: 0:00:01||
Episode 10|Iteration 160|reward:  886.0|last_reward_at:  160|Elapsed Time: 0:00:01||
Episode 10|Iteration 164|reward:  888.0|last_reward_at:  160|Elapsed Time: 0:00:01||
Episode 10|Iteration 164|reward:  888.0|last_reward_at:  164|Elapsed Time: 0:00:01||
Episode 10|Iteration 165|reward:  890.0|last_reward_at:  164|Elapsed Time: 0:00:01||
Episode 10|Iteration 165|reward:  890.0|last_reward_at:  165|Elapsed Time: 0:00:01||
Episode 10|Iteration 169|reward:  896.0|last_reward_at:  165|Elapsed Time: 0:00:01||
Episode 10|Iteration 169|reward:  896.0|last_reward_at:  169|Elapsed Time: 0:00:01||
Episode 10|Iteration 175|reward:  896.0|last_reward_at:  169|Elapsed Time: 0:00:01||
Episode 10|Iteration 179|reward:  902.0|last_reward_at:  169|Elapsed Time: 0:00:01||
Episode 10|Iteration 179|reward:  902.0|last_reward_at:  179|Elapsed Time: 0:00:01||
Episode 10|Iteration 187|reward:  910.0|last_reward_at:  179|Elapsed Time: 0:00:01||
Episode 10|Iteration 187|reward:  910.0|last_reward_at:  187|Elapsed Time: 0:00:01||
Episode 10|Iteration 197|reward:  910.0|last_reward_at:  187|Elapsed Time: 0:00:01||
Episode 10|Iteration 198|reward:  916.0|last_reward_at:  187|Elapsed Time: 0:00:01||
Episode 10|Iteration 198|reward:  916.0|last_reward_at:  198|Elapsed Time: 0:00:01||
Episode 10|Iteration 206|reward:  916.0|last_reward_at:  198|Elapsed Time: 0:00:01||
Episode 10|Iteration 208|reward:  922.0|last_reward_at:  198|Elapsed Time: 0:00:01||
Episode 10|Iteration 208|reward:  922.0|last_reward_at:  208|Elapsed Time: 0:00:01||
Episode 10|Iteration 209|reward: 1022.0|last_reward_at:  208|Elapsed Time: 0:00:02||
Episode 10|Iteration 209|reward: 1022.0|last_reward_at:  209|Elapsed Time: 0:00:02||
Episode 10|Iteration 210|reward: 1036.0|last_reward_at:  209|Elapsed Time: 0:00:02||
Episode 10|Iteration 210|reward: 1036.0|last_reward_at:  210|Elapsed Time: 0:00:02||
Episode 10|Iteration 211|reward: 1136.0|last_reward_at:  210|Elapsed Time: 0:00:02||
Episode 10|Iteration 211|reward: 1136.0|last_reward_at:  211|Elapsed Time: 0:00:02||
Episode 10|Iteration 212|reward: 1150.0|last_reward_at:  211|Elapsed Time: 0:00:02||
Episode 10|Iteration 212|reward: 1150.0|last_reward_at:  212|Elapsed Time: 0:00:02||
Episode 10|Iteration 213|reward: 1156.0|last_reward_at:  212|Elapsed Time: 0:00:02||
Episode 10|Iteration 213|reward: 1156.0|last_reward_at:  213|Elapsed Time: 0:00:02||
Episode 10|Iteration 220|reward: 1158.0|last_reward_at:  213|Elapsed Time: 0:00:02||
Episode 10|Iteration 220|reward: 1158.0|last_reward_at:  220|Elapsed Time: 0:00:02||
Episode 10|Iteration 227|reward: 1166.0|last_reward_at:  220|Elapsed Time: 0:00:02||
Episode 10|Iteration 227|reward: 1166.0|last_reward_at:  227|Elapsed Time: 0:00:02||
Episode 10|Iteration 231|reward: 1168.0|last_reward_at:  227|Elapsed Time: 0:00:02||
Episode 10|Iteration 231|reward: 1168.0|last_reward_at:  231|Elapsed Time: 0:00:02||
Episode 10|Iteration 233|reward: 1170.0|last_reward_at:  231|Elapsed Time: 0:00:02||
Episode 10|Iteration 233|reward: 1170.0|last_reward_at:  233|Elapsed Time: 0:00:02||
Episode 10|Iteration 242|reward: 1170.0|last_reward_at:  233|Elapsed Time: 0:00:02||
Episode 10|Iteration 243|reward: 1176.0|last_reward_at:  233|Elapsed Time: 0:00:02||
Episode 10|Iteration 243|reward: 1176.0|last_reward_at:  243|Elapsed Time: 0:00:02||
Episode 10|Iteration 251|reward: 1176.0|last_reward_at:  243|Elapsed Time: 0:00:02||
Episode 10|Iteration 254|reward: 1276.0|last_reward_at:  243|Elapsed Time: 0:00:02||
Episode 10|Iteration 254|reward: 1276.0|last_reward_at:  254|Elapsed Time: 0:00:02||
Episode 10|Iteration 255|reward: 1290.0|last_reward_at:  254|Elapsed Time: 0:00:02||
Episode 10|Iteration 255|reward: 1290.0|last_reward_at:  255|Elapsed Time: 0:00:02||
Episode 10|Iteration 257|reward: 2290.0|last_reward_at:  255|Elapsed Time: 0:00:02||
Episode 10|Iteration 257|reward: 2290.0|last_reward_at:  257|Elapsed Time: 0:00:02||
Episode 10|Iteration 266|reward: 2290.0|last_reward_at:  257|Elapsed Time: 0:00:02||
Episode 10|Iteration 272|reward: 2296.0|last_reward_at:  257|Elapsed Time: 0:00:02||
Episode 10|Iteration 272|reward: 2296.0|last_reward_at:  272|Elapsed Time: 0:00:02||
Episode 10|Iteration 279|reward: 2296.0|last_reward_at:  272|Elapsed Time: 0:00:02||
Episode 10|Iteration 281|reward: 2298.0|last_reward_at:  272|Elapsed Time: 0:00:02||
Episode 10|Iteration 281|reward: 2298.0|last_reward_at:  281|Elapsed Time: 0:00:02||
Episode 10|Iteration 289|reward: 2298.0|last_reward_at:  281|Elapsed Time: 0:00:03||
Episode 10|Iteration 296|reward: 2298.0|last_reward_at:  281|Elapsed Time: 0:00:03||
Episode 10|Iteration 302|reward: 2298.0|last_reward_at:  281|Elapsed Time: 0:00:03||
Episode 10|Iteration 308|reward: 2298.0|last_reward_at:  281|Elapsed Time: 0:00:03||
Episode 10|Iteration 316|reward: 2298.0|last_reward_at:  281|Elapsed Time: 0:00:03||
Episode 10|Iteration 325|reward: 2298.0|last_reward_at:  281|Elapsed Time: 0:00:03||
Episode 10|Iteration 333|reward: 2298.0|last_reward_at:  281|Elapsed Time: 0:00:03||
Episode 10|Iteration 337|reward: 2304.0|last_reward_at:  281|Elapsed Time: 0:00:03||
Episode 10|Iteration 337|reward: 2304.0|last_reward_at:  337|Elapsed Time: 0:00:03||
Episode 10|Iteration 342|reward: 2304.0|last_reward_at:  337|Elapsed Time: 0:00:03||
Episode 10|Iteration 343|reward: 2304.0|last_reward_at:  337|Elapsed Time: 0:00:04||
Episode 10|Iteration 350|reward: 2304.0|last_reward_at:  337|Elapsed Time: 0:00:04||
Episode 10|Iteration 357|reward: 2304.0|last_reward_at:  337|Elapsed Time: 0:00:04||
Episode 10|Iteration 364|reward: 2304.0|last_reward_at:  337|Elapsed Time: 0:00:04||
Episode 10|Iteration 367|reward: 2304.0|last_reward_at:  337|Elapsed Time: 0:00:04||
Episode 10|Iteration 373|reward: 2304.0|last_reward_at:  337|Elapsed Time: 0:00:04||
Episode 10|Iteration 380|reward: 2304.0|last_reward_at:  337|Elapsed Time: 0:00:04||
Episode 10|Iteration 386|reward: 2304.0|last_reward_at:  337|Elapsed Time: 0:00:04||
Episode 10|Iteration 393|reward: 2304.0|last_reward_at:  337|Elapsed Time: 0:00:04||
Episode 10|Iteration 401|reward: 2304.0|last_reward_at:  337|Elapsed Time: 0:00:04||
Episode 10|Iteration 409|reward: 2304.0|last_reward_at:  337|Elapsed Time: 0:00:05||
Episode 10|Iteration 417|reward: 2304.0|last_reward_at:  337|Elapsed Time: 0:00:05||
Episode 10|Iteration 425|reward: 2304.0|last_reward_at:  337|Elapsed Time: 0:00:05||
Episode 10|Iteration 433|reward: 2304.0|last_reward_at:  337|Elapsed Time: 0:00:05||
Episode 10|Iteration 440|reward: 2304.0|last_reward_at:  337|Elapsed Time: 0:00:05||
Episode 10|Iteration 448|reward: 2304.0|last_reward_at:  337|Elapsed Time: 0:00:05||
Episode 10|Iteration 456|reward: 2304.0|last_reward_at:  337|Elapsed Time: 0:00:05||
Episode 10|Iteration 463|reward: 2304.0|last_reward_at:  337|Elapsed Time: 0:00:05||
Episode 10|Iteration 471|reward: 2304.0|last_reward_at:  337|Elapsed Time: 0:00:05||
Episode 10|Iteration 474|reward: 2304.0|last_reward_at:  337|Elapsed Time: 0:00:05||
Episode 10|Iteration 479|reward: 2304.0|last_reward_at:  337|Elapsed Time: 0:00:06||
Episode 10|Iteration 486|reward: 2304.0|last_reward_at:  337|Elapsed Time: 0:00:06||
Episode 10|Iteration 494|reward: 2304.0|last_reward_at:  337|Elapsed Time: 0:00:06||
Episode 10|Iteration 501|reward: 2304.0|last_reward_at:  337|Elapsed Time: 0:00:06||
Episode 10|Iteration 508|reward: 2304.0|last_reward_at:  337|Elapsed Time: 0:00:06||
Episode 10|Iteration 516|reward: 2304.0|last_reward_at:  337|Elapsed Time: 0:00:06||
Episode 10|Iteration 524|reward: 2304.0|last_reward_at:  337|Elapsed Time: 0:00:06||
Episode 10|Iteration 526|reward: 2304.0|last_reward_at:  337|Elapsed Time: 0:00:06||
Episode 10|Iteration 532|reward: 2304.0|last_reward_at:  337|Elapsed Time: 0:00:06||
Episode 10|Iteration 539|reward: 2304.0|last_reward_at:  337|Elapsed Time: 0:00:07||
Episode 10|Iteration 546|reward: 2304.0|last_reward_at:  337|Elapsed Time: 0:00:07||
Episode 10|Iteration 554|reward: 2304.0|last_reward_at:  337|Elapsed Time: 0:00:07||
Episode 10|Iteration 562|reward: 2304.0|last_reward_at:  337|Elapsed Time: 0:00:07||
Episode 10|Iteration 570|reward: 2304.0|last_reward_at:  337|Elapsed Time: 0:00:07||
Episode 10|Iteration 577|reward: 2304.0|last_reward_at:  337|Elapsed Time: 0:00:07||
Episode 10|Iteration 585|reward: 2304.0|last_reward_at:  337|Elapsed Time: 0:00:07||
Episode 10|Iteration 592|reward: 2304.0|last_reward_at:  337|Elapsed Time: 0:00:07||
Episode 10|Iteration 595|reward: 2304.0|last_reward_at:  337|Elapsed Time: 0:00:07||
Episode 10|Iteration 600|reward: 2304.0|last_reward_at:  337|Elapsed Time: 0:00:07||
Episode 10|Iteration 600|reward: 2304.0|last_reward_at:  337|Elapsed Time: 0:00:07||

  Episode 10 stopped at t=600
  Breakdown [Reward/NoReward (Success rate)]
    explore-local: 2/52 (0.04)
    explore-remote: 8/69 (0.10)
    explore-connect: 0/86 (0.00)
    exploit-local: 19/77 (0.20)
    exploit-remote: 12/258 (0.04)
    exploit-connect: 11/6 (0.65)
  exploit deflected to exploration: 9
simulation ended

In [19]:
dql_exploit_run = learner.epsilon_greedy_search(
    cyberbattlechain_defender,
    ep,
    learner=dqn_with_defender["learner"],
    episode_count=training_episode_count,
    iteration_count=iteration_count,
    epsilon=0.0,  # 0.35,
    render=True,
    # render_last_episode_rewards_to='images/chain10',
    verbosity=Verbosity.Quiet,
    title="Exploiting DQL",
)

###### Exploiting DQL
Learning with: episode_count=10,iteration_count=600,ϵ=0.0,ϵ_min=0.0, γ=0.15, lr=0.01, replaymemory=10000,
batch=256, target_update=5
  ## Episode: 1/10 'Exploiting DQL' ϵ=0.0000, γ=0.15, lr=0.01, replaymemory=10000,
batch=256, target_update=5

Episode 1|Iteration 0|reward: ------|last_reward_at: ----|Elapsed Time: 0:00:00||
Episode 1|Iteration 1|reward:   14.0|last_reward_at: ----|Elapsed Time: 0:00:00||
Episode 1|Iteration 1|reward:   14.0|last_reward_at:    1|Elapsed Time: 0:00:00||
Episode 1|Iteration 4|reward:   16.0|last_reward_at:    1|Elapsed Time: 0:00:00||
Episode 1|Iteration 4|reward:   16.0|last_reward_at:    4|Elapsed Time: 0:00:00||
Episode 1|Iteration 6|reward:  116.0|last_reward_at:    4|Elapsed Time: 0:00:00||
Episode 1|Iteration 6|reward:  116.0|last_reward_at:    6|Elapsed Time: 0:00:00||
Episode 1|Iteration 7|reward:  130.0|last_reward_at:    6|Elapsed Time: 0:00:00||
Episode 1|Iteration 7|reward:  130.0|last_reward_at:    7|Elapsed Time: 0:00:00||
Episode 1|Iteration 8|reward:  136.0|last_reward_at:    7|Elapsed Time: 0:00:00||
Episode 1|Iteration 8|reward:  136.0|last_reward_at:    8|Elapsed Time: 0:00:00||
Episode 1|Iteration 9|reward:  144.0|last_reward_at:    8|Elapsed Time: 0:00:00||
Episode 1|Iteration 9|reward:  144.0|last_reward_at:    9|Elapsed Time: 0:00:00||
Episode 1|Iteration 16|reward:  144.0|last_reward_at:    9|Elapsed Time: 0:00:00||
Episode 1|Iteration 23|reward:  144.0|last_reward_at:    9|Elapsed Time: 0:00:00||
Episode 1|Iteration 29|reward:  150.0|last_reward_at:    9|Elapsed Time: 0:00:00||
Episode 1|Iteration 29|reward:  150.0|last_reward_at:   29|Elapsed Time: 0:00:00||
Episode 1|Iteration 33|reward:  152.0|last_reward_at:   29|Elapsed Time: 0:00:00||
Episode 1|Iteration 33|reward:  152.0|last_reward_at:   33|Elapsed Time: 0:00:00||
Episode 1|Iteration 45|reward:  152.0|last_reward_at:   33|Elapsed Time: 0:00:00||
Episode 1|Iteration 54|reward:  152.0|last_reward_at:   33|Elapsed Time: 0:00:00||
Episode 1|Iteration 56|reward:  252.0|last_reward_at:   33|Elapsed Time: 0:00:00||
Episode 1|Iteration 56|reward:  252.0|last_reward_at:   56|Elapsed Time: 0:00:00||
Episode 1|Iteration 57|reward:  266.0|last_reward_at:   56|Elapsed Time: 0:00:00||
Episode 1|Iteration 57|reward:  266.0|last_reward_at:   57|Elapsed Time: 0:00:00||
Episode 1|Iteration 58|reward:  366.0|last_reward_at:   57|Elapsed Time: 0:00:00||
Episode 1|Iteration 58|reward:  366.0|last_reward_at:   58|Elapsed Time: 0:00:00||
Episode 1|Iteration 59|reward:  380.0|last_reward_at:   58|Elapsed Time: 0:00:00||
Episode 1|Iteration 59|reward:  380.0|last_reward_at:   59|Elapsed Time: 0:00:00||
Episode 1|Iteration 60|reward:  386.0|last_reward_at:   59|Elapsed Time: 0:00:00||
Episode 1|Iteration 60|reward:  386.0|last_reward_at:   60|Elapsed Time: 0:00:00||
Episode 1|Iteration 61|reward:  394.0|last_reward_at:   60|Elapsed Time: 0:00:00||
Episode 1|Iteration 61|reward:  394.0|last_reward_at:   61|Elapsed Time: 0:00:00||
Episode 1|Iteration 68|reward:  396.0|last_reward_at:   61|Elapsed Time: 0:00:00||
Episode 1|Iteration 68|reward:  396.0|last_reward_at:   68|Elapsed Time: 0:00:00||
Episode 1|Iteration 69|reward:  402.0|last_reward_at:   68|Elapsed Time: 0:00:00||
Episode 1|Iteration 69|reward:  402.0|last_reward_at:   69|Elapsed Time: 0:00:00||
Episode 1|Iteration 76|reward:  402.0|last_reward_at:   69|Elapsed Time: 0:00:00||
Episode 1|Iteration 84|reward:  402.0|last_reward_at:   69|Elapsed Time: 0:00:00||
Episode 1|Iteration 89|reward:  408.0|last_reward_at:   69|Elapsed Time: 0:00:00||
Episode 1|Iteration 89|reward:  408.0|last_reward_at:   89|Elapsed Time: 0:00:00||
Episode 1|Iteration 92|reward:  410.0|last_reward_at:   89|Elapsed Time: 0:00:00||
Episode 1|Iteration 92|reward:  410.0|last_reward_at:   92|Elapsed Time: 0:00:00||
Episode 1|Iteration 99|reward:  410.0|last_reward_at:   92|Elapsed Time: 0:00:00||
Episode 1|Iteration 107|reward:  410.0|last_reward_at:   92|Elapsed Time: 0:00:01||
Episode 1|Iteration 114|reward:  410.0|last_reward_at:   92|Elapsed Time: 0:00:01||
Episode 1|Iteration 122|reward:  410.0|last_reward_at:   92|Elapsed Time: 0:00:01||
Episode 1|Iteration 130|reward:  410.0|last_reward_at:   92|Elapsed Time: 0:00:01||
Episode 1|Iteration 137|reward:  410.0|last_reward_at:   92|Elapsed Time: 0:00:01||
Episode 1|Iteration 145|reward:  410.0|last_reward_at:   92|Elapsed Time: 0:00:01||
Episode 1|Iteration 152|reward:  410.0|last_reward_at:   92|Elapsed Time: 0:00:01||
Episode 1|Iteration 160|reward:  410.0|last_reward_at:   92|Elapsed Time: 0:00:01||
Episode 1|Iteration 168|reward:  410.0|last_reward_at:   92|Elapsed Time: 0:00:01||
Episode 1|Iteration 175|reward:  410.0|last_reward_at:   92|Elapsed Time: 0:00:01||
Episode 1|Iteration 176|reward:  510.0|last_reward_at:   92|Elapsed Time: 0:00:01||
Episode 1|Iteration 176|reward:  510.0|last_reward_at:  176|Elapsed Time: 0:00:01||
Episode 1|Iteration 177|reward:  524.0|last_reward_at:  176|Elapsed Time: 0:00:01||
Episode 1|Iteration 177|reward:  524.0|last_reward_at:  177|Elapsed Time: 0:00:01||
Episode 1|Iteration 178|reward:  624.0|last_reward_at:  177|Elapsed Time: 0:00:01||
Episode 1|Iteration 178|reward:  624.0|last_reward_at:  178|Elapsed Time: 0:00:01||
Episode 1|Iteration 179|reward:  638.0|last_reward_at:  178|Elapsed Time: 0:00:01||
Episode 1|Iteration 179|reward:  638.0|last_reward_at:  179|Elapsed Time: 0:00:01||
Episode 1|Iteration 180|reward:  644.0|last_reward_at:  179|Elapsed Time: 0:00:01||
Episode 1|Iteration 180|reward:  644.0|last_reward_at:  180|Elapsed Time: 0:00:01||
Episode 1|Iteration 182|reward:  744.0|last_reward_at:  180|Elapsed Time: 0:00:01||
Episode 1|Iteration 182|reward:  744.0|last_reward_at:  182|Elapsed Time: 0:00:01||
Episode 1|Iteration 183|reward:  758.0|last_reward_at:  182|Elapsed Time: 0:00:01||
Episode 1|Iteration 183|reward:  758.0|last_reward_at:  183|Elapsed Time: 0:00:01||
Episode 1|Iteration 184|reward:  858.0|last_reward_at:  183|Elapsed Time: 0:00:01||
Episode 1|Iteration 184|reward:  858.0|last_reward_at:  184|Elapsed Time: 0:00:01||
Episode 1|Iteration 185|reward:  872.0|last_reward_at:  184|Elapsed Time: 0:00:01||
Episode 1|Iteration 185|reward:  872.0|last_reward_at:  185|Elapsed Time: 0:00:01||
Episode 1|Iteration 186|reward:  878.0|last_reward_at:  185|Elapsed Time: 0:00:01||
Episode 1|Iteration 186|reward:  878.0|last_reward_at:  186|Elapsed Time: 0:00:01||
Episode 1|Iteration 187|reward:  884.0|last_reward_at:  186|Elapsed Time: 0:00:01||
Episode 1|Iteration 187|reward:  884.0|last_reward_at:  187|Elapsed Time: 0:00:01||
Episode 1|Iteration 193|reward:  886.0|last_reward_at:  187|Elapsed Time: 0:00:01||
Episode 1|Iteration 193|reward:  886.0|last_reward_at:  193|Elapsed Time: 0:00:01||
Episode 1|Iteration 197|reward:  986.0|last_reward_at:  193|Elapsed Time: 0:00:01||
Episode 1|Iteration 197|reward:  986.0|last_reward_at:  197|Elapsed Time: 0:00:01||
Episode 1|Iteration 198|reward: 1000.0|last_reward_at:  197|Elapsed Time: 0:00:01||
Episode 1|Iteration 198|reward: 1000.0|last_reward_at:  198|Elapsed Time: 0:00:01||
Episode 1|Iteration 199|reward: 1100.0|last_reward_at:  198|Elapsed Time: 0:00:01||
Episode 1|Iteration 199|reward: 1100.0|last_reward_at:  199|Elapsed Time: 0:00:01||
Episode 1|Iteration 200|reward: 1114.0|last_reward_at:  199|Elapsed Time: 0:00:02||
Episode 1|Iteration 200|reward: 1114.0|last_reward_at:  200|Elapsed Time: 0:00:02||
Episode 1|Iteration 201|reward: 1120.0|last_reward_at:  200|Elapsed Time: 0:00:02||
Episode 1|Iteration 201|reward: 1120.0|last_reward_at:  201|Elapsed Time: 0:00:02||
Episode 1|Iteration 203|reward: 1220.0|last_reward_at:  201|Elapsed Time: 0:00:02||
Episode 1|Iteration 203|reward: 1220.0|last_reward_at:  203|Elapsed Time: 0:00:02||
Episode 1|Iteration 204|reward: 1234.0|last_reward_at:  203|Elapsed Time: 0:00:02||
Episode 1|Iteration 204|reward: 1234.0|last_reward_at:  204|Elapsed Time: 0:00:02||
Episode 1|Iteration 205|reward: 2234.0|last_reward_at:  204|Elapsed Time: 0:00:02||
Episode 1|Iteration 205|reward: 2234.0|last_reward_at:  205|Elapsed Time: 0:00:02||
Episode 1|Iteration 206|reward: 2240.0|last_reward_at:  205|Elapsed Time: 0:00:02||
Episode 1|Iteration 206|reward: 2240.0|last_reward_at:  206|Elapsed Time: 0:00:02||
Episode 1|Iteration 207|reward: 2246.0|last_reward_at:  206|Elapsed Time: 0:00:02||
Episode 1|Iteration 207|reward: 2246.0|last_reward_at:  207|Elapsed Time: 0:00:02||
Episode 1|Iteration 213|reward: 2246.0|last_reward_at:  207|Elapsed Time: 0:00:02||
Episode 1|Iteration 220|reward: 2252.0|last_reward_at:  207|Elapsed Time: 0:00:02||
Episode 1|Iteration 220|reward: 2252.0|last_reward_at:  220|Elapsed Time: 0:00:02||
Episode 1|Iteration 223|reward: 2258.0|last_reward_at:  220|Elapsed Time: 0:00:02||
Episode 1|Iteration 223|reward: 2258.0|last_reward_at:  223|Elapsed Time: 0:00:02||
Episode 1|Iteration 227|reward: 2264.0|last_reward_at:  223|Elapsed Time: 0:00:02||
Episode 1|Iteration 227|reward: 2264.0|last_reward_at:  227|Elapsed Time: 0:00:02||
Episode 1|Iteration 228|reward: 2266.0|last_reward_at:  227|Elapsed Time: 0:00:02||
Episode 1|Iteration 228|reward: 2266.0|last_reward_at:  228|Elapsed Time: 0:00:02||
Episode 1|Iteration 231|reward: 2272.0|last_reward_at:  228|Elapsed Time: 0:00:02||
Episode 1|Iteration 231|reward: 2272.0|last_reward_at:  231|Elapsed Time: 0:00:02||
Episode 1|Iteration 234|reward: 2274.0|last_reward_at:  231|Elapsed Time: 0:00:02||
Episode 1|Iteration 234|reward: 2274.0|last_reward_at:  234|Elapsed Time: 0:00:02||
Episode 1|Iteration 236|reward: 2280.0|last_reward_at:  234|Elapsed Time: 0:00:02||
Episode 1|Iteration 236|reward: 2280.0|last_reward_at:  236|Elapsed Time: 0:00:02||
Episode 1|Iteration 244|reward: 2280.0|last_reward_at:  236|Elapsed Time: 0:00:02||
Episode 1|Iteration 245|reward: 2280.0|last_reward_at:  236|Elapsed Time: 0:00:02||
Episode 1|Iteration 251|reward: 2280.0|last_reward_at:  236|Elapsed Time: 0:00:02||
Episode 1|Iteration 254|reward: 2286.0|last_reward_at:  236|Elapsed Time: 0:00:02||
Episode 1|Iteration 254|reward: 2286.0|last_reward_at:  254|Elapsed Time: 0:00:02||
Episode 1|Iteration 259|reward: 2286.0|last_reward_at:  254|Elapsed Time: 0:00:02||
Episode 1|Iteration 260|reward: 2288.0|last_reward_at:  254|Elapsed Time: 0:00:03||
Episode 1|Iteration 260|reward: 2288.0|last_reward_at:  260|Elapsed Time: 0:00:03||
Episode 1|Iteration 262|reward: 2294.0|last_reward_at:  260|Elapsed Time: 0:00:03||
Episode 1|Iteration 262|reward: 2294.0|last_reward_at:  262|Elapsed Time: 0:00:03||
Episode 1|Iteration 263|reward: 2296.0|last_reward_at:  262|Elapsed Time: 0:00:03||
Episode 1|Iteration 263|reward: 2296.0|last_reward_at:  263|Elapsed Time: 0:00:03||
Episode 1|Iteration 271|reward: 2296.0|last_reward_at:  263|Elapsed Time: 0:00:03||
Episode 1|Iteration 273|reward: 2298.0|last_reward_at:  263|Elapsed Time: 0:00:03||
Episode 1|Iteration 273|reward: 2298.0|last_reward_at:  273|Elapsed Time: 0:00:03||
Episode 1|Iteration 281|reward: 2298.0|last_reward_at:  273|Elapsed Time: 0:00:03||
Episode 1|Iteration 289|reward: 2298.0|last_reward_at:  273|Elapsed Time: 0:00:03||
Episode 1|Iteration 296|reward: 2298.0|last_reward_at:  273|Elapsed Time: 0:00:03||
Episode 1|Iteration 304|reward: 2298.0|last_reward_at:  273|Elapsed Time: 0:00:03||
Episode 1|Iteration 311|reward: 2298.0|last_reward_at:  273|Elapsed Time: 0:00:03||
Episode 1|Iteration 318|reward: 2298.0|last_reward_at:  273|Elapsed Time: 0:00:03||
Episode 1|Iteration 326|reward: 2298.0|last_reward_at:  273|Elapsed Time: 0:00:03||
Episode 1|Iteration 334|reward: 2298.0|last_reward_at:  273|Elapsed Time: 0:00:04||
Episode 1|Iteration 342|reward: 2298.0|last_reward_at:  273|Elapsed Time: 0:00:04||
Episode 1|Iteration 349|reward: 2298.0|last_reward_at:  273|Elapsed Time: 0:00:04||
Episode 1|Iteration 356|reward: 2298.0|last_reward_at:  273|Elapsed Time: 0:00:04||
Episode 1|Iteration 365|reward: 2298.0|last_reward_at:  273|Elapsed Time: 0:00:04||
Episode 1|Iteration 373|reward: 2298.0|last_reward_at:  273|Elapsed Time: 0:00:04||
Episode 1|Iteration 380|reward: 2298.0|last_reward_at:  273|Elapsed Time: 0:00:04||
Episode 1|Iteration 387|reward: 2298.0|last_reward_at:  273|Elapsed Time: 0:00:04||
Episode 1|Iteration 395|reward: 2298.0|last_reward_at:  273|Elapsed Time: 0:00:04||
Episode 1|Iteration 403|reward: 2298.0|last_reward_at:  273|Elapsed Time: 0:00:04||
Episode 1|Iteration 411|reward: 2298.0|last_reward_at:  273|Elapsed Time: 0:00:05||
Episode 1|Iteration 418|reward: 2298.0|last_reward_at:  273|Elapsed Time: 0:00:05||
Episode 1|Iteration 426|reward: 2298.0|last_reward_at:  273|Elapsed Time: 0:00:05||
Episode 1|Iteration 433|reward: 2298.0|last_reward_at:  273|Elapsed Time: 0:00:05||
Episode 1|Iteration 438|reward: 2298.0|last_reward_at:  273|Elapsed Time: 0:00:05||
Episode 1|Iteration 446|reward: 2298.0|last_reward_at:  273|Elapsed Time: 0:00:05||
Episode 1|Iteration 455|reward: 2298.0|last_reward_at:  273|Elapsed Time: 0:00:05||
Episode 1|Iteration 463|reward: 2298.0|last_reward_at:  273|Elapsed Time: 0:00:05||
Episode 1|Iteration 471|reward: 2298.0|last_reward_at:  273|Elapsed Time: 0:00:05||
Episode 1|Iteration 479|reward: 2298.0|last_reward_at:  273|Elapsed Time: 0:00:05||
Episode 1|Iteration 487|reward: 2298.0|last_reward_at:  273|Elapsed Time: 0:00:06||
Episode 1|Iteration 494|reward: 2298.0|last_reward_at:  273|Elapsed Time: 0:00:06||
Episode 1|Iteration 502|reward: 2298.0|last_reward_at:  273|Elapsed Time: 0:00:06||
Episode 1|Iteration 509|reward: 2298.0|last_reward_at:  273|Elapsed Time: 0:00:06||
Episode 1|Iteration 517|reward: 2298.0|last_reward_at:  273|Elapsed Time: 0:00:06||
Episode 1|Iteration 525|reward: 2298.0|last_reward_at:  273|Elapsed Time: 0:00:06||
Episode 1|Iteration 532|reward: 2298.0|last_reward_at:  273|Elapsed Time: 0:00:06||
Episode 1|Iteration 540|reward: 2298.0|last_reward_at:  273|Elapsed Time: 0:00:06||
Episode 1|Iteration 544|reward: 2298.0|last_reward_at:  273|Elapsed Time: 0:00:06||
Episode 1|Iteration 548|reward: 2298.0|last_reward_at:  273|Elapsed Time: 0:00:06||
Episode 1|Iteration 555|reward: 2298.0|last_reward_at:  273|Elapsed Time: 0:00:06||
Episode 1|Iteration 563|reward: 2298.0|last_reward_at:  273|Elapsed Time: 0:00:07||
Episode 1|Iteration 570|reward: 2298.0|last_reward_at:  273|Elapsed Time: 0:00:07||
Episode 1|Iteration 575|reward: 2298.0|last_reward_at:  273|Elapsed Time: 0:00:07||
Episode 1|Iteration 579|reward: 2298.0|last_reward_at:  273|Elapsed Time: 0:00:07||
Episode 1|Iteration 585|reward: 2298.0|last_reward_at:  273|Elapsed Time: 0:00:07||
Episode 1|Iteration 593|reward: 2298.0|last_reward_at:  273|Elapsed Time: 0:00:07||
Episode 1|Iteration 600|reward: 2298.0|last_reward_at:  273|Elapsed Time: 0:00:07||
Episode 1|Iteration 600|reward: 2298.0|last_reward_at:  273|Elapsed Time: 0:00:07||

  Episode 1 stopped at t=600
  Breakdown [Reward/NoReward (Success rate)]
    explore-local: 0/1 (0.00)
    explore-remote: 1/2 (0.33)
    explore-connect: 0/4 (0.00)
    exploit-local: 21/139 (0.13)
    exploit-remote: 19/395 (0.05)
    exploit-connect: 11/7 (0.61)
  exploit deflected to exploration: 8

,status,properties,local_attacks,remote_attacks
id,,,,
start,owned,[],[ScanExplorerRecentFiles],[]
1_LinuxNode,owned,"[MySql, Ubuntu, nginx/1.10.3]","[SudoAttempt, ScanExplorerRecentFiles, ScanBas...","[ProbeWindows, ProbeLinux]"
2_WindowsNode,owned,"[Windows, Win10, Win10Patched]","[ScanExplorerRecentFiles, SudoAttempt, CrackKe...","[ProbeWindows, ProbeLinux]"
3_LinuxNode,owned,"[MySql, Ubuntu, nginx/1.10.3]","[SudoAttempt, ScanExplorerRecentFiles, ScanBas...","[ProbeWindows, ProbeLinux]"
4_WindowsNode,owned,"[Windows, Win10, Win10Patched]","[ScanExplorerRecentFiles, SudoAttempt, CrackKe...","[ProbeWindows, ProbeLinux]"
5_LinuxNode,owned,"[MySql, Ubuntu, nginx/1.10.3]","[SudoAttempt, ScanExplorerRecentFiles, ScanBas...","[ProbeWindows, ProbeLinux]"
6_WindowsNode,owned,"[Windows, Win10, Win10Patched]","[ScanExplorerRecentFiles, SudoAttempt, CrackKe...","[ProbeWindows, ProbeLinux]"
7_LinuxNode,owned,"[MySql, Ubuntu, nginx/1.10.3]","[SudoAttempt, ScanExplorerRecentFiles, ScanBas...","[ProbeWindows, ProbeLinux]"
8_WindowsNode,owned,"[Windows, Win10, Win10Patched]","[ScanExplorerRecentFiles, SudoAttempt, CrackKe...","[ProbeWindows, ProbeLinux]"
9_LinuxNode,owned,"[MySql, Ubuntu, nginx/1.10.3]","[SudoAttempt, ScanExplorerRecentFiles, ScanBas...","[ProbeWindows, ProbeLinux]"
10_WindowsNode,owned,"[Windows, Win10, Win10Patched]","[ScanExplorerRecentFiles, SudoAttempt, CrackKe...","[ProbeWindows, ProbeLinux]"
11_LinuxNode,owned,"[MySql, Ubuntu, nginx/1.10.3, FLAG:Linux]",[],[]

  ## Episode: 2/10 'Exploiting DQL' ϵ=0.0000, γ=0.15, lr=0.01, replaymemory=10000,
batch=256, target_update=5

Episode 2|Iteration 0|reward: ------|last_reward_at: ----|Elapsed Time: 0:00:00||
Episode 2|Iteration 1|reward:   14.0|last_reward_at: ----|Elapsed Time: 0:00:00||
Episode 2|Iteration 1|reward:   14.0|last_reward_at:    1|Elapsed Time: 0:00:00||
Episode 2|Iteration 2|reward:   16.0|last_reward_at:    1|Elapsed Time: 0:00:00||
Episode 2|Iteration 2|reward:   16.0|last_reward_at:    2|Elapsed Time: 0:00:00||
Episode 2|Iteration 15|reward:   16.0|last_reward_at:    2|Elapsed Time: 0:00:00||
Episode 2|Iteration 16|reward:   20.0|last_reward_at:    2|Elapsed Time: 0:00:00||
Episode 2|Iteration 16|reward:   20.0|last_reward_at:   16|Elapsed Time: 0:00:00||
Episode 2|Iteration 31|reward:   20.0|last_reward_at:   16|Elapsed Time: 0:00:00||
Episode 2|Iteration 38|reward:   20.0|last_reward_at:   16|Elapsed Time: 0:00:00||
Episode 2|Iteration 43|reward:  120.0|last_reward_at:   16|Elapsed Time: 0:00:00||
Episode 2|Iteration 43|reward:  120.0|last_reward_at:   43|Elapsed Time: 0:00:00||
Episode 2|Iteration 44|reward:  134.0|last_reward_at:   43|Elapsed Time: 0:00:00||
Episode 2|Iteration 44|reward:  134.0|last_reward_at:   44|Elapsed Time: 0:00:00||
Episode 2|Iteration 45|reward:  140.0|last_reward_at:   44|Elapsed Time: 0:00:00||
Episode 2|Iteration 45|reward:  140.0|last_reward_at:   45|Elapsed Time: 0:00:00||
Episode 2|Iteration 46|reward:  148.0|last_reward_at:   45|Elapsed Time: 0:00:00||
Episode 2|Iteration 46|reward:  148.0|last_reward_at:   46|Elapsed Time: 0:00:00||
Episode 2|Iteration 48|reward:  154.0|last_reward_at:   46|Elapsed Time: 0:00:00||
Episode 2|Iteration 48|reward:  154.0|last_reward_at:   48|Elapsed Time: 0:00:00||
Episode 2|Iteration 61|reward:  154.0|last_reward_at:   48|Elapsed Time: 0:00:00||
Episode 2|Iteration 69|reward:  154.0|last_reward_at:   48|Elapsed Time: 0:00:00||
Episode 2|Iteration 72|reward:  254.0|last_reward_at:   48|Elapsed Time: 0:00:00||
Episode 2|Iteration 72|reward:  254.0|last_reward_at:   72|Elapsed Time: 0:00:00||
Episode 2|Iteration 73|reward:  268.0|last_reward_at:   72|Elapsed Time: 0:00:00||
Episode 2|Iteration 73|reward:  268.0|last_reward_at:   73|Elapsed Time: 0:00:00||
Episode 2|Iteration 74|reward:  368.0|last_reward_at:   73|Elapsed Time: 0:00:00||
Episode 2|Iteration 74|reward:  368.0|last_reward_at:   74|Elapsed Time: 0:00:00||
Episode 2|Iteration 75|reward:  382.0|last_reward_at:   74|Elapsed Time: 0:00:00||
Episode 2|Iteration 75|reward:  382.0|last_reward_at:   75|Elapsed Time: 0:00:00||
Episode 2|Iteration 76|reward:  388.0|last_reward_at:   75|Elapsed Time: 0:00:00||
Episode 2|Iteration 76|reward:  388.0|last_reward_at:   76|Elapsed Time: 0:00:00||
Episode 2|Iteration 80|reward:  394.0|last_reward_at:   76|Elapsed Time: 0:00:00||
Episode 2|Iteration 80|reward:  394.0|last_reward_at:   80|Elapsed Time: 0:00:00||
Episode 2|Iteration 86|reward:  402.0|last_reward_at:   80|Elapsed Time: 0:00:00||
Episode 2|Iteration 86|reward:  402.0|last_reward_at:   86|Elapsed Time: 0:00:00||
Episode 2|Iteration 99|reward:  402.0|last_reward_at:   86|Elapsed Time: 0:00:00||
Episode 2|Iteration 99|reward:  408.0|last_reward_at:   86|Elapsed Time: 0:00:00||
Episode 2|Iteration 99|reward:  408.0|last_reward_at:   99|Elapsed Time: 0:00:00||
Episode 2|Iteration 102|reward:  508.0|last_reward_at:   99|Elapsed Time: 0:00:00||
Episode 2|Iteration 102|reward:  508.0|last_reward_at:  102|Elapsed Time: 0:00:00||
Episode 2|Iteration 103|reward:  522.0|last_reward_at:  102|Elapsed Time: 0:00:00||
Episode 2|Iteration 103|reward:  522.0|last_reward_at:  103|Elapsed Time: 0:00:00||
Episode 2|Iteration 104|reward:  622.0|last_reward_at:  103|Elapsed Time: 0:00:00||
Episode 2|Iteration 104|reward:  622.0|last_reward_at:  104|Elapsed Time: 0:00:00||
Episode 2|Iteration 105|reward:  636.0|last_reward_at:  104|Elapsed Time: 0:00:00||
Episode 2|Iteration 105|reward:  636.0|last_reward_at:  105|Elapsed Time: 0:00:00||
Episode 2|Iteration 106|reward:  642.0|last_reward_at:  105|Elapsed Time: 0:00:00||
Episode 2|Iteration 106|reward:  642.0|last_reward_at:  106|Elapsed Time: 0:00:00||
Episode 2|Iteration 107|reward:  742.0|last_reward_at:  106|Elapsed Time: 0:00:00||
Episode 2|Iteration 107|reward:  742.0|last_reward_at:  107|Elapsed Time: 0:00:00||
Episode 2|Iteration 108|reward:  756.0|last_reward_at:  107|Elapsed Time: 0:00:00||
Episode 2|Iteration 108|reward:  756.0|last_reward_at:  108|Elapsed Time: 0:00:00||
Episode 2|Iteration 109|reward:  856.0|last_reward_at:  108|Elapsed Time: 0:00:00||
Episode 2|Iteration 109|reward:  856.0|last_reward_at:  109|Elapsed Time: 0:00:00||
Episode 2|Iteration 110|reward:  870.0|last_reward_at:  109|Elapsed Time: 0:00:01||
Episode 2|Iteration 110|reward:  870.0|last_reward_at:  110|Elapsed Time: 0:00:01||
Episode 2|Iteration 111|reward:  876.0|last_reward_at:  110|Elapsed Time: 0:00:01||
Episode 2|Iteration 111|reward:  876.0|last_reward_at:  111|Elapsed Time: 0:00:01||
Episode 2|Iteration 112|reward:  878.0|last_reward_at:  111|Elapsed Time: 0:00:01||
Episode 2|Iteration 112|reward:  878.0|last_reward_at:  112|Elapsed Time: 0:00:01||
Episode 2|Iteration 113|reward:  880.0|last_reward_at:  112|Elapsed Time: 0:00:01||
Episode 2|Iteration 113|reward:  880.0|last_reward_at:  113|Elapsed Time: 0:00:01||
Episode 2|Iteration 114|reward:  980.0|last_reward_at:  113|Elapsed Time: 0:00:01||
Episode 2|Iteration 114|reward:  980.0|last_reward_at:  114|Elapsed Time: 0:00:01||
Episode 2|Iteration 115|reward:  994.0|last_reward_at:  114|Elapsed Time: 0:00:01||
Episode 2|Iteration 115|reward:  994.0|last_reward_at:  115|Elapsed Time: 0:00:01||
Episode 2|Iteration 116|reward: 1094.0|last_reward_at:  115|Elapsed Time: 0:00:01||
Episode 2|Iteration 116|reward: 1094.0|last_reward_at:  116|Elapsed Time: 0:00:01||
Episode 2|Iteration 117|reward: 1108.0|last_reward_at:  116|Elapsed Time: 0:00:01||
Episode 2|Iteration 117|reward: 1108.0|last_reward_at:  117|Elapsed Time: 0:00:01||
Episode 2|Iteration 118|reward: 1114.0|last_reward_at:  117|Elapsed Time: 0:00:01||
Episode 2|Iteration 118|reward: 1114.0|last_reward_at:  118|Elapsed Time: 0:00:01||
Episode 2|Iteration 121|reward: 1214.0|last_reward_at:  118|Elapsed Time: 0:00:01||
Episode 2|Iteration 121|reward: 1214.0|last_reward_at:  121|Elapsed Time: 0:00:01||
Episode 2|Iteration 122|reward: 1228.0|last_reward_at:  121|Elapsed Time: 0:00:01||
Episode 2|Iteration 122|reward: 1228.0|last_reward_at:  122|Elapsed Time: 0:00:01||
Episode 2|Iteration 123|reward: 2228.0|last_reward_at:  122|Elapsed Time: 0:00:01||
Episode 2|Iteration 123|reward: 2228.0|last_reward_at:  123|Elapsed Time: 0:00:01||
Episode 2|Iteration 126|reward: 2234.0|last_reward_at:  123|Elapsed Time: 0:00:01||
Episode 2|Iteration 126|reward: 2234.0|last_reward_at:  126|Elapsed Time: 0:00:01||
Episode 2|Iteration 127|reward: 2240.0|last_reward_at:  126|Elapsed Time: 0:00:01||
Episode 2|Iteration 127|reward: 2240.0|last_reward_at:  127|Elapsed Time: 0:00:01||
Episode 2|Iteration 132|reward: 2246.0|last_reward_at:  127|Elapsed Time: 0:00:01||
Episode 2|Iteration 132|reward: 2246.0|last_reward_at:  132|Elapsed Time: 0:00:01||
Episode 2|Iteration 133|reward: 2252.0|last_reward_at:  132|Elapsed Time: 0:00:01||
Episode 2|Iteration 133|reward: 2252.0|last_reward_at:  133|Elapsed Time: 0:00:01||
Episode 2|Iteration 135|reward: 2258.0|last_reward_at:  133|Elapsed Time: 0:00:01||
Episode 2|Iteration 135|reward: 2258.0|last_reward_at:  135|Elapsed Time: 0:00:01||
Episode 2|Iteration 137|reward: 2260.0|last_reward_at:  135|Elapsed Time: 0:00:01||
Episode 2|Iteration 137|reward: 2260.0|last_reward_at:  137|Elapsed Time: 0:00:01||
Episode 2|Iteration 138|reward: 2262.0|last_reward_at:  137|Elapsed Time: 0:00:01||
Episode 2|Iteration 138|reward: 2262.0|last_reward_at:  138|Elapsed Time: 0:00:01||
Episode 2|Iteration 140|reward: 2268.0|last_reward_at:  138|Elapsed Time: 0:00:01||
Episode 2|Iteration 140|reward: 2268.0|last_reward_at:  140|Elapsed Time: 0:00:01||
Episode 2|Iteration 143|reward: 2274.0|last_reward_at:  140|Elapsed Time: 0:00:01||
Episode 2|Iteration 143|reward: 2274.0|last_reward_at:  143|Elapsed Time: 0:00:01||
Episode 2|Iteration 149|reward: 2276.0|last_reward_at:  143|Elapsed Time: 0:00:01||
Episode 2|Iteration 149|reward: 2276.0|last_reward_at:  149|Elapsed Time: 0:00:01||
Episode 2|Iteration 155|reward: 2282.0|last_reward_at:  149|Elapsed Time: 0:00:01||
Episode 2|Iteration 155|reward: 2282.0|last_reward_at:  155|Elapsed Time: 0:00:01||
Episode 2|Iteration 156|reward: 2284.0|last_reward_at:  155|Elapsed Time: 0:00:01||
Episode 2|Iteration 156|reward: 2284.0|last_reward_at:  156|Elapsed Time: 0:00:01||
Episode 2|Iteration 160|reward: 2284.0|last_reward_at:  156|Elapsed Time: 0:00:01||
Episode 2|Iteration 161|reward: 2286.0|last_reward_at:  156|Elapsed Time: 0:00:01||
Episode 2|Iteration 161|reward: 2286.0|last_reward_at:  161|Elapsed Time: 0:00:01||
Episode 2|Iteration 168|reward: 2286.0|last_reward_at:  161|Elapsed Time: 0:00:01||
Episode 2|Iteration 170|reward: 2288.0|last_reward_at:  161|Elapsed Time: 0:00:01||
Episode 2|Iteration 170|reward: 2288.0|last_reward_at:  170|Elapsed Time: 0:00:01||
Episode 2|Iteration 173|reward: 2294.0|last_reward_at:  170|Elapsed Time: 0:00:01||
Episode 2|Iteration 173|reward: 2294.0|last_reward_at:  173|Elapsed Time: 0:00:01||
Episode 2|Iteration 175|reward: 2300.0|last_reward_at:  173|Elapsed Time: 0:00:01||
Episode 2|Iteration 175|reward: 2300.0|last_reward_at:  175|Elapsed Time: 0:00:01||
Episode 2|Iteration 182|reward: 2300.0|last_reward_at:  175|Elapsed Time: 0:00:02||
Episode 2|Iteration 190|reward: 2300.0|last_reward_at:  175|Elapsed Time: 0:00:02||
Episode 2|Iteration 197|reward: 2300.0|last_reward_at:  175|Elapsed Time: 0:00:02||
Episode 2|Iteration 205|reward: 2300.0|last_reward_at:  175|Elapsed Time: 0:00:02||
Episode 2|Iteration 213|reward: 2300.0|last_reward_at:  175|Elapsed Time: 0:00:02||
Episode 2|Iteration 218|reward: 2300.0|last_reward_at:  175|Elapsed Time: 0:00:02||
Episode 2|Iteration 226|reward: 2300.0|last_reward_at:  175|Elapsed Time: 0:00:02||
Episode 2|Iteration 234|reward: 2300.0|last_reward_at:  175|Elapsed Time: 0:00:02||
Episode 2|Iteration 236|reward: 2300.0|last_reward_at:  175|Elapsed Time: 0:00:02||
Episode 2|Iteration 243|reward: 2300.0|last_reward_at:  175|Elapsed Time: 0:00:03||
Episode 2|Iteration 248|reward: 2300.0|last_reward_at:  175|Elapsed Time: 0:00:03||
Episode 2|Iteration 250|reward: 2300.0|last_reward_at:  175|Elapsed Time: 0:00:03||
Episode 2|Iteration 258|reward: 2300.0|last_reward_at:  175|Elapsed Time: 0:00:03||
Episode 2|Iteration 266|reward: 2300.0|last_reward_at:  175|Elapsed Time: 0:00:03||
Episode 2|Iteration 270|reward: 2300.0|last_reward_at:  175|Elapsed Time: 0:00:03||
Episode 2|Iteration 278|reward: 2300.0|last_reward_at:  175|Elapsed Time: 0:00:03||
Episode 2|Iteration 286|reward: 2300.0|last_reward_at:  175|Elapsed Time: 0:00:03||
Episode 2|Iteration 294|reward: 2300.0|last_reward_at:  175|Elapsed Time: 0:00:04||
Episode 2|Iteration 302|reward: 2300.0|last_reward_at:  175|Elapsed Time: 0:00:04||
Episode 2|Iteration 310|reward: 2300.0|last_reward_at:  175|Elapsed Time: 0:00:04||
Episode 2|Iteration 318|reward: 2300.0|last_reward_at:  175|Elapsed Time: 0:00:04||
Episode 2|Iteration 326|reward: 2300.0|last_reward_at:  175|Elapsed Time: 0:00:04||
Episode 2|Iteration 332|reward: 2300.0|last_reward_at:  175|Elapsed Time: 0:00:04||
Episode 2|Iteration 334|reward: 2300.0|last_reward_at:  175|Elapsed Time: 0:00:04||
Episode 2|Iteration 342|reward: 2300.0|last_reward_at:  175|Elapsed Time: 0:00:04||
Episode 2|Iteration 349|reward: 2300.0|last_reward_at:  175|Elapsed Time: 0:00:04||
Episode 2|Iteration 357|reward: 2300.0|last_reward_at:  175|Elapsed Time: 0:00:05||
Episode 2|Iteration 358|reward: 2300.0|last_reward_at:  175|Elapsed Time: 0:00:05||
Episode 2|Iteration 362|reward: 2300.0|last_reward_at:  175|Elapsed Time: 0:00:05||
Episode 2|Iteration 370|reward: 2300.0|last_reward_at:  175|Elapsed Time: 0:00:05||
Episode 2|Iteration 378|reward: 2300.0|last_reward_at:  175|Elapsed Time: 0:00:05||
Episode 2|Iteration 385|reward: 2300.0|last_reward_at:  175|Elapsed Time: 0:00:05||
Episode 2|Iteration 393|reward: 2300.0|last_reward_at:  175|Elapsed Time: 0:00:05||
Episode 2|Iteration 401|reward: 2300.0|last_reward_at:  175|Elapsed Time: 0:00:05||
Episode 2|Iteration 409|reward: 2300.0|last_reward_at:  175|Elapsed Time: 0:00:05||
Episode 2|Iteration 417|reward: 2300.0|last_reward_at:  175|Elapsed Time: 0:00:06||
Episode 2|Iteration 425|reward: 2300.0|last_reward_at:  175|Elapsed Time: 0:00:06||
Episode 2|Iteration 433|reward: 2300.0|last_reward_at:  175|Elapsed Time: 0:00:06||
Episode 2|Iteration 438|reward: 2300.0|last_reward_at:  175|Elapsed Time: 0:00:06||
Episode 2|Iteration 446|reward: 2300.0|last_reward_at:  175|Elapsed Time: 0:00:06||
Episode 2|Iteration 453|reward: 2300.0|last_reward_at:  175|Elapsed Time: 0:00:06||
Episode 2|Iteration 459|reward: 2300.0|last_reward_at:  175|Elapsed Time: 0:00:06||
Episode 2|Iteration 464|reward: 2300.0|last_reward_at:  175|Elapsed Time: 0:00:06||
Episode 2|Iteration 470|reward: 2300.0|last_reward_at:  175|Elapsed Time: 0:00:06||
Episode 2|Iteration 478|reward: 2300.0|last_reward_at:  175|Elapsed Time: 0:00:07||
Episode 2|Iteration 487|reward: 2300.0|last_reward_at:  175|Elapsed Time: 0:00:07||
Episode 2|Iteration 494|reward: 2300.0|last_reward_at:  175|Elapsed Time: 0:00:07||
Episode 2|Iteration 502|reward: 2300.0|last_reward_at:  175|Elapsed Time: 0:00:07||
Episode 2|Iteration 507|reward: 2300.0|last_reward_at:  175|Elapsed Time: 0:00:07||
Episode 2|Iteration 516|reward: 2300.0|last_reward_at:  175|Elapsed Time: 0:00:07||
Episode 2|Iteration 523|reward: 2300.0|last_reward_at:  175|Elapsed Time: 0:00:07||
Episode 2|Iteration 531|reward: 2300.0|last_reward_at:  175|Elapsed Time: 0:00:07||
Episode 2|Iteration 539|reward: 2300.0|last_reward_at:  175|Elapsed Time: 0:00:07||
Episode 2|Iteration 543|reward: 2300.0|last_reward_at:  175|Elapsed Time: 0:00:08||
Episode 2|Iteration 545|reward: 2300.0|last_reward_at:  175|Elapsed Time: 0:00:08||
Episode 2|Iteration 553|reward: 2300.0|last_reward_at:  175|Elapsed Time: 0:00:08||
Episode 2|Iteration 561|reward: 2300.0|last_reward_at:  175|Elapsed Time: 0:00:08||
Episode 2|Iteration 567|reward: 2300.0|last_reward_at:  175|Elapsed Time: 0:00:08||
Episode 2|Iteration 575|reward: 2300.0|last_reward_at:  175|Elapsed Time: 0:00:08||
Episode 2|Iteration 578|reward: 2300.0|last_reward_at:  175|Elapsed Time: 0:00:08||
Episode 2|Iteration 580|reward: 2300.0|last_reward_at:  175|Elapsed Time: 0:00:08||
Episode 2|Iteration 582|reward: 2300.0|last_reward_at:  175|Elapsed Time: 0:00:09||
Episode 2|Iteration 590|reward: 2300.0|last_reward_at:  175|Elapsed Time: 0:00:09||
Episode 2|Iteration 598|reward: 2300.0|last_reward_at:  175|Elapsed Time: 0:00:09||
Episode 2|Iteration 600|reward: 2300.0|last_reward_at:  175|Elapsed Time: 0:00:09||

  Episode 2 stopped at t=600
  Breakdown [Reward/NoReward (Success rate)]
    explore-local: 0/2 (0.00)
    explore-remote: 0/9 (0.00)
    explore-connect: 0/13 (0.00)
    exploit-local: 21/131 (0.14)
    exploit-remote: 20/384 (0.05)
    exploit-connect: 11/9 (0.55)
  exploit deflected to exploration: 24

,status,properties,local_attacks,remote_attacks
id,,,,
start,owned,[],[ScanExplorerRecentFiles],[]
1_LinuxNode,owned,"[MySql, Ubuntu, nginx/1.10.3]","[SudoAttempt, ScanExplorerRecentFiles, ScanBas...","[ProbeWindows, ProbeLinux]"
2_WindowsNode,owned,"[Windows, Win10, Win10Patched]","[ScanExplorerRecentFiles, SudoAttempt, CrackKe...","[ProbeWindows, ProbeLinux]"
3_LinuxNode,owned,"[MySql, Ubuntu, nginx/1.10.3]","[SudoAttempt, ScanExplorerRecentFiles, ScanBas...","[ProbeWindows, ProbeLinux]"
4_WindowsNode,owned,"[Windows, Win10, Win10Patched]","[ScanExplorerRecentFiles, SudoAttempt, CrackKe...","[ProbeWindows, ProbeLinux]"
5_LinuxNode,owned,"[MySql, Ubuntu, nginx/1.10.3]","[SudoAttempt, ScanExplorerRecentFiles, ScanBas...","[ProbeWindows, ProbeLinux]"
6_WindowsNode,owned,"[Windows, Win10, Win10Patched]","[ScanExplorerRecentFiles, SudoAttempt, CrackKe...","[ProbeWindows, ProbeLinux]"
7_LinuxNode,owned,"[MySql, Ubuntu, nginx/1.10.3]","[SudoAttempt, ScanExplorerRecentFiles, ScanBas...","[ProbeWindows, ProbeLinux]"
8_WindowsNode,owned,"[Windows, Win10, Win10Patched]","[ScanExplorerRecentFiles, SudoAttempt, CrackKe...","[ProbeWindows, ProbeLinux]"
9_LinuxNode,owned,"[MySql, Ubuntu, nginx/1.10.3]","[SudoAttempt, ScanExplorerRecentFiles, ScanBas...","[ProbeWindows, ProbeLinux]"
10_WindowsNode,owned,"[Windows, Win10, Win10Patched]","[ScanExplorerRecentFiles, SudoAttempt, CrackKe...","[ProbeWindows, ProbeLinux]"
11_LinuxNode,owned,"[MySql, Ubuntu, nginx/1.10.3, FLAG:Linux]",[],[]

  ## Episode: 3/10 'Exploiting DQL' ϵ=0.0000, γ=0.15, lr=0.01, replaymemory=10000,
batch=256, target_update=5

Episode 3|Iteration 0|reward: ------|last_reward_at: ----|Elapsed Time: 0:00:00||
Episode 3|Iteration 1|reward:   14.0|last_reward_at: ----|Elapsed Time: 0:00:00||
Episode 3|Iteration 1|reward:   14.0|last_reward_at:    1|Elapsed Time: 0:00:00||
Episode 3|Iteration 2|reward:   16.0|last_reward_at:    1|Elapsed Time: 0:00:00||
Episode 3|Iteration 2|reward:   16.0|last_reward_at:    2|Elapsed Time: 0:00:00||
Episode 3|Iteration 13|reward:   20.0|last_reward_at:    2|Elapsed Time: 0:00:00||
Episode 3|Iteration 13|reward:   20.0|last_reward_at:   13|Elapsed Time: 0:00:00||
Episode 3|Iteration 23|reward:   20.0|last_reward_at:   13|Elapsed Time: 0:00:00||
Episode 3|Iteration 31|reward:   20.0|last_reward_at:   13|Elapsed Time: 0:00:00||
Episode 3|Iteration 38|reward:   20.0|last_reward_at:   13|Elapsed Time: 0:00:00||
Episode 3|Iteration 46|reward:   20.0|last_reward_at:   13|Elapsed Time: 0:00:00||
Episode 3|Iteration 54|reward:   20.0|last_reward_at:   13|Elapsed Time: 0:00:00||
Episode 3|Iteration 61|reward:   20.0|last_reward_at:   13|Elapsed Time: 0:00:00||
Episode 3|Iteration 69|reward:   20.0|last_reward_at:   13|Elapsed Time: 0:00:00||
Episode 3|Iteration 76|reward:   20.0|last_reward_at:   13|Elapsed Time: 0:00:00||
Episode 3|Iteration 84|reward:   20.0|last_reward_at:   13|Elapsed Time: 0:00:00||
Episode 3|Iteration 92|reward:   20.0|last_reward_at:   13|Elapsed Time: 0:00:00||
Episode 3|Iteration 99|reward:   20.0|last_reward_at:   13|Elapsed Time: 0:00:00||
Episode 3|Iteration 107|reward:   20.0|last_reward_at:   13|Elapsed Time: 0:00:00||
Episode 3|Iteration 114|reward:   20.0|last_reward_at:   13|Elapsed Time: 0:00:00||
Episode 3|Iteration 122|reward:   20.0|last_reward_at:   13|Elapsed Time: 0:00:01||
Episode 3|Iteration 130|reward:   20.0|last_reward_at:   13|Elapsed Time: 0:00:01||
Episode 3|Iteration 137|reward:   20.0|last_reward_at:   13|Elapsed Time: 0:00:01||
Episode 3|Iteration 145|reward:   20.0|last_reward_at:   13|Elapsed Time: 0:00:01||
Episode 3|Iteration 152|reward:   20.0|last_reward_at:   13|Elapsed Time: 0:00:01||
Episode 3|Iteration 160|reward:   20.0|last_reward_at:   13|Elapsed Time: 0:00:01||
Episode 3|Iteration 166|reward:  120.0|last_reward_at:   13|Elapsed Time: 0:00:01||
Episode 3|Iteration 166|reward:  120.0|last_reward_at:  166|Elapsed Time: 0:00:01||
Episode 3|Iteration 167|reward:  134.0|last_reward_at:  166|Elapsed Time: 0:00:01||
Episode 3|Iteration 167|reward:  134.0|last_reward_at:  167|Elapsed Time: 0:00:01||
Episode 3|Iteration 168|reward:  140.0|last_reward_at:  167|Elapsed Time: 0:00:01||
Episode 3|Iteration 168|reward:  140.0|last_reward_at:  168|Elapsed Time: 0:00:01||
Episode 3|Iteration 172|reward:  146.0|last_reward_at:  168|Elapsed Time: 0:00:01||
Episode 3|Iteration 172|reward:  146.0|last_reward_at:  172|Elapsed Time: 0:00:01||
Episode 3|Iteration 179|reward:  154.0|last_reward_at:  172|Elapsed Time: 0:00:01||
Episode 3|Iteration 179|reward:  154.0|last_reward_at:  179|Elapsed Time: 0:00:01||
Episode 3|Iteration 180|reward:  254.0|last_reward_at:  179|Elapsed Time: 0:00:01||
Episode 3|Iteration 180|reward:  254.0|last_reward_at:  180|Elapsed Time: 0:00:01||
Episode 3|Iteration 181|reward:  268.0|last_reward_at:  180|Elapsed Time: 0:00:01||
Episode 3|Iteration 181|reward:  268.0|last_reward_at:  181|Elapsed Time: 0:00:01||
Episode 3|Iteration 182|reward:  368.0|last_reward_at:  181|Elapsed Time: 0:00:01||
Episode 3|Iteration 182|reward:  368.0|last_reward_at:  182|Elapsed Time: 0:00:01||
Episode 3|Iteration 183|reward:  382.0|last_reward_at:  182|Elapsed Time: 0:00:01||
Episode 3|Iteration 183|reward:  382.0|last_reward_at:  183|Elapsed Time: 0:00:01||
Episode 3|Iteration 184|reward:  388.0|last_reward_at:  183|Elapsed Time: 0:00:01||
Episode 3|Iteration 184|reward:  388.0|last_reward_at:  184|Elapsed Time: 0:00:01||
Episode 3|Iteration 186|reward:  390.0|last_reward_at:  184|Elapsed Time: 0:00:01||
Episode 3|Iteration 186|reward:  390.0|last_reward_at:  186|Elapsed Time: 0:00:01||
Episode 3|Iteration 189|reward:  396.0|last_reward_at:  186|Elapsed Time: 0:00:01||
Episode 3|Iteration 189|reward:  396.0|last_reward_at:  189|Elapsed Time: 0:00:01||
Episode 3|Iteration 194|reward:  398.0|last_reward_at:  189|Elapsed Time: 0:00:01||
Episode 3|Iteration 194|reward:  398.0|last_reward_at:  194|Elapsed Time: 0:00:01||
Episode 3|Iteration 201|reward:  404.0|last_reward_at:  194|Elapsed Time: 0:00:01||
Episode 3|Iteration 201|reward:  404.0|last_reward_at:  201|Elapsed Time: 0:00:01||
Episode 3|Iteration 207|reward:  412.0|last_reward_at:  201|Elapsed Time: 0:00:01||
Episode 3|Iteration 207|reward:  412.0|last_reward_at:  207|Elapsed Time: 0:00:01||
Episode 3|Iteration 213|reward:  412.0|last_reward_at:  207|Elapsed Time: 0:00:01||
Episode 3|Iteration 221|reward:  412.0|last_reward_at:  207|Elapsed Time: 0:00:02||
Episode 3|Iteration 228|reward:  412.0|last_reward_at:  207|Elapsed Time: 0:00:02||
Episode 3|Iteration 236|reward:  412.0|last_reward_at:  207|Elapsed Time: 0:00:02||
Episode 3|Iteration 244|reward:  412.0|last_reward_at:  207|Elapsed Time: 0:00:02||
Episode 3|Iteration 251|reward:  412.0|last_reward_at:  207|Elapsed Time: 0:00:02||
Episode 3|Iteration 259|reward:  412.0|last_reward_at:  207|Elapsed Time: 0:00:02||
Episode 3|Iteration 266|reward:  412.0|last_reward_at:  207|Elapsed Time: 0:00:02||
Episode 3|Iteration 274|reward:  412.0|last_reward_at:  207|Elapsed Time: 0:00:02||
Episode 3|Iteration 282|reward:  412.0|last_reward_at:  207|Elapsed Time: 0:00:02||
Episode 3|Iteration 289|reward:  412.0|last_reward_at:  207|Elapsed Time: 0:00:02||
Episode 3|Iteration 297|reward:  412.0|last_reward_at:  207|Elapsed Time: 0:00:02||
Episode 3|Iteration 304|reward:  412.0|last_reward_at:  207|Elapsed Time: 0:00:02||
Episode 3|Iteration 310|reward:  512.0|last_reward_at:  207|Elapsed Time: 0:00:02||
Episode 3|Iteration 310|reward:  512.0|last_reward_at:  310|Elapsed Time: 0:00:02||
Episode 3|Iteration 311|reward:  526.0|last_reward_at:  310|Elapsed Time: 0:00:02||
Episode 3|Iteration 311|reward:  526.0|last_reward_at:  311|Elapsed Time: 0:00:02||
Episode 3|Iteration 312|reward:  626.0|last_reward_at:  311|Elapsed Time: 0:00:02||
Episode 3|Iteration 312|reward:  626.0|last_reward_at:  312|Elapsed Time: 0:00:02||
Episode 3|Iteration 313|reward:  640.0|last_reward_at:  312|Elapsed Time: 0:00:02||
Episode 3|Iteration 313|reward:  640.0|last_reward_at:  313|Elapsed Time: 0:00:02||
Episode 3|Iteration 314|reward:  646.0|last_reward_at:  313|Elapsed Time: 0:00:02||
Episode 3|Iteration 314|reward:  646.0|last_reward_at:  314|Elapsed Time: 0:00:02||
Episode 3|Iteration 316|reward:  652.0|last_reward_at:  314|Elapsed Time: 0:00:02||
Episode 3|Iteration 316|reward:  652.0|last_reward_at:  316|Elapsed Time: 0:00:02||
Episode 3|Iteration 323|reward:  752.0|last_reward_at:  316|Elapsed Time: 0:00:03||
Episode 3|Iteration 323|reward:  752.0|last_reward_at:  323|Elapsed Time: 0:00:03||
Episode 3|Iteration 324|reward:  766.0|last_reward_at:  323|Elapsed Time: 0:00:03||
Episode 3|Iteration 324|reward:  766.0|last_reward_at:  324|Elapsed Time: 0:00:03||
Episode 3|Iteration 325|reward:  866.0|last_reward_at:  324|Elapsed Time: 0:00:03||
Episode 3|Iteration 325|reward:  866.0|last_reward_at:  325|Elapsed Time: 0:00:03||
Episode 3|Iteration 326|reward:  880.0|last_reward_at:  325|Elapsed Time: 0:00:03||
Episode 3|Iteration 326|reward:  880.0|last_reward_at:  326|Elapsed Time: 0:00:03||
Episode 3|Iteration 327|reward:  886.0|last_reward_at:  326|Elapsed Time: 0:00:03||
Episode 3|Iteration 327|reward:  886.0|last_reward_at:  327|Elapsed Time: 0:00:03||
Episode 3|Iteration 328|reward:  986.0|last_reward_at:  327|Elapsed Time: 0:00:03||
Episode 3|Iteration 328|reward:  986.0|last_reward_at:  328|Elapsed Time: 0:00:03||
Episode 3|Iteration 329|reward: 1000.0|last_reward_at:  328|Elapsed Time: 0:00:03||
Episode 3|Iteration 329|reward: 1000.0|last_reward_at:  329|Elapsed Time: 0:00:03||
Episode 3|Iteration 330|reward: 1100.0|last_reward_at:  329|Elapsed Time: 0:00:03||
Episode 3|Iteration 330|reward: 1100.0|last_reward_at:  330|Elapsed Time: 0:00:03||
Episode 3|Iteration 331|reward: 1114.0|last_reward_at:  330|Elapsed Time: 0:00:03||
Episode 3|Iteration 331|reward: 1114.0|last_reward_at:  331|Elapsed Time: 0:00:03||
Episode 3|Iteration 332|reward: 1120.0|last_reward_at:  331|Elapsed Time: 0:00:03||
Episode 3|Iteration 332|reward: 1120.0|last_reward_at:  332|Elapsed Time: 0:00:03||
Episode 3|Iteration 341|reward: 1126.0|last_reward_at:  332|Elapsed Time: 0:00:03||
Episode 3|Iteration 341|reward: 1126.0|last_reward_at:  341|Elapsed Time: 0:00:03||
Episode 3|Iteration 344|reward: 1132.0|last_reward_at:  341|Elapsed Time: 0:00:03||
Episode 3|Iteration 344|reward: 1132.0|last_reward_at:  344|Elapsed Time: 0:00:03||
Episode 3|Iteration 346|reward: 1138.0|last_reward_at:  344|Elapsed Time: 0:00:03||
Episode 3|Iteration 346|reward: 1138.0|last_reward_at:  346|Elapsed Time: 0:00:03||
Episode 3|Iteration 349|reward: 1140.0|last_reward_at:  346|Elapsed Time: 0:00:03||
Episode 3|Iteration 349|reward: 1140.0|last_reward_at:  349|Elapsed Time: 0:00:03||
Episode 3|Iteration 351|reward: 1142.0|last_reward_at:  349|Elapsed Time: 0:00:03||
Episode 3|Iteration 351|reward: 1142.0|last_reward_at:  351|Elapsed Time: 0:00:03||
Episode 3|Iteration 352|reward: 1144.0|last_reward_at:  351|Elapsed Time: 0:00:03||
Episode 3|Iteration 352|reward: 1144.0|last_reward_at:  352|Elapsed Time: 0:00:03||
Episode 3|Iteration 353|reward: 1152.0|last_reward_at:  352|Elapsed Time: 0:00:03||
Episode 3|Iteration 353|reward: 1152.0|last_reward_at:  353|Elapsed Time: 0:00:03||
Episode 3|Iteration 357|reward: 1158.0|last_reward_at:  353|Elapsed Time: 0:00:03||
Episode 3|Iteration 357|reward: 1158.0|last_reward_at:  357|Elapsed Time: 0:00:03||
Episode 3|Iteration 362|reward: 1160.0|last_reward_at:  357|Elapsed Time: 0:00:03||
Episode 3|Iteration 362|reward: 1160.0|last_reward_at:  362|Elapsed Time: 0:00:03||
Episode 3|Iteration 364|reward: 1166.0|last_reward_at:  362|Elapsed Time: 0:00:03||
Episode 3|Iteration 364|reward: 1166.0|last_reward_at:  364|Elapsed Time: 0:00:03||
Episode 3|Iteration 373|reward: 1166.0|last_reward_at:  364|Elapsed Time: 0:00:03||
Episode 3|Iteration 373|reward: 1168.0|last_reward_at:  364|Elapsed Time: 0:00:03||
Episode 3|Iteration 373|reward: 1168.0|last_reward_at:  373|Elapsed Time: 0:00:03||
Episode 3|Iteration 375|reward: 1174.0|last_reward_at:  373|Elapsed Time: 0:00:03||
Episode 3|Iteration 375|reward: 1174.0|last_reward_at:  375|Elapsed Time: 0:00:03||
Episode 3|Iteration 380|reward: 1174.0|last_reward_at:  375|Elapsed Time: 0:00:03||
Episode 3|Iteration 388|reward: 1174.0|last_reward_at:  375|Elapsed Time: 0:00:03||
Episode 3|Iteration 395|reward: 1174.0|last_reward_at:  375|Elapsed Time: 0:00:04||
Episode 3|Iteration 403|reward: 1174.0|last_reward_at:  375|Elapsed Time: 0:00:04||
Episode 3|Iteration 411|reward: 1174.0|last_reward_at:  375|Elapsed Time: 0:00:04||
Episode 3|Iteration 418|reward: 1174.0|last_reward_at:  375|Elapsed Time: 0:00:04||
Episode 3|Iteration 422|reward: 1176.0|last_reward_at:  375|Elapsed Time: 0:00:04||
Episode 3|Iteration 422|reward: 1176.0|last_reward_at:  422|Elapsed Time: 0:00:04||
Episode 3|Iteration 430|reward: 1182.0|last_reward_at:  422|Elapsed Time: 0:00:04||
Episode 3|Iteration 430|reward: 1182.0|last_reward_at:  430|Elapsed Time: 0:00:04||
Episode 3|Iteration 432|reward: 1282.0|last_reward_at:  430|Elapsed Time: 0:00:04||
Episode 3|Iteration 432|reward: 1282.0|last_reward_at:  432|Elapsed Time: 0:00:04||
Episode 3|Iteration 433|reward: 1296.0|last_reward_at:  432|Elapsed Time: 0:00:04||
Episode 3|Iteration 433|reward: 1296.0|last_reward_at:  433|Elapsed Time: 0:00:04||
Episode 3|Iteration 434|reward: 2296.0|last_reward_at:  433|Elapsed Time: 0:00:04||
Episode 3|Iteration 434|reward: 2296.0|last_reward_at:  434|Elapsed Time: 0:00:04||
Episode 3|Iteration 437|reward: 2296.0|last_reward_at:  434|Elapsed Time: 0:00:04||
Episode 3|Iteration 445|reward: 2296.0|last_reward_at:  434|Elapsed Time: 0:00:04||
Episode 3|Iteration 453|reward: 2296.0|last_reward_at:  434|Elapsed Time: 0:00:04||
Episode 3|Iteration 455|reward: 2296.0|last_reward_at:  434|Elapsed Time: 0:00:05||
Episode 3|Iteration 463|reward: 2296.0|last_reward_at:  434|Elapsed Time: 0:00:05||
Episode 3|Iteration 471|reward: 2296.0|last_reward_at:  434|Elapsed Time: 0:00:05||
Episode 3|Iteration 478|reward: 2296.0|last_reward_at:  434|Elapsed Time: 0:00:05||
Episode 3|Iteration 486|reward: 2296.0|last_reward_at:  434|Elapsed Time: 0:00:05||
Episode 3|Iteration 494|reward: 2296.0|last_reward_at:  434|Elapsed Time: 0:00:05||
Episode 3|Iteration 495|reward: 2296.0|last_reward_at:  434|Elapsed Time: 0:00:05||
Episode 3|Iteration 502|reward: 2296.0|last_reward_at:  434|Elapsed Time: 0:00:05||
Episode 3|Iteration 508|reward: 2296.0|last_reward_at:  434|Elapsed Time: 0:00:05||
Episode 3|Iteration 510|reward: 2296.0|last_reward_at:  434|Elapsed Time: 0:00:05||
Episode 3|Iteration 517|reward: 2296.0|last_reward_at:  434|Elapsed Time: 0:00:05||
Episode 3|Iteration 524|reward: 2296.0|last_reward_at:  434|Elapsed Time: 0:00:06||
Episode 3|Iteration 526|reward: 2296.0|last_reward_at:  434|Elapsed Time: 0:00:06||
Episode 3|Iteration 528|reward: 2302.0|last_reward_at:  434|Elapsed Time: 0:00:06||
Episode 3|Iteration 528|reward: 2302.0|last_reward_at:  528|Elapsed Time: 0:00:06||
Episode 3|Iteration 530|reward: 2302.0|last_reward_at:  528|Elapsed Time: 0:00:06||
Episode 3|Iteration 539|reward: 2302.0|last_reward_at:  528|Elapsed Time: 0:00:06||
Episode 3|Iteration 547|reward: 2302.0|last_reward_at:  528|Elapsed Time: 0:00:06||
Episode 3|Iteration 555|reward: 2302.0|last_reward_at:  528|Elapsed Time: 0:00:06||
Episode 3|Iteration 563|reward: 2302.0|last_reward_at:  528|Elapsed Time: 0:00:06||
Episode 3|Iteration 569|reward: 2302.0|last_reward_at:  528|Elapsed Time: 0:00:06||
Episode 3|Iteration 571|reward: 2302.0|last_reward_at:  528|Elapsed Time: 0:00:07||
Episode 3|Iteration 578|reward: 2302.0|last_reward_at:  528|Elapsed Time: 0:00:07||
Episode 3|Iteration 585|reward: 2302.0|last_reward_at:  528|Elapsed Time: 0:00:07||
Episode 3|Iteration 591|reward: 2302.0|last_reward_at:  528|Elapsed Time: 0:00:07||
Episode 3|Iteration 597|reward: 2302.0|last_reward_at:  528|Elapsed Time: 0:00:07||
Episode 3|Iteration 600|reward: 2302.0|last_reward_at:  528|Elapsed Time: 0:00:07||

  Episode 3 stopped at t=600
  Breakdown [Reward/NoReward (Success rate)]
    explore-local: 0/2 (0.00)
    explore-remote: 1/7 (0.12)
    explore-connect: 0/13 (0.00)
    exploit-local: 21/123 (0.15)
    exploit-remote: 19/393 (0.05)
    exploit-connect: 11/10 (0.52)
  exploit deflected to exploration: 23

,status,properties,local_attacks,remote_attacks
id,,,,
start,owned,[],[ScanExplorerRecentFiles],[]
1_LinuxNode,owned,"[MySql, Ubuntu, nginx/1.10.3]","[SudoAttempt, ScanExplorerRecentFiles, ScanBas...","[ProbeWindows, ProbeLinux]"
2_WindowsNode,owned,"[Windows, Win10, Win10Patched]","[ScanExplorerRecentFiles, SudoAttempt, CrackKe...","[ProbeWindows, ProbeLinux]"
3_LinuxNode,owned,"[MySql, Ubuntu, nginx/1.10.3]","[SudoAttempt, ScanExplorerRecentFiles, ScanBas...","[ProbeWindows, ProbeLinux]"
4_WindowsNode,owned,"[Windows, Win10, Win10Patched]","[ScanExplorerRecentFiles, SudoAttempt, CrackKe...","[ProbeWindows, ProbeLinux]"
5_LinuxNode,owned,"[MySql, Ubuntu, nginx/1.10.3]","[SudoAttempt, ScanExplorerRecentFiles, ScanBas...","[ProbeWindows, ProbeLinux]"
6_WindowsNode,owned,"[Windows, Win10, Win10Patched]","[ScanExplorerRecentFiles, SudoAttempt, CrackKe...","[ProbeWindows, ProbeLinux]"
7_LinuxNode,owned,"[MySql, Ubuntu, nginx/1.10.3]","[SudoAttempt, ScanExplorerRecentFiles, ScanBas...","[ProbeWindows, ProbeLinux]"
8_WindowsNode,owned,"[Windows, Win10, Win10Patched]","[ScanExplorerRecentFiles, SudoAttempt, CrackKe...","[ProbeWindows, ProbeLinux]"
9_LinuxNode,owned,"[MySql, Ubuntu, nginx/1.10.3]","[SudoAttempt, ScanExplorerRecentFiles, ScanBas...","[ProbeWindows, ProbeLinux]"
10_WindowsNode,owned,"[Windows, Win10, Win10Patched]","[ScanExplorerRecentFiles, SudoAttempt, CrackKe...","[ProbeWindows, ProbeLinux]"
11_LinuxNode,owned,"[MySql, Ubuntu, nginx/1.10.3, FLAG:Linux]",[],[]

  ## Episode: 4/10 'Exploiting DQL' ϵ=0.0000, γ=0.15, lr=0.01, replaymemory=10000,
batch=256, target_update=5

Episode 4|Iteration 0|reward: ------|last_reward_at: ----|Elapsed Time: 0:00:00||
Episode 4|Iteration 1|reward:   14.0|last_reward_at: ----|Elapsed Time: 0:00:00||
Episode 4|Iteration 1|reward:   14.0|last_reward_at:    1|Elapsed Time: 0:00:00||
Episode 4|Iteration 2|reward:   16.0|last_reward_at:    1|Elapsed Time: 0:00:00||
Episode 4|Iteration 2|reward:   16.0|last_reward_at:    2|Elapsed Time: 0:00:00||
Episode 4|Iteration 9|reward:   20.0|last_reward_at:    2|Elapsed Time: 0:00:00||
Episode 4|Iteration 9|reward:   20.0|last_reward_at:    9|Elapsed Time: 0:00:00||
Episode 4|Iteration 16|reward:   20.0|last_reward_at:    9|Elapsed Time: 0:00:00||
Episode 4|Iteration 23|reward:   20.0|last_reward_at:    9|Elapsed Time: 0:00:00||
Episode 4|Iteration 31|reward:   20.0|last_reward_at:    9|Elapsed Time: 0:00:00||
Episode 4|Iteration 38|reward:   20.0|last_reward_at:    9|Elapsed Time: 0:00:00||
Episode 4|Iteration 46|reward:   20.0|last_reward_at:    9|Elapsed Time: 0:00:00||
Episode 4|Iteration 54|reward:   20.0|last_reward_at:    9|Elapsed Time: 0:00:00||
Episode 4|Iteration 61|reward:   20.0|last_reward_at:    9|Elapsed Time: 0:00:00||
Episode 4|Iteration 66|reward:   20.0|last_reward_at:    9|Elapsed Time: 0:00:00||
Episode 4|Iteration 72|reward:   20.0|last_reward_at:    9|Elapsed Time: 0:00:00||
Episode 4|Iteration 81|reward:   20.0|last_reward_at:    9|Elapsed Time: 0:00:00||
Episode 4|Iteration 92|reward:   20.0|last_reward_at:    9|Elapsed Time: 0:00:00||
Episode 4|Iteration 99|reward:   20.0|last_reward_at:    9|Elapsed Time: 0:00:00||
Episode 4|Iteration 107|reward:   20.0|last_reward_at:    9|Elapsed Time: 0:00:01||
Episode 4|Iteration 112|reward:  120.0|last_reward_at:    9|Elapsed Time: 0:00:01||
Episode 4|Iteration 112|reward:  120.0|last_reward_at:  112|Elapsed Time: 0:00:01||
Episode 4|Iteration 113|reward:  134.0|last_reward_at:  112|Elapsed Time: 0:00:01||
Episode 4|Iteration 113|reward:  134.0|last_reward_at:  113|Elapsed Time: 0:00:01||
Episode 4|Iteration 114|reward:  140.0|last_reward_at:  113|Elapsed Time: 0:00:01||
Episode 4|Iteration 114|reward:  140.0|last_reward_at:  114|Elapsed Time: 0:00:01||
Episode 4|Iteration 117|reward:  148.0|last_reward_at:  114|Elapsed Time: 0:00:01||
Episode 4|Iteration 117|reward:  148.0|last_reward_at:  117|Elapsed Time: 0:00:01||
Episode 4|Iteration 119|reward:  248.0|last_reward_at:  117|Elapsed Time: 0:00:01||
Episode 4|Iteration 119|reward:  248.0|last_reward_at:  119|Elapsed Time: 0:00:01||
Episode 4|Iteration 120|reward:  262.0|last_reward_at:  119|Elapsed Time: 0:00:01||
Episode 4|Iteration 120|reward:  262.0|last_reward_at:  120|Elapsed Time: 0:00:01||
Episode 4|Iteration 121|reward:  362.0|last_reward_at:  120|Elapsed Time: 0:00:01||
Episode 4|Iteration 121|reward:  362.0|last_reward_at:  121|Elapsed Time: 0:00:01||
Episode 4|Iteration 122|reward:  376.0|last_reward_at:  121|Elapsed Time: 0:00:01||
Episode 4|Iteration 122|reward:  376.0|last_reward_at:  122|Elapsed Time: 0:00:01||
Episode 4|Iteration 123|reward:  382.0|last_reward_at:  122|Elapsed Time: 0:00:01||
Episode 4|Iteration 123|reward:  382.0|last_reward_at:  123|Elapsed Time: 0:00:01||
Episode 4|Iteration 130|reward:  382.0|last_reward_at:  123|Elapsed Time: 0:00:01||
Episode 4|Iteration 133|reward:  388.0|last_reward_at:  123|Elapsed Time: 0:00:01||
Episode 4|Iteration 133|reward:  388.0|last_reward_at:  133|Elapsed Time: 0:00:01||
Episode 4|Iteration 135|reward:  488.0|last_reward_at:  133|Elapsed Time: 0:00:01||
Episode 4|Iteration 135|reward:  488.0|last_reward_at:  135|Elapsed Time: 0:00:01||
Episode 4|Iteration 136|reward:  502.0|last_reward_at:  135|Elapsed Time: 0:00:01||
Episode 4|Iteration 136|reward:  502.0|last_reward_at:  136|Elapsed Time: 0:00:01||
Episode 4|Iteration 137|reward:  602.0|last_reward_at:  136|Elapsed Time: 0:00:01||
Episode 4|Iteration 137|reward:  602.0|last_reward_at:  137|Elapsed Time: 0:00:01||
Episode 4|Iteration 138|reward:  616.0|last_reward_at:  137|Elapsed Time: 0:00:01||
Episode 4|Iteration 138|reward:  616.0|last_reward_at:  138|Elapsed Time: 0:00:01||
Episode 4|Iteration 139|reward:  622.0|last_reward_at:  138|Elapsed Time: 0:00:01||
Episode 4|Iteration 139|reward:  622.0|last_reward_at:  139|Elapsed Time: 0:00:01||
Episode 4|Iteration 141|reward:  630.0|last_reward_at:  139|Elapsed Time: 0:00:01||
Episode 4|Iteration 141|reward:  630.0|last_reward_at:  141|Elapsed Time: 0:00:01||
Episode 4|Iteration 143|reward:  730.0|last_reward_at:  141|Elapsed Time: 0:00:01||
Episode 4|Iteration 143|reward:  730.0|last_reward_at:  143|Elapsed Time: 0:00:01||
Episode 4|Iteration 144|reward:  744.0|last_reward_at:  143|Elapsed Time: 0:00:01||
Episode 4|Iteration 144|reward:  744.0|last_reward_at:  144|Elapsed Time: 0:00:01||
Episode 4|Iteration 145|reward:  844.0|last_reward_at:  144|Elapsed Time: 0:00:01||
Episode 4|Iteration 145|reward:  844.0|last_reward_at:  145|Elapsed Time: 0:00:01||
Episode 4|Iteration 146|reward:  858.0|last_reward_at:  145|Elapsed Time: 0:00:01||
Episode 4|Iteration 146|reward:  858.0|last_reward_at:  146|Elapsed Time: 0:00:01||
Episode 4|Iteration 147|reward:  864.0|last_reward_at:  146|Elapsed Time: 0:00:01||
Episode 4|Iteration 147|reward:  864.0|last_reward_at:  147|Elapsed Time: 0:00:01||
Episode 4|Iteration 148|reward:  870.0|last_reward_at:  147|Elapsed Time: 0:00:01||
Episode 4|Iteration 148|reward:  870.0|last_reward_at:  148|Elapsed Time: 0:00:01||
Episode 4|Iteration 149|reward:  872.0|last_reward_at:  148|Elapsed Time: 0:00:01||
Episode 4|Iteration 149|reward:  872.0|last_reward_at:  149|Elapsed Time: 0:00:01||
Episode 4|Iteration 150|reward:  878.0|last_reward_at:  149|Elapsed Time: 0:00:01||
Episode 4|Iteration 150|reward:  878.0|last_reward_at:  150|Elapsed Time: 0:00:01||
Episode 4|Iteration 151|reward:  884.0|last_reward_at:  150|Elapsed Time: 0:00:01||
Episode 4|Iteration 151|reward:  884.0|last_reward_at:  151|Elapsed Time: 0:00:01||
Episode 4|Iteration 152|reward:  890.0|last_reward_at:  151|Elapsed Time: 0:00:01||
Episode 4|Iteration 152|reward:  890.0|last_reward_at:  152|Elapsed Time: 0:00:01||
Episode 4|Iteration 154|reward:  896.0|last_reward_at:  152|Elapsed Time: 0:00:01||
Episode 4|Iteration 154|reward:  896.0|last_reward_at:  154|Elapsed Time: 0:00:01||
Episode 4|Iteration 160|reward:  896.0|last_reward_at:  154|Elapsed Time: 0:00:01||
Episode 4|Iteration 166|reward:  902.0|last_reward_at:  154|Elapsed Time: 0:00:01||
Episode 4|Iteration 166|reward:  902.0|last_reward_at:  166|Elapsed Time: 0:00:01||
Episode 4|Iteration 170|reward:  904.0|last_reward_at:  166|Elapsed Time: 0:00:01||
Episode 4|Iteration 170|reward:  904.0|last_reward_at:  170|Elapsed Time: 0:00:01||
Episode 4|Iteration 173|reward:  906.0|last_reward_at:  170|Elapsed Time: 0:00:01||
Episode 4|Iteration 173|reward:  906.0|last_reward_at:  173|Elapsed Time: 0:00:01||
Episode 4|Iteration 178|reward:  908.0|last_reward_at:  173|Elapsed Time: 0:00:01||
Episode 4|Iteration 178|reward:  908.0|last_reward_at:  178|Elapsed Time: 0:00:01||
Episode 4|Iteration 187|reward:  908.0|last_reward_at:  178|Elapsed Time: 0:00:02||
Episode 4|Iteration 190|reward:  910.0|last_reward_at:  178|Elapsed Time: 0:00:02||
Episode 4|Iteration 190|reward:  910.0|last_reward_at:  190|Elapsed Time: 0:00:02||
Episode 4|Iteration 192|reward:  918.0|last_reward_at:  190|Elapsed Time: 0:00:02||
Episode 4|Iteration 192|reward:  918.0|last_reward_at:  192|Elapsed Time: 0:00:02||
Episode 4|Iteration 198|reward:  918.0|last_reward_at:  192|Elapsed Time: 0:00:02||
Episode 4|Iteration 204|reward:  924.0|last_reward_at:  192|Elapsed Time: 0:00:02||
Episode 4|Iteration 204|reward:  924.0|last_reward_at:  204|Elapsed Time: 0:00:02||
Episode 4|Iteration 213|reward:  924.0|last_reward_at:  204|Elapsed Time: 0:00:02||
Episode 4|Iteration 213|reward: 1024.0|last_reward_at:  204|Elapsed Time: 0:00:02||
Episode 4|Iteration 213|reward: 1024.0|last_reward_at:  213|Elapsed Time: 0:00:02||
Episode 4|Iteration 214|reward: 1038.0|last_reward_at:  213|Elapsed Time: 0:00:02||
Episode 4|Iteration 214|reward: 1038.0|last_reward_at:  214|Elapsed Time: 0:00:02||
Episode 4|Iteration 215|reward: 1138.0|last_reward_at:  214|Elapsed Time: 0:00:02||
Episode 4|Iteration 215|reward: 1138.0|last_reward_at:  215|Elapsed Time: 0:00:02||
Episode 4|Iteration 216|reward: 1152.0|last_reward_at:  215|Elapsed Time: 0:00:02||
Episode 4|Iteration 216|reward: 1152.0|last_reward_at:  216|Elapsed Time: 0:00:02||
Episode 4|Iteration 217|reward: 1158.0|last_reward_at:  216|Elapsed Time: 0:00:02||
Episode 4|Iteration 217|reward: 1158.0|last_reward_at:  217|Elapsed Time: 0:00:02||
Episode 4|Iteration 219|reward: 1160.0|last_reward_at:  217|Elapsed Time: 0:00:02||
Episode 4|Iteration 219|reward: 1160.0|last_reward_at:  219|Elapsed Time: 0:00:02||
Episode 4|Iteration 224|reward: 1260.0|last_reward_at:  219|Elapsed Time: 0:00:02||
Episode 4|Iteration 224|reward: 1260.0|last_reward_at:  224|Elapsed Time: 0:00:02||
Episode 4|Iteration 225|reward: 1274.0|last_reward_at:  224|Elapsed Time: 0:00:02||
Episode 4|Iteration 225|reward: 1274.0|last_reward_at:  225|Elapsed Time: 0:00:02||
Episode 4|Iteration 226|reward: 2274.0|last_reward_at:  225|Elapsed Time: 0:00:02||
Episode 4|Iteration 226|reward: 2274.0|last_reward_at:  226|Elapsed Time: 0:00:02||
Episode 4|Iteration 229|reward: 2276.0|last_reward_at:  226|Elapsed Time: 0:00:02||
Episode 4|Iteration 229|reward: 2276.0|last_reward_at:  229|Elapsed Time: 0:00:02||
Episode 4|Iteration 230|reward: 2278.0|last_reward_at:  229|Elapsed Time: 0:00:02||
Episode 4|Iteration 230|reward: 2278.0|last_reward_at:  230|Elapsed Time: 0:00:02||
Episode 4|Iteration 236|reward: 2278.0|last_reward_at:  230|Elapsed Time: 0:00:02||
Episode 4|Iteration 243|reward: 2278.0|last_reward_at:  230|Elapsed Time: 0:00:02||
Episode 4|Iteration 251|reward: 2278.0|last_reward_at:  230|Elapsed Time: 0:00:02||
Episode 4|Iteration 257|reward: 2284.0|last_reward_at:  230|Elapsed Time: 0:00:02||
Episode 4|Iteration 257|reward: 2284.0|last_reward_at:  257|Elapsed Time: 0:00:02||
Episode 4|Iteration 265|reward: 2290.0|last_reward_at:  257|Elapsed Time: 0:00:03||
Episode 4|Iteration 265|reward: 2290.0|last_reward_at:  265|Elapsed Time: 0:00:03||
Episode 4|Iteration 270|reward: 2290.0|last_reward_at:  265|Elapsed Time: 0:00:03||
Episode 4|Iteration 279|reward: 2290.0|last_reward_at:  265|Elapsed Time: 0:00:03||
Episode 4|Iteration 288|reward: 2290.0|last_reward_at:  265|Elapsed Time: 0:00:03||
Episode 4|Iteration 289|reward: 2296.0|last_reward_at:  265|Elapsed Time: 0:00:03||
Episode 4|Iteration 289|reward: 2296.0|last_reward_at:  289|Elapsed Time: 0:00:03||
Episode 4|Iteration 297|reward: 2296.0|last_reward_at:  289|Elapsed Time: 0:00:03||
Episode 4|Iteration 304|reward: 2296.0|last_reward_at:  289|Elapsed Time: 0:00:03||
Episode 4|Iteration 311|reward: 2296.0|last_reward_at:  289|Elapsed Time: 0:00:03||
Episode 4|Iteration 314|reward: 2296.0|last_reward_at:  289|Elapsed Time: 0:00:03||
Episode 4|Iteration 323|reward: 2296.0|last_reward_at:  289|Elapsed Time: 0:00:03||
Episode 4|Iteration 332|reward: 2296.0|last_reward_at:  289|Elapsed Time: 0:00:04||
Episode 4|Iteration 334|reward: 2296.0|last_reward_at:  289|Elapsed Time: 0:00:04||
Episode 4|Iteration 342|reward: 2296.0|last_reward_at:  289|Elapsed Time: 0:00:04||
Episode 4|Iteration 345|reward: 2296.0|last_reward_at:  289|Elapsed Time: 0:00:04||
Episode 4|Iteration 353|reward: 2302.0|last_reward_at:  289|Elapsed Time: 0:00:04||
Episode 4|Iteration 353|reward: 2302.0|last_reward_at:  353|Elapsed Time: 0:00:04||
Episode 4|Iteration 362|reward: 2302.0|last_reward_at:  353|Elapsed Time: 0:00:04||
Episode 4|Iteration 370|reward: 2302.0|last_reward_at:  353|Elapsed Time: 0:00:04||
Episode 4|Iteration 379|reward: 2302.0|last_reward_at:  353|Elapsed Time: 0:00:04||
Episode 4|Iteration 383|reward: 2302.0|last_reward_at:  353|Elapsed Time: 0:00:04||
Episode 4|Iteration 392|reward: 2302.0|last_reward_at:  353|Elapsed Time: 0:00:04||
Episode 4|Iteration 401|reward: 2302.0|last_reward_at:  353|Elapsed Time: 0:00:05||
Episode 4|Iteration 410|reward: 2302.0|last_reward_at:  353|Elapsed Time: 0:00:05||
Episode 4|Iteration 418|reward: 2302.0|last_reward_at:  353|Elapsed Time: 0:00:05||
Episode 4|Iteration 423|reward: 2302.0|last_reward_at:  353|Elapsed Time: 0:00:05||
Episode 4|Iteration 429|reward: 2302.0|last_reward_at:  353|Elapsed Time: 0:00:05||
Episode 4|Iteration 435|reward: 2302.0|last_reward_at:  353|Elapsed Time: 0:00:05||
Episode 4|Iteration 441|reward: 2302.0|last_reward_at:  353|Elapsed Time: 0:00:05||
Episode 4|Iteration 449|reward: 2302.0|last_reward_at:  353|Elapsed Time: 0:00:05||
Episode 4|Iteration 456|reward: 2302.0|last_reward_at:  353|Elapsed Time: 0:00:05||
Episode 4|Iteration 464|reward: 2302.0|last_reward_at:  353|Elapsed Time: 0:00:06||
Episode 4|Iteration 471|reward: 2302.0|last_reward_at:  353|Elapsed Time: 0:00:06||
Episode 4|Iteration 479|reward: 2302.0|last_reward_at:  353|Elapsed Time: 0:00:06||
Episode 4|Iteration 487|reward: 2302.0|last_reward_at:  353|Elapsed Time: 0:00:06||
Episode 4|Iteration 494|reward: 2302.0|last_reward_at:  353|Elapsed Time: 0:00:06||
Episode 4|Iteration 502|reward: 2302.0|last_reward_at:  353|Elapsed Time: 0:00:06||
Episode 4|Iteration 507|reward: 2302.0|last_reward_at:  353|Elapsed Time: 0:00:06||
Episode 4|Iteration 515|reward: 2302.0|last_reward_at:  353|Elapsed Time: 0:00:06||
Episode 4|Iteration 524|reward: 2302.0|last_reward_at:  353|Elapsed Time: 0:00:06||
Episode 4|Iteration 532|reward: 2302.0|last_reward_at:  353|Elapsed Time: 0:00:06||
Episode 4|Iteration 540|reward: 2302.0|last_reward_at:  353|Elapsed Time: 0:00:07||
Episode 4|Iteration 546|reward: 2302.0|last_reward_at:  353|Elapsed Time: 0:00:07||
Episode 4|Iteration 555|reward: 2302.0|last_reward_at:  353|Elapsed Time: 0:00:07||
Episode 4|Iteration 563|reward: 2302.0|last_reward_at:  353|Elapsed Time: 0:00:07||
Episode 4|Iteration 570|reward: 2302.0|last_reward_at:  353|Elapsed Time: 0:00:07||
Episode 4|Iteration 576|reward: 2302.0|last_reward_at:  353|Elapsed Time: 0:00:07||
Episode 4|Iteration 584|reward: 2302.0|last_reward_at:  353|Elapsed Time: 0:00:07||
Episode 4|Iteration 592|reward: 2302.0|last_reward_at:  353|Elapsed Time: 0:00:07||
Episode 4|Iteration 594|reward: 2302.0|last_reward_at:  353|Elapsed Time: 0:00:07||
Episode 4|Iteration 600|reward: 2302.0|last_reward_at:  353|Elapsed Time: 0:00:07||
Episode 4|Iteration 600|reward: 2302.0|last_reward_at:  353|Elapsed Time: 0:00:08||

  Episode 4 stopped at t=600
  Breakdown [Reward/NoReward (Success rate)]
    explore-local: 0/5 (0.00)
    explore-remote: 0/7 (0.00)
    explore-connect: 1/4 (0.20)
    exploit-local: 21/137 (0.13)
    exploit-remote: 20/385 (0.05)
    exploit-connect: 10/10 (0.50)
  exploit deflected to exploration: 17

,status,properties,local_attacks,remote_attacks
id,,,,
start,owned,[],[ScanExplorerRecentFiles],[]
1_LinuxNode,owned,"[MySql, Ubuntu, nginx/1.10.3]","[SudoAttempt, ScanExplorerRecentFiles, ScanBas...","[ProbeWindows, ProbeLinux]"
2_WindowsNode,owned,"[Windows, Win10, Win10Patched]","[ScanExplorerRecentFiles, SudoAttempt, CrackKe...","[ProbeWindows, ProbeLinux]"
3_LinuxNode,owned,"[MySql, Ubuntu, nginx/1.10.3]","[SudoAttempt, ScanExplorerRecentFiles, ScanBas...","[ProbeWindows, ProbeLinux]"
4_WindowsNode,owned,"[Windows, Win10, Win10Patched]","[ScanExplorerRecentFiles, SudoAttempt, CrackKe...","[ProbeWindows, ProbeLinux]"
5_LinuxNode,owned,"[MySql, Ubuntu, nginx/1.10.3]","[SudoAttempt, ScanExplorerRecentFiles, ScanBas...","[ProbeWindows, ProbeLinux]"
6_WindowsNode,owned,"[Windows, Win10, Win10Patched]","[ScanExplorerRecentFiles, SudoAttempt, CrackKe...","[ProbeWindows, ProbeLinux]"
7_LinuxNode,owned,"[MySql, Ubuntu, nginx/1.10.3]","[SudoAttempt, ScanExplorerRecentFiles, ScanBas...","[ProbeWindows, ProbeLinux]"
8_WindowsNode,owned,"[Windows, Win10, Win10Patched]","[ScanExplorerRecentFiles, SudoAttempt, CrackKe...","[ProbeWindows, ProbeLinux]"
9_LinuxNode,owned,"[MySql, Ubuntu, nginx/1.10.3]","[SudoAttempt, ScanExplorerRecentFiles, ScanBas...","[ProbeWindows, ProbeLinux]"
10_WindowsNode,owned,"[Windows, Win10, Win10Patched]","[ScanExplorerRecentFiles, SudoAttempt, CrackKe...","[ProbeWindows, ProbeLinux]"
11_LinuxNode,owned,"[MySql, Ubuntu, nginx/1.10.3, FLAG:Linux]",[],[]

  ## Episode: 5/10 'Exploiting DQL' ϵ=0.0000, γ=0.15, lr=0.01, replaymemory=10000,
batch=256, target_update=5

Episode 5|Iteration 0|reward: ------|last_reward_at: ----|Elapsed Time: 0:00:00||
Episode 5|Iteration 1|reward:   14.0|last_reward_at: ----|Elapsed Time: 0:00:00||
Episode 5|Iteration 1|reward:   14.0|last_reward_at:    1|Elapsed Time: 0:00:00||
Episode 5|Iteration 4|reward:   16.0|last_reward_at:    1|Elapsed Time: 0:00:00||
Episode 5|Iteration 4|reward:   16.0|last_reward_at:    4|Elapsed Time: 0:00:00||
Episode 5|Iteration 6|reward:  116.0|last_reward_at:    4|Elapsed Time: 0:00:00||
Episode 5|Iteration 6|reward:  116.0|last_reward_at:    6|Elapsed Time: 0:00:00||
Episode 5|Iteration 7|reward:  130.0|last_reward_at:    6|Elapsed Time: 0:00:00||
Episode 5|Iteration 7|reward:  130.0|last_reward_at:    7|Elapsed Time: 0:00:00||
Episode 5|Iteration 8|reward:  136.0|last_reward_at:    7|Elapsed Time: 0:00:00||
Episode 5|Iteration 8|reward:  136.0|last_reward_at:    8|Elapsed Time: 0:00:00||
Episode 5|Iteration 11|reward:  142.0|last_reward_at:    8|Elapsed Time: 0:00:00||
Episode 5|Iteration 11|reward:  142.0|last_reward_at:   11|Elapsed Time: 0:00:00||
Episode 5|Iteration 15|reward:  150.0|last_reward_at:   11|Elapsed Time: 0:00:00||
Episode 5|Iteration 15|reward:  150.0|last_reward_at:   15|Elapsed Time: 0:00:00||
Episode 5|Iteration 20|reward:  152.0|last_reward_at:   15|Elapsed Time: 0:00:00||
Episode 5|Iteration 20|reward:  152.0|last_reward_at:   20|Elapsed Time: 0:00:00||
Episode 5|Iteration 30|reward:  252.0|last_reward_at:   20|Elapsed Time: 0:00:00||
Episode 5|Iteration 30|reward:  252.0|last_reward_at:   30|Elapsed Time: 0:00:00||
Episode 5|Iteration 31|reward:  266.0|last_reward_at:   30|Elapsed Time: 0:00:00||
Episode 5|Iteration 31|reward:  266.0|last_reward_at:   31|Elapsed Time: 0:00:00||
Episode 5|Iteration 32|reward:  366.0|last_reward_at:   31|Elapsed Time: 0:00:00||
Episode 5|Iteration 32|reward:  366.0|last_reward_at:   32|Elapsed Time: 0:00:00||
Episode 5|Iteration 33|reward:  380.0|last_reward_at:   32|Elapsed Time: 0:00:00||
Episode 5|Iteration 33|reward:  380.0|last_reward_at:   33|Elapsed Time: 0:00:00||
Episode 5|Iteration 34|reward:  386.0|last_reward_at:   33|Elapsed Time: 0:00:00||
Episode 5|Iteration 34|reward:  386.0|last_reward_at:   34|Elapsed Time: 0:00:00||
Episode 5|Iteration 35|reward:  392.0|last_reward_at:   34|Elapsed Time: 0:00:00||
Episode 5|Iteration 35|reward:  392.0|last_reward_at:   35|Elapsed Time: 0:00:00||
Episode 5|Iteration 36|reward:  492.0|last_reward_at:   35|Elapsed Time: 0:00:00||
Episode 5|Iteration 36|reward:  492.0|last_reward_at:   36|Elapsed Time: 0:00:00||
Episode 5|Iteration 37|reward:  506.0|last_reward_at:   36|Elapsed Time: 0:00:00||
Episode 5|Iteration 37|reward:  506.0|last_reward_at:   37|Elapsed Time: 0:00:00||
Episode 5|Iteration 38|reward:  606.0|last_reward_at:   37|Elapsed Time: 0:00:00||
Episode 5|Iteration 38|reward:  606.0|last_reward_at:   38|Elapsed Time: 0:00:00||
Episode 5|Iteration 39|reward:  620.0|last_reward_at:   38|Elapsed Time: 0:00:00||
Episode 5|Iteration 39|reward:  620.0|last_reward_at:   39|Elapsed Time: 0:00:00||
Episode 5|Iteration 40|reward:  626.0|last_reward_at:   39|Elapsed Time: 0:00:00||
Episode 5|Iteration 40|reward:  626.0|last_reward_at:   40|Elapsed Time: 0:00:00||
Episode 5|Iteration 41|reward:  726.0|last_reward_at:   40|Elapsed Time: 0:00:00||
Episode 5|Iteration 41|reward:  726.0|last_reward_at:   41|Elapsed Time: 0:00:00||
Episode 5|Iteration 42|reward:  740.0|last_reward_at:   41|Elapsed Time: 0:00:00||
Episode 5|Iteration 42|reward:  740.0|last_reward_at:   42|Elapsed Time: 0:00:00||
Episode 5|Iteration 43|reward:  840.0|last_reward_at:   42|Elapsed Time: 0:00:00||
Episode 5|Iteration 43|reward:  840.0|last_reward_at:   43|Elapsed Time: 0:00:00||
Episode 5|Iteration 44|reward:  854.0|last_reward_at:   43|Elapsed Time: 0:00:00||
Episode 5|Iteration 44|reward:  854.0|last_reward_at:   44|Elapsed Time: 0:00:00||
Episode 5|Iteration 45|reward:  860.0|last_reward_at:   44|Elapsed Time: 0:00:00||
Episode 5|Iteration 45|reward:  860.0|last_reward_at:   45|Elapsed Time: 0:00:00||
Episode 5|Iteration 47|reward:  866.0|last_reward_at:   45|Elapsed Time: 0:00:00||
Episode 5|Iteration 47|reward:  866.0|last_reward_at:   47|Elapsed Time: 0:00:00||
Episode 5|Iteration 50|reward:  872.0|last_reward_at:   47|Elapsed Time: 0:00:00||
Episode 5|Iteration 50|reward:  872.0|last_reward_at:   50|Elapsed Time: 0:00:00||
Episode 5|Iteration 53|reward:  880.0|last_reward_at:   50|Elapsed Time: 0:00:00||
Episode 5|Iteration 53|reward:  880.0|last_reward_at:   53|Elapsed Time: 0:00:00||
Episode 5|Iteration 54|reward:  882.0|last_reward_at:   53|Elapsed Time: 0:00:00||
Episode 5|Iteration 54|reward:  882.0|last_reward_at:   54|Elapsed Time: 0:00:00||
Episode 5|Iteration 55|reward:  982.0|last_reward_at:   54|Elapsed Time: 0:00:00||
Episode 5|Iteration 55|reward:  982.0|last_reward_at:   55|Elapsed Time: 0:00:00||
Episode 5|Iteration 56|reward:  996.0|last_reward_at:   55|Elapsed Time: 0:00:00||
Episode 5|Iteration 56|reward:  996.0|last_reward_at:   56|Elapsed Time: 0:00:00||
Episode 5|Iteration 57|reward: 1096.0|last_reward_at:   56|Elapsed Time: 0:00:00||
Episode 5|Iteration 57|reward: 1096.0|last_reward_at:   57|Elapsed Time: 0:00:00||
Episode 5|Iteration 58|reward: 1110.0|last_reward_at:   57|Elapsed Time: 0:00:00||
Episode 5|Iteration 58|reward: 1110.0|last_reward_at:   58|Elapsed Time: 0:00:00||
Episode 5|Iteration 59|reward: 1116.0|last_reward_at:   58|Elapsed Time: 0:00:00||
Episode 5|Iteration 59|reward: 1116.0|last_reward_at:   59|Elapsed Time: 0:00:00||
Episode 5|Iteration 62|reward: 1118.0|last_reward_at:   59|Elapsed Time: 0:00:00||
Episode 5|Iteration 62|reward: 1118.0|last_reward_at:   62|Elapsed Time: 0:00:00||
Episode 5|Iteration 65|reward: 1120.0|last_reward_at:   62|Elapsed Time: 0:00:00||
Episode 5|Iteration 65|reward: 1120.0|last_reward_at:   65|Elapsed Time: 0:00:00||
Episode 5|Iteration 66|reward: 1126.0|last_reward_at:   65|Elapsed Time: 0:00:00||
Episode 5|Iteration 66|reward: 1126.0|last_reward_at:   66|Elapsed Time: 0:00:00||
Episode 5|Iteration 67|reward: 1128.0|last_reward_at:   66|Elapsed Time: 0:00:00||
Episode 5|Iteration 67|reward: 1128.0|last_reward_at:   67|Elapsed Time: 0:00:00||
Episode 5|Iteration 68|reward: 1130.0|last_reward_at:   67|Elapsed Time: 0:00:00||
Episode 5|Iteration 68|reward: 1130.0|last_reward_at:   68|Elapsed Time: 0:00:00||
Episode 5|Iteration 69|reward: 1136.0|last_reward_at:   68|Elapsed Time: 0:00:00||
Episode 5|Iteration 69|reward: 1136.0|last_reward_at:   69|Elapsed Time: 0:00:00||
Episode 5|Iteration 75|reward: 1236.0|last_reward_at:   69|Elapsed Time: 0:00:00||
Episode 5|Iteration 75|reward: 1236.0|last_reward_at:   75|Elapsed Time: 0:00:00||
Episode 5|Iteration 76|reward: 1250.0|last_reward_at:   75|Elapsed Time: 0:00:00||
Episode 5|Iteration 76|reward: 1250.0|last_reward_at:   76|Elapsed Time: 0:00:00||
Episode 5|Iteration 77|reward: 2250.0|last_reward_at:   76|Elapsed Time: 0:00:01||
Episode 5|Iteration 77|reward: 2250.0|last_reward_at:   77|Elapsed Time: 0:00:01||
Episode 5|Iteration 79|reward: 2252.0|last_reward_at:   77|Elapsed Time: 0:00:01||
Episode 5|Iteration 79|reward: 2252.0|last_reward_at:   79|Elapsed Time: 0:00:01||
Episode 5|Iteration 84|reward: 2252.0|last_reward_at:   79|Elapsed Time: 0:00:01||
Episode 5|Iteration 89|reward: 2258.0|last_reward_at:   79|Elapsed Time: 0:00:01||
Episode 5|Iteration 89|reward: 2258.0|last_reward_at:   89|Elapsed Time: 0:00:01||
Episode 5|Iteration 97|reward: 2258.0|last_reward_at:   89|Elapsed Time: 0:00:01||
Episode 5|Iteration 99|reward: 2258.0|last_reward_at:   89|Elapsed Time: 0:00:01||
Episode 5|Iteration 105|reward: 2260.0|last_reward_at:   89|Elapsed Time: 0:00:01||
Episode 5|Iteration 105|reward: 2260.0|last_reward_at:  105|Elapsed Time: 0:00:01||
Episode 5|Iteration 108|reward: 2262.0|last_reward_at:  105|Elapsed Time: 0:00:01||
Episode 5|Iteration 108|reward: 2262.0|last_reward_at:  108|Elapsed Time: 0:00:01||
Episode 5|Iteration 113|reward: 2262.0|last_reward_at:  108|Elapsed Time: 0:00:01||
Episode 5|Iteration 121|reward: 2268.0|last_reward_at:  108|Elapsed Time: 0:00:01||
Episode 5|Iteration 121|reward: 2268.0|last_reward_at:  121|Elapsed Time: 0:00:01||
Episode 5|Iteration 130|reward: 2268.0|last_reward_at:  121|Elapsed Time: 0:00:01||
Episode 5|Iteration 131|reward: 2268.0|last_reward_at:  121|Elapsed Time: 0:00:01||
Episode 5|Iteration 135|reward: 2274.0|last_reward_at:  121|Elapsed Time: 0:00:01||
Episode 5|Iteration 135|reward: 2274.0|last_reward_at:  135|Elapsed Time: 0:00:01||
Episode 5|Iteration 136|reward: 2280.0|last_reward_at:  135|Elapsed Time: 0:00:02||
Episode 5|Iteration 136|reward: 2280.0|last_reward_at:  136|Elapsed Time: 0:00:02||
Episode 5|Iteration 144|reward: 2280.0|last_reward_at:  136|Elapsed Time: 0:00:02||
Episode 5|Iteration 152|reward: 2280.0|last_reward_at:  136|Elapsed Time: 0:00:02||
Episode 5|Iteration 152|reward: 2286.0|last_reward_at:  136|Elapsed Time: 0:00:02||
Episode 5|Iteration 152|reward: 2286.0|last_reward_at:  152|Elapsed Time: 0:00:02||
Episode 5|Iteration 155|reward: 2286.0|last_reward_at:  152|Elapsed Time: 0:00:02||
Episode 5|Iteration 160|reward: 2286.0|last_reward_at:  152|Elapsed Time: 0:00:02||
Episode 5|Iteration 167|reward: 2286.0|last_reward_at:  152|Elapsed Time: 0:00:02||
Episode 5|Iteration 174|reward: 2292.0|last_reward_at:  152|Elapsed Time: 0:00:02||
Episode 5|Iteration 174|reward: 2292.0|last_reward_at:  174|Elapsed Time: 0:00:02||
Episode 5|Iteration 176|reward: 2292.0|last_reward_at:  174|Elapsed Time: 0:00:02||
Episode 5|Iteration 183|reward: 2292.0|last_reward_at:  174|Elapsed Time: 0:00:02||
Episode 5|Iteration 183|reward: 2298.0|last_reward_at:  174|Elapsed Time: 0:00:02||
Episode 5|Iteration 183|reward: 2298.0|last_reward_at:  183|Elapsed Time: 0:00:02||
Episode 5|Iteration 190|reward: 2298.0|last_reward_at:  183|Elapsed Time: 0:00:02||
Episode 5|Iteration 196|reward: 2298.0|last_reward_at:  183|Elapsed Time: 0:00:03||
Episode 5|Iteration 204|reward: 2298.0|last_reward_at:  183|Elapsed Time: 0:00:03||
Episode 5|Iteration 213|reward: 2298.0|last_reward_at:  183|Elapsed Time: 0:00:03||
Episode 5|Iteration 220|reward: 2298.0|last_reward_at:  183|Elapsed Time: 0:00:03||
Episode 5|Iteration 228|reward: 2298.0|last_reward_at:  183|Elapsed Time: 0:00:03||
Episode 5|Iteration 235|reward: 2298.0|last_reward_at:  183|Elapsed Time: 0:00:03||
Episode 5|Iteration 239|reward: 2298.0|last_reward_at:  183|Elapsed Time: 0:00:03||
Episode 5|Iteration 241|reward: 2298.0|last_reward_at:  183|Elapsed Time: 0:00:03||
Episode 5|Iteration 250|reward: 2298.0|last_reward_at:  183|Elapsed Time: 0:00:03||
Episode 5|Iteration 252|reward: 2298.0|last_reward_at:  183|Elapsed Time: 0:00:03||
Episode 5|Iteration 259|reward: 2298.0|last_reward_at:  183|Elapsed Time: 0:00:04||
Episode 5|Iteration 265|reward: 2298.0|last_reward_at:  183|Elapsed Time: 0:00:04||
Episode 5|Iteration 273|reward: 2298.0|last_reward_at:  183|Elapsed Time: 0:00:04||
Episode 5|Iteration 282|reward: 2298.0|last_reward_at:  183|Elapsed Time: 0:00:04||
Episode 5|Iteration 289|reward: 2298.0|last_reward_at:  183|Elapsed Time: 0:00:04||
Episode 5|Iteration 297|reward: 2298.0|last_reward_at:  183|Elapsed Time: 0:00:04||
Episode 5|Iteration 304|reward: 2298.0|last_reward_at:  183|Elapsed Time: 0:00:04||
Episode 5|Iteration 311|reward: 2298.0|last_reward_at:  183|Elapsed Time: 0:00:04||
Episode 5|Iteration 319|reward: 2298.0|last_reward_at:  183|Elapsed Time: 0:00:04||
Episode 5|Iteration 326|reward: 2298.0|last_reward_at:  183|Elapsed Time: 0:00:04||
Episode 5|Iteration 327|reward: 2298.0|last_reward_at:  183|Elapsed Time: 0:00:05||
Episode 5|Iteration 335|reward: 2298.0|last_reward_at:  183|Elapsed Time: 0:00:05||
Episode 5|Iteration 342|reward: 2298.0|last_reward_at:  183|Elapsed Time: 0:00:05||
Episode 5|Iteration 349|reward: 2298.0|last_reward_at:  183|Elapsed Time: 0:00:05||
Episode 5|Iteration 357|reward: 2298.0|last_reward_at:  183|Elapsed Time: 0:00:05||
Episode 5|Iteration 364|reward: 2298.0|last_reward_at:  183|Elapsed Time: 0:00:05||
Episode 5|Iteration 370|reward: 2298.0|last_reward_at:  183|Elapsed Time: 0:00:05||
Episode 5|Iteration 377|reward: 2298.0|last_reward_at:  183|Elapsed Time: 0:00:05||
Episode 5|Iteration 383|reward: 2298.0|last_reward_at:  183|Elapsed Time: 0:00:05||
Episode 5|Iteration 388|reward: 2298.0|last_reward_at:  183|Elapsed Time: 0:00:06||
Episode 5|Iteration 391|reward: 2298.0|last_reward_at:  183|Elapsed Time: 0:00:06||
Episode 5|Iteration 399|reward: 2298.0|last_reward_at:  183|Elapsed Time: 0:00:06||
Episode 5|Iteration 407|reward: 2298.0|last_reward_at:  183|Elapsed Time: 0:00:06||
Episode 5|Iteration 415|reward: 2298.0|last_reward_at:  183|Elapsed Time: 0:00:06||
Episode 5|Iteration 423|reward: 2298.0|last_reward_at:  183|Elapsed Time: 0:00:06||
Episode 5|Iteration 432|reward: 2298.0|last_reward_at:  183|Elapsed Time: 0:00:06||
Episode 5|Iteration 440|reward: 2298.0|last_reward_at:  183|Elapsed Time: 0:00:06||
Episode 5|Iteration 448|reward: 2298.0|last_reward_at:  183|Elapsed Time: 0:00:06||
Episode 5|Iteration 456|reward: 2298.0|last_reward_at:  183|Elapsed Time: 0:00:07||
Episode 5|Iteration 460|reward: 2298.0|last_reward_at:  183|Elapsed Time: 0:00:07||
Episode 5|Iteration 468|reward: 2298.0|last_reward_at:  183|Elapsed Time: 0:00:07||
Episode 5|Iteration 476|reward: 2298.0|last_reward_at:  183|Elapsed Time: 0:00:07||
Episode 5|Iteration 483|reward: 2298.0|last_reward_at:  183|Elapsed Time: 0:00:07||
Episode 5|Iteration 491|reward: 2298.0|last_reward_at:  183|Elapsed Time: 0:00:07||
Episode 5|Iteration 499|reward: 2298.0|last_reward_at:  183|Elapsed Time: 0:00:07||
Episode 5|Iteration 504|reward: 2298.0|last_reward_at:  183|Elapsed Time: 0:00:07||
Episode 5|Iteration 506|reward: 2298.0|last_reward_at:  183|Elapsed Time: 0:00:08||
Episode 5|Iteration 514|reward: 2298.0|last_reward_at:  183|Elapsed Time: 0:00:08||
Episode 5|Iteration 522|reward: 2298.0|last_reward_at:  183|Elapsed Time: 0:00:08||
Episode 5|Iteration 524|reward: 2298.0|last_reward_at:  183|Elapsed Time: 0:00:08||
Episode 5|Iteration 532|reward: 2298.0|last_reward_at:  183|Elapsed Time: 0:00:08||
Episode 5|Iteration 533|reward: 2298.0|last_reward_at:  183|Elapsed Time: 0:00:08||
Episode 5|Iteration 540|reward: 2298.0|last_reward_at:  183|Elapsed Time: 0:00:08||
Episode 5|Iteration 547|reward: 2298.0|last_reward_at:  183|Elapsed Time: 0:00:08||
Episode 5|Iteration 554|reward: 2298.0|last_reward_at:  183|Elapsed Time: 0:00:08||
Episode 5|Iteration 562|reward: 2298.0|last_reward_at:  183|Elapsed Time: 0:00:08||
Episode 5|Iteration 570|reward: 2298.0|last_reward_at:  183|Elapsed Time: 0:00:09||
Episode 5|Iteration 577|reward: 2298.0|last_reward_at:  183|Elapsed Time: 0:00:09||
Episode 5|Iteration 585|reward: 2298.0|last_reward_at:  183|Elapsed Time: 0:00:09||
Episode 5|Iteration 592|reward: 2298.0|last_reward_at:  183|Elapsed Time: 0:00:09||
Episode 5|Iteration 600|reward: 2298.0|last_reward_at:  183|Elapsed Time: 0:00:09||
Episode 5|Iteration 600|reward: 2298.0|last_reward_at:  183|Elapsed Time: 0:00:09||
/home/infres/adauz/CyberBattleSim/cyberbattle/agents/baseline/plotting.py:158: RuntimeWarning:

More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`). Consider using `matplotlib.pyplot.close()`.

  Episode 5 stopped at t=600
  Breakdown [Reward/NoReward (Success rate)]
    explore-local: 0/6 (0.00)
    explore-remote: 0/8 (0.00)
    explore-connect: 0/7 (0.00)
    exploit-local: 21/94 (0.18)
    exploit-remote: 20/430 (0.04)
    exploit-connect: 11/3 (0.79)
  exploit deflected to exploration: 21

,status,properties,local_attacks,remote_attacks
id,,,,
start,owned,[],[ScanExplorerRecentFiles],[]
1_LinuxNode,owned,"[MySql, Ubuntu, nginx/1.10.3]","[SudoAttempt, ScanExplorerRecentFiles, ScanBas...","[ProbeWindows, ProbeLinux]"
2_WindowsNode,owned,"[Windows, Win10, Win10Patched]","[ScanExplorerRecentFiles, SudoAttempt, CrackKe...","[ProbeWindows, ProbeLinux]"
3_LinuxNode,owned,"[MySql, Ubuntu, nginx/1.10.3]","[SudoAttempt, ScanExplorerRecentFiles, ScanBas...","[ProbeWindows, ProbeLinux]"
4_WindowsNode,owned,"[Windows, Win10, Win10Patched]","[ScanExplorerRecentFiles, SudoAttempt, CrackKe...","[ProbeWindows, ProbeLinux]"
5_LinuxNode,owned,"[MySql, Ubuntu, nginx/1.10.3]","[SudoAttempt, ScanExplorerRecentFiles, ScanBas...","[ProbeWindows, ProbeLinux]"
6_WindowsNode,owned,"[Windows, Win10, Win10Patched]","[ScanExplorerRecentFiles, SudoAttempt, CrackKe...","[ProbeWindows, ProbeLinux]"
7_LinuxNode,owned,"[MySql, Ubuntu, nginx/1.10.3]","[SudoAttempt, ScanExplorerRecentFiles, ScanBas...","[ProbeWindows, ProbeLinux]"
8_WindowsNode,owned,"[Windows, Win10, Win10Patched]","[ScanExplorerRecentFiles, SudoAttempt, CrackKe...","[ProbeWindows, ProbeLinux]"
9_LinuxNode,owned,"[MySql, Ubuntu, nginx/1.10.3]","[SudoAttempt, ScanExplorerRecentFiles, ScanBas...","[ProbeWindows, ProbeLinux]"
10_WindowsNode,owned,"[Windows, Win10, Win10Patched]","[ScanExplorerRecentFiles, SudoAttempt, CrackKe...","[ProbeWindows, ProbeLinux]"
11_LinuxNode,owned,"[MySql, Ubuntu, nginx/1.10.3, FLAG:Linux]",[],[]

  ## Episode: 6/10 'Exploiting DQL' ϵ=0.0000, γ=0.15, lr=0.01, replaymemory=10000,
batch=256, target_update=5

Episode 6|Iteration 0|reward: ------|last_reward_at: ----|Elapsed Time: 0:00:00||
Episode 6|Iteration 1|reward:   14.0|last_reward_at: ----|Elapsed Time: 0:00:00||
Episode 6|Iteration 1|reward:   14.0|last_reward_at:    1|Elapsed Time: 0:00:00||
Episode 6|Iteration 3|reward:   16.0|last_reward_at:    1|Elapsed Time: 0:00:00||
Episode 6|Iteration 3|reward:   16.0|last_reward_at:    3|Elapsed Time: 0:00:00||
Episode 6|Iteration 7|reward:  116.0|last_reward_at:    3|Elapsed Time: 0:00:00||
Episode 6|Iteration 7|reward:  116.0|last_reward_at:    7|Elapsed Time: 0:00:00||
Episode 6|Iteration 8|reward:  130.0|last_reward_at:    7|Elapsed Time: 0:00:00||
Episode 6|Iteration 8|reward:  130.0|last_reward_at:    8|Elapsed Time: 0:00:00||
Episode 6|Iteration 9|reward:  136.0|last_reward_at:    8|Elapsed Time: 0:00:00||
Episode 6|Iteration 9|reward:  136.0|last_reward_at:    9|Elapsed Time: 0:00:00||
Episode 6|Iteration 11|reward:  144.0|last_reward_at:    9|Elapsed Time: 0:00:00||
Episode 6|Iteration 11|reward:  144.0|last_reward_at:   11|Elapsed Time: 0:00:00||
Episode 6|Iteration 13|reward:  146.0|last_reward_at:   11|Elapsed Time: 0:00:00||
Episode 6|Iteration 13|reward:  146.0|last_reward_at:   13|Elapsed Time: 0:00:00||
Episode 6|Iteration 15|reward:  152.0|last_reward_at:   13|Elapsed Time: 0:00:00||
Episode 6|Iteration 15|reward:  152.0|last_reward_at:   15|Elapsed Time: 0:00:00||
Episode 6|Iteration 23|reward:  152.0|last_reward_at:   15|Elapsed Time: 0:00:00||
Episode 6|Iteration 31|reward:  152.0|last_reward_at:   15|Elapsed Time: 0:00:00||
Episode 6|Iteration 38|reward:  152.0|last_reward_at:   15|Elapsed Time: 0:00:00||
Episode 6|Iteration 46|reward:  152.0|last_reward_at:   15|Elapsed Time: 0:00:00||
Episode 6|Iteration 54|reward:  152.0|last_reward_at:   15|Elapsed Time: 0:00:00||
Episode 6|Iteration 61|reward:  152.0|last_reward_at:   15|Elapsed Time: 0:00:00||
Episode 6|Iteration 69|reward:  152.0|last_reward_at:   15|Elapsed Time: 0:00:00||
Episode 6|Iteration 76|reward:  152.0|last_reward_at:   15|Elapsed Time: 0:00:00||
Episode 6|Iteration 84|reward:  152.0|last_reward_at:   15|Elapsed Time: 0:00:00||
Episode 6|Iteration 92|reward:  152.0|last_reward_at:   15|Elapsed Time: 0:00:00||
Episode 6|Iteration 99|reward:  152.0|last_reward_at:   15|Elapsed Time: 0:00:00||
Episode 6|Iteration 107|reward:  152.0|last_reward_at:   15|Elapsed Time: 0:00:00||
Episode 6|Iteration 114|reward:  152.0|last_reward_at:   15|Elapsed Time: 0:00:01||
Episode 6|Iteration 122|reward:  152.0|last_reward_at:   15|Elapsed Time: 0:00:01||
Episode 6|Iteration 130|reward:  152.0|last_reward_at:   15|Elapsed Time: 0:00:01||
Episode 6|Iteration 137|reward:  152.0|last_reward_at:   15|Elapsed Time: 0:00:01||
Episode 6|Iteration 142|reward:  252.0|last_reward_at:   15|Elapsed Time: 0:00:01||
Episode 6|Iteration 142|reward:  252.0|last_reward_at:  142|Elapsed Time: 0:00:01||
Episode 6|Iteration 143|reward:  266.0|last_reward_at:  142|Elapsed Time: 0:00:01||
Episode 6|Iteration 143|reward:  266.0|last_reward_at:  143|Elapsed Time: 0:00:01||
Episode 6|Iteration 144|reward:  366.0|last_reward_at:  143|Elapsed Time: 0:00:01||
Episode 6|Iteration 144|reward:  366.0|last_reward_at:  144|Elapsed Time: 0:00:01||
Episode 6|Iteration 145|reward:  380.0|last_reward_at:  144|Elapsed Time: 0:00:01||
Episode 6|Iteration 145|reward:  380.0|last_reward_at:  145|Elapsed Time: 0:00:01||
Episode 6|Iteration 146|reward:  386.0|last_reward_at:  145|Elapsed Time: 0:00:01||
Episode 6|Iteration 146|reward:  386.0|last_reward_at:  146|Elapsed Time: 0:00:01||
Episode 6|Iteration 154|reward:  394.0|last_reward_at:  146|Elapsed Time: 0:00:01||
Episode 6|Iteration 154|reward:  394.0|last_reward_at:  154|Elapsed Time: 0:00:01||
Episode 6|Iteration 157|reward:  396.0|last_reward_at:  154|Elapsed Time: 0:00:01||
Episode 6|Iteration 157|reward:  396.0|last_reward_at:  157|Elapsed Time: 0:00:01||
Episode 6|Iteration 161|reward:  496.0|last_reward_at:  157|Elapsed Time: 0:00:01||
Episode 6|Iteration 161|reward:  496.0|last_reward_at:  161|Elapsed Time: 0:00:01||
Episode 6|Iteration 162|reward:  510.0|last_reward_at:  161|Elapsed Time: 0:00:01||
Episode 6|Iteration 162|reward:  510.0|last_reward_at:  162|Elapsed Time: 0:00:01||
Episode 6|Iteration 163|reward:  610.0|last_reward_at:  162|Elapsed Time: 0:00:01||
Episode 6|Iteration 163|reward:  610.0|last_reward_at:  163|Elapsed Time: 0:00:01||
Episode 6|Iteration 164|reward:  624.0|last_reward_at:  163|Elapsed Time: 0:00:01||
Episode 6|Iteration 164|reward:  624.0|last_reward_at:  164|Elapsed Time: 0:00:01||
Episode 6|Iteration 168|reward:  630.0|last_reward_at:  164|Elapsed Time: 0:00:01||
Episode 6|Iteration 168|reward:  630.0|last_reward_at:  168|Elapsed Time: 0:00:01||
Episode 6|Iteration 174|reward:  636.0|last_reward_at:  168|Elapsed Time: 0:00:01||
Episode 6|Iteration 174|reward:  636.0|last_reward_at:  174|Elapsed Time: 0:00:01||
Episode 6|Iteration 177|reward:  642.0|last_reward_at:  174|Elapsed Time: 0:00:01||
Episode 6|Iteration 177|reward:  642.0|last_reward_at:  177|Elapsed Time: 0:00:01||
Episode 6|Iteration 179|reward:  648.0|last_reward_at:  177|Elapsed Time: 0:00:01||
Episode 6|Iteration 179|reward:  648.0|last_reward_at:  179|Elapsed Time: 0:00:01||
Episode 6|Iteration 181|reward:  650.0|last_reward_at:  179|Elapsed Time: 0:00:01||
Episode 6|Iteration 181|reward:  650.0|last_reward_at:  181|Elapsed Time: 0:00:01||
Episode 6|Iteration 185|reward:  656.0|last_reward_at:  181|Elapsed Time: 0:00:01||
Episode 6|Iteration 185|reward:  656.0|last_reward_at:  185|Elapsed Time: 0:00:01||
Episode 6|Iteration 195|reward:  656.0|last_reward_at:  185|Elapsed Time: 0:00:01||
Episode 6|Iteration 204|reward:  756.0|last_reward_at:  185|Elapsed Time: 0:00:02||
Episode 6|Iteration 204|reward:  756.0|last_reward_at:  204|Elapsed Time: 0:00:02||
Episode 6|Iteration 205|reward:  770.0|last_reward_at:  204|Elapsed Time: 0:00:02||
Episode 6|Iteration 205|reward:  770.0|last_reward_at:  205|Elapsed Time: 0:00:02||
Episode 6|Iteration 206|reward:  870.0|last_reward_at:  205|Elapsed Time: 0:00:02||
Episode 6|Iteration 206|reward:  870.0|last_reward_at:  206|Elapsed Time: 0:00:02||
Episode 6|Iteration 207|reward:  884.0|last_reward_at:  206|Elapsed Time: 0:00:02||
Episode 6|Iteration 207|reward:  884.0|last_reward_at:  207|Elapsed Time: 0:00:02||
Episode 6|Iteration 211|reward:  984.0|last_reward_at:  207|Elapsed Time: 0:00:02||
Episode 6|Iteration 211|reward:  984.0|last_reward_at:  211|Elapsed Time: 0:00:02||
Episode 6|Iteration 212|reward:  998.0|last_reward_at:  211|Elapsed Time: 0:00:02||
Episode 6|Iteration 212|reward:  998.0|last_reward_at:  212|Elapsed Time: 0:00:02||
Episode 6|Iteration 213|reward: 1098.0|last_reward_at:  212|Elapsed Time: 0:00:02||
Episode 6|Iteration 213|reward: 1098.0|last_reward_at:  213|Elapsed Time: 0:00:02||
Episode 6|Iteration 214|reward: 1112.0|last_reward_at:  213|Elapsed Time: 0:00:02||
Episode 6|Iteration 214|reward: 1112.0|last_reward_at:  214|Elapsed Time: 0:00:02||
Episode 6|Iteration 220|reward: 1114.0|last_reward_at:  214|Elapsed Time: 0:00:02||
Episode 6|Iteration 220|reward: 1114.0|last_reward_at:  220|Elapsed Time: 0:00:02||
Episode 6|Iteration 221|reward: 1214.0|last_reward_at:  220|Elapsed Time: 0:00:02||
Episode 6|Iteration 221|reward: 1214.0|last_reward_at:  221|Elapsed Time: 0:00:02||
Episode 6|Iteration 222|reward: 1228.0|last_reward_at:  221|Elapsed Time: 0:00:02||
Episode 6|Iteration 222|reward: 1228.0|last_reward_at:  222|Elapsed Time: 0:00:02||
Episode 6|Iteration 223|reward: 2228.0|last_reward_at:  222|Elapsed Time: 0:00:02||
Episode 6|Iteration 223|reward: 2228.0|last_reward_at:  223|Elapsed Time: 0:00:02||
Episode 6|Iteration 225|reward: 2228.0|last_reward_at:  223|Elapsed Time: 0:00:02||
Episode 6|Iteration 226|reward: 2234.0|last_reward_at:  223|Elapsed Time: 0:00:02||
Episode 6|Iteration 226|reward: 2234.0|last_reward_at:  226|Elapsed Time: 0:00:02||
Episode 6|Iteration 227|reward: 2240.0|last_reward_at:  226|Elapsed Time: 0:00:02||
Episode 6|Iteration 227|reward: 2240.0|last_reward_at:  227|Elapsed Time: 0:00:02||
Episode 6|Iteration 230|reward: 2242.0|last_reward_at:  227|Elapsed Time: 0:00:02||
Episode 6|Iteration 230|reward: 2242.0|last_reward_at:  230|Elapsed Time: 0:00:02||
Episode 6|Iteration 236|reward: 2242.0|last_reward_at:  230|Elapsed Time: 0:00:02||
Episode 6|Iteration 237|reward: 2248.0|last_reward_at:  230|Elapsed Time: 0:00:02||
Episode 6|Iteration 237|reward: 2248.0|last_reward_at:  237|Elapsed Time: 0:00:02||
Episode 6|Iteration 239|reward: 2250.0|last_reward_at:  237|Elapsed Time: 0:00:02||
Episode 6|Iteration 239|reward: 2250.0|last_reward_at:  239|Elapsed Time: 0:00:02||
Episode 6|Iteration 242|reward: 2256.0|last_reward_at:  239|Elapsed Time: 0:00:02||
Episode 6|Iteration 242|reward: 2256.0|last_reward_at:  242|Elapsed Time: 0:00:02||
Episode 6|Iteration 244|reward: 2256.0|last_reward_at:  242|Elapsed Time: 0:00:02||
Episode 6|Iteration 251|reward: 2256.0|last_reward_at:  242|Elapsed Time: 0:00:02||
Episode 6|Iteration 257|reward: 2262.0|last_reward_at:  242|Elapsed Time: 0:00:03||
Episode 6|Iteration 257|reward: 2262.0|last_reward_at:  257|Elapsed Time: 0:00:03||
Episode 6|Iteration 258|reward: 2268.0|last_reward_at:  257|Elapsed Time: 0:00:03||
Episode 6|Iteration 258|reward: 2268.0|last_reward_at:  258|Elapsed Time: 0:00:03||
Episode 6|Iteration 264|reward: 2270.0|last_reward_at:  258|Elapsed Time: 0:00:03||
Episode 6|Iteration 264|reward: 2270.0|last_reward_at:  264|Elapsed Time: 0:00:03||
Episode 6|Iteration 265|reward: 2276.0|last_reward_at:  264|Elapsed Time: 0:00:03||
Episode 6|Iteration 265|reward: 2276.0|last_reward_at:  265|Elapsed Time: 0:00:03||
Episode 6|Iteration 272|reward: 2282.0|last_reward_at:  265|Elapsed Time: 0:00:03||
Episode 6|Iteration 272|reward: 2282.0|last_reward_at:  272|Elapsed Time: 0:00:03||
Episode 6|Iteration 277|reward: 2284.0|last_reward_at:  272|Elapsed Time: 0:00:03||
Episode 6|Iteration 277|reward: 2284.0|last_reward_at:  277|Elapsed Time: 0:00:03||
Episode 6|Iteration 280|reward: 2290.0|last_reward_at:  277|Elapsed Time: 0:00:03||
Episode 6|Iteration 280|reward: 2290.0|last_reward_at:  280|Elapsed Time: 0:00:03||
Episode 6|Iteration 288|reward: 2290.0|last_reward_at:  280|Elapsed Time: 0:00:03||
Episode 6|Iteration 296|reward: 2290.0|last_reward_at:  280|Elapsed Time: 0:00:03||
Episode 6|Iteration 299|reward: 2290.0|last_reward_at:  280|Elapsed Time: 0:00:03||
Episode 6|Iteration 304|reward: 2290.0|last_reward_at:  280|Elapsed Time: 0:00:03||
Episode 6|Iteration 305|reward: 2292.0|last_reward_at:  280|Elapsed Time: 0:00:03||
Episode 6|Iteration 305|reward: 2292.0|last_reward_at:  305|Elapsed Time: 0:00:03||
Episode 6|Iteration 307|reward: 2292.0|last_reward_at:  305|Elapsed Time: 0:00:03||
Episode 6|Iteration 312|reward: 2292.0|last_reward_at:  305|Elapsed Time: 0:00:03||
Episode 6|Iteration 319|reward: 2292.0|last_reward_at:  305|Elapsed Time: 0:00:03||
Episode 6|Iteration 327|reward: 2292.0|last_reward_at:  305|Elapsed Time: 0:00:04||
Episode 6|Iteration 333|reward: 2298.0|last_reward_at:  305|Elapsed Time: 0:00:04||
Episode 6|Iteration 333|reward: 2298.0|last_reward_at:  333|Elapsed Time: 0:00:04||
Episode 6|Iteration 342|reward: 2298.0|last_reward_at:  333|Elapsed Time: 0:00:04||
Episode 6|Iteration 350|reward: 2298.0|last_reward_at:  333|Elapsed Time: 0:00:04||
Episode 6|Iteration 357|reward: 2298.0|last_reward_at:  333|Elapsed Time: 0:00:04||
Episode 6|Iteration 361|reward: 2298.0|last_reward_at:  333|Elapsed Time: 0:00:04||
Episode 6|Iteration 365|reward: 2298.0|last_reward_at:  333|Elapsed Time: 0:00:04||
Episode 6|Iteration 368|reward: 2298.0|last_reward_at:  333|Elapsed Time: 0:00:04||
Episode 6|Iteration 370|reward: 2298.0|last_reward_at:  333|Elapsed Time: 0:00:04||
Episode 6|Iteration 377|reward: 2298.0|last_reward_at:  333|Elapsed Time: 0:00:05||
Episode 6|Iteration 385|reward: 2298.0|last_reward_at:  333|Elapsed Time: 0:00:05||
Episode 6|Iteration 393|reward: 2298.0|last_reward_at:  333|Elapsed Time: 0:00:05||
Episode 6|Iteration 400|reward: 2298.0|last_reward_at:  333|Elapsed Time: 0:00:05||
Episode 6|Iteration 406|reward: 2298.0|last_reward_at:  333|Elapsed Time: 0:00:05||
Episode 6|Iteration 411|reward: 2298.0|last_reward_at:  333|Elapsed Time: 0:00:05||
Episode 6|Iteration 416|reward: 2298.0|last_reward_at:  333|Elapsed Time: 0:00:05||
Episode 6|Iteration 422|reward: 2298.0|last_reward_at:  333|Elapsed Time: 0:00:05||
Episode 6|Iteration 426|reward: 2298.0|last_reward_at:  333|Elapsed Time: 0:00:05||
Episode 6|Iteration 428|reward: 2298.0|last_reward_at:  333|Elapsed Time: 0:00:06||
Episode 6|Iteration 433|reward: 2298.0|last_reward_at:  333|Elapsed Time: 0:00:06||
Episode 6|Iteration 440|reward: 2298.0|last_reward_at:  333|Elapsed Time: 0:00:06||
Episode 6|Iteration 448|reward: 2298.0|last_reward_at:  333|Elapsed Time: 0:00:06||
Episode 6|Iteration 454|reward: 2298.0|last_reward_at:  333|Elapsed Time: 0:00:06||
Episode 6|Iteration 462|reward: 2298.0|last_reward_at:  333|Elapsed Time: 0:00:06||
Episode 6|Iteration 469|reward: 2298.0|last_reward_at:  333|Elapsed Time: 0:00:06||
Episode 6|Iteration 472|reward: 2298.0|last_reward_at:  333|Elapsed Time: 0:00:06||
Episode 6|Iteration 479|reward: 2298.0|last_reward_at:  333|Elapsed Time: 0:00:06||
Episode 6|Iteration 481|reward: 2298.0|last_reward_at:  333|Elapsed Time: 0:00:06||
Episode 6|Iteration 484|reward: 2298.0|last_reward_at:  333|Elapsed Time: 0:00:07||
Episode 6|Iteration 492|reward: 2298.0|last_reward_at:  333|Elapsed Time: 0:00:07||
Episode 6|Iteration 501|reward: 2298.0|last_reward_at:  333|Elapsed Time: 0:00:07||
Episode 6|Iteration 509|reward: 2298.0|last_reward_at:  333|Elapsed Time: 0:00:07||
Episode 6|Iteration 517|reward: 2298.0|last_reward_at:  333|Elapsed Time: 0:00:07||
Episode 6|Iteration 519|reward: 2298.0|last_reward_at:  333|Elapsed Time: 0:00:07||
Episode 6|Iteration 525|reward: 2298.0|last_reward_at:  333|Elapsed Time: 0:00:07||
Episode 6|Iteration 532|reward: 2298.0|last_reward_at:  333|Elapsed Time: 0:00:07||
Episode 6|Iteration 539|reward: 2298.0|last_reward_at:  333|Elapsed Time: 0:00:07||
Episode 6|Iteration 547|reward: 2298.0|last_reward_at:  333|Elapsed Time: 0:00:07||
Episode 6|Iteration 548|reward: 2298.0|last_reward_at:  333|Elapsed Time: 0:00:08||
Episode 6|Iteration 555|reward: 2298.0|last_reward_at:  333|Elapsed Time: 0:00:08||
Episode 6|Iteration 562|reward: 2298.0|last_reward_at:  333|Elapsed Time: 0:00:08||
Episode 6|Iteration 570|reward: 2298.0|last_reward_at:  333|Elapsed Time: 0:00:08||
Episode 6|Iteration 577|reward: 2298.0|last_reward_at:  333|Elapsed Time: 0:00:08||
Episode 6|Iteration 585|reward: 2298.0|last_reward_at:  333|Elapsed Time: 0:00:08||
Episode 6|Iteration 591|reward: 2298.0|last_reward_at:  333|Elapsed Time: 0:00:08||
Episode 6|Iteration 599|reward: 2298.0|last_reward_at:  333|Elapsed Time: 0:00:08||
Episode 6|Iteration 600|reward: 2298.0|last_reward_at:  333|Elapsed Time: 0:00:08||

  Episode 6 stopped at t=600
  Breakdown [Reward/NoReward (Success rate)]
    explore-local: 0/5 (0.00)
    explore-remote: 0/4 (0.00)
    explore-connect: 0/9 (0.00)
    exploit-local: 21/198 (0.10)
    exploit-remote: 20/316 (0.06)
    exploit-connect: 11/16 (0.41)
  exploit deflected to exploration: 18

,status,properties,local_attacks,remote_attacks
id,,,,
start,owned,[],[ScanExplorerRecentFiles],[]
1_LinuxNode,owned,"[MySql, Ubuntu, nginx/1.10.3]","[SudoAttempt, ScanExplorerRecentFiles, ScanBas...","[ProbeWindows, ProbeLinux]"
2_WindowsNode,owned,"[Windows, Win10, Win10Patched]","[ScanExplorerRecentFiles, SudoAttempt, CrackKe...","[ProbeWindows, ProbeLinux]"
3_LinuxNode,owned,"[MySql, Ubuntu, nginx/1.10.3]","[SudoAttempt, ScanExplorerRecentFiles, ScanBas...","[ProbeWindows, ProbeLinux]"
4_WindowsNode,owned,"[Windows, Win10, Win10Patched]","[ScanExplorerRecentFiles, SudoAttempt, CrackKe...","[ProbeWindows, ProbeLinux]"
5_LinuxNode,owned,"[MySql, Ubuntu, nginx/1.10.3]","[SudoAttempt, ScanExplorerRecentFiles, ScanBas...","[ProbeWindows, ProbeLinux]"
6_WindowsNode,owned,"[Windows, Win10, Win10Patched]","[ScanExplorerRecentFiles, SudoAttempt, CrackKe...","[ProbeWindows, ProbeLinux]"
7_LinuxNode,owned,"[MySql, Ubuntu, nginx/1.10.3]","[SudoAttempt, ScanExplorerRecentFiles, ScanBas...","[ProbeWindows, ProbeLinux]"
8_WindowsNode,owned,"[Windows, Win10, Win10Patched]","[ScanExplorerRecentFiles, SudoAttempt, CrackKe...","[ProbeWindows, ProbeLinux]"
9_LinuxNode,owned,"[MySql, Ubuntu, nginx/1.10.3]","[SudoAttempt, ScanExplorerRecentFiles, ScanBas...","[ProbeWindows, ProbeLinux]"
10_WindowsNode,owned,"[Windows, Win10, Win10Patched]","[ScanExplorerRecentFiles, SudoAttempt, CrackKe...","[ProbeWindows, ProbeLinux]"
11_LinuxNode,owned,"[MySql, Ubuntu, nginx/1.10.3, FLAG:Linux]",[],[]

  ## Episode: 7/10 'Exploiting DQL' ϵ=0.0000, γ=0.15, lr=0.01, replaymemory=10000,
batch=256, target_update=5

Episode 7|Iteration 0|reward: ------|last_reward_at: ----|Elapsed Time: 0:00:00||
Episode 7|Iteration 1|reward:   14.0|last_reward_at: ----|Elapsed Time: 0:00:00||
Episode 7|Iteration 1|reward:   14.0|last_reward_at:    1|Elapsed Time: 0:00:00||
Episode 7|Iteration 2|reward:   16.0|last_reward_at:    1|Elapsed Time: 0:00:00||
Episode 7|Iteration 2|reward:   16.0|last_reward_at:    2|Elapsed Time: 0:00:00||
Episode 7|Iteration 3|reward:   20.0|last_reward_at:    2|Elapsed Time: 0:00:00||
Episode 7|Iteration 3|reward:   20.0|last_reward_at:    3|Elapsed Time: 0:00:00||
Episode 7|Iteration 15|reward:   20.0|last_reward_at:    3|Elapsed Time: 0:00:00||
Episode 7|Iteration 23|reward:   20.0|last_reward_at:    3|Elapsed Time: 0:00:00||
Episode 7|Iteration 31|reward:   20.0|last_reward_at:    3|Elapsed Time: 0:00:00||
Episode 7|Iteration 38|reward:   20.0|last_reward_at:    3|Elapsed Time: 0:00:00||
Episode 7|Iteration 46|reward:   20.0|last_reward_at:    3|Elapsed Time: 0:00:00||
Episode 7|Iteration 54|reward:   20.0|last_reward_at:    3|Elapsed Time: 0:00:00||
Episode 7|Iteration 61|reward:   20.0|last_reward_at:    3|Elapsed Time: 0:00:00||
Episode 7|Iteration 69|reward:   20.0|last_reward_at:    3|Elapsed Time: 0:00:00||
Episode 7|Iteration 76|reward:   20.0|last_reward_at:    3|Elapsed Time: 0:00:00||
Episode 7|Iteration 84|reward:   20.0|last_reward_at:    3|Elapsed Time: 0:00:00||
Episode 7|Iteration 92|reward:   20.0|last_reward_at:    3|Elapsed Time: 0:00:00||
Episode 7|Iteration 99|reward:   20.0|last_reward_at:    3|Elapsed Time: 0:00:00||
Episode 7|Iteration 107|reward:   20.0|last_reward_at:    3|Elapsed Time: 0:00:00||
Episode 7|Iteration 114|reward:   20.0|last_reward_at:    3|Elapsed Time: 0:00:00||
Episode 7|Iteration 122|reward:   20.0|last_reward_at:    3|Elapsed Time: 0:00:00||
Episode 7|Iteration 130|reward:   20.0|last_reward_at:    3|Elapsed Time: 0:00:01||
Episode 7|Iteration 137|reward:   20.0|last_reward_at:    3|Elapsed Time: 0:00:01||
Episode 7|Iteration 145|reward:   20.0|last_reward_at:    3|Elapsed Time: 0:00:01||
Episode 7|Iteration 152|reward:   20.0|last_reward_at:    3|Elapsed Time: 0:00:01||
Episode 7|Iteration 160|reward:   20.0|last_reward_at:    3|Elapsed Time: 0:00:01||
Episode 7|Iteration 168|reward:   20.0|last_reward_at:    3|Elapsed Time: 0:00:01||
Episode 7|Iteration 175|reward:   20.0|last_reward_at:    3|Elapsed Time: 0:00:01||
Episode 7|Iteration 183|reward:   20.0|last_reward_at:    3|Elapsed Time: 0:00:01||
Episode 7|Iteration 190|reward:   20.0|last_reward_at:    3|Elapsed Time: 0:00:01||
Episode 7|Iteration 198|reward:   20.0|last_reward_at:    3|Elapsed Time: 0:00:01||
Episode 7|Iteration 206|reward:   20.0|last_reward_at:    3|Elapsed Time: 0:00:01||
Episode 7|Iteration 213|reward:   20.0|last_reward_at:    3|Elapsed Time: 0:00:01||
Episode 7|Iteration 221|reward:   20.0|last_reward_at:    3|Elapsed Time: 0:00:01||
Episode 7|Iteration 228|reward:   20.0|last_reward_at:    3|Elapsed Time: 0:00:01||
Episode 7|Iteration 236|reward:   20.0|last_reward_at:    3|Elapsed Time: 0:00:01||
Episode 7|Iteration 244|reward:   20.0|last_reward_at:    3|Elapsed Time: 0:00:02||
Episode 7|Iteration 251|reward:   20.0|last_reward_at:    3|Elapsed Time: 0:00:02||
Episode 7|Iteration 259|reward:   20.0|last_reward_at:    3|Elapsed Time: 0:00:02||
Episode 7|Iteration 266|reward:   20.0|last_reward_at:    3|Elapsed Time: 0:00:02||
Episode 7|Iteration 272|reward:  120.0|last_reward_at:    3|Elapsed Time: 0:00:02||
Episode 7|Iteration 272|reward:  120.0|last_reward_at:  272|Elapsed Time: 0:00:02||
Episode 7|Iteration 273|reward:  134.0|last_reward_at:  272|Elapsed Time: 0:00:02||
Episode 7|Iteration 273|reward:  134.0|last_reward_at:  273|Elapsed Time: 0:00:02||
Episode 7|Iteration 275|reward:  234.0|last_reward_at:  273|Elapsed Time: 0:00:02||
Episode 7|Iteration 275|reward:  234.0|last_reward_at:  275|Elapsed Time: 0:00:02||
Episode 7|Iteration 276|reward:  248.0|last_reward_at:  275|Elapsed Time: 0:00:02||
Episode 7|Iteration 276|reward:  248.0|last_reward_at:  276|Elapsed Time: 0:00:02||
Episode 7|Iteration 277|reward:  348.0|last_reward_at:  276|Elapsed Time: 0:00:02||
Episode 7|Iteration 277|reward:  348.0|last_reward_at:  277|Elapsed Time: 0:00:02||
Episode 7|Iteration 278|reward:  362.0|last_reward_at:  277|Elapsed Time: 0:00:02||
Episode 7|Iteration 278|reward:  362.0|last_reward_at:  278|Elapsed Time: 0:00:02||
Episode 7|Iteration 280|reward:  462.0|last_reward_at:  278|Elapsed Time: 0:00:02||
Episode 7|Iteration 280|reward:  462.0|last_reward_at:  280|Elapsed Time: 0:00:02||
Episode 7|Iteration 281|reward:  476.0|last_reward_at:  280|Elapsed Time: 0:00:02||
Episode 7|Iteration 281|reward:  476.0|last_reward_at:  281|Elapsed Time: 0:00:02||
Episode 7|Iteration 282|reward:  576.0|last_reward_at:  281|Elapsed Time: 0:00:02||
Episode 7|Iteration 282|reward:  576.0|last_reward_at:  282|Elapsed Time: 0:00:02||
Episode 7|Iteration 283|reward:  590.0|last_reward_at:  282|Elapsed Time: 0:00:02||
Episode 7|Iteration 283|reward:  590.0|last_reward_at:  283|Elapsed Time: 0:00:02||
Episode 7|Iteration 285|reward:  690.0|last_reward_at:  283|Elapsed Time: 0:00:02||
Episode 7|Iteration 285|reward:  690.0|last_reward_at:  285|Elapsed Time: 0:00:02||
Episode 7|Iteration 286|reward:  704.0|last_reward_at:  285|Elapsed Time: 0:00:02||
Episode 7|Iteration 286|reward:  704.0|last_reward_at:  286|Elapsed Time: 0:00:02||
Episode 7|Iteration 287|reward:  804.0|last_reward_at:  286|Elapsed Time: 0:00:02||
Episode 7|Iteration 287|reward:  804.0|last_reward_at:  287|Elapsed Time: 0:00:02||
Episode 7|Iteration 288|reward:  818.0|last_reward_at:  287|Elapsed Time: 0:00:02||
Episode 7|Iteration 288|reward:  818.0|last_reward_at:  288|Elapsed Time: 0:00:02||
Episode 7|Iteration 290|reward:  918.0|last_reward_at:  288|Elapsed Time: 0:00:02||
Episode 7|Iteration 290|reward:  918.0|last_reward_at:  290|Elapsed Time: 0:00:02||
Episode 7|Iteration 291|reward:  932.0|last_reward_at:  290|Elapsed Time: 0:00:02||
Episode 7|Iteration 291|reward:  932.0|last_reward_at:  291|Elapsed Time: 0:00:02||
Episode 7|Iteration 292|reward: 1032.0|last_reward_at:  291|Elapsed Time: 0:00:02||
Episode 7|Iteration 292|reward: 1032.0|last_reward_at:  292|Elapsed Time: 0:00:02||
Episode 7|Iteration 293|reward: 1046.0|last_reward_at:  292|Elapsed Time: 0:00:02||
Episode 7|Iteration 293|reward: 1046.0|last_reward_at:  293|Elapsed Time: 0:00:02||
Episode 7|Iteration 295|reward: 1146.0|last_reward_at:  293|Elapsed Time: 0:00:02||
Episode 7|Iteration 295|reward: 1146.0|last_reward_at:  295|Elapsed Time: 0:00:02||
Episode 7|Iteration 296|reward: 1160.0|last_reward_at:  295|Elapsed Time: 0:00:02||
Episode 7|Iteration 296|reward: 1160.0|last_reward_at:  296|Elapsed Time: 0:00:02||
Episode 7|Iteration 297|reward: 2160.0|last_reward_at:  296|Elapsed Time: 0:00:02||
Episode 7|Iteration 297|reward: 2160.0|last_reward_at:  297|Elapsed Time: 0:00:02||
Episode 7|Iteration 299|reward: 2162.0|last_reward_at:  297|Elapsed Time: 0:00:02||
Episode 7|Iteration 299|reward: 2162.0|last_reward_at:  299|Elapsed Time: 0:00:02||
Episode 7|Iteration 300|reward: 2168.0|last_reward_at:  299|Elapsed Time: 0:00:02||
Episode 7|Iteration 300|reward: 2168.0|last_reward_at:  300|Elapsed Time: 0:00:02||
Episode 7|Iteration 301|reward: 2170.0|last_reward_at:  300|Elapsed Time: 0:00:02||
Episode 7|Iteration 301|reward: 2170.0|last_reward_at:  301|Elapsed Time: 0:00:02||
Episode 7|Iteration 304|reward: 2172.0|last_reward_at:  301|Elapsed Time: 0:00:02||
Episode 7|Iteration 304|reward: 2172.0|last_reward_at:  304|Elapsed Time: 0:00:02||
Episode 7|Iteration 306|reward: 2178.0|last_reward_at:  304|Elapsed Time: 0:00:02||
Episode 7|Iteration 306|reward: 2178.0|last_reward_at:  306|Elapsed Time: 0:00:02||
Episode 7|Iteration 308|reward: 2184.0|last_reward_at:  306|Elapsed Time: 0:00:02||
Episode 7|Iteration 308|reward: 2184.0|last_reward_at:  308|Elapsed Time: 0:00:02||
Episode 7|Iteration 310|reward: 2186.0|last_reward_at:  308|Elapsed Time: 0:00:02||
Episode 7|Iteration 310|reward: 2186.0|last_reward_at:  310|Elapsed Time: 0:00:02||
Episode 7|Iteration 311|reward: 2192.0|last_reward_at:  310|Elapsed Time: 0:00:02||
Episode 7|Iteration 311|reward: 2192.0|last_reward_at:  311|Elapsed Time: 0:00:02||
Episode 7|Iteration 314|reward: 2198.0|last_reward_at:  311|Elapsed Time: 0:00:03||
Episode 7|Iteration 314|reward: 2198.0|last_reward_at:  314|Elapsed Time: 0:00:03||
Episode 7|Iteration 316|reward: 2204.0|last_reward_at:  314|Elapsed Time: 0:00:03||
Episode 7|Iteration 316|reward: 2204.0|last_reward_at:  316|Elapsed Time: 0:00:03||
Episode 7|Iteration 317|reward: 2210.0|last_reward_at:  316|Elapsed Time: 0:00:03||
Episode 7|Iteration 317|reward: 2210.0|last_reward_at:  317|Elapsed Time: 0:00:03||
Episode 7|Iteration 320|reward: 2216.0|last_reward_at:  317|Elapsed Time: 0:00:03||
Episode 7|Iteration 320|reward: 2216.0|last_reward_at:  320|Elapsed Time: 0:00:03||
Episode 7|Iteration 326|reward: 2216.0|last_reward_at:  320|Elapsed Time: 0:00:03||
Episode 7|Iteration 331|reward: 2218.0|last_reward_at:  320|Elapsed Time: 0:00:03||
Episode 7|Iteration 331|reward: 2218.0|last_reward_at:  331|Elapsed Time: 0:00:03||
Episode 7|Iteration 333|reward: 2224.0|last_reward_at:  331|Elapsed Time: 0:00:03||
Episode 7|Iteration 333|reward: 2224.0|last_reward_at:  333|Elapsed Time: 0:00:03||
Episode 7|Iteration 335|reward: 2226.0|last_reward_at:  333|Elapsed Time: 0:00:03||
Episode 7|Iteration 335|reward: 2226.0|last_reward_at:  335|Elapsed Time: 0:00:03||
Episode 7|Iteration 336|reward: 2232.0|last_reward_at:  335|Elapsed Time: 0:00:03||
Episode 7|Iteration 336|reward: 2232.0|last_reward_at:  336|Elapsed Time: 0:00:03||
Episode 7|Iteration 339|reward: 2234.0|last_reward_at:  336|Elapsed Time: 0:00:03||
Episode 7|Iteration 339|reward: 2234.0|last_reward_at:  339|Elapsed Time: 0:00:03||
Episode 7|Iteration 345|reward: 2234.0|last_reward_at:  339|Elapsed Time: 0:00:03||
Episode 7|Iteration 347|reward: 2234.0|last_reward_at:  339|Elapsed Time: 0:00:03||
Episode 7|Iteration 349|reward: 2240.0|last_reward_at:  339|Elapsed Time: 0:00:03||
Episode 7|Iteration 349|reward: 2240.0|last_reward_at:  349|Elapsed Time: 0:00:03||
Episode 7|Iteration 351|reward: 2242.0|last_reward_at:  349|Elapsed Time: 0:00:03||
Episode 7|Iteration 351|reward: 2242.0|last_reward_at:  351|Elapsed Time: 0:00:03||
Episode 7|Iteration 357|reward: 2242.0|last_reward_at:  351|Elapsed Time: 0:00:03||
Episode 7|Iteration 360|reward: 2248.0|last_reward_at:  351|Elapsed Time: 0:00:04||
Episode 7|Iteration 360|reward: 2248.0|last_reward_at:  360|Elapsed Time: 0:00:04||
Episode 7|Iteration 365|reward: 2248.0|last_reward_at:  360|Elapsed Time: 0:00:04||
Episode 7|Iteration 371|reward: 2254.0|last_reward_at:  360|Elapsed Time: 0:00:04||
Episode 7|Iteration 371|reward: 2254.0|last_reward_at:  371|Elapsed Time: 0:00:04||
Episode 7|Iteration 374|reward: 2254.0|last_reward_at:  371|Elapsed Time: 0:00:04||
Episode 7|Iteration 380|reward: 2254.0|last_reward_at:  371|Elapsed Time: 0:00:04||
Episode 7|Iteration 387|reward: 2254.0|last_reward_at:  371|Elapsed Time: 0:00:04||
Episode 7|Iteration 389|reward: 2260.0|last_reward_at:  371|Elapsed Time: 0:00:04||
Episode 7|Iteration 389|reward: 2260.0|last_reward_at:  389|Elapsed Time: 0:00:04||
Episode 7|Iteration 395|reward: 2260.0|last_reward_at:  389|Elapsed Time: 0:00:04||
Episode 7|Iteration 397|reward: 2266.0|last_reward_at:  389|Elapsed Time: 0:00:04||
Episode 7|Iteration 397|reward: 2266.0|last_reward_at:  397|Elapsed Time: 0:00:04||
Episode 7|Iteration 403|reward: 2266.0|last_reward_at:  397|Elapsed Time: 0:00:04||
Episode 7|Iteration 410|reward: 2272.0|last_reward_at:  397|Elapsed Time: 0:00:04||
Episode 7|Iteration 410|reward: 2272.0|last_reward_at:  410|Elapsed Time: 0:00:04||
Episode 7|Iteration 411|reward: 2278.0|last_reward_at:  410|Elapsed Time: 0:00:04||
Episode 7|Iteration 411|reward: 2278.0|last_reward_at:  411|Elapsed Time: 0:00:04||
Episode 7|Iteration 418|reward: 2278.0|last_reward_at:  411|Elapsed Time: 0:00:04||
Episode 7|Iteration 419|reward: 2284.0|last_reward_at:  411|Elapsed Time: 0:00:04||
Episode 7|Iteration 419|reward: 2284.0|last_reward_at:  419|Elapsed Time: 0:00:04||
Episode 7|Iteration 426|reward: 2284.0|last_reward_at:  419|Elapsed Time: 0:00:04||
Episode 7|Iteration 428|reward: 2290.0|last_reward_at:  419|Elapsed Time: 0:00:05||
Episode 7|Iteration 428|reward: 2290.0|last_reward_at:  428|Elapsed Time: 0:00:05||
Episode 7|Iteration 433|reward: 2290.0|last_reward_at:  428|Elapsed Time: 0:00:05||
Episode 7|Iteration 441|reward: 2290.0|last_reward_at:  428|Elapsed Time: 0:00:05||
Episode 7|Iteration 446|reward: 2290.0|last_reward_at:  428|Elapsed Time: 0:00:05||
Episode 7|Iteration 454|reward: 2290.0|last_reward_at:  428|Elapsed Time: 0:00:05||
Episode 7|Iteration 457|reward: 2296.0|last_reward_at:  428|Elapsed Time: 0:00:05||
Episode 7|Iteration 457|reward: 2296.0|last_reward_at:  457|Elapsed Time: 0:00:05||
Episode 7|Iteration 464|reward: 2296.0|last_reward_at:  457|Elapsed Time: 0:00:05||
Episode 7|Iteration 471|reward: 2296.0|last_reward_at:  457|Elapsed Time: 0:00:05||
Episode 7|Iteration 479|reward: 2296.0|last_reward_at:  457|Elapsed Time: 0:00:05||
Episode 7|Iteration 487|reward: 2296.0|last_reward_at:  457|Elapsed Time: 0:00:05||
Episode 7|Iteration 489|reward: 2296.0|last_reward_at:  457|Elapsed Time: 0:00:06||
Episode 7|Iteration 494|reward: 2296.0|last_reward_at:  457|Elapsed Time: 0:00:06||
Episode 7|Iteration 502|reward: 2296.0|last_reward_at:  457|Elapsed Time: 0:00:06||
Episode 7|Iteration 509|reward: 2296.0|last_reward_at:  457|Elapsed Time: 0:00:06||
Episode 7|Iteration 516|reward: 2296.0|last_reward_at:  457|Elapsed Time: 0:00:06||
Episode 7|Iteration 524|reward: 2296.0|last_reward_at:  457|Elapsed Time: 0:00:06||
Episode 7|Iteration 531|reward: 2296.0|last_reward_at:  457|Elapsed Time: 0:00:06||
Episode 7|Iteration 539|reward: 2296.0|last_reward_at:  457|Elapsed Time: 0:00:06||
Episode 7|Iteration 547|reward: 2296.0|last_reward_at:  457|Elapsed Time: 0:00:06||
Episode 7|Iteration 554|reward: 2296.0|last_reward_at:  457|Elapsed Time: 0:00:06||
Episode 7|Iteration 562|reward: 2296.0|last_reward_at:  457|Elapsed Time: 0:00:06||
Episode 7|Iteration 570|reward: 2296.0|last_reward_at:  457|Elapsed Time: 0:00:07||
Episode 7|Iteration 577|reward: 2296.0|last_reward_at:  457|Elapsed Time: 0:00:07||
Episode 7|Iteration 585|reward: 2296.0|last_reward_at:  457|Elapsed Time: 0:00:07||
Episode 7|Iteration 590|reward: 2296.0|last_reward_at:  457|Elapsed Time: 0:00:07||
Episode 7|Iteration 598|reward: 2296.0|last_reward_at:  457|Elapsed Time: 0:00:07||
Episode 7|Iteration 600|reward: 2296.0|last_reward_at:  457|Elapsed Time: 0:00:07||

  Episode 7 stopped at t=600
  Breakdown [Reward/NoReward (Success rate)]
    explore-local: 1/5 (0.17)
    explore-remote: 0/10 (0.00)
    explore-connect: 0/10 (0.00)
    exploit-local: 20/156 (0.11)
    exploit-remote: 20/355 (0.05)
    exploit-connect: 11/12 (0.48)
  exploit deflected to exploration: 26

,status,properties,local_attacks,remote_attacks
id,,,,
start,owned,[],[ScanExplorerRecentFiles],[]
1_LinuxNode,owned,"[MySql, Ubuntu, nginx/1.10.3]","[SudoAttempt, ScanExplorerRecentFiles, ScanBas...","[ProbeWindows, ProbeLinux]"
2_WindowsNode,owned,"[Windows, Win10, Win10Patched]","[ScanExplorerRecentFiles, SudoAttempt, CrackKe...","[ProbeWindows, ProbeLinux]"
3_LinuxNode,owned,"[MySql, Ubuntu, nginx/1.10.3]","[SudoAttempt, ScanExplorerRecentFiles, ScanBas...","[ProbeWindows, ProbeLinux]"
4_WindowsNode,owned,"[Windows, Win10, Win10Patched]","[ScanExplorerRecentFiles, SudoAttempt, CrackKe...","[ProbeWindows, ProbeLinux]"
5_LinuxNode,owned,"[MySql, Ubuntu, nginx/1.10.3]","[SudoAttempt, ScanExplorerRecentFiles, ScanBas...","[ProbeWindows, ProbeLinux]"
6_WindowsNode,owned,"[Windows, Win10, Win10Patched]","[ScanExplorerRecentFiles, SudoAttempt, CrackKe...","[ProbeWindows, ProbeLinux]"
7_LinuxNode,owned,"[MySql, Ubuntu, nginx/1.10.3]","[SudoAttempt, ScanExplorerRecentFiles, ScanBas...","[ProbeWindows, ProbeLinux]"
8_WindowsNode,owned,"[Windows, Win10, Win10Patched]","[ScanExplorerRecentFiles, SudoAttempt, CrackKe...","[ProbeWindows, ProbeLinux]"
9_LinuxNode,owned,"[MySql, Ubuntu, nginx/1.10.3]","[SudoAttempt, ScanExplorerRecentFiles, ScanBas...","[ProbeWindows, ProbeLinux]"
10_WindowsNode,owned,"[Windows, Win10, Win10Patched]","[ScanExplorerRecentFiles, SudoAttempt, CrackKe...","[ProbeWindows, ProbeLinux]"
11_LinuxNode,owned,"[MySql, Ubuntu, nginx/1.10.3, FLAG:Linux]",[],[]

  ## Episode: 8/10 'Exploiting DQL' ϵ=0.0000, γ=0.15, lr=0.01, replaymemory=10000,
batch=256, target_update=5

Episode 8|Iteration 0|reward: ------|last_reward_at: ----|Elapsed Time: 0:00:00||
Episode 8|Iteration 1|reward:   14.0|last_reward_at: ----|Elapsed Time: 0:00:00||
Episode 8|Iteration 1|reward:   14.0|last_reward_at:    1|Elapsed Time: 0:00:00||
Episode 8|Iteration 2|reward:   16.0|last_reward_at:    1|Elapsed Time: 0:00:00||
Episode 8|Iteration 2|reward:   16.0|last_reward_at:    2|Elapsed Time: 0:00:00||
Episode 8|Iteration 4|reward:  116.0|last_reward_at:    2|Elapsed Time: 0:00:00||
Episode 8|Iteration 4|reward:  116.0|last_reward_at:    4|Elapsed Time: 0:00:00||
Episode 8|Iteration 5|reward:  130.0|last_reward_at:    4|Elapsed Time: 0:00:00||
Episode 8|Iteration 5|reward:  130.0|last_reward_at:    5|Elapsed Time: 0:00:00||
Episode 8|Iteration 7|reward:  230.0|last_reward_at:    5|Elapsed Time: 0:00:00||
Episode 8|Iteration 7|reward:  230.0|last_reward_at:    7|Elapsed Time: 0:00:00||
Episode 8|Iteration 8|reward:  244.0|last_reward_at:    7|Elapsed Time: 0:00:00||
Episode 8|Iteration 8|reward:  244.0|last_reward_at:    8|Elapsed Time: 0:00:00||
Episode 8|Iteration 9|reward:  344.0|last_reward_at:    8|Elapsed Time: 0:00:00||
Episode 8|Iteration 9|reward:  344.0|last_reward_at:    9|Elapsed Time: 0:00:00||
Episode 8|Iteration 10|reward:  358.0|last_reward_at:    9|Elapsed Time: 0:00:00||
Episode 8|Iteration 10|reward:  358.0|last_reward_at:   10|Elapsed Time: 0:00:00||
Episode 8|Iteration 12|reward:  458.0|last_reward_at:   10|Elapsed Time: 0:00:00||
Episode 8|Iteration 12|reward:  458.0|last_reward_at:   12|Elapsed Time: 0:00:00||
Episode 8|Iteration 13|reward:  472.0|last_reward_at:   12|Elapsed Time: 0:00:00||
Episode 8|Iteration 13|reward:  472.0|last_reward_at:   13|Elapsed Time: 0:00:00||
Episode 8|Iteration 14|reward:  572.0|last_reward_at:   13|Elapsed Time: 0:00:00||
Episode 8|Iteration 14|reward:  572.0|last_reward_at:   14|Elapsed Time: 0:00:00||
Episode 8|Iteration 15|reward:  586.0|last_reward_at:   14|Elapsed Time: 0:00:00||
Episode 8|Iteration 15|reward:  586.0|last_reward_at:   15|Elapsed Time: 0:00:00||
Episode 8|Iteration 17|reward:  686.0|last_reward_at:   15|Elapsed Time: 0:00:00||
Episode 8|Iteration 17|reward:  686.0|last_reward_at:   17|Elapsed Time: 0:00:00||
Episode 8|Iteration 18|reward:  700.0|last_reward_at:   17|Elapsed Time: 0:00:00||
Episode 8|Iteration 18|reward:  700.0|last_reward_at:   18|Elapsed Time: 0:00:00||
Episode 8|Iteration 19|reward:  800.0|last_reward_at:   18|Elapsed Time: 0:00:00||
Episode 8|Iteration 19|reward:  800.0|last_reward_at:   19|Elapsed Time: 0:00:00||
Episode 8|Iteration 20|reward:  814.0|last_reward_at:   19|Elapsed Time: 0:00:00||
Episode 8|Iteration 20|reward:  814.0|last_reward_at:   20|Elapsed Time: 0:00:00||
Episode 8|Iteration 22|reward:  914.0|last_reward_at:   20|Elapsed Time: 0:00:00||
Episode 8|Iteration 22|reward:  914.0|last_reward_at:   22|Elapsed Time: 0:00:00||
Episode 8|Iteration 23|reward:  928.0|last_reward_at:   22|Elapsed Time: 0:00:00||
Episode 8|Iteration 23|reward:  928.0|last_reward_at:   23|Elapsed Time: 0:00:00||
Episode 8|Iteration 24|reward: 1028.0|last_reward_at:   23|Elapsed Time: 0:00:00||
Episode 8|Iteration 24|reward: 1028.0|last_reward_at:   24|Elapsed Time: 0:00:00||
Episode 8|Iteration 25|reward: 1042.0|last_reward_at:   24|Elapsed Time: 0:00:00||
Episode 8|Iteration 25|reward: 1042.0|last_reward_at:   25|Elapsed Time: 0:00:00||
Episode 8|Iteration 27|reward: 1142.0|last_reward_at:   25|Elapsed Time: 0:00:00||
Episode 8|Iteration 27|reward: 1142.0|last_reward_at:   27|Elapsed Time: 0:00:00||
Episode 8|Iteration 28|reward: 1156.0|last_reward_at:   27|Elapsed Time: 0:00:00||
Episode 8|Iteration 28|reward: 1156.0|last_reward_at:   28|Elapsed Time: 0:00:00||
Episode 8|Iteration 29|reward: 2156.0|last_reward_at:   28|Elapsed Time: 0:00:00||
Episode 8|Iteration 29|reward: 2156.0|last_reward_at:   29|Elapsed Time: 0:00:00||
Episode 8|Iteration 30|reward: 2162.0|last_reward_at:   29|Elapsed Time: 0:00:00||
Episode 8|Iteration 30|reward: 2162.0|last_reward_at:   30|Elapsed Time: 0:00:00||
Episode 8|Iteration 31|reward: 2168.0|last_reward_at:   30|Elapsed Time: 0:00:00||
Episode 8|Iteration 31|reward: 2168.0|last_reward_at:   31|Elapsed Time: 0:00:00||
Episode 8|Iteration 33|reward: 2174.0|last_reward_at:   31|Elapsed Time: 0:00:00||
Episode 8|Iteration 33|reward: 2174.0|last_reward_at:   33|Elapsed Time: 0:00:00||
Episode 8|Iteration 36|reward: 2176.0|last_reward_at:   33|Elapsed Time: 0:00:00||
Episode 8|Iteration 36|reward: 2176.0|last_reward_at:   36|Elapsed Time: 0:00:00||
Episode 8|Iteration 39|reward: 2182.0|last_reward_at:   36|Elapsed Time: 0:00:00||
Episode 8|Iteration 39|reward: 2182.0|last_reward_at:   39|Elapsed Time: 0:00:00||
Episode 8|Iteration 43|reward: 2188.0|last_reward_at:   39|Elapsed Time: 0:00:00||
Episode 8|Iteration 43|reward: 2188.0|last_reward_at:   43|Elapsed Time: 0:00:00||
Episode 8|Iteration 44|reward: 2190.0|last_reward_at:   43|Elapsed Time: 0:00:00||
Episode 8|Iteration 44|reward: 2190.0|last_reward_at:   44|Elapsed Time: 0:00:00||
Episode 8|Iteration 46|reward: 2192.0|last_reward_at:   44|Elapsed Time: 0:00:00||
Episode 8|Iteration 46|reward: 2192.0|last_reward_at:   46|Elapsed Time: 0:00:00||
Episode 8|Iteration 48|reward: 2194.0|last_reward_at:   46|Elapsed Time: 0:00:00||
Episode 8|Iteration 48|reward: 2194.0|last_reward_at:   48|Elapsed Time: 0:00:00||
Episode 8|Iteration 49|reward: 2200.0|last_reward_at:   48|Elapsed Time: 0:00:00||
Episode 8|Iteration 49|reward: 2200.0|last_reward_at:   49|Elapsed Time: 0:00:00||
Episode 8|Iteration 51|reward: 2206.0|last_reward_at:   49|Elapsed Time: 0:00:00||
Episode 8|Iteration 51|reward: 2206.0|last_reward_at:   51|Elapsed Time: 0:00:00||
Episode 8|Iteration 52|reward: 2212.0|last_reward_at:   51|Elapsed Time: 0:00:00||
Episode 8|Iteration 52|reward: 2212.0|last_reward_at:   52|Elapsed Time: 0:00:00||
Episode 8|Iteration 53|reward: 2214.0|last_reward_at:   52|Elapsed Time: 0:00:00||
Episode 8|Iteration 53|reward: 2214.0|last_reward_at:   53|Elapsed Time: 0:00:00||
Episode 8|Iteration 54|reward: 2220.0|last_reward_at:   53|Elapsed Time: 0:00:00||
Episode 8|Iteration 54|reward: 2220.0|last_reward_at:   54|Elapsed Time: 0:00:00||
Episode 8|Iteration 59|reward: 2226.0|last_reward_at:   54|Elapsed Time: 0:00:00||
Episode 8|Iteration 59|reward: 2226.0|last_reward_at:   59|Elapsed Time: 0:00:00||
Episode 8|Iteration 61|reward: 2232.0|last_reward_at:   59|Elapsed Time: 0:00:01||
Episode 8|Iteration 61|reward: 2232.0|last_reward_at:   61|Elapsed Time: 0:00:01||
Episode 8|Iteration 69|reward: 2232.0|last_reward_at:   61|Elapsed Time: 0:00:01||
Episode 8|Iteration 76|reward: 2232.0|last_reward_at:   61|Elapsed Time: 0:00:01||
Episode 8|Iteration 76|reward: 2238.0|last_reward_at:   61|Elapsed Time: 0:00:01||
Episode 8|Iteration 76|reward: 2238.0|last_reward_at:   76|Elapsed Time: 0:00:01||
Episode 8|Iteration 83|reward: 2240.0|last_reward_at:   76|Elapsed Time: 0:00:01||
Episode 8|Iteration 83|reward: 2240.0|last_reward_at:   83|Elapsed Time: 0:00:01||
Episode 8|Iteration 86|reward: 2246.0|last_reward_at:   83|Elapsed Time: 0:00:01||
Episode 8|Iteration 86|reward: 2246.0|last_reward_at:   86|Elapsed Time: 0:00:01||
Episode 8|Iteration 89|reward: 2252.0|last_reward_at:   86|Elapsed Time: 0:00:01||
Episode 8|Iteration 89|reward: 2252.0|last_reward_at:   89|Elapsed Time: 0:00:01||
Episode 8|Iteration 96|reward: 2252.0|last_reward_at:   89|Elapsed Time: 0:00:01||
Episode 8|Iteration 100|reward: 2258.0|last_reward_at:   89|Elapsed Time: 0:00:01||
Episode 8|Iteration 100|reward: 2258.0|last_reward_at:  100|Elapsed Time: 0:00:01||
Episode 8|Iteration 103|reward: 2258.0|last_reward_at:  100|Elapsed Time: 0:00:01||
Episode 8|Iteration 105|reward: 2258.0|last_reward_at:  100|Elapsed Time: 0:00:01||
Episode 8|Iteration 107|reward: 2258.0|last_reward_at:  100|Elapsed Time: 0:00:01||
Episode 8|Iteration 109|reward: 2260.0|last_reward_at:  100|Elapsed Time: 0:00:01||
Episode 8|Iteration 109|reward: 2260.0|last_reward_at:  109|Elapsed Time: 0:00:01||
Episode 8|Iteration 110|reward: 2262.0|last_reward_at:  109|Elapsed Time: 0:00:01||
Episode 8|Iteration 110|reward: 2262.0|last_reward_at:  110|Elapsed Time: 0:00:01||
Episode 8|Iteration 118|reward: 2262.0|last_reward_at:  110|Elapsed Time: 0:00:02||
Episode 8|Iteration 121|reward: 2268.0|last_reward_at:  110|Elapsed Time: 0:00:02||
Episode 8|Iteration 121|reward: 2268.0|last_reward_at:  121|Elapsed Time: 0:00:02||
Episode 8|Iteration 124|reward: 2274.0|last_reward_at:  121|Elapsed Time: 0:00:02||
Episode 8|Iteration 124|reward: 2274.0|last_reward_at:  124|Elapsed Time: 0:00:02||
Episode 8|Iteration 128|reward: 2280.0|last_reward_at:  124|Elapsed Time: 0:00:02||
Episode 8|Iteration 128|reward: 2280.0|last_reward_at:  128|Elapsed Time: 0:00:02||
Episode 8|Iteration 131|reward: 2282.0|last_reward_at:  128|Elapsed Time: 0:00:02||
Episode 8|Iteration 131|reward: 2282.0|last_reward_at:  131|Elapsed Time: 0:00:02||
Episode 8|Iteration 137|reward: 2282.0|last_reward_at:  131|Elapsed Time: 0:00:02||
Episode 8|Iteration 144|reward: 2282.0|last_reward_at:  131|Elapsed Time: 0:00:02||
Episode 8|Iteration 147|reward: 2288.0|last_reward_at:  131|Elapsed Time: 0:00:02||
Episode 8|Iteration 147|reward: 2288.0|last_reward_at:  147|Elapsed Time: 0:00:02||
Episode 8|Iteration 152|reward: 2288.0|last_reward_at:  147|Elapsed Time: 0:00:02||
Episode 8|Iteration 159|reward: 2288.0|last_reward_at:  147|Elapsed Time: 0:00:02||
Episode 8|Iteration 167|reward: 2288.0|last_reward_at:  147|Elapsed Time: 0:00:02||
Episode 8|Iteration 170|reward: 2294.0|last_reward_at:  147|Elapsed Time: 0:00:02||
Episode 8|Iteration 170|reward: 2294.0|last_reward_at:  170|Elapsed Time: 0:00:02||
Episode 8|Iteration 175|reward: 2294.0|last_reward_at:  170|Elapsed Time: 0:00:02||
Episode 8|Iteration 181|reward: 2294.0|last_reward_at:  170|Elapsed Time: 0:00:02||
Episode 8|Iteration 189|reward: 2294.0|last_reward_at:  170|Elapsed Time: 0:00:03||
Episode 8|Iteration 197|reward: 2294.0|last_reward_at:  170|Elapsed Time: 0:00:03||
Episode 8|Iteration 206|reward: 2294.0|last_reward_at:  170|Elapsed Time: 0:00:03||
Episode 8|Iteration 213|reward: 2294.0|last_reward_at:  170|Elapsed Time: 0:00:03||
Episode 8|Iteration 220|reward: 2294.0|last_reward_at:  170|Elapsed Time: 0:00:03||
Episode 8|Iteration 227|reward: 2294.0|last_reward_at:  170|Elapsed Time: 0:00:03||
Episode 8|Iteration 235|reward: 2294.0|last_reward_at:  170|Elapsed Time: 0:00:03||
Episode 8|Iteration 244|reward: 2294.0|last_reward_at:  170|Elapsed Time: 0:00:03||
Episode 8|Iteration 247|reward: 2294.0|last_reward_at:  170|Elapsed Time: 0:00:03||
Episode 8|Iteration 255|reward: 2294.0|last_reward_at:  170|Elapsed Time: 0:00:03||
Episode 8|Iteration 261|reward: 2294.0|last_reward_at:  170|Elapsed Time: 0:00:04||
Episode 8|Iteration 266|reward: 2294.0|last_reward_at:  170|Elapsed Time: 0:00:04||
Episode 8|Iteration 273|reward: 2294.0|last_reward_at:  170|Elapsed Time: 0:00:04||
Episode 8|Iteration 282|reward: 2294.0|last_reward_at:  170|Elapsed Time: 0:00:04||
Episode 8|Iteration 289|reward: 2294.0|last_reward_at:  170|Elapsed Time: 0:00:04||
Episode 8|Iteration 291|reward: 2294.0|last_reward_at:  170|Elapsed Time: 0:00:04||
Episode 8|Iteration 297|reward: 2294.0|last_reward_at:  170|Elapsed Time: 0:00:04||
Episode 8|Iteration 300|reward: 2294.0|last_reward_at:  170|Elapsed Time: 0:00:04||
Episode 8|Iteration 305|reward: 2294.0|last_reward_at:  170|Elapsed Time: 0:00:04||
Episode 8|Iteration 312|reward: 2294.0|last_reward_at:  170|Elapsed Time: 0:00:04||
Episode 8|Iteration 319|reward: 2294.0|last_reward_at:  170|Elapsed Time: 0:00:05||
Episode 8|Iteration 327|reward: 2294.0|last_reward_at:  170|Elapsed Time: 0:00:05||
Episode 8|Iteration 335|reward: 2294.0|last_reward_at:  170|Elapsed Time: 0:00:05||
Episode 8|Iteration 342|reward: 2294.0|last_reward_at:  170|Elapsed Time: 0:00:05||
Episode 8|Iteration 349|reward: 2294.0|last_reward_at:  170|Elapsed Time: 0:00:05||
Episode 8|Iteration 357|reward: 2294.0|last_reward_at:  170|Elapsed Time: 0:00:05||
Episode 8|Iteration 364|reward: 2294.0|last_reward_at:  170|Elapsed Time: 0:00:05||
Episode 8|Iteration 371|reward: 2294.0|last_reward_at:  170|Elapsed Time: 0:00:05||
Episode 8|Iteration 373|reward: 2294.0|last_reward_at:  170|Elapsed Time: 0:00:05||
Episode 8|Iteration 376|reward: 2294.0|last_reward_at:  170|Elapsed Time: 0:00:05||
Episode 8|Iteration 384|reward: 2294.0|last_reward_at:  170|Elapsed Time: 0:00:06||
Episode 8|Iteration 388|reward: 2294.0|last_reward_at:  170|Elapsed Time: 0:00:06||
Episode 8|Iteration 395|reward: 2294.0|last_reward_at:  170|Elapsed Time: 0:00:06||
Episode 8|Iteration 401|reward: 2294.0|last_reward_at:  170|Elapsed Time: 0:00:06||
Episode 8|Iteration 403|reward: 2294.0|last_reward_at:  170|Elapsed Time: 0:00:06||
Episode 8|Iteration 410|reward: 2294.0|last_reward_at:  170|Elapsed Time: 0:00:06||
Episode 8|Iteration 418|reward: 2294.0|last_reward_at:  170|Elapsed Time: 0:00:06||
Episode 8|Iteration 425|reward: 2294.0|last_reward_at:  170|Elapsed Time: 0:00:06||
Episode 8|Iteration 433|reward: 2294.0|last_reward_at:  170|Elapsed Time: 0:00:06||
Episode 8|Iteration 440|reward: 2294.0|last_reward_at:  170|Elapsed Time: 0:00:06||
Episode 8|Iteration 449|reward: 2294.0|last_reward_at:  170|Elapsed Time: 0:00:06||
Episode 8|Iteration 451|reward: 2294.0|last_reward_at:  170|Elapsed Time: 0:00:07||
Episode 8|Iteration 456|reward: 2294.0|last_reward_at:  170|Elapsed Time: 0:00:07||
Episode 8|Iteration 457|reward: 2294.0|last_reward_at:  170|Elapsed Time: 0:00:07||
Episode 8|Iteration 464|reward: 2294.0|last_reward_at:  170|Elapsed Time: 0:00:07||
Episode 8|Iteration 471|reward: 2294.0|last_reward_at:  170|Elapsed Time: 0:00:07||
Episode 8|Iteration 478|reward: 2294.0|last_reward_at:  170|Elapsed Time: 0:00:07||
Episode 8|Iteration 486|reward: 2294.0|last_reward_at:  170|Elapsed Time: 0:00:07||
Episode 8|Iteration 494|reward: 2294.0|last_reward_at:  170|Elapsed Time: 0:00:07||
Episode 8|Iteration 501|reward: 2294.0|last_reward_at:  170|Elapsed Time: 0:00:07||
Episode 8|Iteration 509|reward: 2294.0|last_reward_at:  170|Elapsed Time: 0:00:07||
Episode 8|Iteration 516|reward: 2294.0|last_reward_at:  170|Elapsed Time: 0:00:08||
Episode 8|Iteration 524|reward: 2294.0|last_reward_at:  170|Elapsed Time: 0:00:08||
Episode 8|Iteration 532|reward: 2294.0|last_reward_at:  170|Elapsed Time: 0:00:08||
Episode 8|Iteration 539|reward: 2294.0|last_reward_at:  170|Elapsed Time: 0:00:08||
Episode 8|Iteration 547|reward: 2294.0|last_reward_at:  170|Elapsed Time: 0:00:08||
Episode 8|Iteration 554|reward: 2294.0|last_reward_at:  170|Elapsed Time: 0:00:08||
Episode 8|Iteration 562|reward: 2294.0|last_reward_at:  170|Elapsed Time: 0:00:08||
Episode 8|Iteration 570|reward: 2294.0|last_reward_at:  170|Elapsed Time: 0:00:08||
Episode 8|Iteration 574|reward: 2294.0|last_reward_at:  170|Elapsed Time: 0:00:08||
Episode 8|Iteration 576|reward: 2294.0|last_reward_at:  170|Elapsed Time: 0:00:08||
Episode 8|Iteration 583|reward: 2294.0|last_reward_at:  170|Elapsed Time: 0:00:09||
Episode 8|Iteration 588|reward: 2294.0|last_reward_at:  170|Elapsed Time: 0:00:09||
Episode 8|Iteration 592|reward: 2294.0|last_reward_at:  170|Elapsed Time: 0:00:09||
Episode 8|Iteration 600|reward: 2294.0|last_reward_at:  170|Elapsed Time: 0:00:09||
Episode 8|Iteration 600|reward: 2294.0|last_reward_at:  170|Elapsed Time: 0:00:09||

  Episode 8 stopped at t=600
  Breakdown [Reward/NoReward (Success rate)]
    explore-local: 0/4 (0.00)
    explore-remote: 1/7 (0.12)
    explore-connect: 0/5 (0.00)
    exploit-local: 21/219 (0.09)
    exploit-remote: 19/313 (0.06)
    exploit-connect: 11/0 (1.00)
  exploit deflected to exploration: 17

,status,properties,local_attacks,remote_attacks
id,,,,
start,owned,[],[ScanExplorerRecentFiles],[]
1_LinuxNode,owned,"[MySql, Ubuntu, nginx/1.10.3]","[SudoAttempt, ScanExplorerRecentFiles, ScanBas...","[ProbeWindows, ProbeLinux]"
2_WindowsNode,owned,"[Windows, Win10, Win10Patched]","[ScanExplorerRecentFiles, SudoAttempt, CrackKe...","[ProbeWindows, ProbeLinux]"
3_LinuxNode,owned,"[MySql, Ubuntu, nginx/1.10.3]","[SudoAttempt, ScanExplorerRecentFiles, ScanBas...","[ProbeWindows, ProbeLinux]"
4_WindowsNode,owned,"[Windows, Win10, Win10Patched]","[ScanExplorerRecentFiles, SudoAttempt, CrackKe...","[ProbeWindows, ProbeLinux]"
5_LinuxNode,owned,"[MySql, Ubuntu, nginx/1.10.3]","[SudoAttempt, ScanExplorerRecentFiles, ScanBas...","[ProbeWindows, ProbeLinux]"
6_WindowsNode,owned,"[Windows, Win10, Win10Patched]","[ScanExplorerRecentFiles, SudoAttempt, CrackKe...","[ProbeWindows, ProbeLinux]"
7_LinuxNode,owned,"[MySql, Ubuntu, nginx/1.10.3]","[SudoAttempt, ScanExplorerRecentFiles, ScanBas...","[ProbeWindows, ProbeLinux]"
8_WindowsNode,owned,"[Windows, Win10, Win10Patched]","[ScanExplorerRecentFiles, SudoAttempt, CrackKe...","[ProbeWindows, ProbeLinux]"
9_LinuxNode,owned,"[MySql, Ubuntu, nginx/1.10.3]","[SudoAttempt, ScanExplorerRecentFiles, ScanBas...","[ProbeWindows, ProbeLinux]"
10_WindowsNode,owned,"[Windows, Win10, Win10Patched]","[ScanExplorerRecentFiles, SudoAttempt, CrackKe...","[ProbeWindows, ProbeLinux]"
11_LinuxNode,owned,"[MySql, Ubuntu, nginx/1.10.3, FLAG:Linux]",[],[]

  ## Episode: 9/10 'Exploiting DQL' ϵ=0.0000, γ=0.15, lr=0.01, replaymemory=10000,
batch=256, target_update=5

Episode 9|Iteration 0|reward: ------|last_reward_at: ----|Elapsed Time: 0:00:00||
Episode 9|Iteration 1|reward:   14.0|last_reward_at: ----|Elapsed Time: 0:00:00||
Episode 9|Iteration 1|reward:   14.0|last_reward_at:    1|Elapsed Time: 0:00:00||
Episode 9|Iteration 2|reward:   16.0|last_reward_at:    1|Elapsed Time: 0:00:00||
Episode 9|Iteration 2|reward:   16.0|last_reward_at:    2|Elapsed Time: 0:00:00||
Episode 9|Iteration 4|reward:   20.0|last_reward_at:    2|Elapsed Time: 0:00:00||
Episode 9|Iteration 4|reward:   20.0|last_reward_at:    4|Elapsed Time: 0:00:00||
Episode 9|Iteration 16|reward:   20.0|last_reward_at:    4|Elapsed Time: 0:00:00||
Episode 9|Iteration 23|reward:   20.0|last_reward_at:    4|Elapsed Time: 0:00:00||
Episode 9|Iteration 31|reward:   20.0|last_reward_at:    4|Elapsed Time: 0:00:00||
Episode 9|Iteration 38|reward:   20.0|last_reward_at:    4|Elapsed Time: 0:00:00||
Episode 9|Iteration 46|reward:   20.0|last_reward_at:    4|Elapsed Time: 0:00:00||
Episode 9|Iteration 54|reward:   20.0|last_reward_at:    4|Elapsed Time: 0:00:00||
Episode 9|Iteration 61|reward:   20.0|last_reward_at:    4|Elapsed Time: 0:00:00||
Episode 9|Iteration 64|reward:  120.0|last_reward_at:    4|Elapsed Time: 0:00:00||
Episode 9|Iteration 64|reward:  120.0|last_reward_at:   64|Elapsed Time: 0:00:00||
Episode 9|Iteration 65|reward:  134.0|last_reward_at:   64|Elapsed Time: 0:00:00||
Episode 9|Iteration 65|reward:  134.0|last_reward_at:   65|Elapsed Time: 0:00:00||
Episode 9|Iteration 67|reward:  234.0|last_reward_at:   65|Elapsed Time: 0:00:00||
Episode 9|Iteration 67|reward:  234.0|last_reward_at:   67|Elapsed Time: 0:00:00||
Episode 9|Iteration 68|reward:  248.0|last_reward_at:   67|Elapsed Time: 0:00:00||
Episode 9|Iteration 68|reward:  248.0|last_reward_at:   68|Elapsed Time: 0:00:00||
Episode 9|Iteration 69|reward:  348.0|last_reward_at:   68|Elapsed Time: 0:00:00||
Episode 9|Iteration 69|reward:  348.0|last_reward_at:   69|Elapsed Time: 0:00:00||
Episode 9|Iteration 70|reward:  362.0|last_reward_at:   69|Elapsed Time: 0:00:00||
Episode 9|Iteration 70|reward:  362.0|last_reward_at:   70|Elapsed Time: 0:00:00||
Episode 9|Iteration 72|reward:  462.0|last_reward_at:   70|Elapsed Time: 0:00:00||
Episode 9|Iteration 72|reward:  462.0|last_reward_at:   72|Elapsed Time: 0:00:00||
Episode 9|Iteration 73|reward:  476.0|last_reward_at:   72|Elapsed Time: 0:00:00||
Episode 9|Iteration 73|reward:  476.0|last_reward_at:   73|Elapsed Time: 0:00:00||
Episode 9|Iteration 74|reward:  576.0|last_reward_at:   73|Elapsed Time: 0:00:00||
Episode 9|Iteration 74|reward:  576.0|last_reward_at:   74|Elapsed Time: 0:00:00||
Episode 9|Iteration 75|reward:  590.0|last_reward_at:   74|Elapsed Time: 0:00:00||
Episode 9|Iteration 75|reward:  590.0|last_reward_at:   75|Elapsed Time: 0:00:00||
Episode 9|Iteration 77|reward:  690.0|last_reward_at:   75|Elapsed Time: 0:00:00||
Episode 9|Iteration 77|reward:  690.0|last_reward_at:   77|Elapsed Time: 0:00:00||
Episode 9|Iteration 78|reward:  704.0|last_reward_at:   77|Elapsed Time: 0:00:00||
Episode 9|Iteration 78|reward:  704.0|last_reward_at:   78|Elapsed Time: 0:00:00||
Episode 9|Iteration 79|reward:  804.0|last_reward_at:   78|Elapsed Time: 0:00:00||
Episode 9|Iteration 79|reward:  804.0|last_reward_at:   79|Elapsed Time: 0:00:00||
Episode 9|Iteration 80|reward:  818.0|last_reward_at:   79|Elapsed Time: 0:00:00||
Episode 9|Iteration 80|reward:  818.0|last_reward_at:   80|Elapsed Time: 0:00:00||
Episode 9|Iteration 82|reward:  918.0|last_reward_at:   80|Elapsed Time: 0:00:00||
Episode 9|Iteration 82|reward:  918.0|last_reward_at:   82|Elapsed Time: 0:00:00||
Episode 9|Iteration 83|reward:  932.0|last_reward_at:   82|Elapsed Time: 0:00:00||
Episode 9|Iteration 83|reward:  932.0|last_reward_at:   83|Elapsed Time: 0:00:00||
Episode 9|Iteration 84|reward: 1032.0|last_reward_at:   83|Elapsed Time: 0:00:00||
Episode 9|Iteration 84|reward: 1032.0|last_reward_at:   84|Elapsed Time: 0:00:00||
Episode 9|Iteration 85|reward: 1046.0|last_reward_at:   84|Elapsed Time: 0:00:00||
Episode 9|Iteration 85|reward: 1046.0|last_reward_at:   85|Elapsed Time: 0:00:00||
Episode 9|Iteration 87|reward: 1146.0|last_reward_at:   85|Elapsed Time: 0:00:00||
Episode 9|Iteration 87|reward: 1146.0|last_reward_at:   87|Elapsed Time: 0:00:00||
Episode 9|Iteration 88|reward: 1160.0|last_reward_at:   87|Elapsed Time: 0:00:00||
Episode 9|Iteration 88|reward: 1160.0|last_reward_at:   88|Elapsed Time: 0:00:00||
Episode 9|Iteration 89|reward: 2160.0|last_reward_at:   88|Elapsed Time: 0:00:00||
Episode 9|Iteration 89|reward: 2160.0|last_reward_at:   89|Elapsed Time: 0:00:00||
Episode 9|Iteration 91|reward: 2166.0|last_reward_at:   89|Elapsed Time: 0:00:00||
Episode 9|Iteration 91|reward: 2166.0|last_reward_at:   91|Elapsed Time: 0:00:00||
Episode 9|Iteration 92|reward: 2172.0|last_reward_at:   91|Elapsed Time: 0:00:01||
Episode 9|Iteration 92|reward: 2172.0|last_reward_at:   92|Elapsed Time: 0:00:01||
Episode 9|Iteration 95|reward: 2174.0|last_reward_at:   92|Elapsed Time: 0:00:01||
Episode 9|Iteration 95|reward: 2174.0|last_reward_at:   95|Elapsed Time: 0:00:01||
Episode 9|Iteration 96|reward: 2176.0|last_reward_at:   95|Elapsed Time: 0:00:01||
Episode 9|Iteration 96|reward: 2176.0|last_reward_at:   96|Elapsed Time: 0:00:01||
Episode 9|Iteration 97|reward: 2178.0|last_reward_at:   96|Elapsed Time: 0:00:01||
Episode 9|Iteration 97|reward: 2178.0|last_reward_at:   97|Elapsed Time: 0:00:01||
Episode 9|Iteration 98|reward: 2184.0|last_reward_at:   97|Elapsed Time: 0:00:01||
Episode 9|Iteration 98|reward: 2184.0|last_reward_at:   98|Elapsed Time: 0:00:01||
Episode 9|Iteration 101|reward: 2190.0|last_reward_at:   98|Elapsed Time: 0:00:01||
Episode 9|Iteration 101|reward: 2190.0|last_reward_at:  101|Elapsed Time: 0:00:01||
Episode 9|Iteration 103|reward: 2192.0|last_reward_at:  101|Elapsed Time: 0:00:01||
Episode 9|Iteration 103|reward: 2192.0|last_reward_at:  103|Elapsed Time: 0:00:01||
Episode 9|Iteration 104|reward: 2198.0|last_reward_at:  103|Elapsed Time: 0:00:01||
Episode 9|Iteration 104|reward: 2198.0|last_reward_at:  104|Elapsed Time: 0:00:01||
Episode 9|Iteration 109|reward: 2204.0|last_reward_at:  104|Elapsed Time: 0:00:01||
Episode 9|Iteration 109|reward: 2204.0|last_reward_at:  109|Elapsed Time: 0:00:01||
Episode 9|Iteration 110|reward: 2210.0|last_reward_at:  109|Elapsed Time: 0:00:01||
Episode 9|Iteration 110|reward: 2210.0|last_reward_at:  110|Elapsed Time: 0:00:01||
Episode 9|Iteration 112|reward: 2212.0|last_reward_at:  110|Elapsed Time: 0:00:01||
Episode 9|Iteration 112|reward: 2212.0|last_reward_at:  112|Elapsed Time: 0:00:01||
Episode 9|Iteration 113|reward: 2218.0|last_reward_at:  112|Elapsed Time: 0:00:01||
Episode 9|Iteration 113|reward: 2218.0|last_reward_at:  113|Elapsed Time: 0:00:01||
Episode 9|Iteration 118|reward: 2224.0|last_reward_at:  113|Elapsed Time: 0:00:01||
Episode 9|Iteration 118|reward: 2224.0|last_reward_at:  118|Elapsed Time: 0:00:01||
Episode 9|Iteration 121|reward: 2226.0|last_reward_at:  118|Elapsed Time: 0:00:01||
Episode 9|Iteration 121|reward: 2226.0|last_reward_at:  121|Elapsed Time: 0:00:01||
Episode 9|Iteration 125|reward: 2228.0|last_reward_at:  121|Elapsed Time: 0:00:01||
Episode 9|Iteration 125|reward: 2228.0|last_reward_at:  125|Elapsed Time: 0:00:01||
Episode 9|Iteration 130|reward: 2228.0|last_reward_at:  125|Elapsed Time: 0:00:01||
Episode 9|Iteration 137|reward: 2228.0|last_reward_at:  125|Elapsed Time: 0:00:01||
Episode 9|Iteration 143|reward: 2234.0|last_reward_at:  125|Elapsed Time: 0:00:01||
Episode 9|Iteration 143|reward: 2234.0|last_reward_at:  143|Elapsed Time: 0:00:01||
Episode 9|Iteration 151|reward: 2234.0|last_reward_at:  143|Elapsed Time: 0:00:01||
Episode 9|Iteration 154|reward: 2240.0|last_reward_at:  143|Elapsed Time: 0:00:01||
Episode 9|Iteration 154|reward: 2240.0|last_reward_at:  154|Elapsed Time: 0:00:01||
Episode 9|Iteration 155|reward: 2246.0|last_reward_at:  154|Elapsed Time: 0:00:01||
Episode 9|Iteration 155|reward: 2246.0|last_reward_at:  155|Elapsed Time: 0:00:01||
Episode 9|Iteration 158|reward: 2252.0|last_reward_at:  155|Elapsed Time: 0:00:01||
Episode 9|Iteration 158|reward: 2252.0|last_reward_at:  158|Elapsed Time: 0:00:01||
Episode 9|Iteration 163|reward: 2258.0|last_reward_at:  158|Elapsed Time: 0:00:02||
Episode 9|Iteration 163|reward: 2258.0|last_reward_at:  163|Elapsed Time: 0:00:02||
Episode 9|Iteration 168|reward: 2258.0|last_reward_at:  163|Elapsed Time: 0:00:02||
Episode 9|Iteration 170|reward: 2258.0|last_reward_at:  163|Elapsed Time: 0:00:02||
Episode 9|Iteration 175|reward: 2258.0|last_reward_at:  163|Elapsed Time: 0:00:02||
Episode 9|Iteration 177|reward: 2264.0|last_reward_at:  163|Elapsed Time: 0:00:02||
Episode 9|Iteration 177|reward: 2264.0|last_reward_at:  177|Elapsed Time: 0:00:02||
Episode 9|Iteration 179|reward: 2266.0|last_reward_at:  177|Elapsed Time: 0:00:02||
Episode 9|Iteration 179|reward: 2266.0|last_reward_at:  179|Elapsed Time: 0:00:02||
Episode 9|Iteration 181|reward: 2272.0|last_reward_at:  179|Elapsed Time: 0:00:02||
Episode 9|Iteration 181|reward: 2272.0|last_reward_at:  181|Elapsed Time: 0:00:02||
Episode 9|Iteration 189|reward: 2272.0|last_reward_at:  181|Elapsed Time: 0:00:02||
Episode 9|Iteration 197|reward: 2272.0|last_reward_at:  181|Elapsed Time: 0:00:02||
Episode 9|Iteration 199|reward: 2272.0|last_reward_at:  181|Elapsed Time: 0:00:02||
Episode 9|Iteration 206|reward: 2272.0|last_reward_at:  181|Elapsed Time: 0:00:02||
Episode 9|Iteration 213|reward: 2272.0|last_reward_at:  181|Elapsed Time: 0:00:02||
Episode 9|Iteration 220|reward: 2272.0|last_reward_at:  181|Elapsed Time: 0:00:02||
Episode 9|Iteration 228|reward: 2272.0|last_reward_at:  181|Elapsed Time: 0:00:03||
Episode 9|Iteration 229|reward: 2272.0|last_reward_at:  181|Elapsed Time: 0:00:03||
Episode 9|Iteration 236|reward: 2272.0|last_reward_at:  181|Elapsed Time: 0:00:03||
Episode 9|Iteration 243|reward: 2272.0|last_reward_at:  181|Elapsed Time: 0:00:03||
Episode 9|Iteration 251|reward: 2272.0|last_reward_at:  181|Elapsed Time: 0:00:03||
Episode 9|Iteration 258|reward: 2272.0|last_reward_at:  181|Elapsed Time: 0:00:03||
Episode 9|Iteration 266|reward: 2272.0|last_reward_at:  181|Elapsed Time: 0:00:03||
Episode 9|Iteration 273|reward: 2272.0|last_reward_at:  181|Elapsed Time: 0:00:03||
Episode 9|Iteration 281|reward: 2272.0|last_reward_at:  181|Elapsed Time: 0:00:03||
Episode 9|Iteration 289|reward: 2272.0|last_reward_at:  181|Elapsed Time: 0:00:04||
Episode 9|Iteration 297|reward: 2272.0|last_reward_at:  181|Elapsed Time: 0:00:04||
Episode 9|Iteration 304|reward: 2272.0|last_reward_at:  181|Elapsed Time: 0:00:04||
Episode 9|Iteration 311|reward: 2272.0|last_reward_at:  181|Elapsed Time: 0:00:04||
Episode 9|Iteration 319|reward: 2272.0|last_reward_at:  181|Elapsed Time: 0:00:04||
Episode 9|Iteration 326|reward: 2272.0|last_reward_at:  181|Elapsed Time: 0:00:04||
Episode 9|Iteration 334|reward: 2278.0|last_reward_at:  181|Elapsed Time: 0:00:04||
Episode 9|Iteration 334|reward: 2278.0|last_reward_at:  334|Elapsed Time: 0:00:04||
Episode 9|Iteration 342|reward: 2278.0|last_reward_at:  334|Elapsed Time: 0:00:04||
Episode 9|Iteration 343|reward: 2284.0|last_reward_at:  334|Elapsed Time: 0:00:04||
Episode 9|Iteration 343|reward: 2284.0|last_reward_at:  343|Elapsed Time: 0:00:04||
Episode 9|Iteration 350|reward: 2284.0|last_reward_at:  343|Elapsed Time: 0:00:04||
Episode 9|Iteration 351|reward: 2290.0|last_reward_at:  343|Elapsed Time: 0:00:04||
Episode 9|Iteration 351|reward: 2290.0|last_reward_at:  351|Elapsed Time: 0:00:04||
Episode 9|Iteration 353|reward: 2290.0|last_reward_at:  351|Elapsed Time: 0:00:04||
Episode 9|Iteration 357|reward: 2290.0|last_reward_at:  351|Elapsed Time: 0:00:05||
Episode 9|Iteration 365|reward: 2290.0|last_reward_at:  351|Elapsed Time: 0:00:05||
Episode 9|Iteration 372|reward: 2290.0|last_reward_at:  351|Elapsed Time: 0:00:05||
Episode 9|Iteration 380|reward: 2290.0|last_reward_at:  351|Elapsed Time: 0:00:05||
Episode 9|Iteration 387|reward: 2296.0|last_reward_at:  351|Elapsed Time: 0:00:05||
Episode 9|Iteration 387|reward: 2296.0|last_reward_at:  387|Elapsed Time: 0:00:05||
Episode 9|Iteration 395|reward: 2296.0|last_reward_at:  387|Elapsed Time: 0:00:05||
Episode 9|Iteration 402|reward: 2296.0|last_reward_at:  387|Elapsed Time: 0:00:05||
Episode 9|Iteration 410|reward: 2296.0|last_reward_at:  387|Elapsed Time: 0:00:05||
Episode 9|Iteration 418|reward: 2296.0|last_reward_at:  387|Elapsed Time: 0:00:05||
Episode 9|Iteration 425|reward: 2296.0|last_reward_at:  387|Elapsed Time: 0:00:05||
Episode 9|Iteration 433|reward: 2296.0|last_reward_at:  387|Elapsed Time: 0:00:06||
Episode 9|Iteration 436|reward: 2296.0|last_reward_at:  387|Elapsed Time: 0:00:06||
Episode 9|Iteration 441|reward: 2296.0|last_reward_at:  387|Elapsed Time: 0:00:06||
Episode 9|Iteration 449|reward: 2296.0|last_reward_at:  387|Elapsed Time: 0:00:06||
Episode 9|Iteration 451|reward: 2296.0|last_reward_at:  387|Elapsed Time: 0:00:06||
Episode 9|Iteration 452|reward: 2296.0|last_reward_at:  387|Elapsed Time: 0:00:06||
Episode 9|Iteration 459|reward: 2296.0|last_reward_at:  387|Elapsed Time: 0:00:06||
Episode 9|Iteration 464|reward: 2296.0|last_reward_at:  387|Elapsed Time: 0:00:06||
Episode 9|Iteration 471|reward: 2296.0|last_reward_at:  387|Elapsed Time: 0:00:06||
Episode 9|Iteration 479|reward: 2296.0|last_reward_at:  387|Elapsed Time: 0:00:06||
Episode 9|Iteration 486|reward: 2296.0|last_reward_at:  387|Elapsed Time: 0:00:06||
Episode 9|Iteration 494|reward: 2296.0|last_reward_at:  387|Elapsed Time: 0:00:07||
Episode 9|Iteration 502|reward: 2296.0|last_reward_at:  387|Elapsed Time: 0:00:07||
Episode 9|Iteration 509|reward: 2296.0|last_reward_at:  387|Elapsed Time: 0:00:07||
Episode 9|Iteration 516|reward: 2296.0|last_reward_at:  387|Elapsed Time: 0:00:07||
Episode 9|Iteration 523|reward: 2296.0|last_reward_at:  387|Elapsed Time: 0:00:07||
Episode 9|Iteration 532|reward: 2296.0|last_reward_at:  387|Elapsed Time: 0:00:07||
Episode 9|Iteration 540|reward: 2296.0|last_reward_at:  387|Elapsed Time: 0:00:07||
Episode 9|Iteration 547|reward: 2296.0|last_reward_at:  387|Elapsed Time: 0:00:07||
Episode 9|Iteration 555|reward: 2296.0|last_reward_at:  387|Elapsed Time: 0:00:07||
Episode 9|Iteration 563|reward: 2296.0|last_reward_at:  387|Elapsed Time: 0:00:07||
Episode 9|Iteration 570|reward: 2296.0|last_reward_at:  387|Elapsed Time: 0:00:08||
Episode 9|Iteration 578|reward: 2296.0|last_reward_at:  387|Elapsed Time: 0:00:08||
Episode 9|Iteration 585|reward: 2296.0|last_reward_at:  387|Elapsed Time: 0:00:08||
Episode 9|Iteration 587|reward: 2296.0|last_reward_at:  387|Elapsed Time: 0:00:08||
Episode 9|Iteration 593|reward: 2296.0|last_reward_at:  387|Elapsed Time: 0:00:08||
Episode 9|Iteration 599|reward: 2296.0|last_reward_at:  387|Elapsed Time: 0:00:08||
Episode 9|Iteration 600|reward: 2296.0|last_reward_at:  387|Elapsed Time: 0:00:08||

  Episode 9 stopped at t=600
  Breakdown [Reward/NoReward (Success rate)]
    explore-local: 0/4 (0.00)
    explore-remote: 0/3 (0.00)
    explore-connect: 0/6 (0.00)
    exploit-local: 21/154 (0.12)
    exploit-remote: 20/374 (0.05)
    exploit-connect: 11/7 (0.61)
  exploit deflected to exploration: 13

,status,properties,local_attacks,remote_attacks
id,,,,
start,owned,[],[ScanExplorerRecentFiles],[]
1_LinuxNode,owned,"[MySql, Ubuntu, nginx/1.10.3]","[SudoAttempt, ScanExplorerRecentFiles, ScanBas...","[ProbeWindows, ProbeLinux]"
2_WindowsNode,owned,"[Windows, Win10, Win10Patched]","[ScanExplorerRecentFiles, SudoAttempt, CrackKe...","[ProbeWindows, ProbeLinux]"
3_LinuxNode,owned,"[MySql, Ubuntu, nginx/1.10.3]","[SudoAttempt, ScanExplorerRecentFiles, ScanBas...","[ProbeWindows, ProbeLinux]"
4_WindowsNode,owned,"[Windows, Win10, Win10Patched]","[ScanExplorerRecentFiles, SudoAttempt, CrackKe...","[ProbeWindows, ProbeLinux]"
5_LinuxNode,owned,"[MySql, Ubuntu, nginx/1.10.3]","[SudoAttempt, ScanExplorerRecentFiles, ScanBas...","[ProbeWindows, ProbeLinux]"
6_WindowsNode,owned,"[Windows, Win10, Win10Patched]","[ScanExplorerRecentFiles, SudoAttempt, CrackKe...","[ProbeWindows, ProbeLinux]"
7_LinuxNode,owned,"[MySql, Ubuntu, nginx/1.10.3]","[SudoAttempt, ScanExplorerRecentFiles, ScanBas...","[ProbeWindows, ProbeLinux]"
8_WindowsNode,owned,"[Windows, Win10, Win10Patched]","[ScanExplorerRecentFiles, SudoAttempt, CrackKe...","[ProbeWindows, ProbeLinux]"
9_LinuxNode,owned,"[MySql, Ubuntu, nginx/1.10.3]","[SudoAttempt, ScanExplorerRecentFiles, ScanBas...","[ProbeWindows, ProbeLinux]"
10_WindowsNode,owned,"[Windows, Win10, Win10Patched]","[ScanExplorerRecentFiles, SudoAttempt, CrackKe...","[ProbeWindows, ProbeLinux]"
11_LinuxNode,owned,"[MySql, Ubuntu, nginx/1.10.3, FLAG:Linux]",[],[]

  ## Episode: 10/10 'Exploiting DQL' ϵ=0.0000, γ=0.15, lr=0.01, replaymemory=10000,
batch=256, target_update=5

Episode 10|Iteration 0|reward: ------|last_reward_at: ----|Elapsed Time: 0:00:00||
Episode 10|Iteration 1|reward:   14.0|last_reward_at: ----|Elapsed Time: 0:00:00||
Episode 10|Iteration 1|reward:   14.0|last_reward_at:    1|Elapsed Time: 0:00:00||
Episode 10|Iteration 2|reward:   16.0|last_reward_at:    1|Elapsed Time: 0:00:00||
Episode 10|Iteration 2|reward:   16.0|last_reward_at:    2|Elapsed Time: 0:00:00||
Episode 10|Iteration 5|reward:   20.0|last_reward_at:    2|Elapsed Time: 0:00:00||
Episode 10|Iteration 5|reward:   20.0|last_reward_at:    5|Elapsed Time: 0:00:00||
Episode 10|Iteration 16|reward:   20.0|last_reward_at:    5|Elapsed Time: 0:00:00||
Episode 10|Iteration 23|reward:   20.0|last_reward_at:    5|Elapsed Time: 0:00:00||
Episode 10|Iteration 31|reward:   20.0|last_reward_at:    5|Elapsed Time: 0:00:00||
Episode 10|Iteration 38|reward:   20.0|last_reward_at:    5|Elapsed Time: 0:00:00||
Episode 10|Iteration 46|reward:   20.0|last_reward_at:    5|Elapsed Time: 0:00:00||
Episode 10|Iteration 54|reward:   20.0|last_reward_at:    5|Elapsed Time: 0:00:00||
Episode 10|Iteration 61|reward:   20.0|last_reward_at:    5|Elapsed Time: 0:00:00||
Episode 10|Iteration 69|reward:   20.0|last_reward_at:    5|Elapsed Time: 0:00:00||
Episode 10|Iteration 76|reward:   20.0|last_reward_at:    5|Elapsed Time: 0:00:00||
Episode 10|Iteration 84|reward:   20.0|last_reward_at:    5|Elapsed Time: 0:00:00||
Episode 10|Iteration 90|reward:  120.0|last_reward_at:    5|Elapsed Time: 0:00:00||
Episode 10|Iteration 90|reward:  120.0|last_reward_at:   90|Elapsed Time: 0:00:00||
Episode 10|Iteration 91|reward:  134.0|last_reward_at:   90|Elapsed Time: 0:00:00||
Episode 10|Iteration 91|reward:  134.0|last_reward_at:   91|Elapsed Time: 0:00:00||
Episode 10|Iteration 93|reward:  234.0|last_reward_at:   91|Elapsed Time: 0:00:00||
Episode 10|Iteration 93|reward:  234.0|last_reward_at:   93|Elapsed Time: 0:00:00||
Episode 10|Iteration 94|reward:  248.0|last_reward_at:   93|Elapsed Time: 0:00:00||
Episode 10|Iteration 94|reward:  248.0|last_reward_at:   94|Elapsed Time: 0:00:00||
Episode 10|Iteration 95|reward:  348.0|last_reward_at:   94|Elapsed Time: 0:00:01||
Episode 10|Iteration 95|reward:  348.0|last_reward_at:   95|Elapsed Time: 0:00:01||
Episode 10|Iteration 96|reward:  362.0|last_reward_at:   95|Elapsed Time: 0:00:01||
Episode 10|Iteration 96|reward:  362.0|last_reward_at:   96|Elapsed Time: 0:00:01||
Episode 10|Iteration 98|reward:  462.0|last_reward_at:   96|Elapsed Time: 0:00:01||
Episode 10|Iteration 98|reward:  462.0|last_reward_at:   98|Elapsed Time: 0:00:01||
Episode 10|Iteration 99|reward:  476.0|last_reward_at:   98|Elapsed Time: 0:00:01||
Episode 10|Iteration 99|reward:  476.0|last_reward_at:   99|Elapsed Time: 0:00:01||
Episode 10|Iteration 100|reward:  576.0|last_reward_at:   99|Elapsed Time: 0:00:01||
Episode 10|Iteration 100|reward:  576.0|last_reward_at:  100|Elapsed Time: 0:00:01||
Episode 10|Iteration 101|reward:  590.0|last_reward_at:  100|Elapsed Time: 0:00:01||
Episode 10|Iteration 101|reward:  590.0|last_reward_at:  101|Elapsed Time: 0:00:01||
Episode 10|Iteration 103|reward:  690.0|last_reward_at:  101|Elapsed Time: 0:00:01||
Episode 10|Iteration 103|reward:  690.0|last_reward_at:  103|Elapsed Time: 0:00:01||
Episode 10|Iteration 104|reward:  704.0|last_reward_at:  103|Elapsed Time: 0:00:01||
Episode 10|Iteration 104|reward:  704.0|last_reward_at:  104|Elapsed Time: 0:00:01||
Episode 10|Iteration 105|reward:  804.0|last_reward_at:  104|Elapsed Time: 0:00:01||
Episode 10|Iteration 105|reward:  804.0|last_reward_at:  105|Elapsed Time: 0:00:01||
Episode 10|Iteration 106|reward:  818.0|last_reward_at:  105|Elapsed Time: 0:00:01||
Episode 10|Iteration 106|reward:  818.0|last_reward_at:  106|Elapsed Time: 0:00:01||
Episode 10|Iteration 108|reward:  918.0|last_reward_at:  106|Elapsed Time: 0:00:01||
Episode 10|Iteration 108|reward:  918.0|last_reward_at:  108|Elapsed Time: 0:00:01||
Episode 10|Iteration 109|reward:  932.0|last_reward_at:  108|Elapsed Time: 0:00:01||
Episode 10|Iteration 109|reward:  932.0|last_reward_at:  109|Elapsed Time: 0:00:01||
Episode 10|Iteration 110|reward: 1032.0|last_reward_at:  109|Elapsed Time: 0:00:01||
Episode 10|Iteration 110|reward: 1032.0|last_reward_at:  110|Elapsed Time: 0:00:01||
Episode 10|Iteration 111|reward: 1046.0|last_reward_at:  110|Elapsed Time: 0:00:01||
Episode 10|Iteration 111|reward: 1046.0|last_reward_at:  111|Elapsed Time: 0:00:01||
Episode 10|Iteration 113|reward: 1146.0|last_reward_at:  111|Elapsed Time: 0:00:01||
Episode 10|Iteration 113|reward: 1146.0|last_reward_at:  113|Elapsed Time: 0:00:01||
Episode 10|Iteration 114|reward: 1160.0|last_reward_at:  113|Elapsed Time: 0:00:01||
Episode 10|Iteration 114|reward: 1160.0|last_reward_at:  114|Elapsed Time: 0:00:01||
Episode 10|Iteration 115|reward: 2160.0|last_reward_at:  114|Elapsed Time: 0:00:01||
Episode 10|Iteration 115|reward: 2160.0|last_reward_at:  115|Elapsed Time: 0:00:01||
Episode 10|Iteration 117|reward: 2162.0|last_reward_at:  115|Elapsed Time: 0:00:01||
Episode 10|Iteration 117|reward: 2162.0|last_reward_at:  117|Elapsed Time: 0:00:01||
Episode 10|Iteration 118|reward: 2164.0|last_reward_at:  117|Elapsed Time: 0:00:01||
Episode 10|Iteration 118|reward: 2164.0|last_reward_at:  118|Elapsed Time: 0:00:01||
Episode 10|Iteration 119|reward: 2170.0|last_reward_at:  118|Elapsed Time: 0:00:01||
Episode 10|Iteration 119|reward: 2170.0|last_reward_at:  119|Elapsed Time: 0:00:01||
Episode 10|Iteration 121|reward: 2172.0|last_reward_at:  119|Elapsed Time: 0:00:01||
Episode 10|Iteration 121|reward: 2172.0|last_reward_at:  121|Elapsed Time: 0:00:01||
Episode 10|Iteration 122|reward: 2178.0|last_reward_at:  121|Elapsed Time: 0:00:01||
Episode 10|Iteration 122|reward: 2178.0|last_reward_at:  122|Elapsed Time: 0:00:01||
Episode 10|Iteration 124|reward: 2184.0|last_reward_at:  122|Elapsed Time: 0:00:01||
Episode 10|Iteration 124|reward: 2184.0|last_reward_at:  124|Elapsed Time: 0:00:01||
Episode 10|Iteration 125|reward: 2190.0|last_reward_at:  124|Elapsed Time: 0:00:01||
Episode 10|Iteration 125|reward: 2190.0|last_reward_at:  125|Elapsed Time: 0:00:01||
Episode 10|Iteration 126|reward: 2192.0|last_reward_at:  125|Elapsed Time: 0:00:01||
Episode 10|Iteration 126|reward: 2192.0|last_reward_at:  126|Elapsed Time: 0:00:01||
Episode 10|Iteration 128|reward: 2198.0|last_reward_at:  126|Elapsed Time: 0:00:01||
Episode 10|Iteration 128|reward: 2198.0|last_reward_at:  128|Elapsed Time: 0:00:01||
Episode 10|Iteration 132|reward: 2204.0|last_reward_at:  128|Elapsed Time: 0:00:01||
Episode 10|Iteration 132|reward: 2204.0|last_reward_at:  132|Elapsed Time: 0:00:01||
Episode 10|Iteration 135|reward: 2210.0|last_reward_at:  132|Elapsed Time: 0:00:01||
Episode 10|Iteration 135|reward: 2210.0|last_reward_at:  135|Elapsed Time: 0:00:01||
Episode 10|Iteration 137|reward: 2216.0|last_reward_at:  135|Elapsed Time: 0:00:01||
Episode 10|Iteration 137|reward: 2216.0|last_reward_at:  137|Elapsed Time: 0:00:01||
Episode 10|Iteration 145|reward: 2216.0|last_reward_at:  137|Elapsed Time: 0:00:01||
Episode 10|Iteration 146|reward: 2222.0|last_reward_at:  137|Elapsed Time: 0:00:01||
Episode 10|Iteration 146|reward: 2222.0|last_reward_at:  146|Elapsed Time: 0:00:01||
Episode 10|Iteration 147|reward: 2228.0|last_reward_at:  146|Elapsed Time: 0:00:01||
Episode 10|Iteration 147|reward: 2228.0|last_reward_at:  147|Elapsed Time: 0:00:01||
Episode 10|Iteration 149|reward: 2234.0|last_reward_at:  147|Elapsed Time: 0:00:01||
Episode 10|Iteration 149|reward: 2234.0|last_reward_at:  149|Elapsed Time: 0:00:01||
Episode 10|Iteration 158|reward: 2240.0|last_reward_at:  149|Elapsed Time: 0:00:01||
Episode 10|Iteration 158|reward: 2240.0|last_reward_at:  158|Elapsed Time: 0:00:01||
Episode 10|Iteration 160|reward: 2240.0|last_reward_at:  158|Elapsed Time: 0:00:02||
Episode 10|Iteration 160|reward: 2246.0|last_reward_at:  158|Elapsed Time: 0:00:02||
Episode 10|Iteration 160|reward: 2246.0|last_reward_at:  160|Elapsed Time: 0:00:02||
Episode 10|Iteration 168|reward: 2246.0|last_reward_at:  160|Elapsed Time: 0:00:02||
Episode 10|Iteration 169|reward: 2248.0|last_reward_at:  160|Elapsed Time: 0:00:02||
Episode 10|Iteration 169|reward: 2248.0|last_reward_at:  169|Elapsed Time: 0:00:02||
Episode 10|Iteration 175|reward: 2248.0|last_reward_at:  169|Elapsed Time: 0:00:02||
Episode 10|Iteration 175|reward: 2254.0|last_reward_at:  169|Elapsed Time: 0:00:02||
Episode 10|Iteration 175|reward: 2254.0|last_reward_at:  175|Elapsed Time: 0:00:02||
Episode 10|Iteration 183|reward: 2254.0|last_reward_at:  175|Elapsed Time: 0:00:02||
Episode 10|Iteration 190|reward: 2254.0|last_reward_at:  175|Elapsed Time: 0:00:02||
Episode 10|Iteration 197|reward: 2254.0|last_reward_at:  175|Elapsed Time: 0:00:02||
Episode 10|Iteration 198|reward: 2256.0|last_reward_at:  175|Elapsed Time: 0:00:02||
Episode 10|Iteration 198|reward: 2256.0|last_reward_at:  198|Elapsed Time: 0:00:02||
Episode 10|Iteration 202|reward: 2258.0|last_reward_at:  198|Elapsed Time: 0:00:02||
Episode 10|Iteration 202|reward: 2258.0|last_reward_at:  202|Elapsed Time: 0:00:02||
Episode 10|Iteration 205|reward: 2264.0|last_reward_at:  202|Elapsed Time: 0:00:02||
Episode 10|Iteration 205|reward: 2264.0|last_reward_at:  205|Elapsed Time: 0:00:02||
Episode 10|Iteration 207|reward: 2264.0|last_reward_at:  205|Elapsed Time: 0:00:02||
Episode 10|Iteration 213|reward: 2264.0|last_reward_at:  205|Elapsed Time: 0:00:02||
Episode 10|Iteration 220|reward: 2264.0|last_reward_at:  205|Elapsed Time: 0:00:02||
Episode 10|Iteration 228|reward: 2264.0|last_reward_at:  205|Elapsed Time: 0:00:03||
Episode 10|Iteration 232|reward: 2270.0|last_reward_at:  205|Elapsed Time: 0:00:03||
Episode 10|Iteration 232|reward: 2270.0|last_reward_at:  232|Elapsed Time: 0:00:03||
Episode 10|Iteration 238|reward: 2276.0|last_reward_at:  232|Elapsed Time: 0:00:03||
Episode 10|Iteration 238|reward: 2276.0|last_reward_at:  238|Elapsed Time: 0:00:03||
Episode 10|Iteration 241|reward: 2276.0|last_reward_at:  238|Elapsed Time: 0:00:03||
Episode 10|Iteration 250|reward: 2276.0|last_reward_at:  238|Elapsed Time: 0:00:03||
Episode 10|Iteration 255|reward: 2278.0|last_reward_at:  238|Elapsed Time: 0:00:03||
Episode 10|Iteration 255|reward: 2278.0|last_reward_at:  255|Elapsed Time: 0:00:03||
Episode 10|Iteration 264|reward: 2278.0|last_reward_at:  255|Elapsed Time: 0:00:03||
Episode 10|Iteration 272|reward: 2278.0|last_reward_at:  255|Elapsed Time: 0:00:03||
Episode 10|Iteration 274|reward: 2284.0|last_reward_at:  255|Elapsed Time: 0:00:03||
Episode 10|Iteration 274|reward: 2284.0|last_reward_at:  274|Elapsed Time: 0:00:03||
Episode 10|Iteration 278|reward: 2290.0|last_reward_at:  274|Elapsed Time: 0:00:03||
Episode 10|Iteration 278|reward: 2290.0|last_reward_at:  278|Elapsed Time: 0:00:03||
Episode 10|Iteration 285|reward: 2290.0|last_reward_at:  278|Elapsed Time: 0:00:03||
Episode 10|Iteration 288|reward: 2296.0|last_reward_at:  278|Elapsed Time: 0:00:03||
Episode 10|Iteration 288|reward: 2296.0|last_reward_at:  288|Elapsed Time: 0:00:03||
Episode 10|Iteration 296|reward: 2296.0|last_reward_at:  288|Elapsed Time: 0:00:04||
Episode 10|Iteration 299|reward: 2296.0|last_reward_at:  288|Elapsed Time: 0:00:04||
Episode 10|Iteration 304|reward: 2296.0|last_reward_at:  288|Elapsed Time: 0:00:04||
Episode 10|Iteration 312|reward: 2296.0|last_reward_at:  288|Elapsed Time: 0:00:04||
Episode 10|Iteration 313|reward: 2296.0|last_reward_at:  288|Elapsed Time: 0:00:04||
Episode 10|Iteration 319|reward: 2296.0|last_reward_at:  288|Elapsed Time: 0:00:04||
Episode 10|Iteration 327|reward: 2296.0|last_reward_at:  288|Elapsed Time: 0:00:04||
Episode 10|Iteration 335|reward: 2296.0|last_reward_at:  288|Elapsed Time: 0:00:04||
Episode 10|Iteration 338|reward: 2296.0|last_reward_at:  288|Elapsed Time: 0:00:04||
Episode 10|Iteration 346|reward: 2296.0|last_reward_at:  288|Elapsed Time: 0:00:04||
Episode 10|Iteration 354|reward: 2296.0|last_reward_at:  288|Elapsed Time: 0:00:05||
Episode 10|Iteration 361|reward: 2296.0|last_reward_at:  288|Elapsed Time: 0:00:05||
Episode 10|Iteration 369|reward: 2296.0|last_reward_at:  288|Elapsed Time: 0:00:05||
Episode 10|Iteration 377|reward: 2296.0|last_reward_at:  288|Elapsed Time: 0:00:05||
Episode 10|Iteration 385|reward: 2296.0|last_reward_at:  288|Elapsed Time: 0:00:05||
Episode 10|Iteration 393|reward: 2296.0|last_reward_at:  288|Elapsed Time: 0:00:05||
Episode 10|Iteration 401|reward: 2296.0|last_reward_at:  288|Elapsed Time: 0:00:05||
Episode 10|Iteration 409|reward: 2296.0|last_reward_at:  288|Elapsed Time: 0:00:05||
Episode 10|Iteration 416|reward: 2296.0|last_reward_at:  288|Elapsed Time: 0:00:06||
Episode 10|Iteration 424|reward: 2296.0|last_reward_at:  288|Elapsed Time: 0:00:06||
Episode 10|Iteration 432|reward: 2296.0|last_reward_at:  288|Elapsed Time: 0:00:06||
Episode 10|Iteration 435|reward: 2296.0|last_reward_at:  288|Elapsed Time: 0:00:06||
Episode 10|Iteration 441|reward: 2296.0|last_reward_at:  288|Elapsed Time: 0:00:06||
Episode 10|Iteration 448|reward: 2296.0|last_reward_at:  288|Elapsed Time: 0:00:06||
Episode 10|Iteration 453|reward: 2296.0|last_reward_at:  288|Elapsed Time: 0:00:06||
Episode 10|Iteration 460|reward: 2296.0|last_reward_at:  288|Elapsed Time: 0:00:06||
Episode 10|Iteration 469|reward: 2296.0|last_reward_at:  288|Elapsed Time: 0:00:06||
Episode 10|Iteration 477|reward: 2296.0|last_reward_at:  288|Elapsed Time: 0:00:07||
Episode 10|Iteration 486|reward: 2296.0|last_reward_at:  288|Elapsed Time: 0:00:07||
Episode 10|Iteration 494|reward: 2296.0|last_reward_at:  288|Elapsed Time: 0:00:07||
Episode 10|Iteration 502|reward: 2296.0|last_reward_at:  288|Elapsed Time: 0:00:07||
Episode 10|Iteration 509|reward: 2296.0|last_reward_at:  288|Elapsed Time: 0:00:07||
Episode 10|Iteration 510|reward: 2296.0|last_reward_at:  288|Elapsed Time: 0:00:07||
Episode 10|Iteration 517|reward: 2296.0|last_reward_at:  288|Elapsed Time: 0:00:07||
Episode 10|Iteration 524|reward: 2296.0|last_reward_at:  288|Elapsed Time: 0:00:07||
Episode 10|Iteration 531|reward: 2296.0|last_reward_at:  288|Elapsed Time: 0:00:07||
Episode 10|Iteration 537|reward: 2296.0|last_reward_at:  288|Elapsed Time: 0:00:08||
Episode 10|Iteration 545|reward: 2296.0|last_reward_at:  288|Elapsed Time: 0:00:08||
Episode 10|Iteration 553|reward: 2296.0|last_reward_at:  288|Elapsed Time: 0:00:08||
Episode 10|Iteration 561|reward: 2296.0|last_reward_at:  288|Elapsed Time: 0:00:08||
Episode 10|Iteration 567|reward: 2296.0|last_reward_at:  288|Elapsed Time: 0:00:08||
Episode 10|Iteration 575|reward: 2296.0|last_reward_at:  288|Elapsed Time: 0:00:08||
Episode 10|Iteration 581|reward: 2296.0|last_reward_at:  288|Elapsed Time: 0:00:08||
Episode 10|Iteration 589|reward: 2296.0|last_reward_at:  288|Elapsed Time: 0:00:08||
Episode 10|Iteration 597|reward: 2296.0|last_reward_at:  288|Elapsed Time: 0:00:08||
Episode 10|Iteration 600|reward: 2296.0|last_reward_at:  288|Elapsed Time: 0:00:09||

  Episode 10 stopped at t=600
  Breakdown [Reward/NoReward (Success rate)]
    explore-local: 0/6 (0.00)
    explore-remote: 0/10 (0.00)
    explore-connect: 1/15 (0.06)
    exploit-local: 21/222 (0.09)
    exploit-remote: 20/295 (0.06)
    exploit-connect: 10/0 (1.00)
  exploit deflected to exploration: 32

,status,properties,local_attacks,remote_attacks
id,,,,
start,owned,[],[ScanExplorerRecentFiles],[]
1_LinuxNode,owned,"[MySql, Ubuntu, nginx/1.10.3]","[SudoAttempt, ScanExplorerRecentFiles, ScanBas...","[ProbeWindows, ProbeLinux]"
2_WindowsNode,owned,"[Windows, Win10, Win10Patched]","[ScanExplorerRecentFiles, SudoAttempt, CrackKe...","[ProbeWindows, ProbeLinux]"
3_LinuxNode,owned,"[MySql, Ubuntu, nginx/1.10.3]","[SudoAttempt, ScanExplorerRecentFiles, ScanBas...","[ProbeWindows, ProbeLinux]"
4_WindowsNode,owned,"[Windows, Win10, Win10Patched]","[ScanExplorerRecentFiles, SudoAttempt, CrackKe...","[ProbeWindows, ProbeLinux]"
5_LinuxNode,owned,"[MySql, Ubuntu, nginx/1.10.3]","[SudoAttempt, ScanExplorerRecentFiles, ScanBas...","[ProbeWindows, ProbeLinux]"
6_WindowsNode,owned,"[Windows, Win10, Win10Patched]","[ScanExplorerRecentFiles, SudoAttempt, CrackKe...","[ProbeWindows, ProbeLinux]"
7_LinuxNode,owned,"[MySql, Ubuntu, nginx/1.10.3]","[SudoAttempt, ScanExplorerRecentFiles, ScanBas...","[ProbeWindows, ProbeLinux]"
8_WindowsNode,owned,"[Windows, Win10, Win10Patched]","[ScanExplorerRecentFiles, SudoAttempt, CrackKe...","[ProbeWindows, ProbeLinux]"
9_LinuxNode,owned,"[MySql, Ubuntu, nginx/1.10.3]","[SudoAttempt, ScanExplorerRecentFiles, ScanBas...","[ProbeWindows, ProbeLinux]"
10_WindowsNode,owned,"[Windows, Win10, Win10Patched]","[ScanExplorerRecentFiles, SudoAttempt, CrackKe...","[ProbeWindows, ProbeLinux]"
11_LinuxNode,owned,"[MySql, Ubuntu, nginx/1.10.3, FLAG:Linux]",[],[]

simulation ended

In [20]:
credlookup_run = learner.epsilon_greedy_search(
    cyberbattlechain_defender,
    ep,
    learner=rca.CredentialCacheExploiter(),
    episode_count=10,
    iteration_count=iteration_count,
    epsilon=0.90,
    render=False,
    epsilon_exponential_decay=10000,
    epsilon_minimum=0.10,
    verbosity=Verbosity.Quiet,
    title="Credential lookups (ϵ-greedy)",
)

###### Credential lookups (ϵ-greedy)
Learning with: episode_count=10,iteration_count=600,ϵ=0.9,ϵ_min=0.1, ϵ_expdecay=10000,
  ## Episode: 1/10 'Credential lookups (ϵ-greedy)' ϵ=0.9000,

Episode 1|Iteration 0|reward: ------|last_reward_at: ----|Elapsed Time: 0:00:00||
Episode 1|Iteration 1|reward:    0.0|last_reward_at: ----|Elapsed Time: 0:00:00||
Episode 1|Iteration 5|reward:   14.0|last_reward_at: ----|Elapsed Time: 0:00:00||
Episode 1|Iteration 5|reward:   14.0|last_reward_at:    5|Elapsed Time: 0:00:00||
Episode 1|Iteration 12|reward:   16.0|last_reward_at:    5|Elapsed Time: 0:00:00||
Episode 1|Iteration 12|reward:   16.0|last_reward_at:   12|Elapsed Time: 0:00:00||
Episode 1|Iteration 19|reward:  116.0|last_reward_at:   12|Elapsed Time: 0:00:00||
Episode 1|Iteration 19|reward:  116.0|last_reward_at:   19|Elapsed Time: 0:00:00||
Episode 1|Iteration 23|reward:  127.0|last_reward_at:   19|Elapsed Time: 0:00:00||
Episode 1|Iteration 23|reward:  127.0|last_reward_at:   23|Elapsed Time: 0:00:00||
Episode 1|Iteration 26|reward:  129.0|last_reward_at:   23|Elapsed Time: 0:00:00||
Episode 1|Iteration 26|reward:  129.0|last_reward_at:   26|Elapsed Time: 0:00:00||
Episode 1|Iteration 31|reward:  135.0|last_reward_at:   26|Elapsed Time: 0:00:00||
Episode 1|Iteration 31|reward:  135.0|last_reward_at:   31|Elapsed Time: 0:00:00||
Episode 1|Iteration 38|reward:  143.0|last_reward_at:   31|Elapsed Time: 0:00:00||
Episode 1|Iteration 38|reward:  143.0|last_reward_at:   38|Elapsed Time: 0:00:00||
Episode 1|Iteration 69|reward:  143.0|last_reward_at:   38|Elapsed Time: 0:00:00||
Episode 1|Iteration 71|reward:  152.0|last_reward_at:   38|Elapsed Time: 0:00:00||
Episode 1|Iteration 71|reward:  152.0|last_reward_at:   71|Elapsed Time: 0:00:00||
Episode 1|Iteration 83|reward:  252.0|last_reward_at:   71|Elapsed Time: 0:00:00||
Episode 1|Iteration 83|reward:  252.0|last_reward_at:   83|Elapsed Time: 0:00:00||
Episode 1|Iteration 91|reward:  266.0|last_reward_at:   83|Elapsed Time: 0:00:00||
Episode 1|Iteration 91|reward:  266.0|last_reward_at:   91|Elapsed Time: 0:00:00||
Episode 1|Iteration 92|reward:  366.0|last_reward_at:   91|Elapsed Time: 0:00:00||
Episode 1|Iteration 92|reward:  366.0|last_reward_at:   92|Elapsed Time: 0:00:00||
Episode 1|Iteration 98|reward:  368.0|last_reward_at:   92|Elapsed Time: 0:00:00||
Episode 1|Iteration 98|reward:  368.0|last_reward_at:   98|Elapsed Time: 0:00:00||
Episode 1|Iteration 105|reward:  370.0|last_reward_at:   98|Elapsed Time: 0:00:00||
Episode 1|Iteration 105|reward:  370.0|last_reward_at:  105|Elapsed Time: 0:00:00||
Episode 1|Iteration 111|reward:  381.0|last_reward_at:  105|Elapsed Time: 0:00:00||
Episode 1|Iteration 111|reward:  381.0|last_reward_at:  111|Elapsed Time: 0:00:00||
Episode 1|Iteration 121|reward:  387.0|last_reward_at:  111|Elapsed Time: 0:00:00||
Episode 1|Iteration 121|reward:  387.0|last_reward_at:  121|Elapsed Time: 0:00:00||
Episode 1|Iteration 126|reward:  396.0|last_reward_at:  121|Elapsed Time: 0:00:00||
Episode 1|Iteration 126|reward:  396.0|last_reward_at:  126|Elapsed Time: 0:00:00||
Episode 1|Iteration 127|reward:  496.0|last_reward_at:  126|Elapsed Time: 0:00:00||
Episode 1|Iteration 127|reward:  496.0|last_reward_at:  127|Elapsed Time: 0:00:00||
Episode 1|Iteration 145|reward:  496.0|last_reward_at:  127|Elapsed Time: 0:00:00||
Episode 1|Iteration 156|reward:  510.0|last_reward_at:  127|Elapsed Time: 0:00:00||
Episode 1|Iteration 156|reward:  510.0|last_reward_at:  156|Elapsed Time: 0:00:00||
Episode 1|Iteration 161|reward:  512.0|last_reward_at:  156|Elapsed Time: 0:00:00||
Episode 1|Iteration 161|reward:  512.0|last_reward_at:  161|Elapsed Time: 0:00:00||
Episode 1|Iteration 164|reward:  518.0|last_reward_at:  161|Elapsed Time: 0:00:00||
Episode 1|Iteration 164|reward:  518.0|last_reward_at:  164|Elapsed Time: 0:00:00||
Episode 1|Iteration 166|reward:  522.0|last_reward_at:  164|Elapsed Time: 0:00:00||
Episode 1|Iteration 166|reward:  522.0|last_reward_at:  166|Elapsed Time: 0:00:00||
Episode 1|Iteration 172|reward:  622.0|last_reward_at:  166|Elapsed Time: 0:00:00||
Episode 1|Iteration 172|reward:  622.0|last_reward_at:  172|Elapsed Time: 0:00:00||
Episode 1|Iteration 179|reward:  628.0|last_reward_at:  172|Elapsed Time: 0:00:00||
Episode 1|Iteration 179|reward:  628.0|last_reward_at:  179|Elapsed Time: 0:00:00||
Episode 1|Iteration 183|reward:  634.0|last_reward_at:  179|Elapsed Time: 0:00:00||
Episode 1|Iteration 183|reward:  634.0|last_reward_at:  183|Elapsed Time: 0:00:00||
Episode 1|Iteration 206|reward:  634.0|last_reward_at:  183|Elapsed Time: 0:00:00||
Episode 1|Iteration 221|reward:  634.0|last_reward_at:  183|Elapsed Time: 0:00:00||
Episode 1|Iteration 234|reward:  645.0|last_reward_at:  183|Elapsed Time: 0:00:00||
Episode 1|Iteration 234|reward:  645.0|last_reward_at:  234|Elapsed Time: 0:00:00||
Episode 1|Iteration 245|reward:  654.0|last_reward_at:  234|Elapsed Time: 0:00:00||
Episode 1|Iteration 245|reward:  654.0|last_reward_at:  245|Elapsed Time: 0:00:00||
Episode 1|Iteration 250|reward:  662.0|last_reward_at:  245|Elapsed Time: 0:00:00||
Episode 1|Iteration 250|reward:  662.0|last_reward_at:  250|Elapsed Time: 0:00:00||
Episode 1|Iteration 252|reward:  762.0|last_reward_at:  250|Elapsed Time: 0:00:00||
Episode 1|Iteration 252|reward:  762.0|last_reward_at:  252|Elapsed Time: 0:00:00||
Episode 1|Iteration 257|reward:  776.0|last_reward_at:  252|Elapsed Time: 0:00:00||
Episode 1|Iteration 257|reward:  776.0|last_reward_at:  257|Elapsed Time: 0:00:00||
Episode 1|Iteration 258|reward:  782.0|last_reward_at:  257|Elapsed Time: 0:00:00||
Episode 1|Iteration 258|reward:  782.0|last_reward_at:  258|Elapsed Time: 0:00:00||
Episode 1|Iteration 259|reward:  882.0|last_reward_at:  258|Elapsed Time: 0:00:00||
Episode 1|Iteration 259|reward:  882.0|last_reward_at:  259|Elapsed Time: 0:00:00||
Episode 1|Iteration 272|reward:  884.0|last_reward_at:  259|Elapsed Time: 0:00:00||
Episode 1|Iteration 272|reward:  884.0|last_reward_at:  272|Elapsed Time: 0:00:00||
Episode 1|Iteration 289|reward:  884.0|last_reward_at:  272|Elapsed Time: 0:00:01||
Episode 1|Iteration 297|reward:  886.0|last_reward_at:  272|Elapsed Time: 0:00:01||
Episode 1|Iteration 297|reward:  886.0|last_reward_at:  297|Elapsed Time: 0:00:01||
Episode 1|Iteration 311|reward:  892.0|last_reward_at:  297|Elapsed Time: 0:00:01||
Episode 1|Iteration 311|reward:  892.0|last_reward_at:  311|Elapsed Time: 0:00:01||
Episode 1|Iteration 327|reward:  892.0|last_reward_at:  311|Elapsed Time: 0:00:01||
Episode 1|Iteration 330|reward:  903.0|last_reward_at:  311|Elapsed Time: 0:00:01||
Episode 1|Iteration 330|reward:  903.0|last_reward_at:  330|Elapsed Time: 0:00:01||
Episode 1|Iteration 350|reward:  903.0|last_reward_at:  330|Elapsed Time: 0:00:01||
Episode 1|Iteration 365|reward:  903.0|last_reward_at:  330|Elapsed Time: 0:00:01||
Episode 1|Iteration 373|reward:  909.0|last_reward_at:  330|Elapsed Time: 0:00:01||
Episode 1|Iteration 373|reward:  909.0|last_reward_at:  373|Elapsed Time: 0:00:01||
Episode 1|Iteration 383|reward:  918.0|last_reward_at:  373|Elapsed Time: 0:00:01||
Episode 1|Iteration 383|reward:  918.0|last_reward_at:  383|Elapsed Time: 0:00:01||
Episode 1|Iteration 393|reward:  926.0|last_reward_at:  383|Elapsed Time: 0:00:01||
Episode 1|Iteration 393|reward:  926.0|last_reward_at:  393|Elapsed Time: 0:00:01||
Episode 1|Iteration 401|reward: 1026.0|last_reward_at:  393|Elapsed Time: 0:00:01||
Episode 1|Iteration 401|reward: 1026.0|last_reward_at:  401|Elapsed Time: 0:00:01||
Episode 1|Iteration 418|reward: 1026.0|last_reward_at:  401|Elapsed Time: 0:00:01||
Episode 1|Iteration 433|reward: 1026.0|last_reward_at:  401|Elapsed Time: 0:00:01||
Episode 1|Iteration 433|reward: 1040.0|last_reward_at:  401|Elapsed Time: 0:00:01||
Episode 1|Iteration 433|reward: 1040.0|last_reward_at:  433|Elapsed Time: 0:00:01||
Episode 1|Iteration 447|reward: 1140.0|last_reward_at:  433|Elapsed Time: 0:00:01||
Episode 1|Iteration 447|reward: 1140.0|last_reward_at:  447|Elapsed Time: 0:00:01||
Episode 1|Iteration 450|reward: 1142.0|last_reward_at:  447|Elapsed Time: 0:00:01||
Episode 1|Iteration 450|reward: 1142.0|last_reward_at:  450|Elapsed Time: 0:00:01||
Episode 1|Iteration 464|reward: 1142.0|last_reward_at:  450|Elapsed Time: 0:00:01||
Episode 1|Iteration 467|reward: 1144.0|last_reward_at:  450|Elapsed Time: 0:00:01||
Episode 1|Iteration 467|reward: 1144.0|last_reward_at:  467|Elapsed Time: 0:00:01||
Episode 1|Iteration 468|reward: 1158.0|last_reward_at:  467|Elapsed Time: 0:00:01||
Episode 1|Iteration 468|reward: 1158.0|last_reward_at:  468|Elapsed Time: 0:00:01||
Episode 1|Iteration 470|reward: 1164.0|last_reward_at:  468|Elapsed Time: 0:00:01||
Episode 1|Iteration 470|reward: 1164.0|last_reward_at:  470|Elapsed Time: 0:00:01||
Episode 1|Iteration 473|reward: 1264.0|last_reward_at:  470|Elapsed Time: 0:00:01||
Episode 1|Iteration 473|reward: 1264.0|last_reward_at:  473|Elapsed Time: 0:00:01||
Episode 1|Iteration 487|reward: 1264.0|last_reward_at:  473|Elapsed Time: 0:00:02||
Episode 1|Iteration 491|reward: 1270.0|last_reward_at:  473|Elapsed Time: 0:00:02||
Episode 1|Iteration 491|reward: 1270.0|last_reward_at:  491|Elapsed Time: 0:00:02||
Episode 1|Iteration 502|reward: 1270.0|last_reward_at:  491|Elapsed Time: 0:00:02||
Episode 1|Iteration 512|reward: 1276.0|last_reward_at:  491|Elapsed Time: 0:00:02||
Episode 1|Iteration 512|reward: 1276.0|last_reward_at:  512|Elapsed Time: 0:00:02||
Episode 1|Iteration 516|reward: 1290.0|last_reward_at:  512|Elapsed Time: 0:00:02||
Episode 1|Iteration 516|reward: 1290.0|last_reward_at:  516|Elapsed Time: 0:00:02||
Episode 1|Iteration 518|reward: 2290.0|last_reward_at:  516|Elapsed Time: 0:00:02||
Episode 1|Iteration 518|reward: 2290.0|last_reward_at:  518|Elapsed Time: 0:00:02||
Episode 1|Iteration 532|reward: 2290.0|last_reward_at:  518|Elapsed Time: 0:00:02||
Episode 1|Iteration 540|reward: 2290.0|last_reward_at:  518|Elapsed Time: 0:00:02||
Episode 1|Iteration 547|reward: 2290.0|last_reward_at:  518|Elapsed Time: 0:00:02||
Episode 1|Iteration 553|reward: 2296.0|last_reward_at:  518|Elapsed Time: 0:00:02||
Episode 1|Iteration 553|reward: 2296.0|last_reward_at:  553|Elapsed Time: 0:00:02||
Episode 1|Iteration 563|reward: 2296.0|last_reward_at:  553|Elapsed Time: 0:00:02||
Episode 1|Iteration 570|reward: 2296.0|last_reward_at:  553|Elapsed Time: 0:00:02||
Episode 1|Iteration 578|reward: 2296.0|last_reward_at:  553|Elapsed Time: 0:00:02||
Episode 1|Iteration 592|reward: 2296.0|last_reward_at:  553|Elapsed Time: 0:00:02||
Episode 1|Iteration 594|reward: 2302.0|last_reward_at:  553|Elapsed Time: 0:00:02||
Episode 1|Iteration 594|reward: 2302.0|last_reward_at:  594|Elapsed Time: 0:00:02||
Episode 1|Iteration 600|reward: 2302.0|last_reward_at:  594|Elapsed Time: 0:00:02||

  Episode 1 stopped at t=600
  Breakdown [Reward/NoReward (Success rate)]
    explore-local: 21/231 (0.08)
    explore-remote: 20/317 (0.06)
    explore-connect: 0/0 (NaN)
    exploit-local: 0/0 (NaN)
    exploit-remote: 0/0 (NaN)
    exploit-connect: 11/0 (1.00)
  exploit deflected to exploration: 66
  ## Episode: 2/10 'Credential lookups (ϵ-greedy)' ϵ=0.8535,

Episode 2|Iteration 0|reward: ------|last_reward_at: ----|Elapsed Time: 0:00:00||
Episode 2|Iteration 1|reward:    0.0|last_reward_at: ----|Elapsed Time: 0:00:00||
Episode 2|Iteration 15|reward:   14.0|last_reward_at: ----|Elapsed Time: 0:00:00||
Episode 2|Iteration 15|reward:   14.0|last_reward_at:   15|Elapsed Time: 0:00:00||
Episode 2|Iteration 16|reward:   18.0|last_reward_at:   15|Elapsed Time: 0:00:00||
Episode 2|Iteration 16|reward:   18.0|last_reward_at:   16|Elapsed Time: 0:00:00||
Episode 2|Iteration 20|reward:  118.0|last_reward_at:   16|Elapsed Time: 0:00:00||
Episode 2|Iteration 20|reward:  118.0|last_reward_at:   20|Elapsed Time: 0:00:00||
Episode 2|Iteration 21|reward:  132.0|last_reward_at:   20|Elapsed Time: 0:00:00||
Episode 2|Iteration 21|reward:  132.0|last_reward_at:   21|Elapsed Time: 0:00:00||
Episode 2|Iteration 23|reward:  134.0|last_reward_at:   21|Elapsed Time: 0:00:00||
Episode 2|Iteration 23|reward:  134.0|last_reward_at:   23|Elapsed Time: 0:00:00||
Episode 2|Iteration 24|reward:  234.0|last_reward_at:   23|Elapsed Time: 0:00:00||
Episode 2|Iteration 24|reward:  234.0|last_reward_at:   24|Elapsed Time: 0:00:00||
Episode 2|Iteration 31|reward:  240.0|last_reward_at:   24|Elapsed Time: 0:00:00||
Episode 2|Iteration 31|reward:  240.0|last_reward_at:   31|Elapsed Time: 0:00:00||
Episode 2|Iteration 38|reward:  246.0|last_reward_at:   31|Elapsed Time: 0:00:00||
Episode 2|Iteration 38|reward:  246.0|last_reward_at:   38|Elapsed Time: 0:00:00||
Episode 2|Iteration 49|reward:  252.0|last_reward_at:   38|Elapsed Time: 0:00:00||
Episode 2|Iteration 49|reward:  252.0|last_reward_at:   49|Elapsed Time: 0:00:00||
Episode 2|Iteration 58|reward:  266.0|last_reward_at:   49|Elapsed Time: 0:00:00||
Episode 2|Iteration 58|reward:  266.0|last_reward_at:   58|Elapsed Time: 0:00:00||
Episode 2|Iteration 59|reward:  366.0|last_reward_at:   58|Elapsed Time: 0:00:00||
Episode 2|Iteration 59|reward:  366.0|last_reward_at:   59|Elapsed Time: 0:00:00||
Episode 2|Iteration 71|reward:  368.0|last_reward_at:   59|Elapsed Time: 0:00:00||
Episode 2|Iteration 71|reward:  368.0|last_reward_at:   71|Elapsed Time: 0:00:00||
Episode 2|Iteration 81|reward:  370.0|last_reward_at:   71|Elapsed Time: 0:00:00||
Episode 2|Iteration 81|reward:  370.0|last_reward_at:   81|Elapsed Time: 0:00:00||
Episode 2|Iteration 100|reward:  376.0|last_reward_at:   81|Elapsed Time: 0:00:00||
Episode 2|Iteration 100|reward:  376.0|last_reward_at:  100|Elapsed Time: 0:00:00||
Episode 2|Iteration 117|reward:  387.0|last_reward_at:  100|Elapsed Time: 0:00:00||
Episode 2|Iteration 117|reward:  387.0|last_reward_at:  117|Elapsed Time: 0:00:00||
Episode 2|Iteration 133|reward:  396.0|last_reward_at:  117|Elapsed Time: 0:00:00||
Episode 2|Iteration 133|reward:  396.0|last_reward_at:  133|Elapsed Time: 0:00:00||
Episode 2|Iteration 134|reward:  496.0|last_reward_at:  133|Elapsed Time: 0:00:00||
Episode 2|Iteration 134|reward:  496.0|last_reward_at:  134|Elapsed Time: 0:00:00||
Episode 2|Iteration 135|reward:  502.0|last_reward_at:  134|Elapsed Time: 0:00:00||
Episode 2|Iteration 135|reward:  502.0|last_reward_at:  135|Elapsed Time: 0:00:00||
Episode 2|Iteration 139|reward:  516.0|last_reward_at:  135|Elapsed Time: 0:00:00||
Episode 2|Iteration 139|reward:  516.0|last_reward_at:  139|Elapsed Time: 0:00:00||
Episode 2|Iteration 140|reward:  518.0|last_reward_at:  139|Elapsed Time: 0:00:00||
Episode 2|Iteration 140|reward:  518.0|last_reward_at:  140|Elapsed Time: 0:00:00||
Episode 2|Iteration 141|reward:  618.0|last_reward_at:  140|Elapsed Time: 0:00:00||
Episode 2|Iteration 141|reward:  618.0|last_reward_at:  141|Elapsed Time: 0:00:00||
Episode 2|Iteration 151|reward:  624.0|last_reward_at:  141|Elapsed Time: 0:00:00||
Episode 2|Iteration 151|reward:  624.0|last_reward_at:  151|Elapsed Time: 0:00:00||
Episode 2|Iteration 157|reward:  638.0|last_reward_at:  151|Elapsed Time: 0:00:00||
Episode 2|Iteration 157|reward:  638.0|last_reward_at:  157|Elapsed Time: 0:00:00||
Episode 2|Iteration 161|reward:  640.0|last_reward_at:  157|Elapsed Time: 0:00:00||
Episode 2|Iteration 161|reward:  640.0|last_reward_at:  161|Elapsed Time: 0:00:00||
Episode 2|Iteration 162|reward:  646.0|last_reward_at:  161|Elapsed Time: 0:00:00||
Episode 2|Iteration 162|reward:  646.0|last_reward_at:  162|Elapsed Time: 0:00:00||
Episode 2|Iteration 168|reward:  652.0|last_reward_at:  162|Elapsed Time: 0:00:00||
Episode 2|Iteration 168|reward:  652.0|last_reward_at:  168|Elapsed Time: 0:00:00||
Episode 2|Iteration 170|reward:  658.0|last_reward_at:  168|Elapsed Time: 0:00:00||
Episode 2|Iteration 170|reward:  658.0|last_reward_at:  170|Elapsed Time: 0:00:00||
Episode 2|Iteration 179|reward:  666.0|last_reward_at:  170|Elapsed Time: 0:00:00||
Episode 2|Iteration 179|reward:  666.0|last_reward_at:  179|Elapsed Time: 0:00:00||
Episode 2|Iteration 180|reward:  766.0|last_reward_at:  179|Elapsed Time: 0:00:00||
Episode 2|Iteration 180|reward:  766.0|last_reward_at:  180|Elapsed Time: 0:00:00||
Episode 2|Iteration 198|reward:  766.0|last_reward_at:  180|Elapsed Time: 0:00:00||
Episode 2|Iteration 213|reward:  766.0|last_reward_at:  180|Elapsed Time: 0:00:00||
Episode 2|Iteration 228|reward:  766.0|last_reward_at:  180|Elapsed Time: 0:00:00||
Episode 2|Iteration 244|reward:  766.0|last_reward_at:  180|Elapsed Time: 0:00:00||
Episode 2|Iteration 259|reward:  766.0|last_reward_at:  180|Elapsed Time: 0:00:01||
Episode 2|Iteration 274|reward:  766.0|last_reward_at:  180|Elapsed Time: 0:00:01||
Episode 2|Iteration 289|reward:  766.0|last_reward_at:  180|Elapsed Time: 0:00:01||
Episode 2|Iteration 304|reward:  766.0|last_reward_at:  180|Elapsed Time: 0:00:01||
Episode 2|Iteration 319|reward:  766.0|last_reward_at:  180|Elapsed Time: 0:00:01||
Episode 2|Iteration 325|reward:  777.0|last_reward_at:  180|Elapsed Time: 0:00:01||
Episode 2|Iteration 325|reward:  777.0|last_reward_at:  325|Elapsed Time: 0:00:01||
Episode 2|Iteration 342|reward:  777.0|last_reward_at:  325|Elapsed Time: 0:00:01||
Episode 2|Iteration 357|reward:  777.0|last_reward_at:  325|Elapsed Time: 0:00:01||
Episode 2|Iteration 369|reward:  781.0|last_reward_at:  325|Elapsed Time: 0:00:01||
Episode 2|Iteration 369|reward:  781.0|last_reward_at:  369|Elapsed Time: 0:00:01||
Episode 2|Iteration 388|reward:  781.0|last_reward_at:  369|Elapsed Time: 0:00:01||
Episode 2|Iteration 403|reward:  781.0|last_reward_at:  369|Elapsed Time: 0:00:01||
Episode 2|Iteration 407|reward:  783.0|last_reward_at:  369|Elapsed Time: 0:00:01||
Episode 2|Iteration 407|reward:  783.0|last_reward_at:  407|Elapsed Time: 0:00:01||
Episode 2|Iteration 426|reward:  783.0|last_reward_at:  407|Elapsed Time: 0:00:01||
Episode 2|Iteration 441|reward:  783.0|last_reward_at:  407|Elapsed Time: 0:00:01||
Episode 2|Iteration 454|reward:  792.0|last_reward_at:  407|Elapsed Time: 0:00:01||
Episode 2|Iteration 454|reward:  792.0|last_reward_at:  454|Elapsed Time: 0:00:01||
Episode 2|Iteration 457|reward:  892.0|last_reward_at:  454|Elapsed Time: 0:00:01||
Episode 2|Iteration 457|reward:  892.0|last_reward_at:  457|Elapsed Time: 0:00:01||
Episode 2|Iteration 464|reward:  892.0|last_reward_at:  457|Elapsed Time: 0:00:02||
Episode 2|Iteration 471|reward:  892.0|last_reward_at:  457|Elapsed Time: 0:00:02||
Episode 2|Iteration 479|reward:  892.0|last_reward_at:  457|Elapsed Time: 0:00:02||
Episode 2|Iteration 487|reward:  892.0|last_reward_at:  457|Elapsed Time: 0:00:02||
Episode 2|Iteration 491|reward:  903.0|last_reward_at:  457|Elapsed Time: 0:00:02||
Episode 2|Iteration 491|reward:  903.0|last_reward_at:  491|Elapsed Time: 0:00:02||
Episode 2|Iteration 502|reward:  903.0|last_reward_at:  491|Elapsed Time: 0:00:02||
Episode 2|Iteration 507|reward:  909.0|last_reward_at:  491|Elapsed Time: 0:00:02||
Episode 2|Iteration 507|reward:  909.0|last_reward_at:  507|Elapsed Time: 0:00:02||
Episode 2|Iteration 512|reward:  917.0|last_reward_at:  507|Elapsed Time: 0:00:02||
Episode 2|Iteration 512|reward:  917.0|last_reward_at:  512|Elapsed Time: 0:00:02||
Episode 2|Iteration 525|reward:  917.0|last_reward_at:  512|Elapsed Time: 0:00:02||
Episode 2|Iteration 540|reward:  917.0|last_reward_at:  512|Elapsed Time: 0:00:02||
Episode 2|Iteration 547|reward:  917.0|last_reward_at:  512|Elapsed Time: 0:00:02||
Episode 2|Iteration 555|reward:  917.0|last_reward_at:  512|Elapsed Time: 0:00:02||
Episode 2|Iteration 563|reward:  917.0|last_reward_at:  512|Elapsed Time: 0:00:02||
Episode 2|Iteration 570|reward:  917.0|last_reward_at:  512|Elapsed Time: 0:00:02||
Episode 2|Iteration 578|reward:  917.0|last_reward_at:  512|Elapsed Time: 0:00:02||
Episode 2|Iteration 593|reward:  917.0|last_reward_at:  512|Elapsed Time: 0:00:03||
Episode 2|Iteration 600|reward:  917.0|last_reward_at:  512|Elapsed Time: 0:00:03||
Episode 2|Iteration 600|reward:  917.0|last_reward_at:  512|Elapsed Time: 0:00:03||

  Episode 2 stopped at t=600
  Breakdown [Reward/NoReward (Success rate)]
    explore-local: 14/252 (0.05)
    explore-remote: 16/311 (0.05)
    explore-connect: 0/0 (NaN)
    exploit-local: 0/0 (NaN)
    exploit-remote: 0/0 (NaN)
    exploit-connect: 7/0 (1.00)
  exploit deflected to exploration: 98
  ## Episode: 3/10 'Credential lookups (ϵ-greedy)' ϵ=0.8096,

Episode 3|Iteration 0|reward: ------|last_reward_at: ----|Elapsed Time: 0:00:00||
Episode 3|Iteration 1|reward:    0.0|last_reward_at: ----|Elapsed Time: 0:00:00||
Episode 3|Iteration 3|reward:   14.0|last_reward_at: ----|Elapsed Time: 0:00:00||
Episode 3|Iteration 3|reward:   14.0|last_reward_at:    3|Elapsed Time: 0:00:00||
Episode 3|Iteration 5|reward:  114.0|last_reward_at:    3|Elapsed Time: 0:00:00||
Episode 3|Iteration 5|reward:  114.0|last_reward_at:    5|Elapsed Time: 0:00:00||
Episode 3|Iteration 6|reward:  116.0|last_reward_at:    5|Elapsed Time: 0:00:00||
Episode 3|Iteration 6|reward:  116.0|last_reward_at:    6|Elapsed Time: 0:00:00||
Episode 3|Iteration 7|reward:  118.0|last_reward_at:    6|Elapsed Time: 0:00:00||
Episode 3|Iteration 7|reward:  118.0|last_reward_at:    7|Elapsed Time: 0:00:00||
Episode 3|Iteration 9|reward:  129.0|last_reward_at:    7|Elapsed Time: 0:00:00||
Episode 3|Iteration 9|reward:  129.0|last_reward_at:    9|Elapsed Time: 0:00:00||
Episode 3|Iteration 12|reward:  137.0|last_reward_at:    9|Elapsed Time: 0:00:00||
Episode 3|Iteration 12|reward:  137.0|last_reward_at:   12|Elapsed Time: 0:00:00||
Episode 3|Iteration 20|reward:  143.0|last_reward_at:   12|Elapsed Time: 0:00:00||
Episode 3|Iteration 20|reward:  143.0|last_reward_at:   20|Elapsed Time: 0:00:00||
Episode 3|Iteration 34|reward:  152.0|last_reward_at:   20|Elapsed Time: 0:00:00||
Episode 3|Iteration 34|reward:  152.0|last_reward_at:   34|Elapsed Time: 0:00:00||
Episode 3|Iteration 53|reward:  252.0|last_reward_at:   34|Elapsed Time: 0:00:00||
Episode 3|Iteration 53|reward:  252.0|last_reward_at:   53|Elapsed Time: 0:00:00||
Episode 3|Iteration 56|reward:  266.0|last_reward_at:   53|Elapsed Time: 0:00:00||
Episode 3|Iteration 56|reward:  266.0|last_reward_at:   56|Elapsed Time: 0:00:00||
Episode 3|Iteration 57|reward:  272.0|last_reward_at:   56|Elapsed Time: 0:00:00||
Episode 3|Iteration 57|reward:  272.0|last_reward_at:   57|Elapsed Time: 0:00:00||
Episode 3|Iteration 60|reward:  372.0|last_reward_at:   57|Elapsed Time: 0:00:00||
Episode 3|Iteration 60|reward:  372.0|last_reward_at:   60|Elapsed Time: 0:00:00||
Episode 3|Iteration 66|reward:  374.0|last_reward_at:   60|Elapsed Time: 0:00:00||
Episode 3|Iteration 66|reward:  374.0|last_reward_at:   66|Elapsed Time: 0:00:00||
Episode 3|Iteration 76|reward:  374.0|last_reward_at:   66|Elapsed Time: 0:00:00||
Episode 3|Iteration 82|reward:  388.0|last_reward_at:   66|Elapsed Time: 0:00:00||
Episode 3|Iteration 82|reward:  388.0|last_reward_at:   82|Elapsed Time: 0:00:00||
Episode 3|Iteration 88|reward:  394.0|last_reward_at:   82|Elapsed Time: 0:00:00||
Episode 3|Iteration 88|reward:  394.0|last_reward_at:   88|Elapsed Time: 0:00:00||
Episode 3|Iteration 89|reward:  494.0|last_reward_at:   88|Elapsed Time: 0:00:00||
Episode 3|Iteration 89|reward:  494.0|last_reward_at:   89|Elapsed Time: 0:00:00||
Episode 3|Iteration 90|reward:  496.0|last_reward_at:   89|Elapsed Time: 0:00:00||
Episode 3|Iteration 90|reward:  496.0|last_reward_at:   90|Elapsed Time: 0:00:00||
Episode 3|Iteration 92|reward:  502.0|last_reward_at:   90|Elapsed Time: 0:00:00||
Episode 3|Iteration 92|reward:  502.0|last_reward_at:   92|Elapsed Time: 0:00:00||
Episode 3|Iteration 96|reward:  513.0|last_reward_at:   92|Elapsed Time: 0:00:00||
Episode 3|Iteration 96|reward:  513.0|last_reward_at:   96|Elapsed Time: 0:00:00||
Episode 3|Iteration 98|reward:  517.0|last_reward_at:   96|Elapsed Time: 0:00:00||
Episode 3|Iteration 98|reward:  517.0|last_reward_at:   98|Elapsed Time: 0:00:00||
Episode 3|Iteration 101|reward:  523.0|last_reward_at:   98|Elapsed Time: 0:00:00||
Episode 3|Iteration 101|reward:  523.0|last_reward_at:  101|Elapsed Time: 0:00:00||
Episode 3|Iteration 105|reward:  525.0|last_reward_at:  101|Elapsed Time: 0:00:00||
Episode 3|Iteration 105|reward:  525.0|last_reward_at:  105|Elapsed Time: 0:00:00||
Episode 3|Iteration 122|reward:  525.0|last_reward_at:  105|Elapsed Time: 0:00:00||
Episode 3|Iteration 123|reward:  534.0|last_reward_at:  105|Elapsed Time: 0:00:00||
Episode 3|Iteration 123|reward:  534.0|last_reward_at:  123|Elapsed Time: 0:00:00||
Episode 3|Iteration 125|reward:  634.0|last_reward_at:  123|Elapsed Time: 0:00:00||
Episode 3|Iteration 125|reward:  634.0|last_reward_at:  125|Elapsed Time: 0:00:00||
Episode 3|Iteration 136|reward:  645.0|last_reward_at:  125|Elapsed Time: 0:00:00||
Episode 3|Iteration 136|reward:  645.0|last_reward_at:  136|Elapsed Time: 0:00:00||
Episode 3|Iteration 140|reward:  651.0|last_reward_at:  136|Elapsed Time: 0:00:00||
Episode 3|Iteration 140|reward:  651.0|last_reward_at:  140|Elapsed Time: 0:00:00||
Episode 3|Iteration 144|reward:  659.0|last_reward_at:  140|Elapsed Time: 0:00:00||
Episode 3|Iteration 144|reward:  659.0|last_reward_at:  144|Elapsed Time: 0:00:00||
Episode 3|Iteration 152|reward:  659.0|last_reward_at:  144|Elapsed Time: 0:00:00||
Episode 3|Iteration 168|reward:  659.0|last_reward_at:  144|Elapsed Time: 0:00:00||
Episode 3|Iteration 175|reward:  659.0|last_reward_at:  144|Elapsed Time: 0:00:00||
Episode 3|Iteration 181|reward:  668.0|last_reward_at:  144|Elapsed Time: 0:00:01||
Episode 3|Iteration 181|reward:  668.0|last_reward_at:  181|Elapsed Time: 0:00:01||
Episode 3|Iteration 190|reward:  768.0|last_reward_at:  181|Elapsed Time: 0:00:01||
Episode 3|Iteration 190|reward:  768.0|last_reward_at:  190|Elapsed Time: 0:00:01||
Episode 3|Iteration 206|reward:  768.0|last_reward_at:  190|Elapsed Time: 0:00:01||
Episode 3|Iteration 213|reward:  768.0|last_reward_at:  190|Elapsed Time: 0:00:01||
Episode 3|Iteration 221|reward:  768.0|last_reward_at:  190|Elapsed Time: 0:00:01||
Episode 3|Iteration 224|reward:  779.0|last_reward_at:  190|Elapsed Time: 0:00:01||
Episode 3|Iteration 224|reward:  779.0|last_reward_at:  224|Elapsed Time: 0:00:01||
Episode 3|Iteration 241|reward:  781.0|last_reward_at:  224|Elapsed Time: 0:00:01||
Episode 3|Iteration 241|reward:  781.0|last_reward_at:  241|Elapsed Time: 0:00:01||
Episode 3|Iteration 247|reward:  785.0|last_reward_at:  241|Elapsed Time: 0:00:01||
Episode 3|Iteration 247|reward:  785.0|last_reward_at:  247|Elapsed Time: 0:00:01||
Episode 3|Iteration 259|reward:  785.0|last_reward_at:  247|Elapsed Time: 0:00:01||
Episode 3|Iteration 274|reward:  785.0|last_reward_at:  247|Elapsed Time: 0:00:01||
Episode 3|Iteration 289|reward:  785.0|last_reward_at:  247|Elapsed Time: 0:00:01||
Episode 3|Iteration 292|reward:  794.0|last_reward_at:  247|Elapsed Time: 0:00:01||
Episode 3|Iteration 292|reward:  794.0|last_reward_at:  292|Elapsed Time: 0:00:01||
Episode 3|Iteration 296|reward:  894.0|last_reward_at:  292|Elapsed Time: 0:00:01||
Episode 3|Iteration 296|reward:  894.0|last_reward_at:  296|Elapsed Time: 0:00:01||
Episode 3|Iteration 312|reward:  894.0|last_reward_at:  296|Elapsed Time: 0:00:01||
Episode 3|Iteration 327|reward:  894.0|last_reward_at:  296|Elapsed Time: 0:00:01||
Episode 3|Iteration 335|reward:  894.0|last_reward_at:  296|Elapsed Time: 0:00:01||
Episode 3|Iteration 350|reward:  894.0|last_reward_at:  296|Elapsed Time: 0:00:01||
Episode 3|Iteration 365|reward:  894.0|last_reward_at:  296|Elapsed Time: 0:00:02||
Episode 3|Iteration 373|reward:  894.0|last_reward_at:  296|Elapsed Time: 0:00:02||
Episode 3|Iteration 388|reward:  894.0|last_reward_at:  296|Elapsed Time: 0:00:02||
Episode 3|Iteration 403|reward:  894.0|last_reward_at:  296|Elapsed Time: 0:00:02||
Episode 3|Iteration 418|reward:  894.0|last_reward_at:  296|Elapsed Time: 0:00:02||
Episode 3|Iteration 433|reward:  894.0|last_reward_at:  296|Elapsed Time: 0:00:02||
Episode 3|Iteration 449|reward:  894.0|last_reward_at:  296|Elapsed Time: 0:00:02||
Episode 3|Iteration 464|reward:  894.0|last_reward_at:  296|Elapsed Time: 0:00:02||
Episode 3|Iteration 479|reward:  894.0|last_reward_at:  296|Elapsed Time: 0:00:02||
Episode 3|Iteration 494|reward:  894.0|last_reward_at:  296|Elapsed Time: 0:00:02||
Episode 3|Iteration 508|reward:  908.0|last_reward_at:  296|Elapsed Time: 0:00:02||
Episode 3|Iteration 508|reward:  908.0|last_reward_at:  508|Elapsed Time: 0:00:02||
Episode 3|Iteration 511|reward: 1008.0|last_reward_at:  508|Elapsed Time: 0:00:02||
Episode 3|Iteration 511|reward: 1008.0|last_reward_at:  511|Elapsed Time: 0:00:02||
Episode 3|Iteration 514|reward: 1019.0|last_reward_at:  511|Elapsed Time: 0:00:02||
Episode 3|Iteration 514|reward: 1019.0|last_reward_at:  514|Elapsed Time: 0:00:02||
Episode 3|Iteration 522|reward: 1023.0|last_reward_at:  514|Elapsed Time: 0:00:02||
Episode 3|Iteration 522|reward: 1023.0|last_reward_at:  522|Elapsed Time: 0:00:02||
Episode 3|Iteration 534|reward: 1029.0|last_reward_at:  522|Elapsed Time: 0:00:02||
Episode 3|Iteration 534|reward: 1029.0|last_reward_at:  534|Elapsed Time: 0:00:02||
Episode 3|Iteration 538|reward: 1038.0|last_reward_at:  534|Elapsed Time: 0:00:02||
Episode 3|Iteration 538|reward: 1038.0|last_reward_at:  538|Elapsed Time: 0:00:02||
Episode 3|Iteration 542|reward: 1138.0|last_reward_at:  538|Elapsed Time: 0:00:02||
Episode 3|Iteration 542|reward: 1138.0|last_reward_at:  542|Elapsed Time: 0:00:02||
Episode 3|Iteration 550|reward: 1140.0|last_reward_at:  542|Elapsed Time: 0:00:03||
Episode 3|Iteration 550|reward: 1140.0|last_reward_at:  550|Elapsed Time: 0:00:03||
Episode 3|Iteration 563|reward: 1140.0|last_reward_at:  550|Elapsed Time: 0:00:03||
Episode 3|Iteration 565|reward: 1154.0|last_reward_at:  550|Elapsed Time: 0:00:03||
Episode 3|Iteration 565|reward: 1154.0|last_reward_at:  565|Elapsed Time: 0:00:03||
Episode 3|Iteration 570|reward: 1254.0|last_reward_at:  565|Elapsed Time: 0:00:03||
Episode 3|Iteration 570|reward: 1254.0|last_reward_at:  570|Elapsed Time: 0:00:03||
Episode 3|Iteration 578|reward: 1254.0|last_reward_at:  570|Elapsed Time: 0:00:03||
Episode 3|Iteration 586|reward: 1260.0|last_reward_at:  570|Elapsed Time: 0:00:03||
Episode 3|Iteration 586|reward: 1260.0|last_reward_at:  586|Elapsed Time: 0:00:03||
Episode 3|Iteration 589|reward: 1266.0|last_reward_at:  586|Elapsed Time: 0:00:03||
Episode 3|Iteration 589|reward: 1266.0|last_reward_at:  589|Elapsed Time: 0:00:03||
Episode 3|Iteration 600|reward: 1266.0|last_reward_at:  589|Elapsed Time: 0:00:03||
Episode 3|Iteration 600|reward: 1272.0|last_reward_at:  589|Elapsed Time: 0:00:03||
Episode 3|Iteration 600|reward: 1272.0|last_reward_at:  600|Elapsed Time: 0:00:03||
Episode 3|Iteration 600|reward: 1272.0|last_reward_at:  600|Elapsed Time: 0:00:03||

  Episode 3 stopped at t=600
  Breakdown [Reward/NoReward (Success rate)]
    explore-local: 19/250 (0.07)
    explore-remote: 18/303 (0.06)
    explore-connect: 0/0 (NaN)
    exploit-local: 0/0 (NaN)
    exploit-remote: 0/0 (NaN)
    exploit-connect: 10/0 (1.00)
  exploit deflected to exploration: 111
  ## Episode: 4/10 'Credential lookups (ϵ-greedy)' ϵ=0.7683,

Episode 4|Iteration 0|reward: ------|last_reward_at: ----|Elapsed Time: 0:00:00||
Episode 4|Iteration 1|reward:    0.0|last_reward_at: ----|Elapsed Time: 0:00:00||
Episode 4|Iteration 19|reward:   14.0|last_reward_at: ----|Elapsed Time: 0:00:00||
Episode 4|Iteration 19|reward:   14.0|last_reward_at:   19|Elapsed Time: 0:00:00||
Episode 4|Iteration 20|reward:  114.0|last_reward_at:   19|Elapsed Time: 0:00:00||
Episode 4|Iteration 20|reward:  114.0|last_reward_at:   20|Elapsed Time: 0:00:00||
Episode 4|Iteration 23|reward:  116.0|last_reward_at:   20|Elapsed Time: 0:00:00||
Episode 4|Iteration 23|reward:  116.0|last_reward_at:   23|Elapsed Time: 0:00:00||
Episode 4|Iteration 25|reward:  118.0|last_reward_at:   23|Elapsed Time: 0:00:00||
Episode 4|Iteration 25|reward:  118.0|last_reward_at:   25|Elapsed Time: 0:00:00||
Episode 4|Iteration 28|reward:  129.0|last_reward_at:   25|Elapsed Time: 0:00:00||
Episode 4|Iteration 28|reward:  129.0|last_reward_at:   28|Elapsed Time: 0:00:00||
Episode 4|Iteration 37|reward:  138.0|last_reward_at:   28|Elapsed Time: 0:00:00||
Episode 4|Iteration 37|reward:  138.0|last_reward_at:   37|Elapsed Time: 0:00:00||
Episode 4|Iteration 38|reward:  238.0|last_reward_at:   37|Elapsed Time: 0:00:00||
Episode 4|Iteration 38|reward:  238.0|last_reward_at:   38|Elapsed Time: 0:00:00||
Episode 4|Iteration 43|reward:  249.0|last_reward_at:   38|Elapsed Time: 0:00:00||
Episode 4|Iteration 43|reward:  249.0|last_reward_at:   43|Elapsed Time: 0:00:00||
Episode 4|Iteration 45|reward:  258.0|last_reward_at:   43|Elapsed Time: 0:00:00||
Episode 4|Iteration 45|reward:  258.0|last_reward_at:   45|Elapsed Time: 0:00:00||
Episode 4|Iteration 46|reward:  358.0|last_reward_at:   45|Elapsed Time: 0:00:00||
Episode 4|Iteration 46|reward:  358.0|last_reward_at:   46|Elapsed Time: 0:00:00||
Episode 4|Iteration 48|reward:  360.0|last_reward_at:   46|Elapsed Time: 0:00:00||
Episode 4|Iteration 48|reward:  360.0|last_reward_at:   48|Elapsed Time: 0:00:00||
Episode 4|Iteration 54|reward:  366.0|last_reward_at:   48|Elapsed Time: 0:00:00||
Episode 4|Iteration 54|reward:  366.0|last_reward_at:   54|Elapsed Time: 0:00:00||
Episode 4|Iteration 63|reward:  368.0|last_reward_at:   54|Elapsed Time: 0:00:00||
Episode 4|Iteration 63|reward:  368.0|last_reward_at:   63|Elapsed Time: 0:00:00||
Episode 4|Iteration 64|reward:  374.0|last_reward_at:   63|Elapsed Time: 0:00:00||
Episode 4|Iteration 64|reward:  374.0|last_reward_at:   64|Elapsed Time: 0:00:00||
Episode 4|Iteration 84|reward:  374.0|last_reward_at:   64|Elapsed Time: 0:00:00||
Episode 4|Iteration 99|reward:  374.0|last_reward_at:   64|Elapsed Time: 0:00:00||
Episode 4|Iteration 106|reward:  385.0|last_reward_at:   64|Elapsed Time: 0:00:00||
Episode 4|Iteration 106|reward:  385.0|last_reward_at:  106|Elapsed Time: 0:00:00||
Episode 4|Iteration 107|reward:  391.0|last_reward_at:  106|Elapsed Time: 0:00:00||
Episode 4|Iteration 107|reward:  391.0|last_reward_at:  107|Elapsed Time: 0:00:00||
Episode 4|Iteration 114|reward:  400.0|last_reward_at:  107|Elapsed Time: 0:00:00||
Episode 4|Iteration 114|reward:  400.0|last_reward_at:  114|Elapsed Time: 0:00:00||
Episode 4|Iteration 121|reward:  500.0|last_reward_at:  114|Elapsed Time: 0:00:00||
Episode 4|Iteration 121|reward:  500.0|last_reward_at:  121|Elapsed Time: 0:00:00||
Episode 4|Iteration 133|reward:  511.0|last_reward_at:  121|Elapsed Time: 0:00:00||
Episode 4|Iteration 133|reward:  511.0|last_reward_at:  133|Elapsed Time: 0:00:00||
Episode 4|Iteration 137|reward:  520.0|last_reward_at:  133|Elapsed Time: 0:00:00||
Episode 4|Iteration 137|reward:  520.0|last_reward_at:  137|Elapsed Time: 0:00:00||
Episode 4|Iteration 142|reward:  620.0|last_reward_at:  137|Elapsed Time: 0:00:00||
Episode 4|Iteration 142|reward:  620.0|last_reward_at:  142|Elapsed Time: 0:00:00||
Episode 4|Iteration 145|reward:  622.0|last_reward_at:  142|Elapsed Time: 0:00:00||
Episode 4|Iteration 145|reward:  622.0|last_reward_at:  145|Elapsed Time: 0:00:00||
Episode 4|Iteration 152|reward:  628.0|last_reward_at:  145|Elapsed Time: 0:00:00||
Episode 4|Iteration 152|reward:  628.0|last_reward_at:  152|Elapsed Time: 0:00:00||
Episode 4|Iteration 168|reward:  628.0|last_reward_at:  152|Elapsed Time: 0:00:00||
Episode 4|Iteration 168|reward:  630.0|last_reward_at:  152|Elapsed Time: 0:00:00||
Episode 4|Iteration 168|reward:  630.0|last_reward_at:  168|Elapsed Time: 0:00:00||
Episode 4|Iteration 179|reward:  641.0|last_reward_at:  168|Elapsed Time: 0:00:00||
Episode 4|Iteration 179|reward:  641.0|last_reward_at:  179|Elapsed Time: 0:00:00||
Episode 4|Iteration 198|reward:  641.0|last_reward_at:  179|Elapsed Time: 0:00:00||
Episode 4|Iteration 213|reward:  641.0|last_reward_at:  179|Elapsed Time: 0:00:00||
Episode 4|Iteration 228|reward:  641.0|last_reward_at:  179|Elapsed Time: 0:00:00||
Episode 4|Iteration 236|reward:  649.0|last_reward_at:  179|Elapsed Time: 0:00:00||
Episode 4|Iteration 236|reward:  649.0|last_reward_at:  236|Elapsed Time: 0:00:00||
Episode 4|Iteration 251|reward:  649.0|last_reward_at:  236|Elapsed Time: 0:00:00||
Episode 4|Iteration 251|reward:  655.0|last_reward_at:  236|Elapsed Time: 0:00:00||
Episode 4|Iteration 251|reward:  655.0|last_reward_at:  251|Elapsed Time: 0:00:00||
Episode 4|Iteration 266|reward:  655.0|last_reward_at:  251|Elapsed Time: 0:00:01||
Episode 4|Iteration 282|reward:  655.0|last_reward_at:  251|Elapsed Time: 0:00:01||
Episode 4|Iteration 297|reward:  655.0|last_reward_at:  251|Elapsed Time: 0:00:01||
Episode 4|Iteration 312|reward:  655.0|last_reward_at:  251|Elapsed Time: 0:00:01||
Episode 4|Iteration 323|reward:  664.0|last_reward_at:  251|Elapsed Time: 0:00:01||
Episode 4|Iteration 323|reward:  664.0|last_reward_at:  323|Elapsed Time: 0:00:01||
Episode 4|Iteration 324|reward:  764.0|last_reward_at:  323|Elapsed Time: 0:00:01||
Episode 4|Iteration 324|reward:  764.0|last_reward_at:  324|Elapsed Time: 0:00:01||
Episode 4|Iteration 342|reward:  764.0|last_reward_at:  324|Elapsed Time: 0:00:01||
Episode 4|Iteration 350|reward:  764.0|last_reward_at:  324|Elapsed Time: 0:00:01||
Episode 4|Iteration 352|reward:  778.0|last_reward_at:  324|Elapsed Time: 0:00:01||
Episode 4|Iteration 352|reward:  778.0|last_reward_at:  352|Elapsed Time: 0:00:01||
Episode 4|Iteration 354|reward:  878.0|last_reward_at:  352|Elapsed Time: 0:00:01||
Episode 4|Iteration 354|reward:  878.0|last_reward_at:  354|Elapsed Time: 0:00:01||
Episode 4|Iteration 361|reward:  880.0|last_reward_at:  354|Elapsed Time: 0:00:01||
Episode 4|Iteration 361|reward:  880.0|last_reward_at:  361|Elapsed Time: 0:00:01||
Episode 4|Iteration 369|reward:  882.0|last_reward_at:  361|Elapsed Time: 0:00:01||
Episode 4|Iteration 369|reward:  882.0|last_reward_at:  369|Elapsed Time: 0:00:01||
Episode 4|Iteration 371|reward:  888.0|last_reward_at:  369|Elapsed Time: 0:00:01||
Episode 4|Iteration 371|reward:  888.0|last_reward_at:  371|Elapsed Time: 0:00:01||
Episode 4|Iteration 374|reward:  902.0|last_reward_at:  371|Elapsed Time: 0:00:01||
Episode 4|Iteration 374|reward:  902.0|last_reward_at:  374|Elapsed Time: 0:00:01||
Episode 4|Iteration 378|reward: 1002.0|last_reward_at:  374|Elapsed Time: 0:00:01||
Episode 4|Iteration 378|reward: 1002.0|last_reward_at:  378|Elapsed Time: 0:00:01||
Episode 4|Iteration 388|reward: 1002.0|last_reward_at:  378|Elapsed Time: 0:00:01||
Episode 4|Iteration 402|reward: 1008.0|last_reward_at:  378|Elapsed Time: 0:00:01||
Episode 4|Iteration 402|reward: 1008.0|last_reward_at:  402|Elapsed Time: 0:00:01||
Episode 4|Iteration 411|reward: 1008.0|last_reward_at:  402|Elapsed Time: 0:00:01||
Episode 4|Iteration 426|reward: 1008.0|last_reward_at:  402|Elapsed Time: 0:00:01||
Episode 4|Iteration 433|reward: 1008.0|last_reward_at:  402|Elapsed Time: 0:00:01||
Episode 4|Iteration 441|reward: 1008.0|last_reward_at:  402|Elapsed Time: 0:00:01||
Episode 4|Iteration 445|reward: 1019.0|last_reward_at:  402|Elapsed Time: 0:00:02||
Episode 4|Iteration 445|reward: 1019.0|last_reward_at:  445|Elapsed Time: 0:00:02||
Episode 4|Iteration 446|reward: 1025.0|last_reward_at:  445|Elapsed Time: 0:00:02||
Episode 4|Iteration 446|reward: 1025.0|last_reward_at:  446|Elapsed Time: 0:00:02||
Episode 4|Iteration 453|reward: 1027.0|last_reward_at:  446|Elapsed Time: 0:00:02||
Episode 4|Iteration 453|reward: 1027.0|last_reward_at:  453|Elapsed Time: 0:00:02||
Episode 4|Iteration 464|reward: 1027.0|last_reward_at:  453|Elapsed Time: 0:00:02||
Episode 4|Iteration 471|reward: 1027.0|last_reward_at:  453|Elapsed Time: 0:00:02||
Episode 4|Iteration 481|reward: 1033.0|last_reward_at:  453|Elapsed Time: 0:00:02||
Episode 4|Iteration 481|reward: 1033.0|last_reward_at:  481|Elapsed Time: 0:00:02||
Episode 4|Iteration 487|reward: 1033.0|last_reward_at:  481|Elapsed Time: 0:00:02||
Episode 4|Iteration 494|reward: 1033.0|last_reward_at:  481|Elapsed Time: 0:00:02||
Episode 4|Iteration 497|reward: 1037.0|last_reward_at:  481|Elapsed Time: 0:00:02||
Episode 4|Iteration 497|reward: 1037.0|last_reward_at:  497|Elapsed Time: 0:00:02||
Episode 4|Iteration 509|reward: 1037.0|last_reward_at:  497|Elapsed Time: 0:00:02||
Episode 4|Iteration 525|reward: 1037.0|last_reward_at:  497|Elapsed Time: 0:00:02||
Episode 4|Iteration 532|reward: 1037.0|last_reward_at:  497|Elapsed Time: 0:00:02||
Episode 4|Iteration 547|reward: 1037.0|last_reward_at:  497|Elapsed Time: 0:00:02||
Episode 4|Iteration 555|reward: 1037.0|last_reward_at:  497|Elapsed Time: 0:00:02||
Episode 4|Iteration 570|reward: 1037.0|last_reward_at:  497|Elapsed Time: 0:00:02||
Episode 4|Iteration 585|reward: 1037.0|last_reward_at:  497|Elapsed Time: 0:00:02||
Episode 4|Iteration 600|reward: 1037.0|last_reward_at:  497|Elapsed Time: 0:00:03||
Episode 4|Iteration 600|reward: 1037.0|last_reward_at:  497|Elapsed Time: 0:00:03||

  Episode 4 stopped at t=600
  Breakdown [Reward/NoReward (Success rate)]
    explore-local: 16/248 (0.06)
    explore-remote: 18/310 (0.05)
    explore-connect: 0/0 (NaN)
    exploit-local: 0/0 (NaN)
    exploit-remote: 0/0 (NaN)
    exploit-connect: 8/0 (1.00)
  exploit deflected to exploration: 139
  ## Episode: 5/10 'Credential lookups (ϵ-greedy)' ϵ=0.7294,

Episode 5|Iteration 0|reward: ------|last_reward_at: ----|Elapsed Time: 0:00:00||
Episode 5|Iteration 1|reward:    0.0|last_reward_at: ----|Elapsed Time: 0:00:00||
Episode 5|Iteration 14|reward:   14.0|last_reward_at: ----|Elapsed Time: 0:00:00||
Episode 5|Iteration 14|reward:   14.0|last_reward_at:   14|Elapsed Time: 0:00:00||
Episode 5|Iteration 15|reward:  114.0|last_reward_at:   14|Elapsed Time: 0:00:00||
Episode 5|Iteration 15|reward:  114.0|last_reward_at:   15|Elapsed Time: 0:00:00||
Episode 5|Iteration 16|reward:  116.0|last_reward_at:   15|Elapsed Time: 0:00:00||
Episode 5|Iteration 16|reward:  116.0|last_reward_at:   16|Elapsed Time: 0:00:00||
Episode 5|Iteration 27|reward:  118.0|last_reward_at:   16|Elapsed Time: 0:00:00||
Episode 5|Iteration 27|reward:  118.0|last_reward_at:   27|Elapsed Time: 0:00:00||
Episode 5|Iteration 35|reward:  129.0|last_reward_at:   27|Elapsed Time: 0:00:00||
Episode 5|Iteration 35|reward:  129.0|last_reward_at:   35|Elapsed Time: 0:00:00||
Episode 5|Iteration 39|reward:  135.0|last_reward_at:   35|Elapsed Time: 0:00:00||
Episode 5|Iteration 39|reward:  135.0|last_reward_at:   39|Elapsed Time: 0:00:00||
Episode 5|Iteration 40|reward:  143.0|last_reward_at:   39|Elapsed Time: 0:00:00||
Episode 5|Iteration 40|reward:  143.0|last_reward_at:   40|Elapsed Time: 0:00:00||
Episode 5|Iteration 41|reward:  152.0|last_reward_at:   40|Elapsed Time: 0:00:00||
Episode 5|Iteration 41|reward:  152.0|last_reward_at:   41|Elapsed Time: 0:00:00||
Episode 5|Iteration 47|reward:  252.0|last_reward_at:   41|Elapsed Time: 0:00:00||
Episode 5|Iteration 47|reward:  252.0|last_reward_at:   47|Elapsed Time: 0:00:00||
Episode 5|Iteration 59|reward:  266.0|last_reward_at:   47|Elapsed Time: 0:00:00||
Episode 5|Iteration 59|reward:  266.0|last_reward_at:   59|Elapsed Time: 0:00:00||
Episode 5|Iteration 60|reward:  366.0|last_reward_at:   59|Elapsed Time: 0:00:00||
Episode 5|Iteration 60|reward:  366.0|last_reward_at:   60|Elapsed Time: 0:00:00||
Episode 5|Iteration 72|reward:  368.0|last_reward_at:   60|Elapsed Time: 0:00:00||
Episode 5|Iteration 72|reward:  368.0|last_reward_at:   72|Elapsed Time: 0:00:00||
Episode 5|Iteration 77|reward:  374.0|last_reward_at:   72|Elapsed Time: 0:00:00||
Episode 5|Iteration 77|reward:  374.0|last_reward_at:   77|Elapsed Time: 0:00:00||
Episode 5|Iteration 79|reward:  388.0|last_reward_at:   77|Elapsed Time: 0:00:00||
Episode 5|Iteration 79|reward:  388.0|last_reward_at:   79|Elapsed Time: 0:00:00||
Episode 5|Iteration 80|reward:  488.0|last_reward_at:   79|Elapsed Time: 0:00:00||
Episode 5|Iteration 80|reward:  488.0|last_reward_at:   80|Elapsed Time: 0:00:00||
Episode 5|Iteration 84|reward:  494.0|last_reward_at:   80|Elapsed Time: 0:00:00||
Episode 5|Iteration 84|reward:  494.0|last_reward_at:   84|Elapsed Time: 0:00:00||
Episode 5|Iteration 88|reward:  505.0|last_reward_at:   84|Elapsed Time: 0:00:00||
Episode 5|Iteration 88|reward:  505.0|last_reward_at:   88|Elapsed Time: 0:00:00||
Episode 5|Iteration 92|reward:  507.0|last_reward_at:   88|Elapsed Time: 0:00:00||
Episode 5|Iteration 92|reward:  507.0|last_reward_at:   92|Elapsed Time: 0:00:00||
Episode 5|Iteration 105|reward:  513.0|last_reward_at:   92|Elapsed Time: 0:00:00||
Episode 5|Iteration 105|reward:  513.0|last_reward_at:  105|Elapsed Time: 0:00:00||
Episode 5|Iteration 114|reward:  517.0|last_reward_at:  105|Elapsed Time: 0:00:00||
Episode 5|Iteration 114|reward:  517.0|last_reward_at:  114|Elapsed Time: 0:00:00||
Episode 5|Iteration 121|reward:  519.0|last_reward_at:  114|Elapsed Time: 0:00:00||
Episode 5|Iteration 121|reward:  519.0|last_reward_at:  121|Elapsed Time: 0:00:00||
Episode 5|Iteration 123|reward:  525.0|last_reward_at:  121|Elapsed Time: 0:00:00||
Episode 5|Iteration 123|reward:  525.0|last_reward_at:  123|Elapsed Time: 0:00:00||
Episode 5|Iteration 125|reward:  534.0|last_reward_at:  123|Elapsed Time: 0:00:00||
Episode 5|Iteration 125|reward:  534.0|last_reward_at:  125|Elapsed Time: 0:00:00||
Episode 5|Iteration 126|reward:  634.0|last_reward_at:  125|Elapsed Time: 0:00:00||
Episode 5|Iteration 126|reward:  634.0|last_reward_at:  126|Elapsed Time: 0:00:00||
Episode 5|Iteration 134|reward:  648.0|last_reward_at:  126|Elapsed Time: 0:00:00||
Episode 5|Iteration 134|reward:  648.0|last_reward_at:  134|Elapsed Time: 0:00:00||
Episode 5|Iteration 137|reward:  748.0|last_reward_at:  134|Elapsed Time: 0:00:00||
Episode 5|Iteration 137|reward:  748.0|last_reward_at:  137|Elapsed Time: 0:00:00||
Episode 5|Iteration 145|reward:  748.0|last_reward_at:  137|Elapsed Time: 0:00:00||
Episode 5|Iteration 147|reward:  754.0|last_reward_at:  137|Elapsed Time: 0:00:00||
Episode 5|Iteration 147|reward:  754.0|last_reward_at:  147|Elapsed Time: 0:00:00||
Episode 5|Iteration 160|reward:  754.0|last_reward_at:  147|Elapsed Time: 0:00:00||
Episode 5|Iteration 163|reward:  760.0|last_reward_at:  147|Elapsed Time: 0:00:00||
Episode 5|Iteration 163|reward:  760.0|last_reward_at:  163|Elapsed Time: 0:00:00||
Episode 5|Iteration 175|reward:  760.0|last_reward_at:  163|Elapsed Time: 0:00:00||
Episode 5|Iteration 183|reward:  760.0|last_reward_at:  163|Elapsed Time: 0:00:00||
Episode 5|Iteration 198|reward:  760.0|last_reward_at:  163|Elapsed Time: 0:00:00||
Episode 5|Iteration 199|reward:  766.0|last_reward_at:  163|Elapsed Time: 0:00:00||
Episode 5|Iteration 199|reward:  766.0|last_reward_at:  199|Elapsed Time: 0:00:00||
Episode 5|Iteration 221|reward:  766.0|last_reward_at:  199|Elapsed Time: 0:00:01||
Episode 5|Iteration 228|reward:  777.0|last_reward_at:  199|Elapsed Time: 0:00:01||
Episode 5|Iteration 228|reward:  777.0|last_reward_at:  228|Elapsed Time: 0:00:01||
Episode 5|Iteration 230|reward:  779.0|last_reward_at:  228|Elapsed Time: 0:00:01||
Episode 5|Iteration 230|reward:  779.0|last_reward_at:  230|Elapsed Time: 0:00:01||
Episode 5|Iteration 231|reward:  783.0|last_reward_at:  230|Elapsed Time: 0:00:01||
Episode 5|Iteration 231|reward:  783.0|last_reward_at:  231|Elapsed Time: 0:00:01||
Episode 5|Iteration 232|reward:  792.0|last_reward_at:  231|Elapsed Time: 0:00:01||
Episode 5|Iteration 232|reward:  792.0|last_reward_at:  232|Elapsed Time: 0:00:01||
Episode 5|Iteration 237|reward:  892.0|last_reward_at:  232|Elapsed Time: 0:00:01||
Episode 5|Iteration 237|reward:  892.0|last_reward_at:  237|Elapsed Time: 0:00:01||
Episode 5|Iteration 246|reward:  906.0|last_reward_at:  237|Elapsed Time: 0:00:01||
Episode 5|Iteration 246|reward:  906.0|last_reward_at:  246|Elapsed Time: 0:00:01||
Episode 5|Iteration 251|reward: 1006.0|last_reward_at:  246|Elapsed Time: 0:00:01||
Episode 5|Iteration 251|reward: 1006.0|last_reward_at:  251|Elapsed Time: 0:00:01||
Episode 5|Iteration 254|reward: 1017.0|last_reward_at:  251|Elapsed Time: 0:00:01||
Episode 5|Iteration 254|reward: 1017.0|last_reward_at:  254|Elapsed Time: 0:00:01||
Episode 5|Iteration 261|reward: 1021.0|last_reward_at:  254|Elapsed Time: 0:00:01||
Episode 5|Iteration 261|reward: 1021.0|last_reward_at:  261|Elapsed Time: 0:00:01||
Episode 5|Iteration 274|reward: 1021.0|last_reward_at:  261|Elapsed Time: 0:00:01||
Episode 5|Iteration 282|reward: 1021.0|last_reward_at:  261|Elapsed Time: 0:00:01||
Episode 5|Iteration 295|reward: 1027.0|last_reward_at:  261|Elapsed Time: 0:00:01||
Episode 5|Iteration 295|reward: 1027.0|last_reward_at:  295|Elapsed Time: 0:00:01||
Episode 5|Iteration 299|reward: 1033.0|last_reward_at:  295|Elapsed Time: 0:00:01||
Episode 5|Iteration 299|reward: 1033.0|last_reward_at:  299|Elapsed Time: 0:00:01||
Episode 5|Iteration 302|reward: 1039.0|last_reward_at:  299|Elapsed Time: 0:00:01||
Episode 5|Iteration 302|reward: 1039.0|last_reward_at:  302|Elapsed Time: 0:00:01||
Episode 5|Iteration 312|reward: 1039.0|last_reward_at:  302|Elapsed Time: 0:00:01||
Episode 5|Iteration 316|reward: 1041.0|last_reward_at:  302|Elapsed Time: 0:00:01||
Episode 5|Iteration 316|reward: 1041.0|last_reward_at:  316|Elapsed Time: 0:00:01||
Episode 5|Iteration 327|reward: 1041.0|last_reward_at:  316|Elapsed Time: 0:00:01||
Episode 5|Iteration 335|reward: 1041.0|last_reward_at:  316|Elapsed Time: 0:00:01||
Episode 5|Iteration 338|reward: 1050.0|last_reward_at:  316|Elapsed Time: 0:00:01||
Episode 5|Iteration 338|reward: 1050.0|last_reward_at:  338|Elapsed Time: 0:00:01||
Episode 5|Iteration 340|reward: 1150.0|last_reward_at:  338|Elapsed Time: 0:00:01||
Episode 5|Iteration 340|reward: 1150.0|last_reward_at:  340|Elapsed Time: 0:00:01||
Episode 5|Iteration 350|reward: 1164.0|last_reward_at:  340|Elapsed Time: 0:00:01||
Episode 5|Iteration 350|reward: 1164.0|last_reward_at:  350|Elapsed Time: 0:00:01||
Episode 5|Iteration 354|reward: 1264.0|last_reward_at:  350|Elapsed Time: 0:00:01||
Episode 5|Iteration 354|reward: 1264.0|last_reward_at:  354|Elapsed Time: 0:00:01||
Episode 5|Iteration 356|reward: 1270.0|last_reward_at:  354|Elapsed Time: 0:00:01||
Episode 5|Iteration 356|reward: 1270.0|last_reward_at:  356|Elapsed Time: 0:00:01||
Episode 5|Iteration 365|reward: 1270.0|last_reward_at:  356|Elapsed Time: 0:00:02||
Episode 5|Iteration 371|reward: 1281.0|last_reward_at:  356|Elapsed Time: 0:00:02||
Episode 5|Iteration 371|reward: 1281.0|last_reward_at:  371|Elapsed Time: 0:00:02||
Episode 5|Iteration 380|reward: 1281.0|last_reward_at:  371|Elapsed Time: 0:00:02||
Episode 5|Iteration 380|reward: 1290.0|last_reward_at:  371|Elapsed Time: 0:00:02||
Episode 5|Iteration 380|reward: 1290.0|last_reward_at:  380|Elapsed Time: 0:00:02||
Episode 5|Iteration 382|reward: 2290.0|last_reward_at:  380|Elapsed Time: 0:00:02||
Episode 5|Iteration 382|reward: 2290.0|last_reward_at:  382|Elapsed Time: 0:00:02||
Episode 5|Iteration 389|reward: 2296.0|last_reward_at:  382|Elapsed Time: 0:00:02||
Episode 5|Iteration 389|reward: 2296.0|last_reward_at:  389|Elapsed Time: 0:00:02||
Episode 5|Iteration 391|reward: 2302.0|last_reward_at:  389|Elapsed Time: 0:00:02||
Episode 5|Iteration 391|reward: 2302.0|last_reward_at:  391|Elapsed Time: 0:00:02||
Episode 5|Iteration 403|reward: 2302.0|last_reward_at:  391|Elapsed Time: 0:00:02||
Episode 5|Iteration 411|reward: 2302.0|last_reward_at:  391|Elapsed Time: 0:00:02||
Episode 5|Iteration 418|reward: 2302.0|last_reward_at:  391|Elapsed Time: 0:00:02||
Episode 5|Iteration 426|reward: 2302.0|last_reward_at:  391|Elapsed Time: 0:00:02||
Episode 5|Iteration 433|reward: 2302.0|last_reward_at:  391|Elapsed Time: 0:00:02||
Episode 5|Iteration 441|reward: 2302.0|last_reward_at:  391|Elapsed Time: 0:00:02||
Episode 5|Iteration 449|reward: 2302.0|last_reward_at:  391|Elapsed Time: 0:00:02||
Episode 5|Iteration 456|reward: 2302.0|last_reward_at:  391|Elapsed Time: 0:00:02||
Episode 5|Iteration 464|reward: 2302.0|last_reward_at:  391|Elapsed Time: 0:00:02||
Episode 5|Iteration 478|reward: 2302.0|last_reward_at:  391|Elapsed Time: 0:00:02||
Episode 5|Iteration 487|reward: 2302.0|last_reward_at:  391|Elapsed Time: 0:00:02||
Episode 5|Iteration 494|reward: 2302.0|last_reward_at:  391|Elapsed Time: 0:00:03||
Episode 5|Iteration 502|reward: 2302.0|last_reward_at:  391|Elapsed Time: 0:00:03||
Episode 5|Iteration 509|reward: 2302.0|last_reward_at:  391|Elapsed Time: 0:00:03||
Episode 5|Iteration 517|reward: 2302.0|last_reward_at:  391|Elapsed Time: 0:00:03||
Episode 5|Iteration 525|reward: 2302.0|last_reward_at:  391|Elapsed Time: 0:00:03||
Episode 5|Iteration 532|reward: 2302.0|last_reward_at:  391|Elapsed Time: 0:00:03||
Episode 5|Iteration 540|reward: 2302.0|last_reward_at:  391|Elapsed Time: 0:00:03||
Episode 5|Iteration 547|reward: 2302.0|last_reward_at:  391|Elapsed Time: 0:00:03||
Episode 5|Iteration 555|reward: 2302.0|last_reward_at:  391|Elapsed Time: 0:00:03||
Episode 5|Iteration 563|reward: 2302.0|last_reward_at:  391|Elapsed Time: 0:00:03||
Episode 5|Iteration 570|reward: 2302.0|last_reward_at:  391|Elapsed Time: 0:00:03||
Episode 5|Iteration 578|reward: 2302.0|last_reward_at:  391|Elapsed Time: 0:00:03||
Episode 5|Iteration 585|reward: 2302.0|last_reward_at:  391|Elapsed Time: 0:00:03||
Episode 5|Iteration 593|reward: 2302.0|last_reward_at:  391|Elapsed Time: 0:00:03||
Episode 5|Iteration 600|reward: 2302.0|last_reward_at:  391|Elapsed Time: 0:00:03||
Episode 5|Iteration 600|reward: 2302.0|last_reward_at:  391|Elapsed Time: 0:00:03||

  Episode 5 stopped at t=600
  Breakdown [Reward/NoReward (Success rate)]
    explore-local: 21/229 (0.08)
    explore-remote: 20/319 (0.06)
    explore-connect: 0/0 (NaN)
    exploit-local: 0/0 (NaN)
    exploit-remote: 0/0 (NaN)
    exploit-connect: 11/0 (1.00)
  exploit deflected to exploration: 154
  ## Episode: 6/10 'Credential lookups (ϵ-greedy)' ϵ=0.6927,

Episode 6|Iteration 0|reward: ------|last_reward_at: ----|Elapsed Time: 0:00:00||
Episode 6|Iteration 1|reward:    0.0|last_reward_at: ----|Elapsed Time: 0:00:00||
Episode 6|Iteration 10|reward:   14.0|last_reward_at: ----|Elapsed Time: 0:00:00||
Episode 6|Iteration 10|reward:   14.0|last_reward_at:   10|Elapsed Time: 0:00:00||
Episode 6|Iteration 13|reward:   16.0|last_reward_at:   10|Elapsed Time: 0:00:00||
Episode 6|Iteration 13|reward:   16.0|last_reward_at:   13|Elapsed Time: 0:00:00||
Episode 6|Iteration 14|reward:  116.0|last_reward_at:   13|Elapsed Time: 0:00:00||
Episode 6|Iteration 14|reward:  116.0|last_reward_at:   14|Elapsed Time: 0:00:00||
Episode 6|Iteration 19|reward:  127.0|last_reward_at:   14|Elapsed Time: 0:00:00||
Episode 6|Iteration 19|reward:  127.0|last_reward_at:   19|Elapsed Time: 0:00:00||
Episode 6|Iteration 20|reward:  136.0|last_reward_at:   19|Elapsed Time: 0:00:00||
Episode 6|Iteration 20|reward:  136.0|last_reward_at:   20|Elapsed Time: 0:00:00||
Episode 6|Iteration 21|reward:  236.0|last_reward_at:   20|Elapsed Time: 0:00:00||
Episode 6|Iteration 21|reward:  236.0|last_reward_at:   21|Elapsed Time: 0:00:00||
Episode 6|Iteration 22|reward:  238.0|last_reward_at:   21|Elapsed Time: 0:00:00||
Episode 6|Iteration 22|reward:  238.0|last_reward_at:   22|Elapsed Time: 0:00:00||
Episode 6|Iteration 23|reward:  249.0|last_reward_at:   22|Elapsed Time: 0:00:00||
Episode 6|Iteration 23|reward:  249.0|last_reward_at:   23|Elapsed Time: 0:00:00||
Episode 6|Iteration 26|reward:  255.0|last_reward_at:   23|Elapsed Time: 0:00:00||
Episode 6|Iteration 26|reward:  255.0|last_reward_at:   26|Elapsed Time: 0:00:00||
Episode 6|Iteration 27|reward:  261.0|last_reward_at:   26|Elapsed Time: 0:00:00||
Episode 6|Iteration 27|reward:  261.0|last_reward_at:   27|Elapsed Time: 0:00:00||
Episode 6|Iteration 28|reward:  265.0|last_reward_at:   27|Elapsed Time: 0:00:00||
Episode 6|Iteration 28|reward:  265.0|last_reward_at:   28|Elapsed Time: 0:00:00||
Episode 6|Iteration 46|reward:  265.0|last_reward_at:   28|Elapsed Time: 0:00:00||
Episode 6|Iteration 60|reward:  267.0|last_reward_at:   28|Elapsed Time: 0:00:00||
Episode 6|Iteration 60|reward:  267.0|last_reward_at:   60|Elapsed Time: 0:00:00||
Episode 6|Iteration 76|reward:  267.0|last_reward_at:   60|Elapsed Time: 0:00:00||
Episode 6|Iteration 77|reward:  276.0|last_reward_at:   60|Elapsed Time: 0:00:00||
Episode 6|Iteration 77|reward:  276.0|last_reward_at:   77|Elapsed Time: 0:00:00||
Episode 6|Iteration 78|reward:  376.0|last_reward_at:   77|Elapsed Time: 0:00:00||
Episode 6|Iteration 78|reward:  376.0|last_reward_at:   78|Elapsed Time: 0:00:00||
Episode 6|Iteration 92|reward:  376.0|last_reward_at:   78|Elapsed Time: 0:00:00||
Episode 6|Iteration 99|reward:  390.0|last_reward_at:   78|Elapsed Time: 0:00:00||
Episode 6|Iteration 99|reward:  390.0|last_reward_at:   99|Elapsed Time: 0:00:00||
Episode 6|Iteration 100|reward:  490.0|last_reward_at:   99|Elapsed Time: 0:00:00||
Episode 6|Iteration 100|reward:  490.0|last_reward_at:  100|Elapsed Time: 0:00:00||
Episode 6|Iteration 102|reward:  496.0|last_reward_at:  100|Elapsed Time: 0:00:00||
Episode 6|Iteration 102|reward:  496.0|last_reward_at:  102|Elapsed Time: 0:00:00||
Episode 6|Iteration 106|reward:  510.0|last_reward_at:  102|Elapsed Time: 0:00:00||
Episode 6|Iteration 106|reward:  510.0|last_reward_at:  106|Elapsed Time: 0:00:00||
Episode 6|Iteration 112|reward:  610.0|last_reward_at:  106|Elapsed Time: 0:00:00||
Episode 6|Iteration 112|reward:  610.0|last_reward_at:  112|Elapsed Time: 0:00:00||
Episode 6|Iteration 114|reward:  612.0|last_reward_at:  112|Elapsed Time: 0:00:00||
Episode 6|Iteration 114|reward:  612.0|last_reward_at:  114|Elapsed Time: 0:00:00||
Episode 6|Iteration 119|reward:  618.0|last_reward_at:  114|Elapsed Time: 0:00:00||
Episode 6|Iteration 119|reward:  618.0|last_reward_at:  119|Elapsed Time: 0:00:00||
Episode 6|Iteration 132|reward:  624.0|last_reward_at:  119|Elapsed Time: 0:00:00||
Episode 6|Iteration 132|reward:  624.0|last_reward_at:  132|Elapsed Time: 0:00:00||
Episode 6|Iteration 133|reward:  626.0|last_reward_at:  132|Elapsed Time: 0:00:00||
Episode 6|Iteration 133|reward:  626.0|last_reward_at:  133|Elapsed Time: 0:00:00||
Episode 6|Iteration 145|reward:  626.0|last_reward_at:  133|Elapsed Time: 0:00:00||
Episode 6|Iteration 159|reward:  632.0|last_reward_at:  133|Elapsed Time: 0:00:00||
Episode 6|Iteration 159|reward:  632.0|last_reward_at:  159|Elapsed Time: 0:00:00||
Episode 6|Iteration 175|reward:  632.0|last_reward_at:  159|Elapsed Time: 0:00:00||
Episode 6|Iteration 189|reward:  646.0|last_reward_at:  159|Elapsed Time: 0:00:00||
Episode 6|Iteration 189|reward:  646.0|last_reward_at:  189|Elapsed Time: 0:00:00||
Episode 6|Iteration 191|reward:  746.0|last_reward_at:  189|Elapsed Time: 0:00:00||
Episode 6|Iteration 191|reward:  746.0|last_reward_at:  191|Elapsed Time: 0:00:00||
Episode 6|Iteration 205|reward:  757.0|last_reward_at:  191|Elapsed Time: 0:00:00||
Episode 6|Iteration 205|reward:  757.0|last_reward_at:  205|Elapsed Time: 0:00:00||
Episode 6|Iteration 206|reward:  759.0|last_reward_at:  205|Elapsed Time: 0:00:00||
Episode 6|Iteration 206|reward:  759.0|last_reward_at:  206|Elapsed Time: 0:00:00||
Episode 6|Iteration 221|reward:  759.0|last_reward_at:  206|Elapsed Time: 0:00:00||
Episode 6|Iteration 236|reward:  759.0|last_reward_at:  206|Elapsed Time: 0:00:01||
Episode 6|Iteration 248|reward:  765.0|last_reward_at:  206|Elapsed Time: 0:00:01||
Episode 6|Iteration 248|reward:  765.0|last_reward_at:  248|Elapsed Time: 0:00:01||
Episode 6|Iteration 253|reward:  769.0|last_reward_at:  248|Elapsed Time: 0:00:01||
Episode 6|Iteration 253|reward:  769.0|last_reward_at:  253|Elapsed Time: 0:00:01||
Episode 6|Iteration 254|reward:  775.0|last_reward_at:  253|Elapsed Time: 0:00:01||
Episode 6|Iteration 254|reward:  775.0|last_reward_at:  254|Elapsed Time: 0:00:01||
Episode 6|Iteration 266|reward:  775.0|last_reward_at:  254|Elapsed Time: 0:00:01||
Episode 6|Iteration 282|reward:  775.0|last_reward_at:  254|Elapsed Time: 0:00:01||
Episode 6|Iteration 294|reward:  781.0|last_reward_at:  254|Elapsed Time: 0:00:01||
Episode 6|Iteration 294|reward:  781.0|last_reward_at:  294|Elapsed Time: 0:00:01||
Episode 6|Iteration 304|reward:  781.0|last_reward_at:  294|Elapsed Time: 0:00:01||
Episode 6|Iteration 312|reward:  781.0|last_reward_at:  294|Elapsed Time: 0:00:01||
Episode 6|Iteration 327|reward:  781.0|last_reward_at:  294|Elapsed Time: 0:00:01||
Episode 6|Iteration 342|reward:  781.0|last_reward_at:  294|Elapsed Time: 0:00:01||
Episode 6|Iteration 357|reward:  781.0|last_reward_at:  294|Elapsed Time: 0:00:01||
Episode 6|Iteration 365|reward:  781.0|last_reward_at:  294|Elapsed Time: 0:00:01||
Episode 6|Iteration 380|reward:  781.0|last_reward_at:  294|Elapsed Time: 0:00:01||
Episode 6|Iteration 395|reward:  781.0|last_reward_at:  294|Elapsed Time: 0:00:01||
Episode 6|Iteration 411|reward:  781.0|last_reward_at:  294|Elapsed Time: 0:00:02||
Episode 6|Iteration 418|reward:  781.0|last_reward_at:  294|Elapsed Time: 0:00:02||
Episode 6|Iteration 420|reward:  790.0|last_reward_at:  294|Elapsed Time: 0:00:02||
Episode 6|Iteration 420|reward:  790.0|last_reward_at:  420|Elapsed Time: 0:00:02||
Episode 6|Iteration 421|reward:  890.0|last_reward_at:  420|Elapsed Time: 0:00:02||
Episode 6|Iteration 421|reward:  890.0|last_reward_at:  421|Elapsed Time: 0:00:02||
Episode 6|Iteration 433|reward:  890.0|last_reward_at:  421|Elapsed Time: 0:00:02||
Episode 6|Iteration 441|reward:  901.0|last_reward_at:  421|Elapsed Time: 0:00:02||
Episode 6|Iteration 441|reward:  901.0|last_reward_at:  441|Elapsed Time: 0:00:02||
Episode 6|Iteration 448|reward:  907.0|last_reward_at:  441|Elapsed Time: 0:00:02||
Episode 6|Iteration 448|reward:  907.0|last_reward_at:  448|Elapsed Time: 0:00:02||
Episode 6|Iteration 450|reward:  915.0|last_reward_at:  448|Elapsed Time: 0:00:02||
Episode 6|Iteration 450|reward:  915.0|last_reward_at:  450|Elapsed Time: 0:00:02||
Episode 6|Iteration 464|reward:  915.0|last_reward_at:  450|Elapsed Time: 0:00:02||
Episode 6|Iteration 479|reward:  915.0|last_reward_at:  450|Elapsed Time: 0:00:02||
Episode 6|Iteration 494|reward:  915.0|last_reward_at:  450|Elapsed Time: 0:00:02||
Episode 6|Iteration 502|reward:  915.0|last_reward_at:  450|Elapsed Time: 0:00:02||
Episode 6|Iteration 517|reward:  915.0|last_reward_at:  450|Elapsed Time: 0:00:02||
Episode 6|Iteration 525|reward:  915.0|last_reward_at:  450|Elapsed Time: 0:00:02||
Episode 6|Iteration 536|reward:  924.0|last_reward_at:  450|Elapsed Time: 0:00:02||
Episode 6|Iteration 536|reward:  924.0|last_reward_at:  536|Elapsed Time: 0:00:02||
Episode 6|Iteration 537|reward: 1024.0|last_reward_at:  536|Elapsed Time: 0:00:02||
Episode 6|Iteration 537|reward: 1024.0|last_reward_at:  537|Elapsed Time: 0:00:02||
Episode 6|Iteration 555|reward: 1024.0|last_reward_at:  537|Elapsed Time: 0:00:02||
Episode 6|Iteration 570|reward: 1024.0|last_reward_at:  537|Elapsed Time: 0:00:02||
Episode 6|Iteration 574|reward: 1035.0|last_reward_at:  537|Elapsed Time: 0:00:03||
Episode 6|Iteration 574|reward: 1035.0|last_reward_at:  574|Elapsed Time: 0:00:03||
Episode 6|Iteration 578|reward: 1039.0|last_reward_at:  574|Elapsed Time: 0:00:03||
Episode 6|Iteration 578|reward: 1039.0|last_reward_at:  578|Elapsed Time: 0:00:03||
Episode 6|Iteration 585|reward: 1041.0|last_reward_at:  578|Elapsed Time: 0:00:03||
Episode 6|Iteration 585|reward: 1041.0|last_reward_at:  585|Elapsed Time: 0:00:03||
Episode 6|Iteration 600|reward: 1041.0|last_reward_at:  585|Elapsed Time: 0:00:03||
Episode 6|Iteration 600|reward: 1041.0|last_reward_at:  585|Elapsed Time: 0:00:03||

  Episode 6 stopped at t=600
  Breakdown [Reward/NoReward (Success rate)]
    explore-local: 16/243 (0.06)
    explore-remote: 18/315 (0.05)
    explore-connect: 0/0 (NaN)
    exploit-local: 0/0 (NaN)
    exploit-remote: 0/0 (NaN)
    exploit-connect: 8/0 (1.00)
  exploit deflected to exploration: 176
  ## Episode: 7/10 'Credential lookups (ϵ-greedy)' ϵ=0.6582,

Episode 7|Iteration 0|reward: ------|last_reward_at: ----|Elapsed Time: 0:00:00||
Episode 7|Iteration 1|reward:    0.0|last_reward_at: ----|Elapsed Time: 0:00:00||
Episode 7|Iteration 3|reward:   14.0|last_reward_at: ----|Elapsed Time: 0:00:00||
Episode 7|Iteration 3|reward:   14.0|last_reward_at:    3|Elapsed Time: 0:00:00||
Episode 7|Iteration 10|reward:  114.0|last_reward_at:    3|Elapsed Time: 0:00:00||
Episode 7|Iteration 10|reward:  114.0|last_reward_at:   10|Elapsed Time: 0:00:00||
Episode 7|Iteration 12|reward:  116.0|last_reward_at:   10|Elapsed Time: 0:00:00||
Episode 7|Iteration 12|reward:  116.0|last_reward_at:   12|Elapsed Time: 0:00:00||
Episode 7|Iteration 13|reward:  118.0|last_reward_at:   12|Elapsed Time: 0:00:00||
Episode 7|Iteration 13|reward:  118.0|last_reward_at:   13|Elapsed Time: 0:00:00||
Episode 7|Iteration 18|reward:  132.0|last_reward_at:   13|Elapsed Time: 0:00:00||
Episode 7|Iteration 18|reward:  132.0|last_reward_at:   18|Elapsed Time: 0:00:00||
Episode 7|Iteration 20|reward:  232.0|last_reward_at:   18|Elapsed Time: 0:00:00||
Episode 7|Iteration 20|reward:  232.0|last_reward_at:   20|Elapsed Time: 0:00:00||
Episode 7|Iteration 21|reward:  238.0|last_reward_at:   20|Elapsed Time: 0:00:00||
Episode 7|Iteration 21|reward:  238.0|last_reward_at:   21|Elapsed Time: 0:00:00||
Episode 7|Iteration 23|reward:  244.0|last_reward_at:   21|Elapsed Time: 0:00:00||
Episode 7|Iteration 23|reward:  244.0|last_reward_at:   23|Elapsed Time: 0:00:00||
Episode 7|Iteration 27|reward:  250.0|last_reward_at:   23|Elapsed Time: 0:00:00||
Episode 7|Iteration 27|reward:  250.0|last_reward_at:   27|Elapsed Time: 0:00:00||
Episode 7|Iteration 38|reward:  261.0|last_reward_at:   27|Elapsed Time: 0:00:00||
Episode 7|Iteration 38|reward:  261.0|last_reward_at:   38|Elapsed Time: 0:00:00||
Episode 7|Iteration 39|reward:  263.0|last_reward_at:   38|Elapsed Time: 0:00:00||
Episode 7|Iteration 39|reward:  263.0|last_reward_at:   39|Elapsed Time: 0:00:00||
Episode 7|Iteration 54|reward:  263.0|last_reward_at:   39|Elapsed Time: 0:00:00||
Episode 7|Iteration 59|reward:  272.0|last_reward_at:   39|Elapsed Time: 0:00:00||
Episode 7|Iteration 59|reward:  272.0|last_reward_at:   59|Elapsed Time: 0:00:00||
Episode 7|Iteration 63|reward:  276.0|last_reward_at:   59|Elapsed Time: 0:00:00||
Episode 7|Iteration 63|reward:  276.0|last_reward_at:   63|Elapsed Time: 0:00:00||
Episode 7|Iteration 65|reward:  376.0|last_reward_at:   63|Elapsed Time: 0:00:00||
Episode 7|Iteration 65|reward:  376.0|last_reward_at:   65|Elapsed Time: 0:00:00||
Episode 7|Iteration 84|reward:  376.0|last_reward_at:   65|Elapsed Time: 0:00:00||
Episode 7|Iteration 99|reward:  376.0|last_reward_at:   65|Elapsed Time: 0:00:00||
Episode 7|Iteration 110|reward:  390.0|last_reward_at:   65|Elapsed Time: 0:00:00||
Episode 7|Iteration 110|reward:  390.0|last_reward_at:  110|Elapsed Time: 0:00:00||
Episode 7|Iteration 111|reward:  490.0|last_reward_at:  110|Elapsed Time: 0:00:00||
Episode 7|Iteration 111|reward:  490.0|last_reward_at:  111|Elapsed Time: 0:00:00||
Episode 7|Iteration 114|reward:  496.0|last_reward_at:  111|Elapsed Time: 0:00:00||
Episode 7|Iteration 114|reward:  496.0|last_reward_at:  114|Elapsed Time: 0:00:00||
Episode 7|Iteration 130|reward:  496.0|last_reward_at:  114|Elapsed Time: 0:00:00||
Episode 7|Iteration 135|reward:  507.0|last_reward_at:  114|Elapsed Time: 0:00:00||
Episode 7|Iteration 135|reward:  507.0|last_reward_at:  135|Elapsed Time: 0:00:00||
Episode 7|Iteration 137|reward:  513.0|last_reward_at:  135|Elapsed Time: 0:00:00||
Episode 7|Iteration 137|reward:  513.0|last_reward_at:  137|Elapsed Time: 0:00:00||
Episode 7|Iteration 152|reward:  513.0|last_reward_at:  137|Elapsed Time: 0:00:00||
Episode 7|Iteration 152|reward:  517.0|last_reward_at:  137|Elapsed Time: 0:00:00||
Episode 7|Iteration 152|reward:  517.0|last_reward_at:  152|Elapsed Time: 0:00:00||
Episode 7|Iteration 168|reward:  517.0|last_reward_at:  152|Elapsed Time: 0:00:00||
Episode 7|Iteration 183|reward:  517.0|last_reward_at:  152|Elapsed Time: 0:00:00||
Episode 7|Iteration 184|reward:  519.0|last_reward_at:  152|Elapsed Time: 0:00:00||
Episode 7|Iteration 184|reward:  519.0|last_reward_at:  184|Elapsed Time: 0:00:00||
Episode 7|Iteration 194|reward:  525.0|last_reward_at:  184|Elapsed Time: 0:00:00||
Episode 7|Iteration 194|reward:  525.0|last_reward_at:  194|Elapsed Time: 0:00:00||
Episode 7|Iteration 213|reward:  525.0|last_reward_at:  194|Elapsed Time: 0:00:00||
Episode 7|Iteration 228|reward:  525.0|last_reward_at:  194|Elapsed Time: 0:00:01||
Episode 7|Iteration 236|reward:  525.0|last_reward_at:  194|Elapsed Time: 0:00:01||
Episode 7|Iteration 239|reward:  534.0|last_reward_at:  194|Elapsed Time: 0:00:01||
Episode 7|Iteration 239|reward:  534.0|last_reward_at:  239|Elapsed Time: 0:00:01||
Episode 7|Iteration 240|reward:  634.0|last_reward_at:  239|Elapsed Time: 0:00:01||
Episode 7|Iteration 240|reward:  634.0|last_reward_at:  240|Elapsed Time: 0:00:01||
Episode 7|Iteration 259|reward:  634.0|last_reward_at:  240|Elapsed Time: 0:00:01||
Episode 7|Iteration 274|reward:  634.0|last_reward_at:  240|Elapsed Time: 0:00:01||
Episode 7|Iteration 287|reward:  648.0|last_reward_at:  240|Elapsed Time: 0:00:01||
Episode 7|Iteration 287|reward:  648.0|last_reward_at:  287|Elapsed Time: 0:00:01||
Episode 7|Iteration 295|reward:  748.0|last_reward_at:  287|Elapsed Time: 0:00:01||
Episode 7|Iteration 295|reward:  748.0|last_reward_at:  295|Elapsed Time: 0:00:01||
Episode 7|Iteration 298|reward:  754.0|last_reward_at:  295|Elapsed Time: 0:00:01||
Episode 7|Iteration 298|reward:  754.0|last_reward_at:  298|Elapsed Time: 0:00:01||
Episode 7|Iteration 307|reward:  760.0|last_reward_at:  298|Elapsed Time: 0:00:01||
Episode 7|Iteration 307|reward:  760.0|last_reward_at:  307|Elapsed Time: 0:00:01||
Episode 7|Iteration 319|reward:  760.0|last_reward_at:  307|Elapsed Time: 0:00:01||
Episode 7|Iteration 324|reward:  766.0|last_reward_at:  307|Elapsed Time: 0:00:01||
Episode 7|Iteration 324|reward:  766.0|last_reward_at:  324|Elapsed Time: 0:00:01||
Episode 7|Iteration 335|reward:  766.0|last_reward_at:  324|Elapsed Time: 0:00:01||
Episode 7|Iteration 341|reward:  777.0|last_reward_at:  324|Elapsed Time: 0:00:01||
Episode 7|Iteration 341|reward:  777.0|last_reward_at:  341|Elapsed Time: 0:00:01||
Episode 7|Iteration 350|reward:  777.0|last_reward_at:  341|Elapsed Time: 0:00:01||
Episode 7|Iteration 357|reward:  777.0|last_reward_at:  341|Elapsed Time: 0:00:01||
Episode 7|Iteration 358|reward:  781.0|last_reward_at:  341|Elapsed Time: 0:00:01||
Episode 7|Iteration 358|reward:  781.0|last_reward_at:  358|Elapsed Time: 0:00:01||
Episode 7|Iteration 373|reward:  781.0|last_reward_at:  358|Elapsed Time: 0:00:01||
Episode 7|Iteration 373|reward:  790.0|last_reward_at:  358|Elapsed Time: 0:00:01||
Episode 7|Iteration 373|reward:  790.0|last_reward_at:  373|Elapsed Time: 0:00:01||
Episode 7|Iteration 374|reward:  890.0|last_reward_at:  373|Elapsed Time: 0:00:01||
Episode 7|Iteration 374|reward:  890.0|last_reward_at:  374|Elapsed Time: 0:00:01||
Episode 7|Iteration 375|reward:  892.0|last_reward_at:  374|Elapsed Time: 0:00:01||
Episode 7|Iteration 375|reward:  892.0|last_reward_at:  375|Elapsed Time: 0:00:01||
Episode 7|Iteration 385|reward:  906.0|last_reward_at:  375|Elapsed Time: 0:00:01||
Episode 7|Iteration 385|reward:  906.0|last_reward_at:  385|Elapsed Time: 0:00:01||
Episode 7|Iteration 387|reward: 1006.0|last_reward_at:  385|Elapsed Time: 0:00:02||
Episode 7|Iteration 387|reward: 1006.0|last_reward_at:  387|Elapsed Time: 0:00:02||
Episode 7|Iteration 395|reward: 1006.0|last_reward_at:  387|Elapsed Time: 0:00:02||
Episode 7|Iteration 403|reward: 1006.0|last_reward_at:  387|Elapsed Time: 0:00:02||
Episode 7|Iteration 409|reward: 1012.0|last_reward_at:  387|Elapsed Time: 0:00:02||
Episode 7|Iteration 409|reward: 1012.0|last_reward_at:  409|Elapsed Time: 0:00:02||
Episode 7|Iteration 415|reward: 1018.0|last_reward_at:  409|Elapsed Time: 0:00:02||
Episode 7|Iteration 415|reward: 1018.0|last_reward_at:  415|Elapsed Time: 0:00:02||
Episode 7|Iteration 421|reward: 1024.0|last_reward_at:  415|Elapsed Time: 0:00:02||
Episode 7|Iteration 421|reward: 1024.0|last_reward_at:  421|Elapsed Time: 0:00:02||
Episode 7|Iteration 433|reward: 1024.0|last_reward_at:  421|Elapsed Time: 0:00:02||
Episode 7|Iteration 434|reward: 1035.0|last_reward_at:  421|Elapsed Time: 0:00:02||
Episode 7|Iteration 434|reward: 1035.0|last_reward_at:  434|Elapsed Time: 0:00:02||
Episode 7|Iteration 443|reward: 1039.0|last_reward_at:  434|Elapsed Time: 0:00:02||
Episode 7|Iteration 443|reward: 1039.0|last_reward_at:  443|Elapsed Time: 0:00:02||
Episode 7|Iteration 456|reward: 1039.0|last_reward_at:  443|Elapsed Time: 0:00:02||
Episode 7|Iteration 464|reward: 1039.0|last_reward_at:  443|Elapsed Time: 0:00:02||
Episode 7|Iteration 464|reward: 1041.0|last_reward_at:  443|Elapsed Time: 0:00:02||
Episode 7|Iteration 464|reward: 1041.0|last_reward_at:  464|Elapsed Time: 0:00:02||
Episode 7|Iteration 471|reward: 1041.0|last_reward_at:  464|Elapsed Time: 0:00:02||
Episode 7|Iteration 477|reward: 1050.0|last_reward_at:  464|Elapsed Time: 0:00:02||
Episode 7|Iteration 477|reward: 1050.0|last_reward_at:  477|Elapsed Time: 0:00:02||
Episode 7|Iteration 481|reward: 1150.0|last_reward_at:  477|Elapsed Time: 0:00:02||
Episode 7|Iteration 481|reward: 1150.0|last_reward_at:  481|Elapsed Time: 0:00:02||
Episode 7|Iteration 494|reward: 1150.0|last_reward_at:  481|Elapsed Time: 0:00:02||
Episode 7|Iteration 502|reward: 1150.0|last_reward_at:  481|Elapsed Time: 0:00:02||
Episode 7|Iteration 509|reward: 1150.0|last_reward_at:  481|Elapsed Time: 0:00:02||
Episode 7|Iteration 517|reward: 1150.0|last_reward_at:  481|Elapsed Time: 0:00:03||
Episode 7|Iteration 525|reward: 1150.0|last_reward_at:  481|Elapsed Time: 0:00:03||
Episode 7|Iteration 532|reward: 1150.0|last_reward_at:  481|Elapsed Time: 0:00:03||
Episode 7|Iteration 540|reward: 1150.0|last_reward_at:  481|Elapsed Time: 0:00:03||
Episode 7|Iteration 547|reward: 1150.0|last_reward_at:  481|Elapsed Time: 0:00:03||
Episode 7|Iteration 563|reward: 1150.0|last_reward_at:  481|Elapsed Time: 0:00:03||
Episode 7|Iteration 570|reward: 1150.0|last_reward_at:  481|Elapsed Time: 0:00:03||
Episode 7|Iteration 574|reward: 1161.0|last_reward_at:  481|Elapsed Time: 0:00:03||
Episode 7|Iteration 574|reward: 1161.0|last_reward_at:  574|Elapsed Time: 0:00:03||
Episode 7|Iteration 585|reward: 1161.0|last_reward_at:  574|Elapsed Time: 0:00:03||
Episode 7|Iteration 591|reward: 1167.0|last_reward_at:  574|Elapsed Time: 0:00:03||
Episode 7|Iteration 591|reward: 1167.0|last_reward_at:  591|Elapsed Time: 0:00:03||
Episode 7|Iteration 595|reward: 1175.0|last_reward_at:  591|Elapsed Time: 0:00:03||
Episode 7|Iteration 595|reward: 1175.0|last_reward_at:  595|Elapsed Time: 0:00:03||
Episode 7|Iteration 600|reward: 1175.0|last_reward_at:  595|Elapsed Time: 0:00:03||

  Episode 7 stopped at t=600
  Breakdown [Reward/NoReward (Success rate)]
    explore-local: 18/239 (0.07)
    explore-remote: 20/314 (0.06)
    explore-connect: 0/0 (NaN)
    exploit-local: 0/0 (NaN)
    exploit-remote: 0/0 (NaN)
    exploit-connect: 9/0 (1.00)
  exploit deflected to exploration: 212
  ## Episode: 8/10 'Credential lookups (ϵ-greedy)' ϵ=0.6257,

Episode 8|Iteration 0|reward: ------|last_reward_at: ----|Elapsed Time: 0:00:00||
Episode 8|Iteration 1|reward:   14.0|last_reward_at: ----|Elapsed Time: 0:00:00||
Episode 8|Iteration 1|reward:   14.0|last_reward_at:    1|Elapsed Time: 0:00:00||
Episode 8|Iteration 3|reward:  114.0|last_reward_at:    1|Elapsed Time: 0:00:00||
Episode 8|Iteration 3|reward:  114.0|last_reward_at:    3|Elapsed Time: 0:00:00||
Episode 8|Iteration 4|reward:  116.0|last_reward_at:    3|Elapsed Time: 0:00:00||
Episode 8|Iteration 4|reward:  116.0|last_reward_at:    4|Elapsed Time: 0:00:00||
Episode 8|Iteration 7|reward:  127.0|last_reward_at:    4|Elapsed Time: 0:00:00||
Episode 8|Iteration 7|reward:  127.0|last_reward_at:    7|Elapsed Time: 0:00:00||
Episode 8|Iteration 9|reward:  133.0|last_reward_at:    7|Elapsed Time: 0:00:00||
Episode 8|Iteration 9|reward:  133.0|last_reward_at:    9|Elapsed Time: 0:00:00||
Episode 8|Iteration 10|reward:  142.0|last_reward_at:    9|Elapsed Time: 0:00:00||
Episode 8|Iteration 10|reward:  142.0|last_reward_at:   10|Elapsed Time: 0:00:00||
Episode 8|Iteration 11|reward:  150.0|last_reward_at:   10|Elapsed Time: 0:00:00||
Episode 8|Iteration 11|reward:  150.0|last_reward_at:   11|Elapsed Time: 0:00:00||
Episode 8|Iteration 14|reward:  250.0|last_reward_at:   11|Elapsed Time: 0:00:00||
Episode 8|Iteration 14|reward:  250.0|last_reward_at:   14|Elapsed Time: 0:00:00||
Episode 8|Iteration 15|reward:  252.0|last_reward_at:   14|Elapsed Time: 0:00:00||
Episode 8|Iteration 15|reward:  252.0|last_reward_at:   15|Elapsed Time: 0:00:00||
Episode 8|Iteration 31|reward:  252.0|last_reward_at:   15|Elapsed Time: 0:00:00||
Episode 8|Iteration 40|reward:  266.0|last_reward_at:   15|Elapsed Time: 0:00:00||
Episode 8|Iteration 40|reward:  266.0|last_reward_at:   40|Elapsed Time: 0:00:00||
Episode 8|Iteration 41|reward:  366.0|last_reward_at:   40|Elapsed Time: 0:00:00||
Episode 8|Iteration 41|reward:  366.0|last_reward_at:   41|Elapsed Time: 0:00:00||
Episode 8|Iteration 45|reward:  377.0|last_reward_at:   41|Elapsed Time: 0:00:00||
Episode 8|Iteration 45|reward:  377.0|last_reward_at:   45|Elapsed Time: 0:00:00||
Episode 8|Iteration 48|reward:  379.0|last_reward_at:   45|Elapsed Time: 0:00:00||
Episode 8|Iteration 48|reward:  379.0|last_reward_at:   48|Elapsed Time: 0:00:00||
Episode 8|Iteration 54|reward:  385.0|last_reward_at:   48|Elapsed Time: 0:00:00||
Episode 8|Iteration 54|reward:  385.0|last_reward_at:   54|Elapsed Time: 0:00:00||
Episode 8|Iteration 62|reward:  393.0|last_reward_at:   54|Elapsed Time: 0:00:00||
Episode 8|Iteration 62|reward:  393.0|last_reward_at:   62|Elapsed Time: 0:00:00||
Episode 8|Iteration 63|reward:  395.0|last_reward_at:   62|Elapsed Time: 0:00:00||
Episode 8|Iteration 63|reward:  395.0|last_reward_at:   63|Elapsed Time: 0:00:00||
Episode 8|Iteration 84|reward:  395.0|last_reward_at:   63|Elapsed Time: 0:00:00||
Episode 8|Iteration 84|reward:  401.0|last_reward_at:   63|Elapsed Time: 0:00:00||
Episode 8|Iteration 84|reward:  401.0|last_reward_at:   84|Elapsed Time: 0:00:00||
Episode 8|Iteration 89|reward:  410.0|last_reward_at:   84|Elapsed Time: 0:00:00||
Episode 8|Iteration 89|reward:  410.0|last_reward_at:   89|Elapsed Time: 0:00:00||
Episode 8|Iteration 90|reward:  510.0|last_reward_at:   89|Elapsed Time: 0:00:00||
Episode 8|Iteration 90|reward:  510.0|last_reward_at:   90|Elapsed Time: 0:00:00||
Episode 8|Iteration 92|reward:  524.0|last_reward_at:   90|Elapsed Time: 0:00:00||
Episode 8|Iteration 92|reward:  524.0|last_reward_at:   92|Elapsed Time: 0:00:00||
Episode 8|Iteration 93|reward:  526.0|last_reward_at:   92|Elapsed Time: 0:00:00||
Episode 8|Iteration 93|reward:  526.0|last_reward_at:   93|Elapsed Time: 0:00:00||
Episode 8|Iteration 94|reward:  626.0|last_reward_at:   93|Elapsed Time: 0:00:00||
Episode 8|Iteration 94|reward:  626.0|last_reward_at:   94|Elapsed Time: 0:00:00||
Episode 8|Iteration 107|reward:  632.0|last_reward_at:   94|Elapsed Time: 0:00:00||
Episode 8|Iteration 107|reward:  632.0|last_reward_at:  107|Elapsed Time: 0:00:00||
Episode 8|Iteration 120|reward:  634.0|last_reward_at:  107|Elapsed Time: 0:00:00||
Episode 8|Iteration 120|reward:  634.0|last_reward_at:  120|Elapsed Time: 0:00:00||
Episode 8|Iteration 137|reward:  634.0|last_reward_at:  120|Elapsed Time: 0:00:00||
Episode 8|Iteration 146|reward:  648.0|last_reward_at:  120|Elapsed Time: 0:00:00||
Episode 8|Iteration 146|reward:  648.0|last_reward_at:  146|Elapsed Time: 0:00:00||
Episode 8|Iteration 152|reward:  748.0|last_reward_at:  146|Elapsed Time: 0:00:00||
Episode 8|Iteration 152|reward:  748.0|last_reward_at:  152|Elapsed Time: 0:00:00||
Episode 8|Iteration 153|reward:  759.0|last_reward_at:  152|Elapsed Time: 0:00:00||
Episode 8|Iteration 153|reward:  759.0|last_reward_at:  153|Elapsed Time: 0:00:00||
Episode 8|Iteration 160|reward:  765.0|last_reward_at:  153|Elapsed Time: 0:00:00||
Episode 8|Iteration 160|reward:  765.0|last_reward_at:  160|Elapsed Time: 0:00:00||
Episode 8|Iteration 164|reward:  774.0|last_reward_at:  160|Elapsed Time: 0:00:00||
Episode 8|Iteration 164|reward:  774.0|last_reward_at:  164|Elapsed Time: 0:00:00||
Episode 8|Iteration 166|reward:  874.0|last_reward_at:  164|Elapsed Time: 0:00:00||
Episode 8|Iteration 166|reward:  874.0|last_reward_at:  166|Elapsed Time: 0:00:00||
Episode 8|Iteration 170|reward:  876.0|last_reward_at:  166|Elapsed Time: 0:00:00||
Episode 8|Iteration 170|reward:  876.0|last_reward_at:  170|Elapsed Time: 0:00:00||
Episode 8|Iteration 171|reward:  878.0|last_reward_at:  170|Elapsed Time: 0:00:00||
Episode 8|Iteration 171|reward:  878.0|last_reward_at:  171|Elapsed Time: 0:00:00||
Episode 8|Iteration 183|reward:  878.0|last_reward_at:  171|Elapsed Time: 0:00:00||
Episode 8|Iteration 198|reward:  878.0|last_reward_at:  171|Elapsed Time: 0:00:01||
Episode 8|Iteration 202|reward:  892.0|last_reward_at:  171|Elapsed Time: 0:00:01||
Episode 8|Iteration 202|reward:  892.0|last_reward_at:  202|Elapsed Time: 0:00:01||
Episode 8|Iteration 205|reward:  992.0|last_reward_at:  202|Elapsed Time: 0:00:01||
Episode 8|Iteration 205|reward:  992.0|last_reward_at:  205|Elapsed Time: 0:00:01||
Episode 8|Iteration 210|reward:  998.0|last_reward_at:  205|Elapsed Time: 0:00:01||
Episode 8|Iteration 210|reward:  998.0|last_reward_at:  210|Elapsed Time: 0:00:01||
Episode 8|Iteration 217|reward: 1004.0|last_reward_at:  210|Elapsed Time: 0:00:01||
Episode 8|Iteration 217|reward: 1004.0|last_reward_at:  217|Elapsed Time: 0:00:01||
Episode 8|Iteration 228|reward: 1004.0|last_reward_at:  217|Elapsed Time: 0:00:01||
Episode 8|Iteration 244|reward: 1004.0|last_reward_at:  217|Elapsed Time: 0:00:01||
Episode 8|Iteration 248|reward: 1010.0|last_reward_at:  217|Elapsed Time: 0:00:01||
Episode 8|Iteration 248|reward: 1010.0|last_reward_at:  248|Elapsed Time: 0:00:01||
Episode 8|Iteration 259|reward: 1010.0|last_reward_at:  248|Elapsed Time: 0:00:01||
Episode 8|Iteration 259|reward: 1024.0|last_reward_at:  248|Elapsed Time: 0:00:01||
Episode 8|Iteration 259|reward: 1024.0|last_reward_at:  259|Elapsed Time: 0:00:01||
Episode 8|Iteration 263|reward: 1124.0|last_reward_at:  259|Elapsed Time: 0:00:01||
Episode 8|Iteration 263|reward: 1124.0|last_reward_at:  263|Elapsed Time: 0:00:01||
Episode 8|Iteration 271|reward: 1126.0|last_reward_at:  263|Elapsed Time: 0:00:01||
Episode 8|Iteration 271|reward: 1126.0|last_reward_at:  271|Elapsed Time: 0:00:01||
Episode 8|Iteration 274|reward: 1132.0|last_reward_at:  271|Elapsed Time: 0:00:01||
Episode 8|Iteration 274|reward: 1132.0|last_reward_at:  274|Elapsed Time: 0:00:01||
Episode 8|Iteration 289|reward: 1132.0|last_reward_at:  274|Elapsed Time: 0:00:01||
Episode 8|Iteration 297|reward: 1132.0|last_reward_at:  274|Elapsed Time: 0:00:01||
Episode 8|Iteration 312|reward: 1132.0|last_reward_at:  274|Elapsed Time: 0:00:01||
Episode 8|Iteration 318|reward: 1138.0|last_reward_at:  274|Elapsed Time: 0:00:01||
Episode 8|Iteration 318|reward: 1138.0|last_reward_at:  318|Elapsed Time: 0:00:01||
Episode 8|Iteration 327|reward: 1138.0|last_reward_at:  318|Elapsed Time: 0:00:01||
Episode 8|Iteration 329|reward: 1140.0|last_reward_at:  318|Elapsed Time: 0:00:01||
Episode 8|Iteration 329|reward: 1140.0|last_reward_at:  329|Elapsed Time: 0:00:01||
Episode 8|Iteration 342|reward: 1140.0|last_reward_at:  329|Elapsed Time: 0:00:02||
Episode 8|Iteration 350|reward: 1140.0|last_reward_at:  329|Elapsed Time: 0:00:02||
Episode 8|Iteration 357|reward: 1140.0|last_reward_at:  329|Elapsed Time: 0:00:02||
Episode 8|Iteration 364|reward: 1146.0|last_reward_at:  329|Elapsed Time: 0:00:02||
Episode 8|Iteration 364|reward: 1146.0|last_reward_at:  364|Elapsed Time: 0:00:02||
Episode 8|Iteration 373|reward: 1146.0|last_reward_at:  364|Elapsed Time: 0:00:02||
Episode 8|Iteration 380|reward: 1146.0|last_reward_at:  364|Elapsed Time: 0:00:02||
Episode 8|Iteration 388|reward: 1146.0|last_reward_at:  364|Elapsed Time: 0:00:02||
Episode 8|Iteration 402|reward: 1146.0|last_reward_at:  364|Elapsed Time: 0:00:02||
Episode 8|Iteration 411|reward: 1146.0|last_reward_at:  364|Elapsed Time: 0:00:02||
Episode 8|Iteration 418|reward: 1146.0|last_reward_at:  364|Elapsed Time: 0:00:02||
Episode 8|Iteration 426|reward: 1146.0|last_reward_at:  364|Elapsed Time: 0:00:02||
Episode 8|Iteration 433|reward: 1146.0|last_reward_at:  364|Elapsed Time: 0:00:02||
Episode 8|Iteration 441|reward: 1146.0|last_reward_at:  364|Elapsed Time: 0:00:02||
Episode 8|Iteration 449|reward: 1146.0|last_reward_at:  364|Elapsed Time: 0:00:02||
Episode 8|Iteration 463|reward: 1146.0|last_reward_at:  364|Elapsed Time: 0:00:02||
Episode 8|Iteration 471|reward: 1146.0|last_reward_at:  364|Elapsed Time: 0:00:03||
Episode 8|Iteration 479|reward: 1146.0|last_reward_at:  364|Elapsed Time: 0:00:03||
Episode 8|Iteration 487|reward: 1146.0|last_reward_at:  364|Elapsed Time: 0:00:03||
Episode 8|Iteration 494|reward: 1146.0|last_reward_at:  364|Elapsed Time: 0:00:03||
Episode 8|Iteration 502|reward: 1146.0|last_reward_at:  364|Elapsed Time: 0:00:03||
Episode 8|Iteration 509|reward: 1146.0|last_reward_at:  364|Elapsed Time: 0:00:03||
Episode 8|Iteration 517|reward: 1146.0|last_reward_at:  364|Elapsed Time: 0:00:03||
Episode 8|Iteration 525|reward: 1146.0|last_reward_at:  364|Elapsed Time: 0:00:03||
Episode 8|Iteration 526|reward: 1160.0|last_reward_at:  364|Elapsed Time: 0:00:03||
Episode 8|Iteration 526|reward: 1160.0|last_reward_at:  526|Elapsed Time: 0:00:03||
Episode 8|Iteration 531|reward: 1260.0|last_reward_at:  526|Elapsed Time: 0:00:03||
Episode 8|Iteration 531|reward: 1260.0|last_reward_at:  531|Elapsed Time: 0:00:03||
Episode 8|Iteration 532|reward: 1266.0|last_reward_at:  531|Elapsed Time: 0:00:03||
Episode 8|Iteration 532|reward: 1266.0|last_reward_at:  532|Elapsed Time: 0:00:03||
Episode 8|Iteration 536|reward: 1272.0|last_reward_at:  532|Elapsed Time: 0:00:03||
Episode 8|Iteration 536|reward: 1272.0|last_reward_at:  536|Elapsed Time: 0:00:03||
Episode 8|Iteration 547|reward: 1272.0|last_reward_at:  536|Elapsed Time: 0:00:03||
Episode 8|Iteration 555|reward: 1272.0|last_reward_at:  536|Elapsed Time: 0:00:03||
Episode 8|Iteration 563|reward: 1272.0|last_reward_at:  536|Elapsed Time: 0:00:03||
Episode 8|Iteration 570|reward: 1272.0|last_reward_at:  536|Elapsed Time: 0:00:03||
Episode 8|Iteration 578|reward: 1272.0|last_reward_at:  536|Elapsed Time: 0:00:03||
Episode 8|Iteration 593|reward: 1272.0|last_reward_at:  536|Elapsed Time: 0:00:03||
Episode 8|Iteration 600|reward: 1272.0|last_reward_at:  536|Elapsed Time: 0:00:04||
Episode 8|Iteration 600|reward: 1272.0|last_reward_at:  536|Elapsed Time: 0:00:04||

  Episode 8 stopped at t=600
  Breakdown [Reward/NoReward (Success rate)]
    explore-local: 18/229 (0.07)
    explore-remote: 20/323 (0.06)
    explore-connect: 0/0 (NaN)
    exploit-local: 0/0 (NaN)
    exploit-remote: 0/0 (NaN)
    exploit-connect: 10/0 (1.00)
  exploit deflected to exploration: 210
  ## Episode: 9/10 'Credential lookups (ϵ-greedy)' ϵ=0.5951,

Episode 9|Iteration 0|reward: ------|last_reward_at: ----|Elapsed Time: 0:00:00||
Episode 9|Iteration 1|reward:    0.0|last_reward_at: ----|Elapsed Time: 0:00:00||
Episode 9|Iteration 2|reward:   14.0|last_reward_at: ----|Elapsed Time: 0:00:00||
Episode 9|Iteration 2|reward:   14.0|last_reward_at:    2|Elapsed Time: 0:00:00||
Episode 9|Iteration 7|reward:  114.0|last_reward_at:    2|Elapsed Time: 0:00:00||
Episode 9|Iteration 7|reward:  114.0|last_reward_at:    7|Elapsed Time: 0:00:00||
Episode 9|Iteration 8|reward:  128.0|last_reward_at:    7|Elapsed Time: 0:00:00||
Episode 9|Iteration 8|reward:  128.0|last_reward_at:    8|Elapsed Time: 0:00:00||
Episode 9|Iteration 10|reward:  228.0|last_reward_at:    8|Elapsed Time: 0:00:00||
Episode 9|Iteration 10|reward:  228.0|last_reward_at:   10|Elapsed Time: 0:00:00||
Episode 9|Iteration 11|reward:  242.0|last_reward_at:   10|Elapsed Time: 0:00:00||
Episode 9|Iteration 11|reward:  242.0|last_reward_at:   11|Elapsed Time: 0:00:00||
Episode 9|Iteration 12|reward:  248.0|last_reward_at:   11|Elapsed Time: 0:00:00||
Episode 9|Iteration 12|reward:  248.0|last_reward_at:   12|Elapsed Time: 0:00:00||
Episode 9|Iteration 13|reward:  250.0|last_reward_at:   12|Elapsed Time: 0:00:00||
Episode 9|Iteration 13|reward:  250.0|last_reward_at:   13|Elapsed Time: 0:00:00||
Episode 9|Iteration 14|reward:  350.0|last_reward_at:   13|Elapsed Time: 0:00:00||
Episode 9|Iteration 14|reward:  350.0|last_reward_at:   14|Elapsed Time: 0:00:00||
Episode 9|Iteration 15|reward:  352.0|last_reward_at:   14|Elapsed Time: 0:00:00||
Episode 9|Iteration 15|reward:  352.0|last_reward_at:   15|Elapsed Time: 0:00:00||
Episode 9|Iteration 22|reward:  354.0|last_reward_at:   15|Elapsed Time: 0:00:00||
Episode 9|Iteration 22|reward:  354.0|last_reward_at:   22|Elapsed Time: 0:00:00||
Episode 9|Iteration 27|reward:  360.0|last_reward_at:   22|Elapsed Time: 0:00:00||
Episode 9|Iteration 27|reward:  360.0|last_reward_at:   27|Elapsed Time: 0:00:00||
Episode 9|Iteration 29|reward:  374.0|last_reward_at:   27|Elapsed Time: 0:00:00||
Episode 9|Iteration 29|reward:  374.0|last_reward_at:   29|Elapsed Time: 0:00:00||
Episode 9|Iteration 31|reward:  474.0|last_reward_at:   29|Elapsed Time: 0:00:00||
Episode 9|Iteration 31|reward:  474.0|last_reward_at:   31|Elapsed Time: 0:00:00||
Episode 9|Iteration 32|reward:  480.0|last_reward_at:   31|Elapsed Time: 0:00:00||
Episode 9|Iteration 32|reward:  480.0|last_reward_at:   32|Elapsed Time: 0:00:00||
Episode 9|Iteration 33|reward:  486.0|last_reward_at:   32|Elapsed Time: 0:00:00||
Episode 9|Iteration 33|reward:  486.0|last_reward_at:   33|Elapsed Time: 0:00:00||
Episode 9|Iteration 34|reward:  488.0|last_reward_at:   33|Elapsed Time: 0:00:00||
Episode 9|Iteration 34|reward:  488.0|last_reward_at:   34|Elapsed Time: 0:00:00||
Episode 9|Iteration 38|reward:  494.0|last_reward_at:   34|Elapsed Time: 0:00:00||
Episode 9|Iteration 38|reward:  494.0|last_reward_at:   38|Elapsed Time: 0:00:00||
Episode 9|Iteration 50|reward:  505.0|last_reward_at:   38|Elapsed Time: 0:00:00||
Episode 9|Iteration 50|reward:  505.0|last_reward_at:   50|Elapsed Time: 0:00:00||
Episode 9|Iteration 60|reward:  514.0|last_reward_at:   50|Elapsed Time: 0:00:00||
Episode 9|Iteration 60|reward:  514.0|last_reward_at:   60|Elapsed Time: 0:00:00||
Episode 9|Iteration 61|reward:  614.0|last_reward_at:   60|Elapsed Time: 0:00:00||
Episode 9|Iteration 61|reward:  614.0|last_reward_at:   61|Elapsed Time: 0:00:00||
Episode 9|Iteration 62|reward:  616.0|last_reward_at:   61|Elapsed Time: 0:00:00||
Episode 9|Iteration 62|reward:  616.0|last_reward_at:   62|Elapsed Time: 0:00:00||
Episode 9|Iteration 64|reward:  627.0|last_reward_at:   62|Elapsed Time: 0:00:00||
Episode 9|Iteration 64|reward:  627.0|last_reward_at:   64|Elapsed Time: 0:00:00||
Episode 9|Iteration 67|reward:  633.0|last_reward_at:   64|Elapsed Time: 0:00:00||
Episode 9|Iteration 67|reward:  633.0|last_reward_at:   67|Elapsed Time: 0:00:00||
Episode 9|Iteration 73|reward:  639.0|last_reward_at:   67|Elapsed Time: 0:00:00||
Episode 9|Iteration 73|reward:  639.0|last_reward_at:   73|Elapsed Time: 0:00:00||
Episode 9|Iteration 81|reward:  647.0|last_reward_at:   73|Elapsed Time: 0:00:00||
Episode 9|Iteration 81|reward:  647.0|last_reward_at:   81|Elapsed Time: 0:00:00||
Episode 9|Iteration 97|reward:  649.0|last_reward_at:   81|Elapsed Time: 0:00:00||
Episode 9|Iteration 97|reward:  649.0|last_reward_at:   97|Elapsed Time: 0:00:00||
Episode 9|Iteration 98|reward:  658.0|last_reward_at:   97|Elapsed Time: 0:00:00||
Episode 9|Iteration 98|reward:  658.0|last_reward_at:   98|Elapsed Time: 0:00:00||
Episode 9|Iteration 99|reward:  758.0|last_reward_at:   98|Elapsed Time: 0:00:00||
Episode 9|Iteration 99|reward:  758.0|last_reward_at:   99|Elapsed Time: 0:00:00||
Episode 9|Iteration 100|reward:  772.0|last_reward_at:   99|Elapsed Time: 0:00:00||
Episode 9|Iteration 100|reward:  772.0|last_reward_at:  100|Elapsed Time: 0:00:00||
Episode 9|Iteration 107|reward:  872.0|last_reward_at:  100|Elapsed Time: 0:00:00||
Episode 9|Iteration 107|reward:  872.0|last_reward_at:  107|Elapsed Time: 0:00:00||
Episode 9|Iteration 122|reward:  872.0|last_reward_at:  107|Elapsed Time: 0:00:00||
Episode 9|Iteration 126|reward:  886.0|last_reward_at:  107|Elapsed Time: 0:00:00||
Episode 9|Iteration 126|reward:  886.0|last_reward_at:  126|Elapsed Time: 0:00:00||
Episode 9|Iteration 127|reward:  986.0|last_reward_at:  126|Elapsed Time: 0:00:00||
Episode 9|Iteration 127|reward:  986.0|last_reward_at:  127|Elapsed Time: 0:00:00||
Episode 9|Iteration 130|reward:  988.0|last_reward_at:  127|Elapsed Time: 0:00:00||
Episode 9|Iteration 130|reward:  988.0|last_reward_at:  130|Elapsed Time: 0:00:00||
Episode 9|Iteration 131|reward:  994.0|last_reward_at:  130|Elapsed Time: 0:00:00||
Episode 9|Iteration 131|reward:  994.0|last_reward_at:  131|Elapsed Time: 0:00:00||
Episode 9|Iteration 132|reward: 1000.0|last_reward_at:  131|Elapsed Time: 0:00:00||
Episode 9|Iteration 132|reward: 1000.0|last_reward_at:  132|Elapsed Time: 0:00:00||
Episode 9|Iteration 135|reward: 1006.0|last_reward_at:  132|Elapsed Time: 0:00:00||
Episode 9|Iteration 135|reward: 1006.0|last_reward_at:  135|Elapsed Time: 0:00:00||
Episode 9|Iteration 139|reward: 1008.0|last_reward_at:  135|Elapsed Time: 0:00:00||
Episode 9|Iteration 139|reward: 1008.0|last_reward_at:  139|Elapsed Time: 0:00:00||
Episode 9|Iteration 152|reward: 1008.0|last_reward_at:  139|Elapsed Time: 0:00:00||
Episode 9|Iteration 160|reward: 1008.0|last_reward_at:  139|Elapsed Time: 0:00:01||
Episode 9|Iteration 175|reward: 1008.0|last_reward_at:  139|Elapsed Time: 0:00:01||
Episode 9|Iteration 175|reward: 1014.0|last_reward_at:  139|Elapsed Time: 0:00:01||
Episode 9|Iteration 175|reward: 1014.0|last_reward_at:  175|Elapsed Time: 0:00:01||
Episode 9|Iteration 190|reward: 1014.0|last_reward_at:  175|Elapsed Time: 0:00:01||
Episode 9|Iteration 206|reward: 1014.0|last_reward_at:  175|Elapsed Time: 0:00:01||
Episode 9|Iteration 221|reward: 1014.0|last_reward_at:  175|Elapsed Time: 0:00:01||
Episode 9|Iteration 236|reward: 1014.0|last_reward_at:  175|Elapsed Time: 0:00:01||
Episode 9|Iteration 251|reward: 1014.0|last_reward_at:  175|Elapsed Time: 0:00:01||
Episode 9|Iteration 266|reward: 1014.0|last_reward_at:  175|Elapsed Time: 0:00:01||
Episode 9|Iteration 274|reward: 1014.0|last_reward_at:  175|Elapsed Time: 0:00:01||
Episode 9|Iteration 282|reward: 1014.0|last_reward_at:  175|Elapsed Time: 0:00:01||
Episode 9|Iteration 289|reward: 1014.0|last_reward_at:  175|Elapsed Time: 0:00:01||
Episode 9|Iteration 304|reward: 1014.0|last_reward_at:  175|Elapsed Time: 0:00:01||
Episode 9|Iteration 312|reward: 1014.0|last_reward_at:  175|Elapsed Time: 0:00:02||
Episode 9|Iteration 327|reward: 1014.0|last_reward_at:  175|Elapsed Time: 0:00:02||
Episode 9|Iteration 342|reward: 1014.0|last_reward_at:  175|Elapsed Time: 0:00:02||
Episode 9|Iteration 350|reward: 1014.0|last_reward_at:  175|Elapsed Time: 0:00:02||
Episode 9|Iteration 364|reward: 1014.0|last_reward_at:  175|Elapsed Time: 0:00:02||
Episode 9|Iteration 373|reward: 1014.0|last_reward_at:  175|Elapsed Time: 0:00:02||
Episode 9|Iteration 380|reward: 1014.0|last_reward_at:  175|Elapsed Time: 0:00:02||
Episode 9|Iteration 388|reward: 1014.0|last_reward_at:  175|Elapsed Time: 0:00:02||
Episode 9|Iteration 395|reward: 1014.0|last_reward_at:  175|Elapsed Time: 0:00:02||
Episode 9|Iteration 403|reward: 1014.0|last_reward_at:  175|Elapsed Time: 0:00:02||
Episode 9|Iteration 418|reward: 1014.0|last_reward_at:  175|Elapsed Time: 0:00:02||
Episode 9|Iteration 419|reward: 1025.0|last_reward_at:  175|Elapsed Time: 0:00:02||
Episode 9|Iteration 419|reward: 1025.0|last_reward_at:  419|Elapsed Time: 0:00:02||
Episode 9|Iteration 427|reward: 1029.0|last_reward_at:  419|Elapsed Time: 0:00:02||
Episode 9|Iteration 427|reward: 1029.0|last_reward_at:  427|Elapsed Time: 0:00:02||
Episode 9|Iteration 441|reward: 1029.0|last_reward_at:  427|Elapsed Time: 0:00:02||
Episode 9|Iteration 441|reward: 1035.0|last_reward_at:  427|Elapsed Time: 0:00:02||
Episode 9|Iteration 441|reward: 1035.0|last_reward_at:  441|Elapsed Time: 0:00:02||
Episode 9|Iteration 444|reward: 1044.0|last_reward_at:  441|Elapsed Time: 0:00:02||
Episode 9|Iteration 444|reward: 1044.0|last_reward_at:  444|Elapsed Time: 0:00:02||
Episode 9|Iteration 445|reward: 1144.0|last_reward_at:  444|Elapsed Time: 0:00:02||
Episode 9|Iteration 445|reward: 1144.0|last_reward_at:  445|Elapsed Time: 0:00:02||
Episode 9|Iteration 456|reward: 1144.0|last_reward_at:  445|Elapsed Time: 0:00:03||
Episode 9|Iteration 464|reward: 1144.0|last_reward_at:  445|Elapsed Time: 0:00:03||
Episode 9|Iteration 471|reward: 1144.0|last_reward_at:  445|Elapsed Time: 0:00:03||
Episode 9|Iteration 480|reward: 1146.0|last_reward_at:  445|Elapsed Time: 0:00:03||
Episode 9|Iteration 480|reward: 1146.0|last_reward_at:  480|Elapsed Time: 0:00:03||
Episode 9|Iteration 494|reward: 1146.0|last_reward_at:  480|Elapsed Time: 0:00:03||
Episode 9|Iteration 502|reward: 1146.0|last_reward_at:  480|Elapsed Time: 0:00:03||
Episode 9|Iteration 509|reward: 1146.0|last_reward_at:  480|Elapsed Time: 0:00:03||
Episode 9|Iteration 517|reward: 1146.0|last_reward_at:  480|Elapsed Time: 0:00:03||
Episode 9|Iteration 525|reward: 1146.0|last_reward_at:  480|Elapsed Time: 0:00:03||
Episode 9|Iteration 533|reward: 1157.0|last_reward_at:  480|Elapsed Time: 0:00:03||
Episode 9|Iteration 533|reward: 1157.0|last_reward_at:  533|Elapsed Time: 0:00:03||
Episode 9|Iteration 540|reward: 1157.0|last_reward_at:  533|Elapsed Time: 0:00:03||
Episode 9|Iteration 547|reward: 1157.0|last_reward_at:  533|Elapsed Time: 0:00:03||
Episode 9|Iteration 555|reward: 1157.0|last_reward_at:  533|Elapsed Time: 0:00:03||
Episode 9|Iteration 563|reward: 1157.0|last_reward_at:  533|Elapsed Time: 0:00:03||
Episode 9|Iteration 570|reward: 1157.0|last_reward_at:  533|Elapsed Time: 0:00:03||
Episode 9|Iteration 575|reward: 1166.0|last_reward_at:  533|Elapsed Time: 0:00:03||
Episode 9|Iteration 575|reward: 1166.0|last_reward_at:  575|Elapsed Time: 0:00:03||
Episode 9|Iteration 576|reward: 1266.0|last_reward_at:  575|Elapsed Time: 0:00:03||
Episode 9|Iteration 576|reward: 1266.0|last_reward_at:  576|Elapsed Time: 0:00:03||
Episode 9|Iteration 585|reward: 1266.0|last_reward_at:  576|Elapsed Time: 0:00:04||
Episode 9|Iteration 587|reward: 1272.0|last_reward_at:  576|Elapsed Time: 0:00:04||
Episode 9|Iteration 587|reward: 1272.0|last_reward_at:  587|Elapsed Time: 0:00:04||
Episode 9|Iteration 593|reward: 1272.0|last_reward_at:  587|Elapsed Time: 0:00:04||
Episode 9|Iteration 600|reward: 1272.0|last_reward_at:  587|Elapsed Time: 0:00:04||
Episode 9|Iteration 600|reward: 1272.0|last_reward_at:  587|Elapsed Time: 0:00:04||

  Episode 9 stopped at t=600
  Breakdown [Reward/NoReward (Success rate)]
    explore-local: 19/236 (0.07)
    explore-remote: 19/316 (0.06)
    explore-connect: 0/0 (NaN)
    exploit-local: 0/0 (NaN)
    exploit-remote: 0/0 (NaN)
    exploit-connect: 10/0 (1.00)
  exploit deflected to exploration: 245
  ## Episode: 10/10 'Credential lookups (ϵ-greedy)' ϵ=0.5662,

Episode 10|Iteration 0|reward: ------|last_reward_at: ----|Elapsed Time: 0:00:00||
Episode 10|Iteration 1|reward:    0.0|last_reward_at: ----|Elapsed Time: 0:00:00||
Episode 10|Iteration 8|reward:   14.0|last_reward_at: ----|Elapsed Time: 0:00:00||
Episode 10|Iteration 8|reward:   14.0|last_reward_at:    8|Elapsed Time: 0:00:00||
Episode 10|Iteration 9|reward:   16.0|last_reward_at:    8|Elapsed Time: 0:00:00||
Episode 10|Iteration 9|reward:   16.0|last_reward_at:    9|Elapsed Time: 0:00:00||
Episode 10|Iteration 10|reward:  116.0|last_reward_at:    9|Elapsed Time: 0:00:00||
Episode 10|Iteration 10|reward:  116.0|last_reward_at:   10|Elapsed Time: 0:00:00||
Episode 10|Iteration 11|reward:  118.0|last_reward_at:   10|Elapsed Time: 0:00:00||
Episode 10|Iteration 11|reward:  118.0|last_reward_at:   11|Elapsed Time: 0:00:00||
Episode 10|Iteration 13|reward:  129.0|last_reward_at:   11|Elapsed Time: 0:00:00||
Episode 10|Iteration 13|reward:  129.0|last_reward_at:   13|Elapsed Time: 0:00:00||
Episode 10|Iteration 19|reward:  137.0|last_reward_at:   13|Elapsed Time: 0:00:00||
Episode 10|Iteration 19|reward:  137.0|last_reward_at:   19|Elapsed Time: 0:00:00||
Episode 10|Iteration 21|reward:  146.0|last_reward_at:   19|Elapsed Time: 0:00:00||
Episode 10|Iteration 21|reward:  146.0|last_reward_at:   21|Elapsed Time: 0:00:00||
Episode 10|Iteration 22|reward:  246.0|last_reward_at:   21|Elapsed Time: 0:00:00||
Episode 10|Iteration 22|reward:  246.0|last_reward_at:   22|Elapsed Time: 0:00:00||
Episode 10|Iteration 23|reward:  260.0|last_reward_at:   22|Elapsed Time: 0:00:00||
Episode 10|Iteration 23|reward:  260.0|last_reward_at:   23|Elapsed Time: 0:00:00||
Episode 10|Iteration 24|reward:  360.0|last_reward_at:   23|Elapsed Time: 0:00:00||
Episode 10|Iteration 24|reward:  360.0|last_reward_at:   24|Elapsed Time: 0:00:00||
Episode 10|Iteration 29|reward:  362.0|last_reward_at:   24|Elapsed Time: 0:00:00||
Episode 10|Iteration 29|reward:  362.0|last_reward_at:   29|Elapsed Time: 0:00:00||
Episode 10|Iteration 30|reward:  368.0|last_reward_at:   29|Elapsed Time: 0:00:00||
Episode 10|Iteration 30|reward:  368.0|last_reward_at:   30|Elapsed Time: 0:00:00||
Episode 10|Iteration 31|reward:  374.0|last_reward_at:   30|Elapsed Time: 0:00:00||
Episode 10|Iteration 31|reward:  374.0|last_reward_at:   31|Elapsed Time: 0:00:00||
Episode 10|Iteration 35|reward:  385.0|last_reward_at:   31|Elapsed Time: 0:00:00||
Episode 10|Iteration 35|reward:  385.0|last_reward_at:   35|Elapsed Time: 0:00:00||
Episode 10|Iteration 38|reward:  393.0|last_reward_at:   35|Elapsed Time: 0:00:00||
Episode 10|Iteration 38|reward:  393.0|last_reward_at:   38|Elapsed Time: 0:00:00||
Episode 10|Iteration 45|reward:  402.0|last_reward_at:   38|Elapsed Time: 0:00:00||
Episode 10|Iteration 45|reward:  402.0|last_reward_at:   45|Elapsed Time: 0:00:00||
Episode 10|Iteration 46|reward:  502.0|last_reward_at:   45|Elapsed Time: 0:00:00||
Episode 10|Iteration 46|reward:  502.0|last_reward_at:   46|Elapsed Time: 0:00:00||
Episode 10|Iteration 53|reward:  508.0|last_reward_at:   46|Elapsed Time: 0:00:00||
Episode 10|Iteration 53|reward:  508.0|last_reward_at:   53|Elapsed Time: 0:00:00||
Episode 10|Iteration 69|reward:  508.0|last_reward_at:   53|Elapsed Time: 0:00:00||
Episode 10|Iteration 84|reward:  508.0|last_reward_at:   53|Elapsed Time: 0:00:00||
Episode 10|Iteration 90|reward:  522.0|last_reward_at:   53|Elapsed Time: 0:00:00||
Episode 10|Iteration 90|reward:  522.0|last_reward_at:   90|Elapsed Time: 0:00:00||
Episode 10|Iteration 94|reward:  622.0|last_reward_at:   90|Elapsed Time: 0:00:00||
Episode 10|Iteration 94|reward:  622.0|last_reward_at:   94|Elapsed Time: 0:00:00||
Episode 10|Iteration 95|reward:  624.0|last_reward_at:   94|Elapsed Time: 0:00:00||
Episode 10|Iteration 95|reward:  624.0|last_reward_at:   95|Elapsed Time: 0:00:00||
Episode 10|Iteration 102|reward:  630.0|last_reward_at:   95|Elapsed Time: 0:00:00||
Episode 10|Iteration 102|reward:  630.0|last_reward_at:  102|Elapsed Time: 0:00:00||
Episode 10|Iteration 107|reward:  641.0|last_reward_at:  102|Elapsed Time: 0:00:00||
Episode 10|Iteration 107|reward:  641.0|last_reward_at:  107|Elapsed Time: 0:00:00||
Episode 10|Iteration 112|reward:  643.0|last_reward_at:  107|Elapsed Time: 0:00:00||
Episode 10|Iteration 112|reward:  643.0|last_reward_at:  112|Elapsed Time: 0:00:00||
Episode 10|Iteration 115|reward:  645.0|last_reward_at:  112|Elapsed Time: 0:00:00||
Episode 10|Iteration 115|reward:  645.0|last_reward_at:  115|Elapsed Time: 0:00:00||
Episode 10|Iteration 121|reward:  654.0|last_reward_at:  115|Elapsed Time: 0:00:00||
Episode 10|Iteration 121|reward:  654.0|last_reward_at:  121|Elapsed Time: 0:00:00||
Episode 10|Iteration 122|reward:  754.0|last_reward_at:  121|Elapsed Time: 0:00:00||
Episode 10|Iteration 122|reward:  754.0|last_reward_at:  122|Elapsed Time: 0:00:00||
Episode 10|Iteration 124|reward:  760.0|last_reward_at:  122|Elapsed Time: 0:00:00||
Episode 10|Iteration 124|reward:  760.0|last_reward_at:  124|Elapsed Time: 0:00:00||
Episode 10|Iteration 135|reward:  766.0|last_reward_at:  124|Elapsed Time: 0:00:00||
Episode 10|Iteration 135|reward:  766.0|last_reward_at:  135|Elapsed Time: 0:00:00||
Episode 10|Iteration 145|reward:  766.0|last_reward_at:  135|Elapsed Time: 0:00:00||
Episode 10|Iteration 160|reward:  766.0|last_reward_at:  135|Elapsed Time: 0:00:00||
Episode 10|Iteration 168|reward:  766.0|last_reward_at:  135|Elapsed Time: 0:00:00||
Episode 10|Iteration 178|reward:  780.0|last_reward_at:  135|Elapsed Time: 0:00:01||
Episode 10|Iteration 178|reward:  780.0|last_reward_at:  178|Elapsed Time: 0:00:01||
Episode 10|Iteration 179|reward:  880.0|last_reward_at:  178|Elapsed Time: 0:00:01||
Episode 10|Iteration 179|reward:  880.0|last_reward_at:  179|Elapsed Time: 0:00:01||
Episode 10|Iteration 190|reward:  880.0|last_reward_at:  179|Elapsed Time: 0:00:01||
Episode 10|Iteration 198|reward:  880.0|last_reward_at:  179|Elapsed Time: 0:00:01||
Episode 10|Iteration 206|reward:  880.0|last_reward_at:  179|Elapsed Time: 0:00:01||
Episode 10|Iteration 218|reward:  882.0|last_reward_at:  179|Elapsed Time: 0:00:01||
Episode 10|Iteration 218|reward:  882.0|last_reward_at:  218|Elapsed Time: 0:00:01||
Episode 10|Iteration 228|reward:  882.0|last_reward_at:  218|Elapsed Time: 0:00:01||
Episode 10|Iteration 230|reward:  896.0|last_reward_at:  218|Elapsed Time: 0:00:01||
Episode 10|Iteration 230|reward:  896.0|last_reward_at:  230|Elapsed Time: 0:00:01||
Episode 10|Iteration 231|reward:  996.0|last_reward_at:  230|Elapsed Time: 0:00:01||
Episode 10|Iteration 231|reward:  996.0|last_reward_at:  231|Elapsed Time: 0:00:01||
Episode 10|Iteration 239|reward: 1002.0|last_reward_at:  231|Elapsed Time: 0:00:01||
Episode 10|Iteration 239|reward: 1002.0|last_reward_at:  239|Elapsed Time: 0:00:01||
Episode 10|Iteration 251|reward: 1002.0|last_reward_at:  239|Elapsed Time: 0:00:01||
Episode 10|Iteration 252|reward: 1008.0|last_reward_at:  239|Elapsed Time: 0:00:01||
Episode 10|Iteration 252|reward: 1008.0|last_reward_at:  252|Elapsed Time: 0:00:01||
Episode 10|Iteration 255|reward: 1014.0|last_reward_at:  252|Elapsed Time: 0:00:01||
Episode 10|Iteration 255|reward: 1014.0|last_reward_at:  255|Elapsed Time: 0:00:01||
Episode 10|Iteration 266|reward: 1014.0|last_reward_at:  255|Elapsed Time: 0:00:01||
Episode 10|Iteration 282|reward: 1014.0|last_reward_at:  255|Elapsed Time: 0:00:01||
Episode 10|Iteration 291|reward: 1020.0|last_reward_at:  255|Elapsed Time: 0:00:01||
Episode 10|Iteration 291|reward: 1020.0|last_reward_at:  291|Elapsed Time: 0:00:01||
Episode 10|Iteration 295|reward: 1022.0|last_reward_at:  291|Elapsed Time: 0:00:01||
Episode 10|Iteration 295|reward: 1022.0|last_reward_at:  295|Elapsed Time: 0:00:01||
Episode 10|Iteration 304|reward: 1022.0|last_reward_at:  295|Elapsed Time: 0:00:01||
Episode 10|Iteration 312|reward: 1022.0|last_reward_at:  295|Elapsed Time: 0:00:01||
Episode 10|Iteration 319|reward: 1022.0|last_reward_at:  295|Elapsed Time: 0:00:02||
Episode 10|Iteration 335|reward: 1022.0|last_reward_at:  295|Elapsed Time: 0:00:02||
Episode 10|Iteration 348|reward: 1022.0|last_reward_at:  295|Elapsed Time: 0:00:02||
Episode 10|Iteration 357|reward: 1022.0|last_reward_at:  295|Elapsed Time: 0:00:02||
Episode 10|Iteration 365|reward: 1022.0|last_reward_at:  295|Elapsed Time: 0:00:02||
Episode 10|Iteration 373|reward: 1022.0|last_reward_at:  295|Elapsed Time: 0:00:02||
Episode 10|Iteration 380|reward: 1022.0|last_reward_at:  295|Elapsed Time: 0:00:02||
Episode 10|Iteration 388|reward: 1022.0|last_reward_at:  295|Elapsed Time: 0:00:02||
Episode 10|Iteration 398|reward: 1033.0|last_reward_at:  295|Elapsed Time: 0:00:02||
Episode 10|Iteration 398|reward: 1033.0|last_reward_at:  398|Elapsed Time: 0:00:02||
Episode 10|Iteration 411|reward: 1033.0|last_reward_at:  398|Elapsed Time: 0:00:02||
Episode 10|Iteration 426|reward: 1033.0|last_reward_at:  398|Elapsed Time: 0:00:02||
Episode 10|Iteration 433|reward: 1033.0|last_reward_at:  398|Elapsed Time: 0:00:02||
Episode 10|Iteration 441|reward: 1033.0|last_reward_at:  398|Elapsed Time: 0:00:02||
Episode 10|Iteration 449|reward: 1037.0|last_reward_at:  398|Elapsed Time: 0:00:02||
Episode 10|Iteration 449|reward: 1037.0|last_reward_at:  449|Elapsed Time: 0:00:02||
Episode 10|Iteration 450|reward: 1046.0|last_reward_at:  449|Elapsed Time: 0:00:02||
Episode 10|Iteration 450|reward: 1046.0|last_reward_at:  450|Elapsed Time: 0:00:02||
Episode 10|Iteration 452|reward: 1146.0|last_reward_at:  450|Elapsed Time: 0:00:02||
Episode 10|Iteration 452|reward: 1146.0|last_reward_at:  452|Elapsed Time: 0:00:02||
Episode 10|Iteration 461|reward: 1157.0|last_reward_at:  452|Elapsed Time: 0:00:03||
Episode 10|Iteration 461|reward: 1157.0|last_reward_at:  461|Elapsed Time: 0:00:03||
Episode 10|Iteration 471|reward: 1157.0|last_reward_at:  461|Elapsed Time: 0:00:03||
Episode 10|Iteration 479|reward: 1157.0|last_reward_at:  461|Elapsed Time: 0:00:03||
Episode 10|Iteration 487|reward: 1157.0|last_reward_at:  461|Elapsed Time: 0:00:03||
Episode 10|Iteration 492|reward: 1159.0|last_reward_at:  461|Elapsed Time: 0:00:03||
Episode 10|Iteration 492|reward: 1159.0|last_reward_at:  492|Elapsed Time: 0:00:03||
Episode 10|Iteration 499|reward: 1167.0|last_reward_at:  492|Elapsed Time: 0:00:03||
Episode 10|Iteration 499|reward: 1167.0|last_reward_at:  499|Elapsed Time: 0:00:03||
Episode 10|Iteration 509|reward: 1167.0|last_reward_at:  499|Elapsed Time: 0:00:03||
Episode 10|Iteration 517|reward: 1167.0|last_reward_at:  499|Elapsed Time: 0:00:03||
Episode 10|Iteration 525|reward: 1167.0|last_reward_at:  499|Elapsed Time: 0:00:03||
Episode 10|Iteration 537|reward: 1167.0|last_reward_at:  499|Elapsed Time: 0:00:03||
Episode 10|Iteration 547|reward: 1167.0|last_reward_at:  499|Elapsed Time: 0:00:03||
Episode 10|Iteration 555|reward: 1167.0|last_reward_at:  499|Elapsed Time: 0:00:03||
Episode 10|Iteration 563|reward: 1167.0|last_reward_at:  499|Elapsed Time: 0:00:03||
Episode 10|Iteration 570|reward: 1167.0|last_reward_at:  499|Elapsed Time: 0:00:03||
Episode 10|Iteration 570|reward: 1173.0|last_reward_at:  499|Elapsed Time: 0:00:03||
Episode 10|Iteration 570|reward: 1173.0|last_reward_at:  570|Elapsed Time: 0:00:03||
Episode 10|Iteration 578|reward: 1173.0|last_reward_at:  570|Elapsed Time: 0:00:03||
Episode 10|Iteration 585|reward: 1173.0|last_reward_at:  570|Elapsed Time: 0:00:04||
Episode 10|Iteration 593|reward: 1173.0|last_reward_at:  570|Elapsed Time: 0:00:04||
Episode 10|Iteration 600|reward: 1173.0|last_reward_at:  570|Elapsed Time: 0:00:04||
Episode 10|Iteration 600|reward: 1173.0|last_reward_at:  570|Elapsed Time: 0:00:04||

  Episode 10 stopped at t=600
  Breakdown [Reward/NoReward (Success rate)]
    explore-local: 18/242 (0.07)
    explore-remote: 20/311 (0.06)
    explore-connect: 0/0 (NaN)
    exploit-local: 0/0 (NaN)
    exploit-remote: 0/0 (NaN)
    exploit-connect: 9/0 (1.00)
  exploit deflected to exploration: 257
simulation ended

In [21]:
# Plots
all_runs = [credlookup_run, dqn_with_defender, dql_exploit_run]
p.plot_averaged_cummulative_rewards(all_runs=all_runs, title=f"Attacker agents vs Basic Defender -- rewards\n env={cyberbattlechain_defender.name}, episodes={training_episode_count}", save_at=os.path.join(plots_dir, "withdefender-cumreward.png"))
# p.plot_episodes_length(all_runs)
p.plot_averaged_availability(title=f"Attacker agents vs Basic Defender -- availability\n env={cyberbattlechain_defender.name}, episodes={training_episode_count}", all_runs=all_runs, show=False)